### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by siquan001** [win12-online/win12#10]
我发现在同时打开设置和文件资源管理器的时候，设置会被文件资源管理器遮挡，并且无法在不关闭文件资源管理器的情况下，让设置出现在最上方。
还有，也许是我电脑的原因，我使用起来有点卡。

**Comment by tjy-gitnub** [comment]
emm 这个焦点切换的实现有一些困难，如果每次只开一个窗口就不会有问题
但是这确实是一个问题。。。我争取在下一个版本（v3.3.0) 解决
卡顿主要是因为窗口模糊效果导致的
如果焦点不在这个窗口就取消模糊似乎是一个解决方案，还是和第一个问题有关
我会尽快解决的，感谢建议

**Comment by huangzh20** [comment]
这个问题好

**Comment by lao-liu-6** [comment]
啊对对对

**Comment by Samtjs** [comment]
万万不要取消窗口毛玻璃呀！！！！

**Comment by tjy-gitnub** [comment]
> 万万不要取消窗口毛玻璃呀！！！！
??为什么??🙃
