### ISSUE TITLE
一个简单但是没有的功能

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#101]
任务栏右键应用图标关闭应用，你们这个功能为啥不做啊。
是懒惰，还是难做（莫名押韵）？
```
document.getElementById('myDiv').oncontextmenu = function(event) {
    // 阻止默认的右键菜单
    event.preventDefault();

    // 在这里执行您想要的操作
    // ...
}
```
这不是蛮简单的吗

**Comment by tjy-gitnub** [comment]
emm事实上已经封装了右键菜单了，只需要调用
![image](https://github.com/tjy-gitnub/win12/assets/71509955/d7f89083-5dad-4fa8-aa02-018e60961a05)
就行了的
就是懒惰...
好吧，v6（什么都v6

**Comment by NB-Group** [comment]
> emm事实上已经封装了右键菜单了，只需要调用 ![image](https://user-images.githubusercontent.com/71509955/243106593-d7f89083-5dad-4fa8-aa02-018e60961a05.png) 就行了的 就是懒惰... 好吧，v6（什么都v6

好好好，v6

**Comment by User782Tec** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/115236204/91b00793-2ad5-4d4b-83b8-277c352a3783)


不用等v6了
我做好了

**Comment by NB-Group** [comment]
好好好，赶紧合并，这个功能想要好久了

**Comment by User782Tec** [comment]
> 好好好，赶紧合并，这个功能想要好久了

那控制中心...

**Comment by NB-Group** [comment]
啥控制中心啊，我做的那个win安全中心吗

**Comment by User782Tec** [comment]
> 啥控制中心啊，我做的那个win安全中心吗

我说我那个
控制中心
我本来做的电池与亮度
emm太垃圾了
所以打算重写

**Comment by tjy-gitnub** [comment]
啊，这...
太简陋了吧...
![image](https://github.com/tjy-gitnub/win12/assets/71509955/65e0047e-91f2-4487-a46c-f4c9727e0b4c)
应该居中，还有向上展开啊...
行吧，我之后改一下...
