### ISSUE TITLE
壁纸投稿

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#102]
![R-C](https://github.com/tjy-gitnub/win12/assets/126944988/e9d1c05e-d76f-4073-bffa-5acf2dfb644b)

**Comment by User782Tec** [comment]
可以去隔壁<https://github.com/tjy-gitnub/win12-theme>看一看

**Comment by NebulaTechs** [comment]
[bing](bing.com)

**Comment by NebulaTechs** [comment]
https://bing.com/
