### ISSUE TITLE
几个意思

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#103]
<img width="85" alt="屏幕截图 2023-06-13 185407" src="https://github.com/tjy-gitnub/win12/assets/126944988/9d3e7bf5-24ed-4964-a4d5-71868acec6cc">

**Comment by NebulaTechs** [comment]
这或许有些过分

**Comment by User782Tec** [comment]
我不知道
但win11就是这样做的

**Comment by tjy-gitnub** [comment]
就个摆设，不要太较真

**Comment by NebulaTechs** [comment]
就是还差个箭头,而且辅助功能是点不亮的
