### ISSUE TITLE
联系方式

### ISSUE THREAD

**Issue by ProgramCX** [win12-online/win12#104]
你好，我和你年龄相仿相差3岁吧，可以加一个QQ：2860245799吗。想邀请你加入水滴实验室，很欣赏你的才华。你可以把联系方式发到我的email：2860245799@qq.com

**Comment by NB-Group** [comment]
所以你指的是哪位开发者，win12的开发团队有三个人，我，谭景元，user782

**Comment by ProgramCX** [comment]
你们三个，都想和你们认识认识

**Comment by ProgramCX** [comment]
> 所以你指的是哪位开发者，win12的开发团队有三个人，我，谭景元，user782

@NB-Group @tjy-gitnub @User782Tec 你们三个，都想和你们认识认识

**Comment by ProgramCX** [comment]
@NB-Group @tjy-gitnub @User782Tec 你们不介意吧

**Comment by ProgramCX** [comment]
@NB-Group @tjy-gitnub @User782Tec 
[https://github.com/WaterDropLab](url)
我邀请你们加入水滴实验室组织，将上面的链接复制到地址栏，回车进入水滴实验室主页接受邀请。(直接点链接没用)
QQ：2860245799

**Comment by NB-Group** [comment]
好，我加了，你们这个组织是干啥的？

**Comment by ProgramCX** [comment]
> 好，我加了，你们这个组织是干啥的？

看组织的About-Us存储库

**Comment by ProgramCX** [comment]
@NB-Group 加一下QQ，把你拉群里，交流一下

**Comment by User782Tec** [comment]
所以话说你几岁(

**Comment by ProgramCX** [comment]
> 所以话说你几岁(

@User782Tec 17岁

**Comment by NB-Group** [comment]
（比我们都大

**Comment by ProgramCX** [comment]
> （比我们都大

但比我牛

**Comment by ProgramCX** [comment]
马上高三了 @NB-Group @NB-Group

**Comment by NB-Group** [comment]
我来自我介绍一下吧

**Comment by ProgramCX** [comment]
好

**Comment by ProgramCX** [comment]
欢迎加入QQ群：水滴实验室WaterDrop Lab，目前6人(包括成员研发的QQ机器人)群号码：913417095 @User782Tec @NB-Group @tjy-gitnub

**Comment by ProgramCX** [comment]
我有点事，明天上午我来详细的介绍一下自己 @NB-Group

**Comment by NB-Group** [comment]
qq群我星期天加，现在我在外面旅游忘带手机了

**Comment by ProgramCX** [comment]
> qq群我星期天加，现在我在外面旅游忘带手机了

好的，等你，旅游愉快

**Comment by tjy-gitnub** [comment]
17岁！ amz_zing)o
有点高级
但是遗憾的是我似乎不大能帮上忙欸，我比较擅长写html，当然uwp和安卓也写过
c++本人非常讨厌，不是因为它本身，而是学信息学竞赛的都要用c++，所以不大喜欢...
当然也非常乐意加入，如果有能帮上忙的。
<hr>
ps:自我介绍可以看 [这里](https://tjy-gitnub.github.io)
<hr>

我没有qq(不要惊讶，但是可以加teams(Microsoft Teams) a2017225905@outlook.com

**Comment by ProgramCX** [comment]
> 17岁！ amz_zing)o 有点高级 但是遗憾的是我似乎不大能帮上忙欸，我比较擅长写html，当然uwp和安卓也写过 c++本人非常讨厌，不是因为它本身，而是学信息学竞赛的都要用c++，所以不大喜欢... 当然也非常乐意加入，如果有能帮上忙的。
> 
> ps:自我介绍可以看 [这里](https://tjy-gitnub.github.io)
> 我没有qq(不要惊讶，但是可以加teams(Microsoft Teams) [a2017225905@outlook.com](mailto:a2017225905@outlook.com)

我们正好缺精通html的，我只会html的盒模型和内联css的基础用法，js是一点不懂，你没有qq，那就加入水滴实验室的组织github,我要邀请你了

**Comment by tjy-gitnub** [comment]
> 我们正好缺精通html的，我只会html的盒模型和内联css的基础用法，js是一点不懂，你没有qq，那就加入水滴实验室的组织github,我要邀请你了

嗯，感谢认可，我其实已经加了

**Comment by ProgramCX** [comment]
> > 我们正好缺精通html的，我只会html的盒模型和内联css的基础用法，js是一点不懂，你没有qq，那就加入水滴实验室的组织github,我要邀请你了
> 
> 嗯，感谢认可，我其实已经加了

我的自我介绍发到你的outlook邮箱里了，英文版的。有错误多多包容。

**Comment by User782Tec** [comment]
可以带我一个吗(

**Comment by ProgramCX** [comment]
@NB-Group 你好像忘了加QQ群了吧。

**Comment by ProgramCX** [comment]
@User782Tec 你旁边的两位高手已经加入了水滴实验室，你要不要也考虑一下吧。
[https://github.com/WaterDropLab](url)
我邀请已经你加入水滴实验室组织，如果愿意加入，请将上面的链接复制到地址栏，回车进入水滴实验室主页接受邀请。(直接点链接没用)
QQ：2860245799

**Comment by User782Tec** [comment]
行 我考虑一下

**Comment by NB-Group** [comment]
> @NB-Group 你好像忘了加QQ群了吧。

啊对对对，我待会加下

**Comment by ProgramCX** [comment]
@NB-Group @User782Tec OK

**Comment by NB-Group** [comment]
> @User782Tec 你旁边的两位高手已经加入了水滴实验室，你要不要也考虑一下吧。 [https://github.com/WaterDropLab](url) 我邀请已经你加入水滴实验室组织，如果愿意加入，请将上面的链接复制到地址栏，回车进入水滴实验室主页接受邀请。(直接点链接没用) QQ：2860245799

欸，这个qq为啥搜不到啊

**Comment by ProgramCX** [comment]
> > @User782Tec 你旁边的两位高手已经加入了水滴实验室，你要不要也考虑一下吧。 [https://github.com/WaterDropLab](url) 我邀请已经你加入水滴实验室组织，如果愿意加入，请将上面的链接复制到地址栏，回车进入水滴实验室主页接受邀请。(直接点链接没用) QQ：2860245799
> 
> 欸，这个qq为啥搜不到啊

很多人都搜不到，不知为什么。你好像进群了

**Comment by NB-Group** [comment]
对，我进群了

**Comment by ProgramCX** [comment]
> 对，我进群了

等我考完试。

**Comment by tjy-gitnub** [comment]
> > > @User782Tec 你旁边的两位高手已经加入了水滴实验室，你要不要也考虑一下吧。 [https://github.com/WaterDropLab](/tjy-gitnub/win12/issues/url) 我邀请已经你加入水滴实验室组织，如果愿意加入，请将上面的链接复制到地址栏，回车进入水滴实验室主页接受邀请。(直接点链接没用) QQ：2860245799
> > 
> > 
> > 欸，这个qq为啥搜不到啊
> 
> 很多人都搜不到，不知为什么。你好像进群了

真的搜不到。。

**Comment by NB-Group** [comment]
@tjy-gitnub 913417095 这个是他们群号

**Comment by NB-Group** [comment]
@ProgramCX [这里](https://nb-group.github.io)是我的主页，你可以去康康。
![image](https://github.com/tjy-gitnub/win12/assets/121747915/e7074731-7ed1-429a-80c5-9c3d97afe970)
直接点这个，其他的没什么好看的

**Comment by ProgramCX** [comment]
> @ProgramCX [这里](https://nb-group.github.io)是我的主页，你可以去康康。 ![image](https://user-images.githubusercontent.com/121747915/252523528-e7074731-7ed1-429a-80c5-9c3d97afe970.png) 直接点这个，其他的没什么好看的

动态效果不错

**Comment by ProgramCX** [comment]
> @ProgramCX [这里](https://nb-group.github.io)是我的主页，你可以去康康。 ![image](https://user-images.githubusercontent.com/121747915/252523528-e7074731-7ed1-429a-80c5-9c3d97afe970.png) 直接点这个，其他的没什么好看的
