### ISSUE TITLE
Some Advises

### ISSUE THREAD

**Issue by ProgramCX** [win12-online/win12#111]
建议弄一个Windows文件对话框。
![1](https://github.com/tjy-gitnub/win12/assets/124671913/3499794c-7600-49a5-8e9e-44cc29525196)

**Comment by ProgramCX** [comment]
相机点了后跳出一个许可对话框，同意后没有打开相机，没反应。 @tjy-gitnub

**Comment by ProgramCX** [comment]
我只能提提建议了。本人对做网页基本上一窍不通

**Comment by NB-Group** [comment]
相机是因为你关了网站的获取摄像头权限
