### ISSUE TITLE
A small suggestion

### ISSUE THREAD

**Issue by Nick-DL** [win12-online/win12#112]
中国把宇航员称作航天员

建议添加新闻：流浪地球4首支预告片发布

**Comment by User782Tec** [comment]
ok
(虽然但是流浪地球3还没发布吧233333)

**Comment by User782Tec** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/115236204/214582b3-db18-45af-99d4-5bdf07d6bb81)
这样行吗

**Comment by Nick-DL** [comment]
我看很行啊

**Comment by User782Tec** [comment]
ok
