### ISSUE TITLE
You should add windows update!

### ISSUE THREAD

**Issue by newfiles-github** [win12-online/win12#114]
$建议把设置应用做全面一些,增加windows update$

**Comment by User782Tec** [comment]
Windows Update在做啦～

**Comment by tjy-gitnub** [comment]
现在已经放弃啦~

**Comment by User782Tec** [comment]
> 现在已经放弃啦~

。。。6

**Comment by NebulaTechs** [comment]
> 现在已经放弃啦~

。。。其实很简单，clearcache命令就可以啦~

**Comment by tjy-gitnub** [comment]
但是还有要检测版本更新才清除数据啊，目前的问题就是没办法在更新之后触发新功能的提示什么的。。

**Comment by NebulaTechs** [comment]
那就不用触发和提示了，直接点一下更新就clearcache。

**Comment by tjy-gitnub** [comment]
呃。。不好吧。。那岂不是手动检测更新（？
我再试一下吧，7.1左右出吧

**Comment by NebulaTechs** [comment]
> 呃。。不好吧。。那岂不是手动检测更新（？ 我再试一下吧，7.1左右出吧

其实没事。win11react就是手动更新。

**Comment by Mbilse** [comment]
> > 呃。。不好吧。。那岂不是手动检测更新（？ 我再试一下吧，7.1左右出吧
> 
> 其实没事。win11react就是手动更新。

哇，你们两年前就在了
