### ISSUE TITLE
新图标有着落了

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#116]
https://www.flaticon.com/search/?author_id=1&style_id=147&type=standard

另外：
<img width="361" alt="image" src="https://github.com/tjy-gitnub/win12/assets/126944988/c9b56884-7e2b-418d-8019-849f71372a8c">

**Comment by User782Tec** [comment]
> https://www.flaticon.com/search/?author_id=1&style_id=147&type=standard
> 
> 另外： <img alt="image" width="361" src="https://user-images.githubusercontent.com/126944988/255390263-c9b56884-7e2b-418d-8019-849f71372a8c.png">

额
这个马上可能会改的(
因为我们已经发了v7.0(bushi)

**Comment by NebulaTechs** [comment]
的确，但是更新记录为什么没了？

**Comment by tjy-gitnub** [comment]
这个图标。。似乎并不是我们需要的欸。。
（你指的是应用图标/设置项的图标/菜单的图标？
设置的我们是用的win11的图标，菜单的我们是用的booticon的，应用呢是手画+抄win11的。。

**Comment by NebulaTechs** [comment]
> > https://www.flaticon.com/search/?author_id=1&style_id=147&type=standard
> > 另外： <img alt="image" width="361" src="http://user-images.githubusercontent.com/126944988/255390263-c9b56884-7e2b-418d-8019-849f71372a8c.png">
> 
> 额 这个马上可能大概也许，maybe会改的( 因为我们已经发了v7.0(bushi)
真怀旧啊！
