### ISSUE TITLE
已经实现的梦

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#119]
文件系统已经建立，可以勾上了。

**Comment by User782Tec** [comment]
不过这个不是真的文件系统（bushi）
等tjy

**Comment by User782Tec** [comment]
不过这个不是真的文件系统（bushi）
等tjy

**Comment by NebulaTechs** [comment]
> 不过这个不是真的文件系统（bushi） 等tjy

是的，C盘都删光了，系统还能正常运转。。。(bushi)

**Comment by NebulaTechs** [comment]
还能随意创建同名文件(夹)，创建包含禁止字符的文件(夹)。。。

**Comment by User782Tec** [comment]
> 还能随意创建同名文件(夹)，创建包含禁止字符的文件(夹)。。。

这个你去问一下 @NB-Group 是咋做的(bushi

> 是的，C盘都删光了，系统还能正常运转。。。(bushi)

众所周知，内存里还有(bushi

**Comment by NB-Group** [comment]
> 还能随意创建同名文件(夹)，创建包含禁止字符的文件(夹)。。。

![image](https://github.com/tjy-gitnub/win12/assets/121747915/0a2b849d-af52-488c-a8cb-285fbf4d1eb5)
很明显重名不了好吧

**Comment by lh11117** [comment]
《关于100多G的C盘删完以后剩余空间仍然只有20多G这件事》

**Comment by NB-Group** [comment]
隐藏文件（误）

**Comment by NebulaTechs** [comment]
> > 还能随意创建同名文件(夹)，创建包含禁止字符的文件(夹)。。。
> 
> ![image](http://user-images.githubusercontent.com/121747915/255775476-0a2b849d-af52-488c-a8cb-285fbf4d1eb5.png) 很明显重名不了好吧

那也许是你发布了新版本，我用的时候是可以的。
