### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#122]
文件夹又可以重名了，可能是复制粘贴的bug(其实具体发作原因我也不知道)代码是否有bug？

**Comment by NebulaTechs** [comment]
照片都发不上来。。。。。

**Comment by User782Tec** [comment]
再去问问 @NB-Group （bushi）

**Comment by User782Tec** [comment]
However, are you a student? Or do you work?

**Comment by NebulaTechs** [comment]
Student.

**Comment by NebulaTechs** [comment]
@NB-Group 在不在呀？

**Comment by User782Tec** [comment]
我叫过他了
应该马上就来了

**Comment by NB-Group** [comment]
我来了

**Comment by User782Tec** [comment]
> 我来了

赶紧修bug吖（

**Comment by NB-Group** [comment]
我试了好几次，它不是不能重名吗，你能提供一下触发这个bug的过程吗

**Comment by NebulaTechs** [comment]
我也忘记了。。。以后使用时会注意一下的。

**Comment by NebulaTechs** [comment]
> 我也忘记了。。。以后使用时会注意一下的。

我现在就去试。
另外我又发现了一个大bug:新建一个新文本文档，不重命名，再次创建就会显示文件名重复。
$建议的方法:不要提示文件名重复，后面加一个(2)。$

**Comment by NebulaTechs** [comment]
哎呀，不小心关闭了。

**Comment by NebulaTechs** [comment]
我知道是怎么样了:首先，在C盘创建一个Microsoft文件夹，将其复制到D盘，此时不会提示文件名重复，打开D盘原有的Microsoft文件夹，再退出来时，就会有两个同名的Microsoft文件夹。

**Comment by NebulaTechs** [comment]
当然也可能比这个更简单，至少我看到是这样的。(不过也许是我机子的问题，毕竟这配置呀，我无言以对)

**Comment by NebulaTechs** [comment]
另外，重名的两个文件夹会同步内容。

**Comment by User782Tec** [comment]
按照该方法，未能成功复现该bug

**Comment by NebulaTechs** [comment]
那就说明是我机子的问题。。。。。。

**Comment by NebulaTechs** [comment]
> > 我也忘记了。。。以后使用时会注意一下的。
> 
> 我现在就去试。 另外我又发现了一个大bug:新建一个新文本文档，不重命名，再次创建就会显示文件名重复。 建议的方法不要提示文件名重复，后面加一个。建议的方法:不要提示文件名重复，后面加一个(2)。

这个问题复现成功了吗？

**Comment by User782Tec** [comment]
你这为啥弄这么多次（

**Comment by NebulaTechs** [comment]
这个嘛。。。对了，你们试出来了吗？

**Comment by User782Tec** [comment]
没有
(可以提供一下浏览器版本?)

**Comment by NebulaTechs** [comment]
最新版本Edge.
看来是我机子的问题。。。。。。。。。。。

**Comment by User782Tec** [comment]
那我就不到了(

**Comment by NB-Group** [comment]
试不出来
