### ISSUE TITLE
@user782tec

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#126]
你使用Nativefier打包的吗？

**Comment by User782Tec** [comment]
Electron（好像Nativefier基于Electron）

**Comment by NebulaTechs** [comment]
oh,能打包Windows版吗？我打包报错 (悲

**Comment by User782Tec** [comment]
我看看吧，因为我现在手头没有windows电脑QAQ

**Comment by NebulaTechs** [comment]
那你就把命令发一下吧，native不行我试试electron。

**Comment by Haifeng320** [comment]
> oh，能打包Windows版吗？我打包报错 （悲

Windows可以用inno setup（不过似乎没有中文（悲

**Comment by NebulaTechs** [comment]
不可能吧，inno setup就是个安装包制作器呀？

**Comment by Haifeng320** [comment]
个人认为打个包再用系统浏览器打开就可以~~应付~~了（bushi

**Comment by Haifeng320** [comment]
有总比没有好 $（我为了尝试win12特地装了debian的虚拟机）$

**Comment by User782Tec** [comment]
> 个人认为打个包再用系统浏览器打开就可以~应付~了（bushi

6
