### ISSUE TITLE
一个诡异的现象

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#127]
我发现似乎没有年龄>=18的人来参与你们的项目，这是什么情况？是缺乏宣传吗？如果是的话，可以在YouTube上宣传，但可能需要~~翻墙~~ 出国留学。

**Comment by NebulaTechs** [comment]
[Doge]

**Comment by User782Tec** [comment]
我不到（
我觉得可能因为我们用的都是中文 所以老外看不懂（
老外看不懂的话 再怎么宣传也只能吸引国人（
我们已经在筹划推出英文版 目前拟定让我来翻译这个项目

**Comment by User782Tec** [comment]
（话说你的年龄也<18吗（bs

**Comment by User782Tec** [comment]
（我们现在准备在bilibili上发布宣传片）

**Comment by NebulaTechs** [comment]
翻译工作我可以试一下，我比较有耐心。
(但是我你有可能把代码粘贴到bing翻译直接翻译成英语[doge])

**Comment by User782Tec** [comment]
>  (但是我你有可能把代码粘贴到bing翻译直接翻译成英语[doge])

关键字&函数：6

**Comment by User782Tec** [comment]
（话说你多大？）

**Comment by NebulaTechs** [comment]
12

**Comment by NebulaTechs** [comment]
我对HTML不精通，所以我只能写js。。
HTML语言调用还是要麻烦你的。

**Comment by User782Tec** [comment]
> 12

哇
和我一样大！

> 我对HTML不精通，所以我只能写js。。 HTML语言调用还是要麻烦你的。

行

**Comment by NebulaTechs** [comment]
> > 12
> 
> 哇 和我一样大！
> 
> > 我对HTML不精通，所以我只能写js。。 HTML语言调用还是要麻烦你的。
> 
> 行

我会尽量在这周日提交zh-hans.js和en-us.js

**Comment by tjy-gitnub** [comment]
呃，@NebulaTechs，我们计划把你拉进teams的团队里面，
https://teams.live.com/l/invite/FBAbuRBpg5OKy32fwQ
可以考虑一下？
