### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Haifeng320** [win12-online/win12#128]
1.BIOS，可以借鉴win7simu（https://win7simu.visnalize.com/）
2.文件系统，可以借鉴windows96（https://windows96.net/）

**Comment by Haifeng320** [comment]
又双叒叕发现一个问题
![问题](https://github.com/tjy-gitnub/win12/assets/53048304/698def44-32f3-4545-b43f-41c85a42b03b)

**Comment by Haifeng320** [comment]
对了，如果没有密码开机一般会直接登录。而且win12似乎没有锁屏界面（就是显示时间的那个）

**Comment by NebulaTechs** [comment]
Https://98.js.org/

**Comment by Haifeng320** [comment]
IBM PC & Windows 1.0 ~ Windows 95: https://pcjs.org



Windows 93: http://www.windows93.net/



Windows 96: https://windows96.net/



Windows 98: https://98.js.org/



Windows 95 ~ XP & Mac OS X: http://www.virtualdesktop.org



Windows XP: https://winxp.vercel.app/



https://lrusso.github.io/VirtualXP/VirtualXP.htm



Windows 7: http://win7simu.visnalize.com/



Windows 11: https://win11.blueedge.me/Win11



Windows 12 (Concept): https://win12.conceptualize.app/



https://tjy-gitnub.github.io/win12/desktop.html



macOS: https://macos-web.app/



https://page-osrc-85b825a0e1bf658d8e059bc4f7d1adce.osrc.com/



System 7：https://system7.app/



Mac OS 8: https://macos8.app/



Mac OS 9: https://macos9.app/



Android: https://android11react.osrc.com/



Ubuntu: https://page-osrc-f098d70278d187eb15fec33f71c49868.osrc.com/



[doge][doge]

**Comment by NebulaTechs** [comment]
issues::ERR_REQUEST_FAILED

**Comment by NebulaTechs** [comment]
你应该懂的。
