### ISSUE TITLE
浏览器

### ISSUE THREAD

**Issue by yiliabai** [win12-online/win12#13]
![屏幕截图 2022-12-23 192154](https://user-images.githubusercontent.com/121293136/209327621-d9c81aed-a8e6-4c58-944f-6906f8491e4b.png)
图标变亮点

**Comment by yiliabai** [comment]
建议你把图标更新一下
https://icons8.com/icons/fluency

**Comment by yiliabai** [comment]
建议你把图标更新一下
https://icons8.com/icons/fluency
![Uploading 屏幕截图 2022-12-23 192351.png…]()

**Comment by yiliabai** [comment]
建议你把图标更新一下
https://icons8.com/icons/fluency
![屏幕截图 2022-12-23 192351](https://user-images.githubusercontent.com/121293136/209328141-dc4987cd-e610-4a35-b551-5132ea6a63b0.png)

**Comment by yiliabai** [comment]
你需要整一个浏览器
![7ef657a9-a4b8-4a49-87b3-795f93c63000](https://user-images.githubusercontent.com/121293136/209329361-c43d91c7-e1c0-4960-aceb-e09cf6dce8c4.png)

**Comment by tjy-gitnub** [comment]
emm...
这个图标似乎已经是最新的win11的了欸
这个浏览器...怎么...感觉...怪怪的？
啊！它不是长这样的？
![image](https://user-images.githubusercontent.com/71509955/209436046-4c5dfa3a-5f71-4577-be89-3dafc8e38684.png)
好吧，浏览器以后会有的。。。

**Comment by Samtjs** [comment]
不会的话可以从geekprank开源项目里找！打开Github搜geekprank就行了

**Comment by User782Tec** [comment]
浏览器好啦！（虽然早好了233333
