### ISSUE TITLE
关于teams的小问题

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#131]
昨天电脑登录没问题，今天手机Microsoft报错：
我们无法完成你的请求
unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.

**Comment by NebulaTechs** [comment]
你们是不是关闭了通道？

**Comment by User782Tec** [comment]
手机不能登录Teams

可以试一下网页版

**Comment by NebulaTechs** [comment]
网页版进不去

**Comment by NebulaTechs** [comment]
麻烦给个通道

**Comment by NebulaTechs** [comment]
嗯。你的浏览器版本不受支持。最快的解决方法? 下载 mobile 应用。

**Comment by NebulaTechs** [comment]
￼

**Comment by NebulaTechs** [comment]
哪个最好？
- [x] Teams
- [ ] WeChat 
- [ ] DingTalk
- [ ] Mail

**Comment by User782Tec** [comment]
那你还是用电脑吧（
