### ISSUE TITLE
一个新闻

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#133]
- [x] 我已阅读并同意[最终用户协议](https://bilibili.com/) 和[隐私政策](https://youtube.com/) 
- [x] 我已准备好接受巨大冲击
- [x] 我已准备好将其载入史册
勾选以上复选框后，我会将新闻发到issues里（如有特殊需求可以让我发邮箱里）。

**Comment by User782Tec** [comment]
...?

**Comment by NebulaTechs** [comment]
今日凌晨，Blender推出7.0版本,Maya该何去何从？
