### ISSUE TITLE
我为你们做了一个win12安卓版

### ISSUE THREAD

**Issue by lh11117** [win12-online/win12#136]
上链接：https://www.123pan.com/s/BpOiVv-0E5Q3.html

提示：autojs打包的，可能报毒

希望tjy可以添加到release里面

@tjy-gitnub

**Comment by lh11117** [comment]
如果需要，我甚至可以做一个windows版

之前做了一个，基于pyqt的，但是都能卡出翔来

需要我可以用C# form写一个

**Comment by tjy-gitnub** [comment]
你这是针对api几的啊。。
![image](https://github.com/tjy-gitnub/win12/assets/71509955/6e17ca9c-7693-4038-a29d-ec9d19728907)
是本地网页存下来不用联网的吗还是要联网才能访问？

**Comment by lh11117** [comment]
用autojs打包的，安卓10正常运行

**Comment by lh11117** [comment]
可能需要联网加载

**Comment by lh11117** [comment]
对了，请教一下，android版打开一直转圈，如何移除转圈界面，直接到登录页面？
@tjy-gitnub

**Comment by User782Tec** [comment]
这个加载界面是为了加载资源而设置的
最好不要动（

**Comment by User782Tec** [comment]
安卓13测试无问题（maybe

**Comment by lh11117** [comment]
请问，可以考虑加入release吗？开源地址：https://github.com/lh11117/win12-for-android/

**Comment by skytdu** [comment]
我咋说咋一直进不去呢？原来必须要安卓10

**Comment by lh11117** [comment]
> 我咋说咋一直进不去呢？原来必须要安卓10

我这边也是一直卡在转圈页面
