### ISSUE TITLE
文件删除后磁盘容量建议进行变动，也提示不要删除系统文件

### ISSUE THREAD

**Issue by Eric-Wang0506** [win12-online/win12#137]
文件删除后磁盘容量建议进行变动，也提示不要删除系统文件

**Comment by NebulaTechs** [comment]
hmmm,本来就没有系统文件......
但是硬盘空间变动应该是不能实现的，至少暂时有点困难。

**Comment by NB-Group** [comment]
不懂不要乱说啊，这个还是可以实现的

**Comment by User782Tec** [comment]
> 不懂不要乱说啊，这个还是可以实现的

对啊对啊
从理论上来说不仅可以实现磁盘空间变动
还可以计算文件体积

**Comment by NebulaTechs** [comment]
我知道是可以实现的，但是可能有点儿难。考虑到磁盘空间过大，可能超过某些用户电脑。毕竟本来就没有系统文件，所以占用肯定特别的小。

**Comment by NB-Group** [comment]
？？？？你这话说的前后矛盾，一会说磁盘过大，一会说占用啸，自相矛盾，虎头蛇尾

**Comment by NB-Group** [comment]
@User782Tec 你为啥这么长时间不上teams啊，是有啥事情吗

**Comment by NB-Group** [comment]
> > 不懂不要乱说啊，这个还是可以实现的
> 
> 对啊对啊 从理论上来说不仅可以实现磁盘空间变动 还可以计算文件体积

对，而且现在没有实现上传文件和修改文件内容的功能，所以直接标称量子储存器，无限空间都行（确信

**Comment by NebulaTechs** [comment]
或者直接读取用户电脑数据（不过这可能真的就难了）。

**Comment by NebulaTechs** [comment]
> > > 不懂不要乱说啊，这个还是可以实现的
> > 
> > 
> > 对啊对啊 从理论上来说不仅可以实现磁盘空间变动 还可以计算文件体积
> 
> 对，而且现在没有实现上传文件和修改文件内容的功能，所以直接标称量子储存器，无限空间都行（确信

请问你懂不懂量子？量子不代表无限。

**Comment by NB-Group** [comment]
参考刘慈欣的《镜子》，超弦理论，物质的基本粒子不是点状物，而是无限细的一维弦，在十一维空间中振动，现在，我们可以操纵这根弦，沿其一维长度存贮和处理信息，这就是超弦计算机的原理。

在传统的电子计算机中的一块CPU，或一条内存，在超弦机中只是一个原子！超弦电路是基于粒子的十一维微观空间结构运行的，这种超空间微观矩阵，使人类拥有了几乎无限的运算和存贮能力。将过去的巨型计算机同超弦机相比，就如我们的十根手指头同那台巨型机相比一般。就是说，它可以将已知宇宙中的每一个基本粒子的状态都存贮起来并进行运算，就是说，如果是基于三维空间和一维时间，超弦机甚至能够在原子级别上模拟整个宇宙

**Comment by NB-Group** [comment]
上面说的方法可能有一些科幻了，现实中，量子储存器使用量子位（qubit）作为基本单元。Qubit 具有量子叠加态和量子纠缠等特性，使得量子储存器能够在某些情况下比经典储存器更加高效地存储和处理信息。

量子储存器的实现原理可以有多种方式，以下是几种常见的实现方式：

量子比特的物理实现：量子比特可以通过使用量子体系中的某个可控系统来实现。例如，超导电路中的 Josephson 结、离子阱中的离子、量子点中的自旋等系统都可以用作量子比特的物理实现。

量子叠加态：与经典比特只能处于 0 或 1 的状态不同，量子比特可以处于叠加态。叠加态表示 qubit 同时处于多个状态的线性组合。通过施加适当的操作，可以将 qubit 设置为叠加态，从而扩展了储存器的容量和表达能力。

量子纠缠：量子纠缠是量子力学的一项重要特性，它使得多个比特之间产生相互依赖的关系。通过纠缠态，两个或多个比特之间的状态是相互关联的，对一个比特进行操作会影响到其他比特。这种纠缠特性可以用于实现量子通信和量子计算中的并行计算，提高储存器的容量和处理速度。

量子态的保持和控制：为了储存和处理量子信息，需要能够有效地保持和控制量子比特的状态。量子储存器通常需要保持比特的量子态稳定，以防止信息丢失或退化。同时，通过施加适当的操作（例如量子门）来控制 qubit 的演化，从而进行量子计算或信息处理。

**Comment by NebulaTechs** [comment]
的确，但是现在谷歌的悬铃木计算机，也不过用了不到53个量子比特，所以距离实现量子存储器可能还需要100'000年，但是100'000年之后人类也许早已发现更好的存储介质。量子并不是样样精通，是有一定局限性的。另外！ChatGPT用的爽吗？

**Comment by NebulaTechs** [comment]
量子虽然可以装下整个宇宙，但这些对于人类太过于遥远。
建议出一些在500年内可以实现的技术。

**Comment by NB-Group** [comment]
首先人类的科技爆炸是你不能想象的，人类第一次工业革命在18世纪60年代，到现在也不过3世纪，另外，手写雀氏蛮爽的

**Comment by NB-Group** [comment]
三世纪以前人们连蒸汽机都没有

**Comment by NB-Group** [comment]
而且我的意思是相对来说，现在文件系统里能够使用的空间和动不动就几个G的内存空间相比雀氏就是量子储存器

**Comment by NebulaTechs** [comment]
也好，~~毕竟这样可以装13。。。~~

**Comment by User782Tec** [comment]
> @User782Tec 你为啥这么长时间不上teams啊，是有啥事情吗

我的傻逼平板上不去teams
电脑被收了
8月7日之后上线

**Comment by tjy-gitnub** [comment]
遇事不决，量子力学（
另外不要在issues里吵架啊

<hr>

这里给个答复，本项目重点在ui上，不会考虑这些细枝末节的功能问题，ui好看才是宗旨，所以暂不考虑。

**Comment by NebulaTechs** [comment]
.......
