### ISSUE TITLE
我为你们做了一个win12windows版

### ISSUE THREAD

**Issue by Haifeng320** [win12-online/win12#138]
太大了，我建了一个存储库，在[这](https://github.com/Haifeng320/win12-for-windows/releases/)下载

**Comment by NB-Group** [comment]
嗯，好

**Comment by NebulaTechs** [comment]
你是用什么做的？

**Comment by Haifeng320** [comment]
> 你是用什么做的？

nwjs-sdk+enigmavb，怎么做的我在[这里](https://github.com/Haifeng320/win12-for-windows)有写

**Comment by User782Tec** [comment]
很好啊（赞赏
就是软件包太大了
建议弄那种安装包

**Comment by Haifeng320** [comment]
。。。我试逝看

**Comment by Haifeng320** [comment]
ok了

**Comment by NebulaTechs** [comment]
你™开始和我一样了是吧？？

**Comment by NebulaTechs** [comment]
。。。。你™想干嘛？！。。。。。

**Comment by NebulaTechs** [comment]
@tjy-gitnub 麻烦关一下。。

**Comment by tjy-gitnub** [comment]
漂亮。
<hr>
在这里说一下啊：
就是做得非常好，表示赞赏。但是前面也说了，软件包较大，还有最重要的一点是没大用，还不如pwa来的方便，也没有离线使用和更新功能(?)，综上所述呢暂时不予采纳，还请谅解。
