### ISSUE TITLE
做微软商店

### ISSUE THREAD

**Issue by Flystra** [win12-online/win12#139]
windows 12微软商店(图片有彩蛋↓)
![屏幕截图 2023-08-01 120600](https://github.com/tjy-gitnub/win12/assets/126071197/db2f37c3-2732-4cad-8358-a573b1829010)

**Comment by ghost** [comment]
What?

**Comment by User782Tec** [comment]
我逝逝(毕竟是有一定难度的)

**Comment by ghost** [comment]
模仿Win11？

**Comment by ghost** [comment]
真的服了

**Comment by User782Tec** [comment]
也许是的(

**Comment by ghost** [comment]
我怀疑得问问 @tjy-gitnub

**Comment by User782Tec** [comment]
可以(
不过他最近比较忙
(可能)晚上6点以后才能回来

**Comment by ghost** [comment]
懂了

**Comment by ghost** [comment]
他是忙啥

**Comment by User782Tec** [comment]
我也不到(
他前几天在忙csp-s

**Comment by tjy-gitnub** [comment]
先算了吧，
我知道你们对win12有接近工作使用的巨大需求，但你们...能不能先，先凑合着用一下win11（恳切地

**Comment by NebulaTechs** [comment]
我们最近确实有一些需求

**Comment by tjy-gitnub** [comment]
好像已经加上了: )
