### ISSUE TITLE
win12无法保存使用进度

### ISSUE THREAD

**Issue by lao-liu-6** [win12-online/win12#14]
在关闭后可以保存，下一次启动时恢复上一次的布局（如在桌面的快捷方式、小组件等）

**Comment by lao-liu-6** [comment]
在部分浏览器中的下载的应用时会出现黑条
![image](https://user-images.githubusercontent.com/121339154/209433999-88768f53-3efa-4ae7-b5d9-b930902a1e6e.png)

**Comment by tjy-gitnub** [comment]
奥
这个是浏览器的问题？吗？
是chrome吗？这个。。。无伤大雅吧

**Comment by tjy-gitnub** [comment]
这个进度的话网页版功能不多，相信不会有人用来工作吧🙃
布局的话后期可以考虑
thanks for advising

**Comment by NB-Group** [comment]
以后做大做强，创了辉煌之后我还是选择拿它来工作（

**Comment by tjy-gitnub** [comment]
拭目以待。。。
