### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Flystra** [win12-online/win12#142]
我把一个软件创建了桌面链接，结果删不了了😭。能不能做一个删除的功能😁。

**Comment by NebulaTechs** [comment]
话说，@user782Tec，你Teams为什么那么久不上线？去北京了被那边的防火墙隔离了？

**Comment by User782Tec** [comment]
> 话说，@User782Tec，你Teams为什么那么久不上线？去北京了被那边的防火墙隔离了？

Maybe(
反正现在是彻底加载不出来了

**Comment by User782Tec** [comment]
不是上不去
是加载不出来

**Comment by User782Tec** [comment]
就是卡在了加载界面

**Comment by tjy-gitnub** [comment]
这个功能会加的，具体呢反正就最近或者之后吧（反正会加（

**Comment by User782Tec** [comment]
咱不想惹祸(

**Comment by tjy-gitnub** [comment]
设置 > 隐私和安全性
