### ISSUE TITLE
关于《文件系统》的建议

### ISSUE THREAD

**Issue by Haifeng320** [win12-online/win12#143]
1.system32下面文件没有
2.刷新界面后文件恢复原样
3.磁盘显示容量不变
4.建议加入上传本地文件的功能
5.模仿[这个](https://windows96.net/)

**Comment by NebulaTechs** [comment]
1，。。。知周所众，有隐藏文件（直说：你想累死开发者啊？！
2，cookie应该可以解决。
3，已经在策划了。
4，应该可以 `https://webos.tenfell.cn/`（如果能和他合作的话
5，我去问问。

**Comment by Haifeng320** [comment]
不急，v14.0之前应该可以搞好

**Comment by NebulaTechs** [comment]
不，v114.5.1版本之前可以搞好（bushi

**Comment by Haifeng320** [comment]
[win12.zip](https://github.com/tjy-gitnub/win12/files/12268829/win12.zip)
老古董(git reset 2e5d07dc0a8076bb675b13a0addf07a8c821653d --hard)

**Comment by NebulaTechs** [comment]
> [win12.zip](https://github.com/tjy-gitnub/win12/files/12268829/win12.zip)

so?
<img width="1027" alt="屏幕截图 2023-08-06 160814" src="https://github.com/tjy-gitnub/win12/assets/126944988/a7f0cfa2-0ad3-49e5-a310-d4d1fe98c588">

**Comment by NB-Group** [comment]
不要乱说
2，我们坚决不用cookie这种拉只因，用sessionStorage、localStorage
3，没有策划
3，不懂不要乱说，就是加载本地文件到内存里而已，什么webos.tenfell.cn，什么合作，统统不需要

**Comment by NB-Group** [comment]
不要乱说
2，我们坚决不用cookie这种拉只因，用sessionStorage、localStorage
3，没有策划
3，不懂不要乱说，就是加载本地文件到内存里而已，什么webos.tenfell.cn，什么合作，统统不需要

**Comment by NebulaTechs** [comment]
所以说你们要什么时候才能发布啊啊啊
