### ISSUE TITLE
对#138的延续

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#144]
漂亮。
<hr>
在这里说一下啊：
就是做得非常好，表示赞赏。但是前面也说了，软件包较大，还有最重要的一点是没大用，还不如pwa来的方便，也没有离线使用和更新功能(?)，综上所述呢暂时不予采纳，还请谅解。

_Originally posted by @tjy-gitnub in https://github.com/tjy-gitnub/win12/issues/138#issuecomment-1665485537_

**Comment by NebulaTechs** [comment]
会的人可以用electron打包（我已经把package.json写好了

**Comment by NebulaTechs** [comment]
[package.zip](https://github.com/tjy-gitnub/win12/files/12260686/package.zip)

**Comment by NebulaTechs** [comment]
其实有点用。。。让某些人（比如我开心一点。。

**Comment by User782Tec** [comment]
其实我会用electron打包
但是我没有windows电脑

**Comment by Haifeng320** [comment]
事先说明，我js只会helloworld。。。

**Comment by Haifeng320** [comment]
@User782Tec 你可以用虚拟~机~只因

**Comment by NebulaTechs** [comment]
> 其实我会用electron打包 但是我没有windows电脑
把命令发一下，让HF打包。

**Comment by tjy-gitnub** [comment]
pwa不香吗。淘神费力

**Comment by NebulaTechs** [comment]
..不能离线使用的就不香

**Comment by tjy-gitnub** [comment]
pwa可以离线和更新啊

**Comment by Haifeng320** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/53048304/e9e0dd04-2a2f-44be-82be-669e73b70617)
（v7.0.0）这有点问题。。。不是网页版吧。。。

**Comment by NebulaTechs** [comment]
> ![image](https://user-images.githubusercontent.com/53048304/259379966-e9e0dd04-2a2f-44be-82be-669e73b70617.png) （v7.0.0）这有点问题。。。不是网页版吧。。。

为什么用Ubuntu,不用Debain?

**Comment by User782Tec** [comment]
> @User782Tec 你可以用虚拟~机~只因

My computer is shit

**Comment by Haifeng320** [comment]
> > ![image](https://user-images.githubusercontent.com/53048304/259379966-e9e0dd04-2a2f-44be-82be-669e73b70617.png) （v7.0.0）这有点问题。。。不是网页版吧。。。
> 
> 为什么用Ubuntu,不用Debain?

反正dpkg -i都装的上，*ubuntu的内核跟debian一样*

**Comment by Haifeng320** [comment]
> > @User782Tec 你可以用虚拟~机~只因
> 
> My computer is shit

me too
![1](https://github.com/tjy-gitnub/win12/assets/53048304/c940fef6-a74c-4042-bf35-7d48d63c20e7)
![2](https://github.com/tjy-gitnub/win12/assets/53048304/6f642cc3-8766-46af-936e-6a4addcb56b9)
*虚拟机开机两分半，内存、磁盘、cpu使用率114%*

**Comment by User782Tec** [comment]
。
最关键是我是机械硬盘啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by NebulaTechs** [comment]
。。。。6

**Comment by Haifeng320** [comment]
对了，我用electron打包了下，你们[看看](https://github.com/Haifeng320/win12-for-windows/releases/)

**Comment by NebulaTechs** [comment]
不错，这次果然小多了

**Comment by zijiwork** [comment]
https://github.com/dnsjia/luban

**Comment by super117893344p** [comment]
6  家里连好的电脑都不给配啊

**Comment by Mbilse** [comment]
> 。
> 最关键是我是机械硬盘啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

关键是我用w7呢...
