### ISSUE TITLE
部分图片在 electron 环境下无法正常显示

### ISSUE THREAD

**Issue by iewnfod** [win12-online/win12#155]
所有使用 `::before {content: "\f***"}` 的图片全都无法在自己本地的 electron 环境下显示
例如 开关机键的 `\f4ff`

测试环境：
* 设备：MacBook Pro 2020 M1
* 系统：MacOS 13.5
* 打包结果：[release](https://github.com/iewnfod/win12/releases)

初步怀疑是 `\f***` 的特殊图形无法被 electron 的 web engine 解析并正确显示，但不知道如何解决

问题样例：
| Web | Electron |
| ----- | -------- |
| ![WechatIMG1278](https://github.com/tjy-gitnub/win12/assets/108739262/50bf3d18-ec5d-4f02-bf6c-264b774a2c9c) | ![WechatIMG1276](https://github.com/tjy-gitnub/win12/assets/108739262/112f914a-2cc4-433d-94e0-58c01057cd9d) |

**Comment by NB-Group** [comment]
好的，我们尝试修复

**Comment by iewnfod** [comment]
你们自己release里面的那个版本有这个问题嘛？
你们应该也是用 Electron 打包的吧？

**Comment by User782Tec** [comment]
是用electron打包的
等会我去测试一下

**Comment by iewnfod** [comment]
此问题已成功解决

## 问题原因
由于 electron 或 web 代码的一些原因，导致在获取 bootstrap icons 字体文件时出现参数，因此 electron 无法正常读取到并返回所需文件

## 解决方法
自定义 file protocol，手动为字体文件去除参数，保证读取正常

```javascript
protocol.interceptFileProtocol('file', (request, callback) => {
    const url = request.url.substr(8).split('?');
    console.log(url);
    // 如果是字体文件，也就是以 woff / woff2 结尾
    // 把问号后面的东西都去掉，也就是去掉参数
    if (url[0].endsWith('.woff') || url[0].endsWith('.woff2')) {
        callback(decodeURI(url[0]));
    } else {
        // 否则返回正常的完整字符串
        callback(decodeURI(url.join('?')));
    }
}, (error) => {
    if (error) {
        console.log("Failed to register protocol. ");
    }
});
```

**Comment by NebulaTechs** [comment]
不是，在electron环境下根本进不去。

**Comment by iewnfod** [comment]
> 不是，在electron环境下根本进不去。

?
我进得去啊

**Comment by NebulaTechs** [comment]
我就一直卡在开机logo了，🆘。
