### ISSUE TITLE
右键菜单完善

### ISSUE THREAD

**Issue by Yellwo-Dog** [win12-online/win12#156]
1.在右键菜单内添加“新建”功能
2.在右键文件添加“打开”功能（就当个装饰也行）
3.在右键文件添加“属性”功能（同上）

**Comment by tjy-gitnub** [comment]
没大用，有误导效果

**Comment by tjy-gitnub** [comment]
还有，新建文件不是已经有了吗。。？

**Comment by Yellwo-Dog** [comment]
> 还有，新建文件不是已经有了吗。。？

emmmm，当时没发现
