### ISSUE TITLE
mica效果仍然需要完善

### ISSUE THREAD

**Issue by littlewhitecloud** [win12-online/win12#157]
在换完桌面壁纸以后任然是第一张背景的模糊效果
![image](https://github.com/tjy-gitnub/win12/assets/71159641/4908297e-ebc2-45bd-b240-8c2ab0f39f4c)

**Comment by tjy-gitnub** [comment]
《试验》
主题这边的适配还没跟上，毕竟不是正式效果

**Comment by littlewhitecloud** [comment]
实验的时候给点建议呗
窗口失去焦点的时候可以去除效果

**Comment by tjy-gitnub** [comment]
意思说把桌面也放进焦点排序？

**Comment by littlewhitecloud** [comment]
嗯

**Comment by tjy-gitnub** [comment]
确实有待完善，感谢反馈
