### ISSUE TITLE
Untitled Issues

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#159]
**实际上，我觉得，
`https://github.com/dice2o/BingGPT/`
和
`https://github.com/lencx/ChatGPT`
作为不同的开发者，外观如此相像，应该是同一种内核做成的应用。
这个应该也可以用这个内核做成应用。**
_（我就是Luke Zhang，ZSR-XXXXXXX@XXXXXXX.com）_

_Originally posted by @Github-Luke-Zhang in https://github.com/tjy-gitnub/win12/discussions/74#discussioncomment-6727356_

**Comment by User782Tec** [comment]
不理解

**Comment by tjy-gitnub** [comment]
虽然我不认识你，也不知道你在说啥，但我觉得你说得很对~

**Comment by NebulaTechs** [comment]
～
