### ISSUE TITLE
投稿新闻

### ISSUE THREAD

**Issue by XoQit** [win12-online/win12#161]
微软开发出 意念Window，可以靠意念操作！
![Uploading OIG (10).jpeg…]()

**Comment by User782Tec** [comment]
额...图片没上传完？

**Comment by XoQit** [comment]
微软开发出 意念Window，可以靠意念操作！
图片（bing生成）https://th.bing.com/th/id/OIG.FWgRA9e_Uh6BxVIgIjR.?pid=ImgGn
