### ISSUE TITLE
投稿App

### ISSUE THREAD

**Issue by XoQit** [win12-online/win12#162]
投稿app
名称 
LQ浏览器
图标https://th.bing.com/th/id/OIG.brB.63uW6L_dIkJ2e_I1?pid=ImgGn
源码（不支持上传HTML，只能这样了）
`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>浏览器</title>
    <style>
    #box {
      width: 200px;
      height: 200px;
      background-color: #3498db;
      border-radius: 50%;
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      opacity: 0.5;
      filter: blur(10px);
    }

    @keyframes fade {
      0% {
        opacity: 0.5;
      }
      50% {
        opacity: 1;
      }
      100% {
        opacity: 0.5;
      }
    }
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 500px;
        }

        .search-container {
            position: relative;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: rgba(255, 255, 255, 0.8);
            border-radius: 20px;
            padding: 10px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .search-container input[type="text"] {
            padding: 5px;
            border: none;
            background-color: transparent;
            border-radius: 5px;
            outline: none;
        }

        .search-container #search-engines {
            display: flex;
            margin-left: 10px;
        }

        .search-container .search-engine {
            padding: 5px 10px;
            border: none;
            background-color: transparent;
            cursor: pointer;
            outline: none;
        }

        .search-container .search-engine.active {
            background-color: lightgray;
        }
    </style>
</head>
<body>
    <div class="search-container">
        <input type="text" id="search-input" placeholder="ks：ylcldklns1">
        <div id="search-engines">
            <button class="search-engine" data-engine="bing">Bing</button>
            <button class="search-engine" data-engine="baidu">百度</button>
            <button class="search-engine" data-engine="ks">作者快手</button>
        </div>
        <button id="search-button">搜索</button>
    </div>
    <div id="search-results"></div>
 <div id="box" class="animated"></div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>
    <script>
    
        // 获取DOM元素
        const searchInput = document.getElementById('search-input');
        const searchEngines = document.getElementById('search-engines');
        const searchButton = document.getElementById('search-button');
        const searchResults = document.getElementById('search-results');

        // 设置搜索引擎数组
        const engines = [
            { name: 'bing', url: 'https://www.bing.com/search?q=' },
            { name: 'baidu', url: 'https://www.baidu.com/s?wd=' },
            { name: 'ks', url: 'https://v.kuaishou.com/VNatbO' },
        ];

        // 设置默认搜索引擎
        let activeEngine = engines[0];

        // 切换搜索引擎
        searchEngines.addEventListener('click', (e) => {
            const engine = e.target.dataset.engine;
            if(engine){
                activeEngine = engines.find(item => item.name === engine);
                const engineButtons = searchEngines.querySelectorAll('.search-engine');
                engineButtons.forEach(button => {
                    button.classList.remove('active');
                });
                e.target.classList.add('active');
            }
        });

        // 执行搜索
        searchButton.addEventListener('click', () => {
            const keyword = searchInput.value;
            const url = activeEngine.url + encodeURIComponent(keyword);
            window.open(url, '_blank');
            const inputContainer = searchInput.parentElement;
            inputContainer.style.top = '0';
            inputContainer.style.position = 'fixed';
            searchInput.value = '';
        });
        
    anime({
      targets: '#box',
      duration: 2000,
      keyframes: [
        { scale: 1 },
        { scale: 1.2 },
        { scale: 1 }
      ],
      loop: true,
      easing: 'easeInOutQuad'
    });
    </script>
</body>
</html>`

**Comment by NB-Group** [comment]
可以改完了提交一个PR呀

**Comment by User782Tec** [comment]
可以提交pr
(这个作者快手是谁
