### ISSUE TITLE
A new bug

### ISSUE THREAD

**Issue by lh11117** [win12-online/win12#164]
在复制的文件夹里面重命名，会影响到复制前的文件夹

例如，复制Windows到Program Files，进入复制后的C:/Program Files/windows，重命名C:/Program Files/windows/System32为System114，C:/windows目录里的system32文件夹不见了，变成了重命名后的system114

解决一下吧！

**Comment by lh11117** [comment]
更离谱的是，复制C:/Program Files/windows到c:/Program Files/windows/windows，竟然可以无限打开windows文件夹套娃。。
![image](https://github.com/tjy-gitnub/win12/assets/99455215/ac25767c-1f97-4369-9e14-708e88c4e76c)

**Comment by lh11117** [comment]
《文件汐统》

**Comment by User782Tec** [comment]
《././././././././././././*》
问 @NB-Group （

**Comment by lh11117** [comment]
@NB-Group 你看怎么办？

**Comment by NB-Group** [comment]
斯

**Comment by NB-Group** [comment]
让我康康哈

**Comment by NB-Group** [comment]
> 在复制的文件夹里面重命名，会影响到复制前的文件夹
> 
> 例如，复制Windows到Program Files，进入复制后的C:/Program Files/windows，重命名C:/Program Files/windows/System32为System114，C:/windows目录里的system32文件夹不见了，变成了重命名后的system114
> 
> 解决一下吧！

其实真正的windows也有这个bug，这个不算bug，实际上复制只复制了路径，你会发现把源文件删了就没办法黏贴了。

**Comment by fs523577192** [comment]
Windows 不会有这样的 bug 吧，除非是用 `mklink` 命令生成的符号链接或者软链接

**Comment by NB-Group** [comment]
你可以试试哦，确实有这个bug
