### ISSUE TITLE
【建议】建议添加特性[双击左上角关闭窗口]

### ISSUE THREAD

**Issue by Jingbing1030** [win12-online/win12#166]
希望沿用这个逻辑

**Comment by tjy-gitnub** [comment]
想到过，但是以现在的趋势win11在弃用这个逻辑了
而是懒（

**Comment by NebulaTechs** [comment]
What？我还从来没发现过！

**Comment by Jingbing1030** [comment]
> 想到过，但是以现在的趋势win11在弃用这个逻辑了 而是懒（

猜到了（

**Comment by Jingbing1030** [comment]
> 什么？我还从来没发现过！
> 
> 什么？我从来没有注意到！
![2023-08-17 22-38-54](https://github.com/tjy-gitnub/win12/assets/129979803/7fe08f02-a16e-473b-9170-46affd2acb4a)

**Comment by Haifeng320** [comment]
win10也有！
还有中键关标签页，打开应用（在任务栏上）
