### ISSUE TITLE
[漏洞]文件资源管理器

### ISSUE THREAD

**Issue by Haifeng320** [win12-online/win12#169]
## 描述

1. 在文件夹上右键显示`Open in a new tab`，应改为`在新标签页中打开`；
2. 在文件上右键没有用

## 重现

打开文件资源管理器，在文件(夹)上右键

## 测试环境

浏览器：Edge, Chrome, Chromium
浏览器版本：[edge](https://github.com/tjy-gitnub/win12/files/12385760/edge.txt) [chrome](https://github.com/tjy-gitnub/win12/files/12385764/chrome.txt) [chromium](https://github.com/tjy-gitnub/win12/files/12385766/chromium.txt)
操作系统：Microsoft Windows 10 企业版 版本22H2(内部版本19045.3271)

**Comment by User782Tec** [comment]
ok
感谢您的反馈

**Comment by User782Tec** [comment]
经测试可以正常在文件夹和文件上右键并能正确弹出右键菜单
请确认:
1. 您是用的是最新版本
2. 如果您用的是电脑，请尝试对准文件后右键或稍等一会
3. 您使用的不是iPad/iPhone等设备，因为这些设备不支持右键处理
4. 如果您是用的是其他类型的移动设备，请尝试长按

**Comment by Haifeng320** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/53048304/1fa650fe-9fd1-4e2a-a32a-331645671776)
![image](https://github.com/tjy-gitnub/win12/assets/53048304/dbcfc351-075c-4bd5-820d-8bc87d7c75f7)

**Comment by Haifeng320** [comment]
文件右键与空白右键一样。。。

**Comment by Haifeng320** [comment]
*（不小心关掉了*

**Comment by User782Tec** [comment]
好的
我去看一下

**Comment by User782Tec** [comment]
现已修复该bug
会随着下一版本发布
