### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by ghost** [win12-online/win12#171]
## 描述

同时打开终端和资源管理器，当焦点在终端上时，再点击资源管理器，焦点有可能不会移到资源管理器

## 重现

按以下步骤可重新复现该漏洞：

打卡终端和资源管理器，在终端随便输入点什么，再点击资源管理器（有可能不会成功

## 截图

 NULL

## 测试环境

浏览器：Chrome
浏览器版本：版本 109.0.5414.120（正式版本） （64 位）
操作系统：Windows 7

## 其他

无

**Comment by User782Tec** [comment]
测试未发现问题
建议附上录屏，以便更好地分析

**Comment by tjy-gitnub** [comment]
这个，标签页的标题栏似乎是有这个问题，下一个版本修复，感谢反馈~

**Comment by User782Tec** [comment]
该漏洞已被修复
