### ISSUE TITLE
一点点[建议]

### ISSUE THREAD

**Issue by Haifeng320** [win12-online/win12#178]
## 描述

运行加入打开链接的功能，如`ms-settings://`打开对应设置项，用edge打开`https://` `http://`链接，文件资源管理器打开`ftp://`链接；edge加入打开文件链接的功能（`file:///`)；设置位于`C:\Windows\ImmersiveControlPanel\SystemSettings.exe`，请移动；鼠标中键关闭标签页，在任务栏上打开应用；加入快捷键——文件资源管理器`F1`帮助`F2`重命名`F3`搜索`F4`打开路径`F5`刷新`F6`切换，edge`F5`软刷新`Ctrl+F5`硬刷新`Ctrl+R`软刷新`Ctrl+Shift+R`硬刷新`F11`全屏`F12`DevTools`Ctrl+W`关闭标签页（但都冲突了bs）；增加office，ms store，照片查看器，媒体播放器，类似@User782Tec /@user782的[audio-player](https://github.com/User782Tec/audio-player)；加入注销及锁定；vscode用https://vscode.dev/ ；夜间模式变黄；飞行模式关闭wifi蓝牙；wifi蓝牙关闭后图标改变。

## 方案

同上

**Comment by NebulaTechs** [comment]
第一条:我们试一试吧应该是行的，但可能有点儿困难。
第二条：我们试一试吧。
第三条：我们试一试吧。
第四条：不
第五条：Office和msstore的话，等我们买到服务器再说。
第六条：那个不支持嵌套。。。所以我们预计开发一款新的编辑器。。。(当然这不太可能成功
第七条：好的，感谢反馈。

**Comment by Haifeng320** [comment]
还有加入star-history
![star-history-2023822](https://github.com/tjy-gitnub/win12/assets/53048304/27cbe9a4-5a4b-4d68-a20a-1b7a9efc01b1)

**Comment by Haifeng320** [comment]
这™涨得也太快了吧。。。

**Comment by User782Tec** [comment]
然而不太能访问ftp
我们并不知道怎么实现检测中键(
正如你说的 快捷键都冲突了(
不要瞎说，msstore根本不要服务器，office可能要的
(好家伙我的摆烂项目都出来了(bushi)
vscode.dev没法嵌套 我们打算弄一个User782Tec/neutron-editor

**Comment by Haifeng320** [comment]
notepad`F5`插入时间，在第一行写`.LOG`自动插入时间
![image](https://github.com/tjy-gitnub/win12/assets/53048304/f7f7eb9f-0a8c-4008-bf90-2a0f73494202)

**Comment by Haifeng320** [comment]
```html
<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://api.star-history.com/svg?repos=tjy-gitnub/win12&type=Date&theme=dark" />
    <source media="(prefers-color-scheme: light)" srcset="https://api.star-history.com/svg?repos=tjy-gitnub/win12&type=Date" />
    <img alt="Star History Chart" src="https://api.star-history.com/svg?repos=tjy-gitnub/win12&type=Date" />
</picture>
```
实时[star-history](https://star-history.com/)
<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://api.star-history.com/svg?repos=tjy-gitnub/win12&type=Date&theme=dark" />
    <source media="(prefers-color-scheme: light)" srcset="https://api.star-history.com/svg?repos=tjy-gitnub/win12&type=Date" />
    <img alt="Star History Chart" src="https://api.star-history.com/svg?repos=tjy-gitnub/win12&type=Date" />
</picture>

**Comment by tjy-gitnub** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/71509955/75087e21-22fb-4f48-8681-b072e8e1ddec)
其他一些几乎无法实现了。。http:// 打开edge好像除外吧
