### ISSUE TITLE
计算器可以写js代码

### ISSUE THREAD

**Issue by siquan001** [win12-online/win12#18]
偶然发现的，计算器可以直接写js代码，按“=”就可以执行，就很离谱。

**Comment by tjy-gitnub** [comment]
哈哈...主要是我比较懒，直接eval的🙃

**Comment by User782Tec** [comment]
我也发现了（
https://github.com/tjy-gitnub/win12/issues/16#issuecomment-1368147316

**Comment by NB-Group** [comment]
> 哈哈...主要是我比较懒，直接eval的🙃

小心被xxs跨站脚本攻击哦

**Comment by User782Tec** [comment]
> > 哈哈...主要是我比较懒，直接eval的upside_down_face
> 
> 小心被xxs跨站脚本攻击哦

《 X X S 》

**Comment by NB-Group** [comment]
> > > 哈哈...主要是我比较懒，直接eval的upside_down_face
> > 
> > 
> > 小心被xxs跨站脚本攻击哦
> 
> 《 X X S 》

![image](https://github.com/tjy-gitnub/win12/assets/121747915/e6120c55-eb28-48ad-8b49-511d1fe135fb)

还有去看下那个聊天discussions，可以实现实时获取主题了
