### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by yxl6716** [win12-online/win12#180]
## 描述
点击电池进入操作中心，操作中心点击wifi、蓝牙等功能开启或关闭时，任务栏内的wifi、蓝牙图标没有同时显示或隐藏
（请简要描述一下建议）

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by yxl6716** [comment]
操作中心显示时，后面鼠标点击操作中心框以外的地方，操作中心应该自动隐藏

**Comment by tjy-gitnub** [comment]
第一条我只能说不要在意这些细节
至于焦点呢我目前还没有想到什么有效的措施，像右键菜单那样用input模拟焦点移动端工作又不太好。。

**Comment by wangzhe1997** [comment]
把点击电池隐藏操作中心的函数，放在整个document

**Comment by yxl6716** [comment]
把点击电池隐藏操作中心的函数，放在整个document，大概是这样：
// 获取 control 元素和整个文档对象
var control = $('#control');
var doc = $(document);
// 给整个文档对象添加点击事件监听器
doc.on('click', function(event) {
var target = $(event.target); // 获取被点击的元素
// 如果被点击的元素不是 control 元素或 control 元素的后代元素
if (target !== control && !control.find(target)) {
    control.removeClass('show-begin show');
}
});
