### ISSUE TITLE
[漏洞]edge无法无限嵌套网页

### ISSUE THREAD

**Issue by Wyatex** [win12-online/win12#181]
## 描述

打开edge，再打开win12这个项目，好像最多只能嵌套两层，然后就报错了。

## 重现

按以下步骤可重新复现该漏洞：

（请用步骤的方式描述一下如何重新复现该漏洞）

## 截图

![微信截图_20230822101616](https://github.com/tjy-gitnub/win12/assets/13297495/746e81db-4817-48e6-a08a-8cd2c6dd7039)

## 测试环境

浏览器：Edge 
浏览器版本：115.0.1901.203 (正式版本) (64 位)
操作系统：Windows 11 22H2

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
好的
感谢您的反馈

**Comment by tjy-gitnub** [comment]
浏览器限制，无能为力，感谢反馈
