### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Gary998065** [win12-online/win12#182]
Can I replace the Windows 12 command window with my Windows 10 command window

**Comment by Haifeng320** [comment]
翻译：`我可以将 Windows 12 命令窗口替换为我的 Windows 10 命令窗口吗`

**Comment by User782Tec** [comment]
Sorry, I cannot understand.

**Comment by tjy-gitnub** [comment]
What language are you speaking? I think it's not English for sure.

**Comment by ghost** [comment]
他说：我可以将 Windows 12 命令窗口替换为我的 Windows 10 命令窗口吗 @tjy-gitnub @User782Tec

**Comment by tjy-gitnub** [comment]
你说的是什么语言？我敢肯定这不是中文。
（意思是说把我们的窗口样式改成像win10那样？

**Comment by ghost** [comment]
@tjy-gitnub 你在搞笑吗？我不是中国人吗？！
可能是

**Comment by tjy-gitnub** [comment]
肖害，不咬激东，幽话豪蒿说，揪使幽店听补懂啊
不使亨哩节依司罢了

**Comment by ZigaoWang** [comment]
各位别太离谱好吧

**Comment by ZigaoWang** [comment]
反正这个命令应用没什么用，这个改了也没意义，所以我建议把这个PR关了吧，谢谢！

**Comment by ghost** [comment]
@tjy-gitnub 你说的什么语言？我敢肯定这不是中文。

**Comment by tjy-gitnub** [comment]
西的，折十喔们皇军的众蚊

**Comment by ghost** [comment]
@tjy-gitnub 我服了

**Comment by ZigaoWang** [comment]
都是“”帅哥“

**Comment by ghost** [comment]
又是你？！

**Comment by ZigaoWang** [comment]
交个朋友？

**Comment by ghost** [comment]
好啊

**Comment by ZigaoWang** [comment]
发我邮件：z@zigao.xyz
我加你微信（在这透露不太好）

**Comment by ghost** [comment]
OK，发了

**Comment by User782Tec** [comment]
6（默默注视（bushi

**Comment by ghost** [comment]
OK

**Comment by ghost** [comment]
@User782Tec 你也要？

**Comment by User782Tec** [comment]
我算了
我就是个路人（

**Comment by ZigaoWang** [comment]
@User782Tec 交个朋友？

**Comment by Gary998065** [comment]
Zigao Wang ***@***.***>于2023年9月9日 周六下午7:03写道：

**Comment by ZigaoWang** [comment]
？发我邮件：z@zigao.xyz

**Comment by User782Tec** [comment]
算了(

**Comment by owenporgs** [comment]
What on earth is going on.

**Comment by ZigaoWang** [comment]
lol

**Comment by ghost** [comment]
这怎么还说起英文了

**Comment by ZigaoWang** [comment]
@owenporgs Do i need to translate everything for ya? Their discussion was waaaaaaay toooooo hilarious u know?😂

**Comment by owenporgs** [comment]
@ZigaoWang No I can copy+paste into Google translate but I cant right-click and "translate to English" (it Was funny. but it took forever)
> Why are you still talking in English? (translated)

because we speak English
