### ISSUE TITLE
[漏洞]安装包

### ISSUE THREAD

**Issue by Haifeng320** [win12-online/win12#183]
## 描述

在树莓派上安装win12时遇到以下问题
```
pi@raspberrypi:~/Downloads $ sudo dpkg -i windows12_7.0.0_amd64.deb
dpkg-deb: 错误: 归档 windows12_7.0.0_amd64.deb 对成员 control.tar.zst 使用了未知的压缩，放弃操作
dpkg: 处理归档 windows12_7.0.0_amd64.deb (--install)时出错：
 dpkg-deb --control 子进程返回错误状态 2
在处理时有错误发生：
 windows12_7.0.0_amd64.deb
```

## 重现

按以下步骤可重新复现该漏洞：

1. 买一台树莓派
2. 下载安装`windows12_7.0.0_amd64.deb`

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/53048304/f445c78c-c0ae-47df-b300-a0036648ac53)

## 测试环境

~浏览器：~
~浏览器版本：~
操作系统：Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by User782Tec** [comment]
amd64是给采用了AMD64（x86-64）架构CPU的电脑用的
不是给树莓派（ARM架构）用的
（

**Comment by Haifeng320** [comment]
你能打包什么架构
- [x] amd64
- [ ] x86
- [ ] arm_v1
- [ ] arm_v2
- [ ] arm_v3
- [ ] arm_v4
- [ ] arm_v5
- [ ] arm_v6
- [ ] arm_v7
- [ ] arm64
- [ ] ia64
- [ ] mips
- [ ] mips64

**Comment by User782Tec** [comment]
我这只有amd64（x86_64）电脑 qwq
可能x86还能试一下
arm就say goodbye了

**Comment by Haifeng320** [comment]
https://zhuanlan.zhihu.com/p/616596556
看看这个qwq
