### ISSUE TITLE
[漏洞]无法使用移动端查看该项目

### ISSUE THREAD

**Issue by ghost** [win12-online/win12#186]
## 测试环境

浏览器：chrome
浏览器版本：91.0.4472.77
操作系统：Android 9.0 S5 Build/PKQ1.190319.001

**Comment by NebulaTechs** [comment]
请提供具体描述，建议包含图片

**Comment by ghost** [comment]
一直卡在开机界面

**Comment by User782Tec** [comment]
好的
感谢您的反馈

**Comment by ghost** [comment]
请在下一个版本（或者更快）更新，谢谢

**Comment by NebulaTechs** [comment]
> 一直卡在开机界面

应该没有问题，因为我的移动设备也经常需要加载很久。所以如果加载时间在两分钟内，应该没什么问题。

**Comment by tjy-gitnub** [comment]
主要是那个pyhon的影响，太慢了。。不过一次之后会缓存下来，后面就快了。
目前情况建议多多刷新几次

**Comment by ghost** [comment]
@tjy-gitnub @NebulaTechs who说没有问题了？
卡在界面好久了😭

**Comment by ghost** [comment]
刷新了一万次都没好
