### ISSUE TITLE
[漏洞]edge地址栏无法输入网址

### ISSUE THREAD

**Issue by ghost** [win12-online/win12#188]
## 描述

edge地址栏无法输入网址

## 重现

按以下步骤可重新复现该漏洞：

1. 打开edge
2. 随便输入网址

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/134162766/d166b389-c8ad-472c-936b-c49a9f9f1854)

## 测试环境

浏览器：Chrome
浏览器版本：116.0.5845.111 (正式版本) （64 位） (cohort: Stable) 
操作系统：Windows 10 Version 22H2 (Build 19045.3324)

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
经测试发现问题存在：
1. HTTP 问题，将“<http://github.com>”里的http改为https，以后会增加https自动检测
2. 由于跨域问题，无法访问部分网站（包括github.com），该问题无法解决
