### ISSUE TITLE
触屏拖拽窗口问题未完全解决

### ISSUE THREAD

**Issue by User782Tec** [win12-online/win12#19]
草，怎么还是拖不动（恼

**Comment by tjy-gitnub** [comment]
???麻烦详细一点
设备信号是什么？
浏览器？版本？
资源管理器的文件夹能打开吗？
谢谢

**Comment by User782Tec** [comment]
和Issue<https://github.com/tjy-gitnub/win12/issues/16>一样的配置
```
测试设备：

iPad7 系统版本：iPadOS 15.7

测试浏览器：

Chrome Beta109.0.5414.46
```
窗口还是拖不了
文件夹能打开

**Comment by tjy-gitnub** [comment]
啊这。。。

**Comment by tjy-gitnub** [comment]
你可以尝试一下
1.切换桌面版网站后刷新页面
2.不使用桌面版网站
看一下能不能解决问题
感谢

**Comment by User782Tec** [comment]
没用, 桌面版网站和移动版网站都拖拽不了
不知道咋回事

**Comment by User782Tec** [comment]
还有, 有时候拖拽时会触发其他事件(如下拉刷新, 左滑返回等), 非常影响拖拽窗口
这段代码(应该)能解决问题
```css
html {
    touch-action: none;
}
```

**Comment by tjy-gitnub** [comment]
桌面版也不行了？😲

**Comment by User782Tec** [comment]
(桌面版是说我那iPad上浏览器请求的桌面版网站, 电脑上可以正常拖拽)

**Comment by tjy-gitnub** [comment]
哦
那 可能是 ipad
比较
高级吧

**Comment by User782Tec** [comment]
此问题已在Commit<https://github.com/tjy-gitnub/win12/commit/e4d544a7d4c3ad5a07793092da927bcb481561ac>(Pull Request #41 )中解决。
