### ISSUE TITLE
[漏洞]关闭相机软件后摄像头不会自动关闭

### ISSUE THREAD

**Issue by daiziwen163** [win12-online/win12#191]
## 描述

关闭相机软件后摄像头不会自动关闭，一直保持打开状态

## 重现

按以下步骤可重新复现该漏洞：
您可以使用以下代码来关闭摄像头：

`// 获取MediaStream对象
var stream = video.srcObject;
// 获取所有轨道
var tracks = stream.getTracks();
// 停止所有轨道
tracks.forEach(function(track) {
  track.stop();
});
// 清空video元素的srcObject属性
video.srcObject = null;
`

## 截图

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：Edge
浏览器版本：115.0.1901.203 (正式版本) (64 位)
操作系统：Windows 11,

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
好的
感谢您的反馈
