### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by WoshiLaoDENG** [win12-online/win12#192]
## 描述

edge无法访问网页

## 重现

按以下步骤可重新复现该漏洞：打开Microsoft Edge ,输入www.baidu.com,会发现一直转圈

## 截图

<img width="958" alt="屏幕截图 2023-08-30 123409" src="https://github.com/tjy-gitnub/win12/assets/142273970/db4d6857-7af6-4262-b20f-cd9fcf88b5fb">

## 测试环境

浏览器：edge
浏览器版本：116.0.1938.62 (正式版本) (64 位)
操作系统：Windows11
## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
经测试发现问题存在：由于跨域问题，无法访问部分网站（包括baidu.com），该问题无法解决

感谢您的反馈！

**Comment by NebulaTechs** [comment]
跨域问题真的很麻烦，我上次为了调试看了一下控制台，里面一堆惨不忍睹的红色报错，很多都是跨域问题
