### ISSUE TITLE
命令行关机提示优化

### ISSUE THREAD

**Issue by Tsingkai** [win12-online/win12#195]
## 描述
  当使用 `shutdown -s -t 1` 来关机时，应该是1s后关机，但是页面上是 `0.16666666666666 分钟后关机`，，在时间的描述这块需要修改一下

## 方案
按照秒数的长短，使用类似`1小时15分24秒`、`5分2秒`、`3秒`类似的字样，自适应描述

**Comment by tjy-gitnub** [comment]
不要太细致了，windows原生就这样
我们其实是有意这样来模仿windows原生效果和本地感的（管你信不信

**Comment by lh11117** [comment]
@Tsingkai 
> ## 描述
> 当使用 `shutdown -s -t 1` 来关机时，应该是1s后关机，但是页面上是 `0.16666666666666 分钟后关机`，，在时间的描述这块需要修改一下
> 
> ## 方案
> 按照秒数的长短，使用类似`1小时15分24秒`、`5分2秒`、`3秒`类似的字样，自适应描述
> 
> ## 其他

我是win12 shutdown命令的作者，时间是用`秒数/60`来计算分钟的，我们后续会进行改进，感谢反馈意见

**Comment by NebulaTechs** [comment]
(
