### ISSUE TITLE
[漏洞] 打开任务管理器之后就会变卡，关闭了窗口还是卡

### ISSUE THREAD

**Issue by sigeer** [win12-online/win12#198]
## 描述

打开任务管理器之后就会变卡，关闭了窗口还是卡

## 重现

按以下步骤可重新复现该漏洞：

运行`taskmgr`后就开始卡顿，关闭后仍卡

## 测试环境

浏览器：Edge
浏览器版本：版本 116.0.1938.69 (正式版本) (64 位)

**Comment by User782Tec** [comment]
该问题将于下一版本修复
感谢您的反馈
