### ISSUE TITLE
[建议]关于项目结构和开发方式的一点疑问

### ISSUE THREAD

**Issue by HyperClockUp** [win12-online/win12#199]
## 描述

1、没看到代码格式化工具配置，修改代码的时候会自动格式化当前代码，其中有很多格式上的改动。同时发现项目里有一些格式化上的问题，是否有采用工程化开发的想法（webpack/vite系列）？

2、看到[https://github.com/tjy-gitnub/win12/issues/198](https://github.com/tjy-gitnub/win12/issues/198) 之后发现很多都是由于DOM操作过于频繁导致的卡顿，是否考虑过使用前端开发框架如React/Vue/Svelte等，减少DOM操作导致的页面卡顿？

3、当前开发的PR流程是什么，有交流群/社区来领取issue修复吗？

**Comment by User782Tec** [comment]
1. 我们目前使用vscode的默认格式化工具进行格式化js和css文件，但我们正在寻找一个更通用的格式化工具
2. 这个卡顿是因为我写的任务管理器Canvas渲染过于卡顿及关闭窗口后未及时删除渲染任务造成的，我们已经通过svg+offscreencanvas渲染并设置关闭后删除渲染任务的方式解决了这个问题，将在下一版本进行更新。由于我们的项目已经成型，所以我们暂时不打算更换框架
3. 目前没有交流群，但我们以后会增加，现在所有贡献都是自己提交的
感谢您的反馈

**Comment by HyperClockUp** [comment]
好的，感谢回复，请问现在欢迎社区贡献代码吗，还是仅供团队成员维护？我想试着给你们提一些PR，不知是否可以，以及如果可以需要遵循哪些规范？

----
看到了[贡献指南](https://github.com/tjy-gitnub/win12/blob/main/CONTRIBUTING.md)

**Comment by NB-Group** [comment]
可以贡献pr哦

**Comment by User782Tec** [comment]
任何人都可以贡献PR噢~
感谢您的支持!
