### ISSUE TITLE
一些BUG

### ISSUE THREAD

**Issue by MSEDGE-CORE** [win12-online/win12#2]
https://user-images.githubusercontent.com/74437699/190834100-9a8c2884-a3e1-4177-84a8-db2fa3ea5587.mp4
1.开始菜单和搜索框关闭的高度会闪一下（顺便可以改一下头像图标）
![account](https://user-images.githubusercontent.com/74437699/190834087-79e2f94c-0c80-45b5-82b7-1dbe7e5a0f66.png)
2.“关于”应用侧边滑入的新界面会导致旧界面的文字发生改变，新界面的动画不是非线性动画（如果我太细了可以当作没看见awa）

https://user-images.githubusercontent.com/74437699/190834615-1d701c23-ffb6-42f5-a63e-ae142ace5cbd.mp4
3.层级可以适当改一下不知道可不可以改
4.亚克力目前是截取窗口背后图片加模糊，建议直接截不带窗口的全屏加模糊加遮罩，观感会更好，要不然就会出现背景闪的情况

**Comment by tjy-gitnub** [comment]
非常感谢你的宝贵意见，我会在下一个版本中做出改进。
另外，第四条关于亚克力透明的实现有一些困难，不过我会尽量改善的。
再次感谢。
