### ISSUE TITLE
有盗版

### ISSUE THREAD

**Issue by Samtjs** [win12-online/win12#20]
![microsoft_office_word_logo_icon_145724](https://user-images.githubusercontent.com/121801304/211180563-0caaf5b2-1175-4f64-a8b9-f4a0cbfd628b.svg)
`[盗版Windows12](https://win12.osrc.com/) `

**Comment by tjy-gitnub** [comment]
这个叫fork
不叫盗版
它注明了作者和出处的

**Comment by tjy-gitnub** [comment]
这个图标哪来的啊
？

**Comment by Samtjs** [comment]
icons8

**Comment by Samtjs** [comment]
不过说实话，你得给他更新一下他那个才1.1.4版本。
