### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by TobyLi223** [win12-online/win12#200]
## 描述

（请描述一下这个漏洞是什么样的）
![屏幕截图 2023-09-04 215033](https://github.com/tjy-gitnub/win12/assets/96031501/947aa6ac-b64d-4827-b4bb-4fc01522d9bf)
![屏幕截图 2023-09-04 220446](https://github.com/tjy-gitnub/win12/assets/96031501/2e33a5ce-8e53-4330-821f-e1764b0a5fa9)
![屏幕截图 2023-09-04 215044](https://github.com/tjy-gitnub/win12/assets/96031501/684e2317-9d57-4b1f-ad8d-8135374b6fc8)

## 重现

按以下步骤可重新复现该漏洞：

（请用步骤的方式描述一下如何重新复现该漏洞）

## 截图

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]
浏览器版本：[请在这里填入浏览器的版本]
操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
1. 作者还没做呢qwq
2. 也还没做呢qwq
3. 我们应该会优化一下的
感谢您的反馈
