### ISSUE TITLE
[建议]可以一起做“将exe文件转化并执行”的功能

### ISSUE THREAD

**Issue by bombless** [win12-online/win12#208]
## 描述

看到前景规划里有“将exe文件转化并执行”这一段感觉可以一起做

## 方案

https://github.com/bombless/pe
我在这里有一个解析exe文件的项目，可以进一步开发整合过来。我倾向于用rust语言做这个功能，不过切换到js也没问题

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by huolongguo1O** [comment]
如果你研究过pe，应该对pe有些了解。
虽然pe由系统解析，但执行还是由cpu来干，否则exe就会像python一样慢。
然而，浏览器不支持直接执行字节码的功能，如果转换字节码，很难，再说需要各种库，其中还包含各种版权问题。

**Comment by NB-Group** [comment]
确实啊，各种软件用的都是windows提供的开发框架，难道我们要重写一遍？

**Comment by SinguJ** [comment]
建议做一款插件，该插件直接运行在操作系统上，以 Web Server 的方式为 `Win12` 界面提供底层支持。有了这个插件就可以实现很多功能了，比如实时交互的 Python 解释器、CMD 命令行等。甚至可以部署到一台 Linux 服务器上，让用户以远程的方式使用 `Win12`。

**Comment by SinguJ** [comment]
插件可以使用 Python 开发，用 Flask 框架，一些功能的实现方式就可以变成下面这样：

* `Python 解释器`：插件启动一个独立的 Python 解释器进程，然后把 `Win12` 中用户的输入全部转发到该进程中，并将进程的反馈转发给 `Win12`。 
* `命令行（终端）`：与 `Python 解释器` 类似，启动命令行进程，然后转发输入输出。
* `EXE 可执行程序`：找找一些虚拟系统的 Python 库，然后让 exe 程序运行在这个虚拟系统中，插件实时将虚拟系统的画面作为视频流推给 `Win12`。

**Comment by NB-Group** [comment]
命令行的话。。。
del *.* ？

虚拟系统的python库？高看py了吧

而且工作量+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by sml2** [comment]
等WebAsm技术更成熟应该会有其他解决

**Comment by NB-Group** [comment]
现在有能够直接运行c++代码的网页版解释器，但是程序调用的windows api还是个问题

**Comment by NB-Group** [comment]
现在大多数应用都是网页套壳，例如微信，新版qq，阿巴阿巴，经过反编译也许可以移植到win12里

**Comment by huolongguo1O** [comment]
> 现在大多数应用都是网页套壳，例如微信，新版qq，阿巴阿巴，经过反编译也许可以移植到win12里

至少有很大一部分不是网页，甚至可以说核心功能与网页无关

**Comment by User782Tec** [comment]
> > 现在大多数应用都是网页套壳，例如微信，新版qq，阿巴阿巴，经过反编译也许可以移植到win12里
> 
> 至少有很大一部分不是网页，甚至可以说核心功能与网页无关

我不知道这些软件是不是
但像vscode这样的软件基本就是用网页写的

**Comment by huolongguo1O** [comment]
> 等WebAsm技术更成熟应该会有其他解决

您是指[WebAssembly](https://developer.mozilla.org/zh-CN/docs/WebAssembly)吗
WebAsm和x86字节码完全不是一个东西，据我所知，webasm->x86容易，但反过来很难，很慢

**Comment by MCheping8108** [comment]
可以用tauri-app来打包exe程序
https://tauri.app/zh-cn/

**Comment by NB-Group** [comment]
不不不，这个功能最主要的问题是程序的API，我们需要逐个重新实现。
