### ISSUE TITLE
[建议] 尽快使用格式化工具统一代码规范

### ISSUE THREAD

**Issue by bd-dxg** [win12-online/win12#209]
## 描述

尽快使用格式化工具统一代码规范, 我阅读了提交规范,里面提到了
> 请尽量不要使用格式化工具格式化HTML文件
对于JavaScript和CSS文件，可以使用Visual Studio Code自带的格式化工具格式化

这在开源项目里是非常让人困扰, 不仅影响了团队协作开发, 也为想提供 Pr 的贡献者制造了额外的障碍

## 方案

建议使用 Prettier 工具来格式化代码, 具体规则可以讨论后决定,或者统一采用已经成熟的格式化方案

vscode中 prettier 插件安装地址: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

一些通用的格式化配置(可以参考),可以直接写在 vscode 的设置配置文件里,也可以在项目根目录创建`.prettierrc.json`文件进行配置

```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode", // 定义一个默认格式化程序
  "prettier.singleQuote": true, // 使用单引号
  "prettier.semi": false, // 禁止分号结尾
  "prettier.trailingComma": "es5", // 在结尾处如果是对象和数组，就追加逗号
  "prettier.printWidth": 120,
  "prettier.useTabs": false, // 缩进不使用tab，使用空格
  "prettier.arrowParens": "avoid", // 箭头函数参数只有一个时，不使用括号
  "prettier.quoteProps": "as-needed", // 只在需要的情况下给对象加引号
}

```

提供一个在线网址,方便你们指定格式化规则:https://prettier.io/playground/

**Comment by ahnuljz** [comment]
顶！ 要是能采用前端的工程化开发就更棒了！

**Comment by User782Tec** [comment]
我们曾经尝试过Prettier，但效果并不理想
感谢您的反馈

**Comment by JasonMo1** [comment]
具体不理想在哪些地方？ @User782Tec

**Comment by JasonMo1** [comment]
> 我们曾经尝试过Prettier，但效果并不理想 感谢您的反馈

具体不理想在哪些地方？

**Comment by AZCodingAccount** [comment]
我遇到了这个问题，现在我准备重新进行pr，我不小心把js文件给格式化了......
