### ISSUE TITLE
Office

### ISSUE THREAD

**Issue by Samtjs** [win12-online/win12#21]
弱弱的说一句:
你需要他(小声)
![icons8-microsoft-office-2019-256](https://user-images.githubusercontent.com/121801304/211180651-e3ff3831-35b2-4451-9db6-2f1deac9ed06.png)

**Comment by tjy-gitnub** [comment]
不，我不需要😏
这是一个。。很。。。。。大胆的想法
😏
这个的话计划 v2π.e.i 版本推出
尽请期待！🙃

**Comment by linnerA-2913** [comment]
...作者没这么厉害吧🙄🙄🙄

**Comment by Samtjs** [comment]
没事做个封面就行了像设置一样

**Comment by linnerA-2913** [comment]
《Microsoft office2021 for html》

**Comment by tjy-gitnub** [comment]
哈哈
以后会考虑的

**Comment by freedom-323** [comment]
结果真有 word 了(
