### ISSUE TITLE
基于作者的win12 我基于Rust 编译成了exe安装版本，大家可以体验一下！

### ISSUE THREAD

**Issue by pronouncing** [win12-online/win12#211]
基于作者的WIN12我编译成了exe安装版，大家可以体验一下！
![image](https://github.com/tjy-gitnub/win12/assets/3447053/260f35c0-d95c-42e9-b15c-fdf41c60831d)

![image](https://github.com/tjy-gitnub/win12/assets/3447053/8e6b01ac-c342-421e-8fb0-e240571915c9)

WIN12安装版附件下载：
[windows12.zip](https://github.com/tjy-gitnub/win12/files/12545438/windows12.zip)

**Comment by NebulaTechs** [comment]
感谢！

**Comment by lingr7** [comment]
这个是怎么打包的？

**Comment by Britz-rabbit** [comment]
> 

应该是tauri吧

**Comment by ghost** [comment]
这么牛？！
