### ISSUE TITLE
[错误]: 蓝屏进度百分比

### ISSUE THREAD

**Issue by huangbaishui** [win12-online/win12#212]
## 描述
蓝屏进度会超过100%

## 截图
![1694073914535](https://github.com/tjy-gitnub/win12/assets/138289944/0c2ec772-911b-489e-ab99-5811ab57a603)

## 测试环境

浏览器：Chrome
浏览器版本：116.0.5845.179
操作系统：windows 11

**Comment by liyouzhuo** [comment]
竟然还会蓝屏啊

**Comment by tjy-gitnub** [comment]
> 竟然还会蓝屏啊

是的呢，需要眼疾手快以迅雷不及掩耳之势在任务管理器结束System进程。

**Comment by ghost** [comment]
> > 竟然还会蓝屏啊
> 
> 是的呢，需要眼疾手快以迅雷不及掩耳之势在任务管理器结束System进程。

这个算彩蛋嘛

**Comment by Cassian824** [comment]
此问题已被 #242 修复

**Comment by User782Tec** [comment]
> > > 竟然还会蓝屏啊
> > 
> > 
> > 是的呢，需要眼疾手快以迅雷不及掩耳之势在任务管理器结束System进程。
> 
> 这个算彩蛋嘛

算的
