### ISSUE TITLE
底部任务栏无法点击桌面取消

### ISSUE THREAD

**Issue by liuyiming1124** [win12-online/win12#214]
## 描述

底部任务栏点击后，弹出的内容框无法直接点击桌面取消，只能再次点击任务栏图标才能关掉内容框

## 重现

按以下步骤可重新复现该漏洞：

1.点击底部任务栏放大镜
2.弹出内容框后再次点击桌面
3.内容框无法取消，只能再次点击底部任务栏放大镜进行取消

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/58318691/4eb90dfa-e4be-4540-95cf-90eee84371b6)

## 测试环境

浏览器：Edge
浏览器版本：116.0.1938.69 (正式版本) (64 位)
操作系统：Windows 11
## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
感谢您的反馈
我们日后会完善焦点

**Comment by tjy-gitnub** [comment]
移步 #221
