### ISSUE TITLE
[建议]悬浮窗长时间不隐藏

### ISSUE THREAD

**Issue by huangbaishui** [win12-online/win12#215]
## 描述
当删除小组件后tooltip悬浮框长时间显示

## 重现
1. 鼠标右键进入编辑模式
2. 添加任意小组件
3. 鼠标移入删除图标并等待tooltip悬浮框展示
4. 点击删除按钮, 删除小组件,但tooltip悬浮框未隐藏

## 截图
![image](https://github.com/tjy-gitnub/win12/assets/138289944/9a6af687-6cf9-4a5a-a65a-ca53fc0eae69)

**Comment by User782Tec** [comment]
感谢您的反馈
我们将在下一版本进行修复

**Comment by jobsofferings** [comment]
这个可以关了 @User782Tec
