### ISSUE TITLE
优化win12项目(3天前提交，目前仍未回复)[建议]

### ISSUE THREAD

**Issue by XueJourney** [win12-online/win12#219]
## 描述
尊敬的贵开发团队，您好！我注意到了贵团队的windows12项目，觉得创意非常好。然而，我也发现该项目的网站是搭建在GitHub上的。众所周知，GitHub的访问速度非常慢，这无疑会影响用户体验。此外，如果使用GitHub搭建网页，搜索引擎将无法对其进行索引。

## 方案
我知道对于初创团队以及学生团队来说，这些挑战可能非常大。因此，我愿意无偿帮助你们。我有一个位于香港的服务器，以及一个域名"windows12.top"。通过将网站索引到搜索引擎，可以提高网站的知名度；而使用香港的服务器则可以加快网站的访问速度。

## 其他
在此声明，我会注明原作者信息，已经在爱发电平台进行捐款。

**Comment by User782Tec** [comment]
要不您先进我们的开发团队吧，有些事在这里不太好说
