### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by szdatai** [win12-online/win12#222]
## 描述

首先为小作者景元点赞！
1. 建议不要叫Windows 12，改一个自主可控的产品名称和Logo；
2. 开发后台文件系统难度很大，建议考虑与国产操作系统如欧拉、HarmonyOS等。

真心期待这个产品能够成长为国产操作系统的一个组成部分！

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by tjy-gitnub** [comment]
过于离谱，鄙人暂且还无如此雄心壮志。
另提一句，两者似乎都是基于Linux的~
