### ISSUE TITLE
[建议]调解亮度和文件copy的问题

### ISSUE THREAD

**Issue by kemomi** [win12-online/win12#223]
## 描述
1.在亮度调到最高时候，点击夜间模式没有反应
2.在c盘新建文件时无法剪切到其他目录下
3.py.exe右键要添加一个管理员权限

## 方案

添加管理员权限

## 其他

初中生太6了，我初中还在河里挖泥，真是自愧不如

**Comment by tjy-gitnub** [comment]
管理员权限？？（Microsoft: win12已经没有管理员了~

**Comment by ghost** [comment]
那么admin是什么
admin:你把我当空气呀 @tjy-gitnub

**Comment by tjy-gitnub** [comment]
微软：不好意思，win12已经没有多用户啦~

**Comment by ghost** [comment]
@tjy-gitnub win12：😡😡😡
