### ISSUE TITLE
[建议] 很优秀，可以接入第三方的来实现打开office文件

### ISSUE THREAD

**Issue by andotorg** [win12-online/win12#224]
## 描述

（请简要描述一下建议）

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
感谢您的建议
由于我们资金不是非常充足，暂时无法搭建office服务器或接入第三方office

**Comment by xiaowumin-mark** [comment]
可以用我的 https://ow365.cn/?i=32441&furl=[这里加服务器上的文件链接]
这个只可以用tjy-gitnub.github.io域名上的文件
附加图片https://img1.imgtp.com/2023/10/04/Rd3yJD8a.png
![Uploading Snipaste_2023-10-04_23-30-29.png…]()

**Comment by tjy-gitnub** [comment]
移步 #340

**Comment by freedom-323** [comment]
考古一下，其实用 LibreOffice 不就好了

**Comment by xiaowumin-mark** [comment]
哈哈
