### ISSUE TITLE
[建议] 初三做到这样非常棒了！

### ISSUE THREAD

**Issue by mtsee** [win12-online/win12#225]
初三就可以做到这样，非常棒！个人建议可以使用模块化去开发，毕竟代码量是非常大的！

因为涉及到了多人开发，建议定义一个命名规范，避免id或者class名称冲突

加油！

**Comment by User782Tec** [comment]
感谢您的建议！

**Comment by tjy-gitnub** [comment]
谢谢！（鞠躬）非常感谢！（鞠躬）
