### ISSUE TITLE
窗口层叠问题仍未解决

### ISSUE THREAD

**Issue by Samtjs** [win12-online/win12#23]
打开文件管理器后打开设置，设置还是在文管之下，且永世不得翻身。
但也有可能是由于HTML语言的限制，这有可能没救了。。。
但是尽力而为吧，我也搜一些方法帮助您。
:）
βYE！

**Comment by tjy-gitnub** [comment]
不
不可能
impossible
绝对不可能
这个问题是解决了的
设备？系统？浏览器？版本？
麻烦详细一点，谢谢
