### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by Jimmy-Effe** [win12-online/win12#230]
## 描述

完善设置内相关功能（检查更新不知道是没有还是我加载不出来）

## 方案

暂无

## 其他

我希望能加入你们的开发团队，本人今年18，从13年开始玩软件开发，希望能为这个项目贡献力量

**Comment by lh11117** [comment]
我觉得你可以加入我们。具体等 @User782Tec  看了以后再说吧

**Comment by Jimmy-Effe** [comment]
好的

**Comment by lh11117** [comment]
我已经通知782了
<img width="715" alt="image" src="https://github.com/tjy-gitnub/win12/assets/99455215/90d96342-c895-4ee2-a59f-15e572aa5f95">

**Comment by Jimmy-Effe** [comment]
感谢

**Comment by lh11117** [comment]
对了，你会网页三件套吗（HTML+Javascript+CSS）？

**Comment by Jimmy-Effe** [comment]
js用的比较少，其他的都可以（你可以看看我github的项目，ps：几百年没有上传了）但是基本的都还可以，最近主要在搞php项目，mysql数据库方面比较熟

**Comment by User782Tec** [comment]
我们非常欢迎您加入我们的开发团队！
请您留下您的邮箱以便我们进行联系！

**Comment by Jimmy-Effe** [comment]
junchen.yi@icloud.com

**Comment by Jimmy-Effe** [comment]
或者用我的github的邮箱2896396216@qq.com

**Comment by User782Tec** [comment]
设置中的 Windows 更新基于Github API实现，部分地区可能无法访问或提示使用超限
感谢您的反馈！

**Comment by Jimmy-Effe** [comment]
那下一步是什么

**Comment by User782Tec** [comment]
我把邀请链接发送在您的qq邮箱上了
请查收

**Comment by Jimmy-Effe** [comment]
收到了，正在操作
