### ISSUE TITLE
[漏洞]在随机情况下，蓝屏进度百分比大于100%

### ISSUE THREAD

**Issue by Cassian824** [win12-online/win12#235]
## 描述

通过任务管理器杀死System进程后，会弹出恶搞式的在bluescreen.html中实现的蓝屏界面。经过测试，即使经过了[这次提交后](https://github.com/tjy-gitnub/win12/commit/d17876ce44c250f641ed79b401c114cb4cc65ee7)后，此问题仍未解决。
另请参见:(#212)
核心代码位于bluescreen.html的223-232行。

## 重现

通过任务管理器杀死System进程后，会弹出恶搞式的在bluescreen.html中实现的蓝屏界面。耐心等待，有几率在跳转到引导界面的前一秒看到异常的蓝屏百分比。

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/106961263/3c8fa946-5a98-4b80-bf8d-c9be50dcd375)

## 测试环境

浏览器：Chrome
浏览器版本：116.0.5845.180
操作系统：Windows 11

## 其他
我已经在我的本地解决此问题，我即将提交pull request(#237)

**Comment by Chenqijia1234** [comment]
问题已经解决

**Comment by Cassian824** [comment]
问题已经解决
