### ISSUE TITLE
[建议]申请加入

### ISSUE THREAD

**Issue by XueJourney** [win12-online/win12#240]
## 引言

贵团队，你好！我近期发现了贵团队的win12项目，项目整体来看是非常不错的，但我也发现了一点问题。

## 问题

贵团队并没有自己的企业邮箱，也没有自己的域名和服务器，这些我认为是一个网站最重要的东西，并且网站的SEO优化也做的不是很好

## 影响

企业邮箱可以方便团队内的沟通，域名可以绑定网站，离国内近一点的服务器可以增加访问速度

## 修复

我正好有一个windows12.top的域名，也有一个香港的服务器，并且也会SEO和运维，虽然我并没有太多的时间，但我认为如果有我的加入整个团队和网站会变得更好

## 其他

#219 lssues也是我提的

**Comment by XueJourney** [comment]
## 联系方式

- 邮箱：admin@xinghuo.website
- QQ：2432287445
- 推特：https://twitter.com/MrXue33081
- 电报：https://t.me/MrXue1

**Comment by NB-Group** [comment]
我们决定将你拉入开发组审核群，请下载teams同意并加入

**Comment by XueJourney** [comment]
已下载

**Comment by XueJourney** [comment]
我没有收到任何登录邀请

**Comment by NB-Group** [comment]
https://teams.live.com/l/invite/FEA0yrNkE_bAn-ddwM

**Comment by NB-Group** [comment]
请点击链接接受邀请

**Comment by XueJourney** [comment]
![Screenshot_20230910_194047](https://github.com/tjy-gitnub/win12/assets/143483602/797b5026-f31a-4b06-933a-eb8b9465e905)

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/87d486ca-d826-423f-9a35-a62a30f58169)这个是你？

**Comment by NB-Group** [comment]
哦，那人偷渡的

**Comment by XueJourney** [comment]
是我，但是我进不去

**Comment by NB-Group** [comment]
笑死，我已经把你删了（

**Comment by NB-Group** [comment]
https://teams.live.com/l/invite/FEA0yrNkE_bAn-ddwM

**Comment by NB-Group** [comment]
再逝一次吧

**Comment by XueJourney** [comment]
你这让我很难办诶
![Screenshot_20230910_200420](https://github.com/tjy-gitnub/win12/assets/143483602/2033064f-ad60-4a0a-a009-c8c544aeed6c)

**Comment by NB-Group** [comment]
你进了？

**Comment by XueJourney** [comment]
you are right

**Comment by enwali** [comment]
哈哈哈
