### ISSUE TITLE
[漏洞]无法关机

### ISSUE THREAD

**Issue by LeekinGTA** [win12-online/win12#245]
## 描述
怎么无法关机

**Comment by tjy-gitnub** [comment]
啊啊啊？你可以
1. 打开开始菜单，在电源选项中点击关机
2. 右键开始按钮，点击关机
3. 在运行/cmd中输入shutdown -s -t 0关机
希望能帮到您~

**Comment by Cyan-Coco** [comment]
> 啊啊啊？你可以
> 
> 1. 打开开始菜单，在电源选项中点击关机
> 2. 右键开始按钮，点击关机
> 3. 在运行/cmd中输入shutdown -s -t 0关机
>    希望能帮到您~

关了机如何开机，哈哈哈

**Comment by tjy-gitnub** [comment]
我们为你们贴心地设置了一个快捷键：`Alt+向左键` ~

**Comment by LeekinGTA** [comment]
只是黑屏，我的电脑怎么还开着。

**Comment by aa1555** [comment]
高
