### ISSUE TITLE
几只建议

### ISSUE THREAD

**Issue by Samtjs** [win12-online/win12#25]
1，把图标分辨率提升一下
www.icons8.com
2，`while True:
    input('')`
(把它变成HTML制成终端）
🕘🕚😀

**Comment by tjy-gitnub** [comment]
我其实是有高分辨率的图标的
因为github太慢，有意压缩的
这个终端是个好想法，下个版本😏

**Comment by User782Tec** [comment]
我做了个能用的终端（自豪
