### ISSUE TITLE
[建议]你好，这个壁纸太漂亮了啊，能不能单独把壁纸链接放出来，下载做电脑壁纸用

### ISSUE THREAD

**Issue by shanhaimyt** [win12-online/win12#252]
## 描述
大神你好，这个壁纸太漂亮了啊，想提取出来做电脑壁纸。
大神能不能把壁纸链接放出来，感谢啦！
或者发邮箱至shanhaimyt@gmail.com

**Comment by ghost** [comment]
[https://tjy-gitnub.github.io/win12/bg.svg](url)

**Comment by tjy-gitnub** [comment]
壁纸是项目根目录下的bg.svg和bg-dark.svg文件哦~

**Comment by shanhaimyt** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    大神您好：我将bg.svg文件转换为png或者jpg文件后是1：1的正方形，如何将其转换成3840*2160这种比例的尺寸呢？
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                shanhaimyt
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年09月11日 22:27
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [tjy-gitnub/win12] [建议]你好，这个壁纸太漂亮了啊，能不能单独把壁纸链接放出来，下载做电脑壁纸用 (Issue #252)
        
      
    
  
  
壁纸是项目根目录下的bg.svg和bg-dark.svg文件哦~

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by tjy-gitnub** [comment]
呐，你可以转了之后再裁剪。转的话个人习惯使用ppt~
