### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by Pandar1Young** [win12-online/win12#255]
## 描述

套娃（？失败

## 重现

按以下步骤可重新复现该漏洞：

访问https://tjy-gitnub.github.io/win12/desktop.html后（桌面），
用Edge再访问 https://tjy-gitnub.github.io/win12/desktop.html（套娃1）
再用套娃1的Edge访问https://tjy-gitnub.github.io/win12/desktop.html（套娃2）
套娃2无法显示

## 截图
![image](https://github.com/tjy-gitnub/win12/assets/33281511/c6b8d123-6392-4619-b4dc-160a690ede07)

## 测试环境

浏览器：Chrome
浏览器版本：lastest
操作系统：win11

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
浏览器有嵌套层数限制。。

**Comment by User782Tec** [comment]
该bug属实，我们会尽快修复的
感谢您的反馈

**Comment by tjy-gitnub** [comment]
这要取决于你的设备硬件和浏览器限制了，无能为力，抱歉
