### ISSUE TITLE
[建议]关于浏览器获取网站图标与名称解决方案

### ISSUE THREAD

**Issue by ssxfssxf2000** [win12-online/win12#256]
![tab](https://user-images.githubusercontent.com/52859841/236610204-34f82aee-4f92-4fda-8cff-8d57efb89045.jpg)

php可以实现，

后面加上输入的地址就可获取到网站的ICO       （有些网站获取不到，反外链等乱七八糟的，比如163就不行。）
https://www.cnwao.cn/fav/fav.php?url=

这个后面加输入的地址可以获取到网站的名称
https://www.cnwao.cn/fav/t.php?url=
打开试一试  https://www.cnwao.cn/fav/t.php?url=https://www.baidu.com

记得加完整地址，http:// or https://

**鉴于你这个是纯静态，所以用api是个很适合的解决方案。**

例子：（可以用回车键获取，或者实时，想怎么搞就怎么搞，代码省略，以下是获取网站ico部分代码，获取title类似。）
前面略......仅供参考......
var icon = $("<span>").addClass("link-icon").appendTo(a);
            var img = $("<img>").attr("src", "https://www.cnwao.cn/fav/fav.php?url=" + data.url + "").appendTo(icon).on("error", function() {
                $(this).attr("src", "abc.ico")//如果获取失败则显示自定义图标
            });

最后，
各位小伙加油！我们都老了！

**Comment by ssxfssxf2000** [comment]
这里打不出代码，自动屏蔽了，$("")里面的就是个标签，比如span、img什么的。

**Comment by NB-Group** [comment]
有跨域问题吗？

**Comment by ssxfssxf2000** [comment]
没

**Comment by NB-Group** [comment]
那可以哦，您的建议已经采纳，预计将在下个版本添加，感谢您的建议~
@User782Tec

**Comment by tjy-gitnub** [comment]
我们甚至斥巨资（6 元）用后端服务器专门获取网页标题。
（虽然内网穿透并不能正常连续工作。

**Comment by lingbopro** [comment]
但是理论上JavaScript应该是可以访问iframe里的文档的…

**Comment by tjy-gitnub** [comment]
这是个错误的理论

**Comment by lingbopro** [comment]
> 这是个错误的理论

不，事实上JavaScript确实可以获取到（参见[MDN Web Docs](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLIFrameElement/contentDocument)，但是仅限同源:(

**Comment by tjy-gitnub** [comment]
👍很会说废话
