### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by DuanGeGit** [win12-online/win12#259]
## 描述

建议开发一款能够直接使用的主题好，毕竟都是看好UI

## 方案

类似于一些美化工具

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by ghost** [comment]
StartAllBack?

**Comment by DuanGeGit** [comment]
> StartAllBack?

差不多就类似软件，还有好多比如nexus，star11，translucentTB等等..

**Comment by NB-Group** [comment]
额，这只是个网页啊，美化软件我们不会啊（

**Comment by DuanGeGit** [comment]
> 额，这只是个网页啊，美化软件我们不会啊（

所以是建议啊，网页的话实用性不是很强，只能体验到你们的新UI，但是不可以应用到自己的Windows上。要想做大做强的话还是偏实用点好
