### ISSUE TITLE
新闻

### ISSUE THREAD

**Issue by Samtjs** [win12-online/win12#26]
曾经的霸主如今无人问津！回顾IE传奇的一生。
这是真事儿，2023.2.14 微软将永久禁用IE。
图片资源:
![641](https://user-images.githubusercontent.com/121801304/211249612-7b59df7d-25b9-4e9e-83ac-76470659261e.jpeg)

**Comment by Samtjs** [comment]
不过这等大事我认为要做一个页面来吊唁IE。

**Comment by Samtjs** [comment]
所以辛苦一下作者啦。
😃🕙🕘🕚
我也尽可能找一些资料帮你
:)

**Comment by Samtjs** [comment]
不过我得承认:
![641 (1)](https://user-images.githubusercontent.com/121801304/211250552-1583a557-e66d-44e2-9fbb-1027ca09515d.jpeg)
死神:快点！再不走我可是会被开除的！

**Comment by Samtjs** [comment]
＞shell
![Bing-Emblem](https://user-images.githubusercontent.com/121801304/211251018-208866b9-946f-4f65-8d63-f6ad176be469.png)

**Comment by Samtjs** [comment]
对了建议把reload.html里的“正在关机”改为“正在重启”

**Comment by tjy-gitnub** [comment]
嗯，我知道

**Comment by tjy-gitnub** [comment]
嗯，我知道
视频都做好了准备14号发的b站上面😏
当天准备网站搞黑白(filter)
这个新闻要不当天搞吧
重启下个版本会改
感谢

**Comment by Samtjs** [comment]
建议制作`IE的故事`Desktop App
点进去直接进B站视频

**Comment by tjy-gitnub** [comment]
啊。。。可以可以

**Comment by Samtjs** [comment]
`while True:
input('>>>')`
