### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by lh11117** [win12-online/win12#262]
## 描述

点击设置-》更新-》历史版本会打开关于，但是设置窗口拥有了毛玻璃效果，再返回设置窗口，毛玻璃效果消失了

## 重现

按以下步骤可重新复现该漏洞：

点击设置-》更新-》历史版本

## 截图

https://github.com/tjy-gitnub/win12/assets/99455215/f491664c-e378-4ebe-a6a7-74d480b1e9c3

视频在线观看较慢，建议下载后在观看

## 测试环境

浏览器：chrome
浏览器版本：115.0.5790.110（正式版本） （64 位）
操作系统：Windows NT 10.0

## 其他

没有其他

**Comment by ghost** [comment]
我是用Edge，没bug

**Comment by lh11117** [comment]
抱歉，是我忘记了我开启了“多窗口透明”
