### ISSUE TITLE
[漏洞]编辑模式下计算器位置偏移bug

### ISSUE THREAD

**Issue by icebearss77** [win12-online/win12#267]
## 描述

（在编辑模式下移动计算器位置会出现偏移）

## 重现

按以下步骤可重新复现该漏洞：

鼠标右键单击，点击编辑模式，添加小组件计算器，此时点击计算机组件位置会出现偏移

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/86485291/f4493156-6154-4d05-806a-9d3cef5c56c1)

## 测试环境

浏览器：[Edge]
浏览器版本：[版本 117.0.2045.31 (正式版本) (64 位)]
操作系统：[Windows 11]

**Comment by suxmao** [comment]
这个我认为不是bug，应该设计如此，桌面小组件的移动是按网格移动的

**Comment by tjy-gitnub** [comment]
确实呢，这个设计的是自动按网格移动的。可能是因为你的设备是触屏（？

**Comment by icebearss77** [comment]
> 这个我认为不是bug，应该设计如此，桌面小组件的移动是按网格移动的

我的鼠标是放在删除图标左边的位置
![图片](https://github.com/tjy-gitnub/win12/assets/86485291/16a1d29d-18d5-4343-ad2c-e9f00b6e0024)
，但是他的网格却直接向右偏移了很多

**Comment by icebearss77** [comment]
> 确实呢，这个设计的是自动按网格移动的。可能是因为你的设备是触屏（？

我的是台式机啊，win11系统，我的鼠标是放在原来计算器上面
![图片](https://github.com/tjy-gitnub/win12/assets/86485291/7359d79f-c287-4144-84c5-c87b0c1b34fc)
位置的，没有往右移，但是他蓝框自动往右移了

**Comment by User782Tec** [comment]
感谢您的反馈
我们会尽快修复
