### ISSUE TITLE
[漏洞]一些漏洞

### ISSUE THREAD

**Issue by MoeCinnamo** [win12-online/win12#269]
## 描述

我有一個問題，我認為它是一個漏洞。
在打開Edge瀏覽器時，在搜索框輸入自定義網址，發現它一直加載；以及當我從bing搜索進入維基百科的時候，地址欄的地址不會顯示為維基百科地址反而是bing。
另外，剛才我在線體驗了你們的win12，發現運行速度過於緩慢。

## 重现

按以下步骤可重新复现该漏洞：

打開Edge，地址欄輸入google.com會發現不能打開Google，顯示一直轉圈的畫面。
打開Edge，搜索維基百科，點進去，會發現頁面已經改變，但是Edge的地址欄地址沒變。
使用iPad打開在線體驗頁面，嘗試連結藍芽鼠標點擊，會發現很緩慢。

## 截图

沒有

## 测试环境

浏览器：Safari
浏览器版本：605.1.15
操作系统：iPadOS 16.6

## 其他

沒有

**Comment by jincheng-xiao** [comment]
繁体中文写的不错

**Comment by tjy-gitnub** [comment]
这个呢，是因为浏览器的安全机制而被阻止获取其标题。因为浏览器的安全机制，父页面并不能监听到iframe的重定向等行为，同样也无法直接获取到网页的logo，标题之类的内容。不可抗力的，抱歉。
