### ISSUE TITLE
[漏洞]在重启Python后不会重置上下文

### ISSUE THREAD

**Issue by szdytom** [win12-online/win12#272]
## 描述

在重启Python后不会重置上下文。

## 重现

按以下步骤可重新复现该漏洞：

1. 打开应用Python3.10.3，输入 `a=1`。
2. 关闭该应用
3. 重新打开应用Python3.10.3，输入 `a`，得到输出 `1`。

## 截图

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：Mozilla Firefox
浏览器版本：117.0.1
操作系统：Manjaro Linux x86_64

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by ghost** [comment]
是有这个bug

**Comment by NB-Group** [comment]
经过测试发现确实有这个bug，您的建议已采纳，将在下个版本修复。
感谢您的建议~
@User782Tec

**Comment by ghost** [comment]
@NB-Group 你咋啥都求User782Tec?

**Comment by NB-Group** [comment]
我现在迫于学业的压力（确信），没时间写代码

**Comment by ghost** [comment]
我也是

**Comment by User782Tec** [comment]
> 我现在迫于学业的压力（确信），没时间写代码

我的压力比你重（确信

**Comment by tjy-gitnub** [comment]
所以你们打算怎么实现（

**Comment by NB-Group** [comment]
关闭窗口之后去重置一下历史记录变量呗，很简单啊（

**Comment by tjy-gitnub** [comment]
《很简单》

**Comment by NB-Group** [comment]
难道不是吗？（）这个新版py是782写的，我不大清楚他怎么实现的（
