### ISSUE TITLE
Support for multiple languages.

### ISSUE THREAD

**Issue by alxspiker** [win12-online/win12#274]
As long as you create a method for me to add other languages, I will spend the time to add more languages to support more people.

I am English and would love to use this on a raspberry pi 4b

**Comment by gaoe6661** [comment]
i think they are trying to translate it into different languages now: 

https://github.com/tjy-gitnub/win12/issues/275

**Comment by tjy-gitnub** [comment]
Thanks for your recognition, we are working on it. For the detailed progress, please ask @NebulaTechs .

**Comment by NebulaTechs** [comment]
due the huge amount of translate,It may take a while.

**Comment by NebulaTechs** [comment]
of course you can also participate translate.

**Comment by tjy-gitnub** [comment]
Well, actually, @NebulaTechs. According our plan, we can translate it together. Your job is just making a template……

**Comment by owenporgs** [comment]
Anyone have a idea when the translation will be done?

**Comment by NebulaTechs** [comment]
If nothing else, it could be completed by the end of the year.

**Comment by User782Tec** [comment]
@NebulaTechs Good luck~

**Comment by NebulaTechs** [comment]
> @NebulaTechs Good luck~

Thanks

**Comment by tjy-gitnub** [comment]
The translate work has been stoped because we are too lazy, thanks for your abvice and support
