### ISSUE TITLE
[建议] 無法切換多國語系

### ISSUE THREAD

**Issue by wastu01** [win12-online/win12#275]
## 描述

設定 > 時間和語言 > Windows 顯示語言 
切換語言後並無運作

## 方案

使用[jq-multi-lang](https://github.com/parsagachkardev/jq-multi-lang) 套件
https://github.com/parsagachkardev/jq-multi-lang

## 其他

希望能增加繁體中文

**Comment by NB-Group** [comment]
我们目前已经在进行翻译工作了，人工翻译。
您这个是机翻，我们要杜绝机翻（）
感谢您的建议~

**Comment by ghost** [comment]
那人工翻译，你们不累吗

**Comment by NebulaTechs** [comment]
我。。。在。。。翻译。。。。。（疲惫不堪

**Comment by NB-Group** [comment]
这位是御用翻译（

**Comment by tjy-gitnub** [comment]
我们目前已经放弃了翻译工作了。
但是您这个是机翻，我们仍然要杜绝机翻（）
再次感谢您的建议~

**Comment by wastu01** [comment]
好
