### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by 3605336948** [win12-online/win12#276]
## 描述

（请简要描述一下建议）
让手机访问时也能访问到win12系统里面，而不是转圈
## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）
如果是我的个人手机问题请无视，vivos10

**Comment by NB-Group** [comment]
确实有这个问题，我的红米（自带的浏览器）和苹果（Safari）手机确实都不能正常访问。
感谢您的反馈~
@User782Tec

**Comment by tjy-gitnub** [comment]
确实改换cdn了，极大影响了用户体验
（理论上网络可靠的话移动设备也是可以正常使用的

**Comment by ghost** [comment]
包括我的平板Chrome也无法访问

**Comment by ghost** [comment]
在那转啊转

**Comment by tjy-gitnub** [comment]
亲测，家低配红米手机一直转圈，小米鸿蒙秒上，鉴定为个人问题

**Comment by lingbopro** [comment]
我觉得应该是浏览器内核的问题，可能缺少支持的ES6语法或者缺少Web API，也不排除网络问题
