### ISSUE TITLE
建议搞个类似Cortana的语音助手，把它放在"Windows 12网页版 谭景元原创"这块位置

### ISSUE THREAD

**Issue by linnerA-2913** [win12-online/win12#28]
建议搞个类似Cortana的语音助手，把它放在"Windows 12网页版 谭景元原创"这块位置,可以参考一下https://zhuanlan.zhihu.com/p/371945331#:~:text=%E5%A6%82%E4%BD%95%E8%AE%A9%E4%BD%A0%E7%9A%84%E7%BD%91%E9%A1%B5%E7%94%9F%E6%88%90%E4%B8%80%E4%B8%AA%E8%AF%AD%E9%9F%B3%E5%8A%A9%E6%89%8B%201%201.%20%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%AB%20%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%AB%E7%9A%84%E6%8E%A5%E5%8F%A3%E4%B8%BA%20SpeechRecognition%20%E3%80%82%20%E7%9B%AE%E5%89%8D%E7%9A%84%E6%94%AF%E6%8C%81%E4%B8%8D%E6%98%AF%E5%BE%88%E5%AE%8C%E5%96%84%EF%BC%8C%E9%9C%80%E8%A6%81%E5%8A%A0%E4%B8%8A,%E6%9F%A5%E7%9C%8B%E3%80%82%20Github%20%E5%9C%B0%E5%9D%80%E4%B8%BA%3A%20github.com%2Fsuedar%2Ftalk%20%3D-%20The%20End%20-%3D

**Comment by tjy-gitnub** [comment]
我试了一下
挺高级的
但是它似乎只能识别英语😶

**Comment by linnerA-2913** [comment]
So You will be like them abandon......

**Comment by tjy-gitnub** [comment]
？

**Comment by linnerA-2913** [comment]
在语音助手和输入之间增加翻译模块，将翻译文字朗读到语音助手。(是不是有点麻烦）

**Comment by tjy-gitnub** [comment]
不是
我指的是它只能识别你说英语
除非你在脑子里装翻译模块
否则它只会识别出来与你说的话的读音相近的英语

**Comment by User782Tec** [comment]
通俗点讲就是空耳
