### ISSUE TITLE
添加适用于Windows的Classical Minecraft和原神启动！

### ISSUE THREAD

**Issue by HQYSteven** [win12-online/win12#280]
## 描述

添加适用于Windows的Classical Minecraft

## 方案

网页套壳
链接：https://classic.minecraft.net/?join=N8z9ymatmwvJ0UyG
链接：https://genshin.gamemcu.com/

## 其他

这些都是其他大牛做好的网站，直接用就可以

**Comment by User782Tec** [comment]
感谢您的建议
Classic Minecraft暂时无法网页套壳使用
原神貌似只有启动界面
故暂不采纳该建议
请见谅
