### ISSUE TITLE
[漏洞]无线套娃，套第三个的时候卡住了

### ISSUE THREAD

**Issue by CJohnSnow** [win12-online/win12#283]
## 描述

（请描述一下这个漏洞是什么样的）

## 重现

按以下步骤可重新复现该漏洞：

## 截图
![image](https://github.com/tjy-gitnub/win12/assets/51982566/967e8ad2-2ee0-46ed-a605-9a11a00b58e0)

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]
浏览器版本：[请在这里填入浏览器的版本]
操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NebulaTechs** [comment]
感谢！我们会尽可能在下一个版本修复。

**Comment by tjy-gitnub** [comment]
修复毛线，浏览器限制，无能为力，非常抱歉

**Comment by ghost** [comment]
那么为何陈思全的Win10online可以

**Comment by ghost** [comment]
siquan001.github.io/Win10online/windows

**Comment by User782Tec** [comment]
谁告诉你这是浏览器限制嗯哼?(

**Comment by tjy-gitnub** [comment]
> 谁告诉你这是浏览器限制嗯哼?(

那是啥限制？电脑配置限制？

**Comment by User782Tec** [comment]
当然是项目bug咯(

**Comment by HanXiaozeng** [comment]
> 当然是项目bug咯（

哈哈哈

**Comment by kooriookami** [comment]
其实这也不算bug吧，如果非要修复可以加一个嵌套层数的限制

**Comment by cwcw2424** [comment]
在一个页面中嵌套多个相同的 URL 的 iframe，可能会导致页面无法正常加载
浏览器在加载 iframe 时会遇到安全策略限制，防止恶意网站通过嵌套 iframe 进行恶意操作或滥用资源

**Comment by wbzd24** [comment]
网页有自带的Win12
