### ISSUE TITLE
组件删除后“删除按钮”停留至桌面

### ISSUE THREAD

**Issue by HanXiaozeng** [win12-online/win12#285]
## 描述
组件删除后“删除按钮”停留至桌面

## 重现
按以下步骤可重新复现该漏洞：
右键“桌面”点击“进入编辑模式”再次点击“添加小组件”按钮，点击任意组件（如计算器）完成后点击屏幕上方添加小组件和个性化右边的"X",点击小组件的"..."，停留在‘’垃圾桶‘’按钮上方一会（得久点，出现“删除”后），点击"垃圾桶"按钮即可出现。

**并且只能通过刷新网页进行修复。**
![image](https://github.com/tjy-gitnub/win12/assets/110365422/81830fba-1500-49d9-b17b-405b88a34d8a)

https://github.com/tjy-gitnub/win12/assets/110365422/fe99b8d0-cda9-48e3-a6e7-fce59e1c99bd

提示：可能有点卡，只能上传10mb以内的视频...
## 测试环境
浏览器 Edge 117.0.2045.43 (正式版本) (64 位)
版本	Windows 11 专业工作站版
版本	23H2
安装日期	‎2023/‎7/‎17
操作系统版本	22631.2361
体验	Windows Feature Experience Pack 1000.22674.1000.0

**Comment by User782Tec** [comment]
感谢您的反馈
该漏洞属实，我们会在下一版本修复
