### ISSUE TITLE
全选时除鼠标指着的应用外无法选择图标

### ISSUE THREAD

**Issue by HanXiaozeng** [win12-online/win12#286]
## 描述
全选时除鼠标指着的应用外无法选择图标

**描述的可能不太清楚**
## 重现
全选
## 视频

https://github.com/tjy-gitnub/win12/assets/110365422/96b7a90c-75a3-4d5e-81a1-aea5ec3654f9

## 测试环境
浏览器 Edge 117.0.2045.43 (正式版本) (64 位)
Windows 11 专业工作站版
版本	23H2
安装日期	‎2023/‎7/‎17
操作系统版本	22631.2361
体验	Windows Feature Experience Pack 1000.22674.1000.0

**Comment by User782Tec** [comment]
这是因为我们还没有真正实现全选或多选的功能(
我们可能会尽快实现
感谢您的反馈
