### ISSUE TITLE
[建议] 关于copilot的api

### ISSUE THREAD

**Issue by TianmuTNT** [win12-online/win12#287]
## 描述
换一个copilot的api
因为那个...我就不说了 很不稳定

## 方案
可以直接内嵌开源项目go-proxy-bingai
https://github.com/Harry-zklcdc/go-proxy-bingai

## 其他
可以直接使用作者搭好的 https://bingai.zklcdc.xyz/ 这个界面
自己搭建比较麻烦
（我 也是个初二生 玩ai玩了有半年多了

**Comment by lh11117** [comment]
<img width="887" alt="image" src="https://github.com/tjy-gitnub/win12/assets/99455215/1dbc5a6b-f009-4237-957d-4724f1c71167">
《关于AI搜索你好的回答这件事》

**Comment by TianmuTNT** [comment]
> <img alt="图像" width="887" src="https://user-images.githubusercontent.com/99455215/271740850-1dbc5a6b-f009-4237-957d-4724f1c71167.png"> 《关于AI搜索你好的回答这件事》

eeeeeee

**Comment by User782Tec** [comment]
我们之前尝试过
但是这个api通讯好像是加密传输的
而且之前有段时间用不了(

**Comment by TianmuTNT** [comment]
> 我们之前尝试过 但是这个api通讯好像是加密传输的 而且之前有段时间用不了(

可以直接把这个界面嵌入进来😅

**Comment by TianmuTNT** [comment]
没必要再去整人家的api

**Comment by User782Tec** [comment]
那就没有了嵌入式系统助手的灵魂了——不能直接操作系统或给出操作的建议

**Comment by TianmuTNT** [comment]
> 那就没有了嵌入式系统助手的灵魂了——不能直接操作系统或给出操作的建议

e

**Comment by codesdevs** [comment]
可以试试这个http://amgpt4.github.io

**Comment by NebulaTechs** [comment]
所以说怎么办

**Comment by User782Tec** [comment]
copilot ai要复活辣！

**Comment by NebulaTechs** [comment]
:)

**Comment by TianmuTNT** [comment]
所以解决方案是什么（

**Comment by User782Tec** [comment]
> copilot ai要复活辣！

@NB-Group 的服务器起死回生 要复活辣！

**Comment by NB-Group** [comment]
啊对对对，我正在重写，预计十年后应该可以使用

**Comment by TianmuTNT** [comment]
6

**Comment by tjy-gitnub** [comment]
写啥啊，服务器都没有（恼

**Comment by NB-Group** [comment]
我斥6元巨资买了个内网穿透啊，服务器就是我的电脑

**Comment by TianmuTNT** [comment]
随随便便用e5搭个服务器就行
最低的话只要100多
然后去跟电信客服申请个公网ip
反正我有个朋友的mc服务器就是这样的

**Comment by NB-Group** [comment]
没这个必要。
