### ISSUE TITLE
网页版右键出现edge菜单

### ISSUE THREAD

**Issue by HanXiaozeng** [win12-online/win12#288]
## 描述
tjy-gitnub.github.io/win12/desktop.html 这个网页无法正常右键显示桌面菜单
而本地版（**在https://github.com/tjy-gitnub/win12/上下载下来的网页**）可以右键显示windows12右键菜单
## 重现
打开 https://tjy-gitnub.github.io/win12/desktop.html
打开 index.html (本地下载下来的windows12)
## 截图&视频
**网页:**
![image](https://github.com/tjy-gitnub/win12/assets/110365422/180a00fd-0dcb-4c29-beb7-64f90b2811c5)
**本地:**
![image](https://github.com/tjy-gitnub/win12/assets/110365422/0c531539-7790-43e3-9611-eb4a90ae5641)

## 测试环境
Microsoft Edge  版本 117.0.2045.43 (正式版本) (64 位)
版本	Windows 11 专业工作站版
版本	23H2
安装日期	‎2023/‎7/‎17
操作系统版本	22631.2361
体验	Windows Feature Experience Pack 1000.22674.1000.0
处理器	11th Gen Intel(R) Core(TM) i7-1160G7 @ 1.20GHz   2.11 GHz
机带 RAM	16.0 GB (15.8 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

**Comment by User782Tec** [comment]
好的
感谢您的反馈

**Comment by tjy-gitnub** [comment]
所以有排查出来吗？

**Comment by tjy-gitnub** [comment]
没有遇到此类情况
