### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by lh11117** [win12-online/win12#289]
## 描述

使用Live Severe构建的win12网页没有登录界面

## 重现

按以下步骤可重新复现该漏洞：

1. 安装 Windows系统（安装了就跳过）
2. 安装 VS Code（安装了就跳过）
3. 安装 [Live Severe插件](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) （安装了就跳过）
4. 拉取 Win12 代码
5. 用VS Code 打开代码文件夹
6. 用VS Code编辑器打开 `desktop.html`文件
7. 右键
8. 选择`Open with Live Severe`
9. 此时会打开浏览器
10. 你会看到这个神奇的bug

## 截图

https://github.com/tjy-gitnub/win12/assets/99455215/12960c1c-2158-4460-8e4d-851bc4505ce3

## 测试环境

浏览器：Chrome   （后来发现Edge也是这样）
浏览器版本：版本 117.0.5938.92（正式版本） （64 位）
操作系统：Windows NT 10.0 22621.2361

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
我故意的(
为了开发的时候不用再去点这个登录浪费时间
然后于是我写了个小小的js程序
目的是为了检测是否处在开发模式，如果是就跳过登录，并且不进行页面缓存，以便实时调试

**Comment by lh11117** [comment]
。。。
