### ISSUE TITLE
FireFox问题

### ISSUE THREAD

**Issue by User782Tec** [win12-online/win12#29]
https://user-images.githubusercontent.com/115236204/211279057-3d489aa6-8af0-48b3-8d19-cd864fba4ef1.mp4

浏览器： Firefox108.0.2 (32 位)，系统：Windows10
这些窗口开始菜单都是几乎透明的，看起来（尤其是窗口）可能不太好看
并且菜单布局有些问题
Firefox浏览器不太适配，Chrome就没问题
所以能适配一下吗

**Comment by User782Tec** [comment]
![](https://user-images.githubusercontent.com/115236204/211282274-35038108-29fd-4e1e-8f6c-7b2cd9c2e92f.png)
![](https://user-images.githubusercontent.com/115236204/211282410-6cc314db-6505-4833-b554-676c3fe430ee.png)

**Comment by tjy-gitnub** [comment]
https://blog.csdn.net/qq_38835219/article/details/121809452

**Comment by tjy-gitnub** [comment]
它也不支持pwa
![image](https://user-images.githubusercontent.com/71509955/211293450-a3ccfc18-8cad-4f42-9d22-32f3d50be574.png)

行，火狐还是最新版
👍
不过垃圾归垃圾，还是要适配一下
直接提示浏览器不受支持 吧

**Comment by User782Tec** [comment]
笑死, 我都不知道如何用火狐浏览器安装pwa(

**Comment by User782Tec** [comment]
> 不过垃圾归垃圾
Firefox厨震怒(

**Comment by User782Tec** [comment]
我好像发现这个Safari浏览器也有这个状态栏布局问题诶

**Comment by tjy-gitnub** [comment]
啊这...

**Comment by User782Tec** [comment]
而且这个safari浏览器不仅是布局有问题, 图标都离家出走了

**Comment by User782Tec** [comment]
![](https://user-images.githubusercontent.com/115236204/212448081-15be5f1b-a92a-42bd-803d-ea75349a60ca.PNG)
