### ISSUE TITLE
[建议] 设置里面的“主页”

### ISSUE THREAD

**Issue by lh11117** [win12-online/win12#290]
## 描述

微软又给整了一个“主页”
<img width="716" alt="image" src="https://github.com/tjy-gitnub/win12/assets/99455215/2f87f17f-2214-45f3-93d2-0b663b2a7a60">

## 方案

我们win12也不能落下！添加上去！

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
6

**Comment by Jemesnb** [comment]
牛逼啊

**Comment by ghost** [comment]
666

**Comment by lh11117** [comment]
已经做好了：#291
