### ISSUE TITLE
EDGE主页不错，希望可以独立出一个项目来开发一个chrome插件[建议]

### ISSUE THREAD

**Issue by ghost** [win12-online/win12#292]
## 描述

（请简要描述一下建议）

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
Edge主页是模仿的Chrome在以Google为默认搜索引擎时的主页(
好的，我们会尽力尝试的

**Comment by tjy-gitnub** [comment]
啊，喜欢极简风是吧。
