### ISSUE TITLE
[漏洞] 任务栏消失

### ISSUE THREAD

**Issue by lh11117** [win12-online/win12#294]
## 描述

经过一系列骚操作（见下面的视频），任务栏消失了

## 重现

按以下步骤可重新复现该漏洞：

见下面的视频

## 截图

https://github.com/tjy-gitnub/win12/assets/99455215/747c3bec-fdf8-43b4-a264-4a9fa47b82f4

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：chrome（edge也是如此）
浏览器版本：版本 117.0.5938.132（正式版本） （64 位）
操作系统：Windows NT 10.0   (windows11 22h2)

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
好的
感谢您的反馈

**Comment by ghost** [comment]
咋有这个bug

**Comment by lh11117** [comment]
简单来说，就是通过任务管理器结束未打开的应用的进程   @User782Tec

**Comment by User782Tec** [comment]
是的(
我会排查一下的
