### ISSUE TITLE
Github的Star在关于“Windows12网页版”的页面无法正常刷新

### ISSUE THREAD

**Issue by HanXiaozeng** [win12-online/win12#295]
## 描述
Github的Star在关于“Windows12网页版”的页面无法正常刷新
## 重现
打开“关于Windows12网页版”找到Star，再次新建窗口打开 https://github.com/tjy-gitnub/win12 页面，若已添加Star先取消Star，打开windows12网页版，刷新Star，再次返回 https://github.com/tjy-gitnub/win12 页面 点击Star，再次返回Windows12网页版，再次刷新，并未更新
**描述可能不清楚，请看下面视频**
## 视频&截图
![image](https://github.com/tjy-gitnub/win12/assets/110365422/028a5519-5abe-4e12-ae38-d9ccece8d593)

https://github.com/tjy-gitnub/win12/assets/110365422/808eb2fc-9b1c-43bf-935d-af4d3aadbb44

## 测试环境

浏览器 Edge 版本 117.0.2045.47 (正式版本) (64 位)
Windows
处理器	11th Gen Intel(R) Core(TM) i7-1160G7 @ 1.20GHz   2.11 GHz
机带 RAM	16.0 GB (15.8 GB 可用)
## 其他
**我一开始以为时微软员工透露的，可没想到！！！竟然时是初中生做的！！！**

**Comment by User782Tec** [comment]
这是因为Github上显示的星标会四舍五入
而我们获取的是准确数值
所以会有误差
在Github项目右侧点击“4.8k stars”（不是顶部）后所进入页面里会显示实际的星标数（即星标人数）

**Comment by HanXiaozeng** [comment]
原来如此！
