### ISSUE TITLE
应用商店打不开

### ISSUE THREAD

**Issue by I-love-paper** [win12-online/win12#297]
## 描述

应用商店打不开

## 重现

按以下步骤可重新复现该漏洞：

## 截图

https://github.com/tjy-gitnub/win12/assets/138297017/60e1a83e-a8b6-44bf-8a71-77f582d32b35

## 测试环境
浏览器：[360安全浏览器]
浏览器版本：[14.1.1278.0]
操作系统：[win11]

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
我们目前没有实现微软商店
见谅
