### ISSUE TITLE
[建议]能登录GitHub账号

### ISSUE THREAD

**Issue by I-love-paper** [win12-online/win12#299]
## 描述

希望能在网页版的win12里面登录GitHub账号还不是使用Administrator用户

## 方案

使用GitHub的OAuth Apps来实现

## 其他

还希望能登录微软账号。

**Comment by User782Tec** [comment]
Github的OAuth主要是以一个用户的身份去操作GitHub上的代码仓库、Issue & PR等等功能
所以在我们这个项目里实现GitHub账户登录的意义并不是很大（除非我们的项目要内置GitHub Desktop，但实现难度比较大）
微软账号可能会比较繁琐，而且同上，没有多大意义
所以我们短期内是不会考虑的
感谢您的理解
