### ISSUE TITLE
问1

### ISSUE THREAD

**Issue by huangzh20** [win12-online/win12#3]
什么时候可以适配安卓手机或iPhone手机啊？
希望快点适配所有软件，安卓手机和iPhone手机在设置里面，无论怎么点都无法点进选项？

**Comment by huangzh20** [comment]
希望快点更新2.0版本
么么哒😚

**Comment by tjy-gitnub** [comment]
感谢支持！
这个设置呢..呃...其实就是点不进去的......主要是.....好看😉

**Comment by huangzh20** [comment]
希望在5.0版本中可以点进去

**Comment by tjy-gitnub** [comment]
5.0🤣

**Comment by User782Tec** [comment]
现在差不多适配了(

**Comment by Mbilse** [comment]
> 现在差不多适配了(

都9.0了
