### ISSUE TITLE
[建议]CDN

### ISSUE THREAD

**Issue by I-love-paper** [win12-online/win12#300]
## 描述

访问速度太慢，希望使用CDN加速。

## 方案

自建CDN或CF或者其它CDN

## 其他

还可以换自定义域名

**Comment by User782Tec** [comment]
感谢您的反馈
我们使用的Pyodide, Ace, Chart.js等第三方库均是cdn
但可能cdn访问速度较慢

**Comment by I-love-paper** [comment]
不是第三方库的问题，是你的代码文件在GitHub上，GitHub访问巨慢

**Comment by User782Tec** [comment]
代码托管？那还是算了

**Comment by tjy-gitnub** [comment]
我们已经采用了模拟存储和更新的手段加快了加载速度，目前主要问题还是在cdn上，就我这边的网络环境来看cdn比github慢
