### ISSUE TITLE
[建议]Copilot的后端

### ISSUE THREAD

**Issue by I-love-paper** [win12-online/win12#301]
## 描述

Copilot后端用不了，希望能换成其它容器搭建后端。
## 方案

没钱可以用免费服务器，例如甲骨文云(永久免费，注册要信用卡)、GitHub的Actions(公共储存库没有限制)、replit(可能会休眠但访问得到的域名会自动重启，可以定时ping一下)等等

## 其他

还可以使用https://github.com/chatanywhere/GPT_API_free#%E5%85%8D%E8%B4%B9%E4%BD%BF%E7%94%A8 的免费API

**Comment by ghost** [comment]
这个我早就想过了

**Comment by NB-Group** [comment]
最近我正在尝试恢复后端，已经开始逆向chatGPT镜像站，后端重写完毕，预计将在10个版本前更新（

**Comment by ghost** [comment]
十个版本。。。😰😰😰

**Comment by NB-Group** [comment]
嗯呢

**Comment by tjy-gitnub** [comment]
没梯子，笑死

**Comment by NB-Group** [comment]
https://github.com/Dreamacro/clash

**Comment by Harry-zklcdc** [comment]
你可以再去看看我的那个项目了，支持BingAPI、支持自动通过人机验证

**Comment by NB-Group** [comment]
> 你可以再去看看我的那个项目了，支持BingAPI、支持自动通过人机验证

哦！是大佬耶，您的项目我老早就开始用了！我会去尝试的
