### ISSUE TITLE
[漏洞]选择的文件和删除的文件不一致

### ISSUE THREAD

**Issue by I-love-paper** [win12-online/win12#302]
## 描述

选择一个文件删除时删除的文件不是选择的文件

## 重现

按以下步骤可重新复现该漏洞：

选择一个文件，然后点删除，删除的文件并不是选择的文件

## 截图

https://github.com/tjy-gitnub/win12/assets/138297017/83dc1587-1d2e-4e15-bdf4-204cc13b4503

## 测试环境

浏览器：360
浏览器版本：最新版
操作系统：Windows 11

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
经过测试发现确实有这个问题，感谢您的反馈~
@User782Tec

**Comment by ghost** [comment]
原来是桌面图标😂😂😂

**Comment by User782Tec** [comment]
这不关我事对吧 (

**Comment by ghost** [comment]
@User782Tec 啊对对对（bushi
