### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by MicGan6** [win12-online/win12#303]
## 描述

  性能优化

## 方案

在使用本产品的时候，产生了明显的卡顿、过度动画不自然的现象，建议对部分动画进行优化或取消

**Comment by NB-Group** [comment]
那是您的电脑配置问题哦，我们782用的999垃圾电脑都没有任何卡顿。

**Comment by User782Tec** [comment]
> 那是您的电脑配置问题哦，我们782用的999垃圾电脑都没有任何卡顿。

6

**Comment by tjy-gitnub** [comment]
ui我所欲也，性能亦我所欲也，ui与性能不可兼得，舍性能而取ui者也。

**Comment by NB-Group** [comment]
好！（）
