### ISSUE TITLE
[贡献]我可以为win12的copilot提供服务器

### ISSUE THREAD

**Issue by xiaowumin-mark** [win12-online/win12#305]
我可以为win12的copilot提供服务器
配置：阿里云2c2g服务器
系统：win server 2019
有python环境
需要请联系qq：1853046879
邮箱：1853046879@qq.com或xiaowumin-mark@outlook.com

**Comment by xiaowumin-mark** [comment]
@NB-Group

**Comment by NB-Group** [comment]
我们不大原意接受他人赞助服务器，最为服务器提供方，需要承受各类攻击，服务器一寄我们承担不了。
我们打算采用我花6元巨资买的内网穿透服务，配合我的电脑作为ai服务器。
感谢您的支持和好意~

**Comment by xiaowumin-mark** [comment]
额。。。一股ai味
我是一位初三的学生，对编程很感兴趣，目前掌握前端，蟒蛇，go，以及electron框架（包括写作业）
我可以为win12打包，封装成一个独立的应用程序（想象：win12网页版的每个应用可以融合到windows中）
我会将各种功能集中到其中，方便用js进行调用

**Comment by xiaowumin-mark** [comment]
目前学业比较紧，所以等中高后希望和你们一起开发[微笑]

**Comment by NB-Group** [comment]
嗯

**Comment by NB-Group** [comment]
我说话有ai味？（

**Comment by NB-Group** [comment]
至于加入到我们团队，那当然是热烈欢迎啦~（

**Comment by ghost** [comment]
《蟒蛇》。。。
是Python

**Comment by xiaowumin-mark** [comment]
@NB-Group 怎么加入团队？
我把这个项目打包成了软件给个权限我上传到releases

**Comment by NB-Group** [comment]
软件版本已经有了啊？
温馨提示：我们不支持提交windows版本的windows12网页版应用，因为不如pwa
linux版的已经有了

**Comment by User782Tec** [comment]
> 额。。。一股ai味 我是一位初三的学生，对编程很感兴趣，目前掌握前端，蟒蛇，go，以及electron框架（包括写作业） 我可以为win12打包，封装成一个独立的应用程序（想象：win12网页版的每个应用可以融合到windows中） 我会将各种功能集中到其中，方便用js进行调用

我打包过(
仅限Linux(

**Comment by tjy-gitnub** [comment]
对对对对对对对对对（别问，问就是我也不知道
