### ISSUE TITLE
[建议] 支持真实的文件资源管理功能

### ISSUE THREAD

**Issue by leeyoshinari** [win12-online/win12#306]
## 描述
我写了一个后端，支持真实的文件管理功能，搭配作者的前端，支持类似windows文件资源管理器一样的功能，详见：https://github.com/leeyoshinari/OneDrive

## 方案
后端：python3.8+ 、FastApi

## 其他
在作者的基础上，我做了很多改动，删了很多纯静态功能的代码（不好意思，强迫症患者），目前有以下功能：
1、文件夹的新建、删除、重命名、移动、导出
2、文件上传、下载、新建、删除、移动、重命名、分享
3、txt 和 markdown 文档的在线预览、编辑和实时保存
4、不同用户的数据完全隔离
5、可任意挂载多个磁盘

如果作者感兴趣的话，可以引入到这个项目里

**Comment by ghost** [comment]
好是好，就是我下载的是离线版的，我不会创用户

**Comment by ghost** [comment]
再说了，我也不会开源项目

**Comment by ghost** [comment]
有没有默认账户＆密码？

**Comment by leeyoshinari** [comment]
@jincheng-xiao 这。。。第7步不是写了，直接在浏览器输入url请求就行了 http://IP:Port/配置文件中的prefix/user/test/createUser?username=用户名&password=密码&password1=再次确认密码

**Comment by leeyoshinari** [comment]
这个东西不接入公网就失去灵魂了，要做到随时随地访问就得接入公网

**Comment by ghost** [comment]
我不会😂😂😂

**Comment by leeyoshinari** [comment]
@jincheng-xiao 如果你部署在本地，端口和prefix没改的话，就用这个链接，把你的用户名和密码写到这个url里就行了
http://127.0.0.1:15200/mycloud/user/test/createUser?username=用户名&password=密码&password1=再次确认密码

**Comment by NB-Group** [comment]
我来了，你这个提议给我看的一头雾水但是又好像明白（

你是指在服务器端部署你这个项目让windows12能够访问一个类似网盘的东西？

**Comment by NB-Group** [comment]
你这个貌似有点没用啊，我们的项目能够使用的磁盘空间非常少，没有必要在云端搞一个云储存

**Comment by leeyoshinari** [comment]
@NB-Group 不是云储存，是一个类似百度网盘的私有云盘，让你的这个项目的文件系统不再是静态的，而是真实映射到本地磁盘的、动态的、可交互的一个文件系统

**Comment by NB-Group** [comment]
那么为什么不用windows自带的文件资源管理器呢？（

**Comment by ghost** [comment]
@leeyoshinari Thanks

**Comment by leeyoshinari** [comment]
@NB-Group 个人私有云盘呀，windows自带的又不能共享和随时随地查看，，而且还有不一定要是windows，还可以是 linux 或者 mac，以及国产操作系统。

**Comment by NB-Group** [comment]
行，但是移植到我们项目我觉得有点困难，不过感谢你的提议啦~（

**Comment by jincheng-xiao** [comment]
![Uploading QQ截图20231007124528.png…]()

**Comment by ghost** [comment]
![QQ截图20231007124528](https://github.com/tjy-gitnub/win12/assets/140949421/0f2889c6-5c48-4bff-abbf-de0836ee602f)

**Comment by ghost** [comment]
What's This???

**Comment by NB-Group** [comment]
又是一个不看文档的人

ta不是让你先去运行ta的项目再打开这个链接吗。。。

**Comment by leeyoshinari** [comment]
@jincheng-xiao 
windows和mac启动命令：python3 main.py
linux启动：sh startup.sh
