### ISSUE TITLE
[建议]搜索UI建议

### ISSUE THREAD

**Issue by andyajhs** [win12-online/win12#307]
## 描述

改进一下搜索UI字体缩小一下，更改一下UI。
像这样:https://i.ibb.co/r5DmZ67/2023-10-06-172732.png
## 方案

希望内建AI和新闻，还有工作列希望能把搜索独立出来

**Comment by xiaowumin-mark** [comment]
你这链接访问不了啊

**Comment by andyajhs** [comment]
墙的问题吗（
我重发好了

**Comment by andyajhs** [comment]
https://b23.tv/Ywj7tE4
我不知道用什么，用逼哩逼哩好了

**Comment by NB-Group** [comment]
我一头雾水，你这表达很不清晰啊
首先，搜寻是个啥？（
其次，字体大小css是可以直接设置的，没必要去再找个字体
最后，内建AI？指的是副驾驶吗？工作列？搜索？？？

**Comment by andyajhs** [comment]
我也一头雾水
你有看连结吗吗?
更何况我也没有说要找字体阿，
AI就是原本那个Copilot(虽然坏掉了)啊，
不然搜索自己内建一套AI啊?
我语法错误也改了

**Comment by andyajhs** [comment]
我寻思你连AI也听不懂啊?(

**Comment by andyajhs** [comment]
https://github.com/andyajhs/andyajhs/blob/main/%E8%9E%A2%E5%B9%95%E6%93%B7%E5%8F%96%E7%95%AB%E9%9D%A2%202023-10-06%20172732.png?raw=true

**Comment by NB-Group** [comment]
”连结吗“？？
链接吗？
然后就是你这个ai的建议，我感觉。。特别多余（ ，毕竟搜索就是一个用来搜索的地方，干嘛再搞个ai窗口，并且从任务栏里能打开的那个ai就可以直接添加引用搜索结果和新闻的功能啊，根本没必要再加一个。

还有，你这个”不然搜索自己内建一套AI啊?“我也没看懂，你这链接里不就是搜索里内嵌了ai吗？

**Comment by andyajhs** [comment]
确实，Ai只是其要，但是我觉得ui 要改，不然太阳春了

**Comment by NB-Group** [comment]
话说你是不是港澳台的

**Comment by andyajhs** [comment]
对啊

**Comment by NB-Group** [comment]
问一下你写评论的时候是不是用的翻译中文之后翻译成简体中文的，如果是翻译的就可以让ta直接用繁体中文来写。(

**Comment by andyajhs** [comment]
我用翻譯啊，我對大陸人較喜歡用簡體(
不然每個人都叫我灣灣（

**Comment by NB-Group** [comment]
但是你这个翻译貌似蛮差的（

像我用的这个就不错（
![image](https://github.com/tjy-gitnub/win12/assets/121747915/42471b87-0010-4404-be22-4c611ef661bf)

**Comment by andyajhs** [comment]
我用Google 翻譯還有Mac 用內建Apple翻譯，都是臭名昭著的翻譯（

**Comment by NB-Group** [comment]
.

**Comment by tjy-gitnub** [comment]
呃，同志，不用自卑啊，其实我们也挺向往那边的。
另外这个图片是photoshop的吗？这个ai我们找不到合适的api，所以搁置了呢

**Comment by andyajhs** [comment]
同志?感覺.....我當然是用photoshop啊，因為我只會寫很陽春的網頁(

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/79f4ea89-d932-4a4c-9ef3-e72a20ecf5af)
"阳春中文意思是'溫暖的春天'
但在台灣生活用法，"最基本"的意思。"
这个百度翻译也是蛮（）的（

**Comment by tjy-gitnub** [comment]
是啊，你们那边难道不是三民主义吗（不会是我记错了吧，难道还是资本？

<hr>

可是为什么ai要放在搜索里面啊？还有ai是真的没办法搞。。

**Comment by andyajhs** [comment]
沒有，我們不是泛藍就是泛綠，沒有那麼偏資本，現在沒有三民主義了吧，我們政治圈很亂
我也不清楚我幹嘛放裡面，我那時可能覺得（這樣很微軟）（

**Comment by NB-Group** [comment]
首先放了没啥用（），其次放了没法用（）

**Comment by andyajhs** [comment]
很想反駁，但反駁不了（

**Comment by tjy-gitnub** [comment]
呃，  @andyajhs 冒昧问一句啊，可以不用回答，但是我很想知道你们那边比较支持哪边？你是怎么想的？觉得不好公开说可以email我，单纯想问，保证不说出去

**Comment by andyajhs** [comment]
中立吧，好像比較多人偏民進黨，3大黨都有人支持（民進黨、國民黨、共產黨）

**Comment by NebulaTechs** [comment]
政治...........《话说这github是不是过于开放了？（弱》

**Comment by andyajhs** [comment]
畢竟主要客群是歐美國家(

**Comment by tjy-gitnub** [comment]
github算半个外网了吧，你是习惯了国内的专政了 >u-)o

**Comment by andyajhs** [comment]
那倒確實（）

**Comment by NebulaTechs** [comment]
其实(敢)讨论政治也挺好的

**Comment by andyajhs** [comment]
反正台灣在牆外d(`･∀･)b

**Comment by NebulaTechs** [comment]
唉

**Comment by tjy-gitnub** [comment]
6，好奇怪的画风
