### ISSUE TITLE
蓝屏时出现的问题（2点）

### ISSUE THREAD

**Issue by HanXiaozeng** [win12-online/win12#308]
## 描述
1.蓝屏时，出现鼠标指针  
2.蓝屏时 XXX% 完成无限循环
## 重现
1.点击设置，找到主页，找到“登录”按钮，按下引发蓝屏后看视频！！
2.蓝屏后看 XXX% 完成
## 视频

https://github.com/tjy-gitnub/win12/assets/110365422/c2498a77-2560-481a-8331-0a7197fc3a4f

https://github.com/tjy-gitnub/win12/assets/110365422/7630735a-34d7-475c-8ba9-82cdcbbdf0e6

## 测试环境
浏览器 Microsoft Edge 版本 117.0.2045.60 (正式版本) (64 位)
版本	Windows 11 专业工作站版
版本	23H2
安装日期	‎2023/‎7/‎17
操作系统版本	22631.2361
体验	Windows Feature Experience Pack 1000.22674.1000.0

**Comment by User782Tec** [comment]
鼠标没有隐藏确实是个bug，我们会修复的
这个无限循环的进度是我们自己弄的彩蛋
感谢您的反馈

**Comment by ghost** [comment]
I don't like this 彩蛋

**Comment by HanXiaozeng** [comment]
> 我不喜欢这个彩蛋

Me too

**Comment by tjy-gitnub** [comment]
I do like it : )
