### ISSUE TITLE
有没有考虑用前端框架重写

### ISSUE THREAD

**Issue by sishen654** [win12-online/win12#309]
使用 Vue 或者 React 进行构建，性能是否会更好

**Comment by User782Tec** [comment]
有，但不多(bushi
我们最近其实也在打算这件事
用框架的确好，但要花很长时间重写
而如果就按现在这么写的话，虽然可以继续开发，但开发可能比较困难
感谢您的建议

**Comment by NebulaTechs** [comment]
我们可能没有足够的时间，但我们会尽可能满足您

**Comment by WJHAC** [comment]
有没有想去苹果公司上班

**Comment by sishen654** [comment]
> 我们可能没有足够的时间，但我们会尽可能满足您

我想着用框架性能更好，开发更快，不过对于目前这么多如果要重构确实不方便。
如果后续用框架重构了，可以出一份力。

**Comment by tjy-gitnub** [comment]
大概率不会重构了
