### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by OI233** [win12-online/win12#310]
##漏洞
-网络蓝牙那个界面的时候夜间模式按钮不管用

（请描述一下这个漏洞是什么样的）

## 重现

按以下步骤可重新复现该漏洞：
-emm无

（请用步骤的方式描述一下如何重新复现该漏洞）

## 截图

https://github.com/tjy-gitnub/win12/assets/146888651/67da25e3-2905-4697-a10f-e4ee9c1f168e

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境
浏览器：[Edge]
浏览器版本：[不知道，估计是最新版]
操作系统：Windows 10]

## 其他

https://github.com/tjy-gitnub/win12/assets/146888651/314dd841-b0c3-4b3c-b7fe-591c6b74efdf

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
该Issue与Issue<https://github.com/tjy-gitnub/win12/issues/223>重复
请谅解
