### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by shu-qian** [win12-online/win12#311]
## 描述
使用触摸板进行星源页面的查看时，向下滚动才会出现页面并且图片逐渐出现的方式很奇怪

## 重现

按以下步骤可重新复现该漏洞：
点击星源页面，使用触摸板向下滑动查看

## 截图
<img width="960" alt="屏幕截图 2023-10-19 225336" src="https://github.com/tjy-gitnub/win12/assets/147619734/0c7ae210-6851-4bff-b6a0-afbbf8ee9103">

<img width="960" alt="屏幕截图 2023-10-19 225439" src="https://github.com/tjy-gitnub/win12/assets/147619734/b00e0f54-f031-42ef-a62a-678e2b91a19c">

## 测试环境

浏览器：Edge
浏览器版本：118.0.2088.46
操作系统：Windows 11

**Comment by NB-Group** [comment]
本身就是这样设计的呀（

**Comment by tjy-gitnub** [comment]
我不是很理解：
1. 你在说什么奇妙的东西，听不懂smd
2. 为什么在win12的issue里，is there anything to do with it?

**Comment by NB-Group** [comment]
《smd》
