### ISSUE TITLE
“Windows更新”相关

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#312]
## 描述
（请简要描述一下建议）
由于“Windows更新”不完善，提出以下建议
## 方案
在打开自动更新的情况下，每次“开机”之后自动检测更新，如果检测到新版本就在托盘上显示Windows更新的图标。

附：问题：点击检测更新后一直显示“正在检测更新”。

**Comment by tjy-gitnub** [comment]
你的网络问题，因为失败不会提示，所以看起来是这样。
关于这个bug，这边建议您咨询一下 @User782Tec 呢~

**Comment by User782Tec** [comment]
我也不知道为什么一直在检测更新
我这边内网测的是好的，而且pages上也没有报错

**Comment by NB-Group** [comment]
那其实catch一下然后加个提示就行了

**Comment by User782Tec** [comment]
不是它根本就没报错

**Comment by NB-Group** [comment]
斯

**Comment by tjy-gitnub** [comment]
那就别管他，能更就行
