### ISSUE TITLE
更改本地软件实现原理

### ISSUE THREAD

**Issue by algfwq** [win12-online/win12#315]
## 描述

建议更改本地软件实现原理

## 方案

建议使用Tauri实现，使用系统的浏览器内核，体积更小，速度更快，开发方便

**Comment by NB-Group** [comment]
斯，首先，然后，其次，最后，任何windows的web GUI 框架，都没有 pwa 方便

**Comment by algfwq** [comment]
额，PWA是什么？

**Comment by algfwq** [comment]
那不是手机上的吗？

**Comment by NB-Group** [comment]
<img width="915" alt="image" src="https://github.com/tjy-gitnub/win12/assets/121747915/fb4f2be4-27b8-4399-8416-608d7b1e1d20">

这个安装后就是PWA应用

**Comment by algfwq** [comment]
AZ，请问触发这个的条件是什么？

**Comment by NB-Group** [comment]
1,网站支持（得写配置文件）
2,浏览器支持

**Comment by User782Tec** [comment]
> 1,网站支持（得写配置文件） 2,浏览器支持

像某个名字叫Firefox的浏览器自然就不支持啦

**Comment by tjy-gitnub** [comment]
pwa能跨平台，编写方便，也支持本地，何乐不为
