### ISSUE TITLE
[建议]使用的时候很卡

### ISSUE THREAD

**Issue by Umbreonuk** [win12-online/win12#318]
## 描述

（请简要描述一下建议）

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by ghost** [comment]
请主要描述问题，也可以附上截图

**Comment by xiaowumin-mark** [comment]
这个是浏览器缓存太多了，或者是你设备性能的问题

**Comment by Umbreonuk** [comment]
话说那个Copilot显示“发生错误，请查看控制台输出或重试”是怎么回事？？

**Comment by NebulaTechs** [comment]
电脑性能太差了吧

**Comment by ghost** [comment]
（copilot根本没修好）

**Comment by NebulaTechs** [comment]
yeah

**Comment by User782Tec** [comment]
> （copilot根本没修好）

服务器又去世了

**Comment by ghost** [comment]
@User782Tec 服了你们。。。
