### ISSUE TITLE
作者   :)

### ISSUE THREAD

**Issue by Samtjs** [win12-online/win12#32]
作者研究出什么了吗
♞上就要更新了
但是
`index.html`好像运行不了了
可能
需要修改DNS地址
才能运行
所以
比较麻烦
希望
作者可以早点研究出来
Bless
当然
也可以
向Developer
提交
Issue
多次提交
也许
可以成功
βγe

**Comment by Samtjs** [comment]
![icons8-bing-256](https://user-images.githubusercontent.com/121801304/211540995-aa241133-60c6-4682-92e9-ffb4d300310a.png)

**Comment by tjy-gitnub** [comment]
嗯
它的那个好像是基于一种神秘框架的
我好像编译不了
其实代码html,js,css分开不太好抄
我借鉴借鉴吧

**Comment by Samtjs** [comment]
不过如果有条件的话可以直接把库复制下来把图形改改变成Win12

**Comment by tjy-gitnub** [comment]
啊。。。
我还是有很多超过它的啊
比如右键菜单、窗口最大化、动画都做得更好啊
