### ISSUE TITLE
[漏洞]夜间模式

### ISSUE THREAD

**Issue by Zhang94500** [win12-online/win12#321]
## 描述

点击夜间模式,系统主题不会跟随改变深色模式

## 重现

按以下步骤可重新复现该漏洞：

（正常点击夜间模式就可实现）

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]
浏览器版本：[请在这里填入浏览器的版本]
操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
《故意这么设计的》

**Comment by tjy-gitnub** [comment]
小知识：深色模式和夜间模式不是同一个东西~你可以试试
