### ISSUE TITLE
【问题】如何更快速的进行开发调试

### ISSUE THREAD

**Issue by 1741718728** [win12-online/win12#326]
你们好我有一个疑问，请问一下你们是怎么开发调试的呀？比如说改动了一个样式，我想看看效果，刷新浏览器，系统就会回到登录页，这样开发特别费时间

**Comment by NB-Group** [comment]
其实。。我们就是这样开发的（

**Comment by User782Tec** [comment]
噢我们一般有两种解决方案
第一是可以用vscode的live server插件，启动该服务之后样式变动就不用刷新页面了，但要注意可能会触发缓存机制导致更新不及时，可参考下面方案
第二是可以在开发用的网址（可以是localhost, IP或者域名，file:///应该也行）后面加上"?develop=true"（不包括双引号），就能在刷新之后自动跳过登录界面和开机弹窗，并禁用缓存机制

**Comment by NB-Group** [comment]
行

**Comment by 1741718728** [comment]
好的感谢解答，我按照这种方式试一下
