### ISSUE TITLE
A True DE

### ISSUE THREAD

**Issue by Neuron-Group** [win12-online/win12#327]
## 描述

这个项目非常受欢迎。如果将它开发成为一个真正的适配 Linux 或者 FreeBSD 平台的 DE，也许可以比 KDE，GNOME 甚至 深度 的 DDE 更加优秀。

## 方案

Electron 作为一个真正的 DE 来说还有些卡顿。很容易看出来，它并不适合处理拖动事件。可以选用 QT 这类前端框架进行开发，并赋予用户一定的个性化定制特性，例如可以添加自己配置或者编写的窗口 最小化 最大化 关闭 动画或者 Dock 栏动画，就像 KDE 做的那样（但是不一定要像 KDE 那样提供全方位的可定制性），编写支持拖动和应用文件夹的 Launch Pad（KDE 没有这类 Launch Pad），添加对于 wayland 的支持。这一定令人兴奋！

## 其他

最终，我们也许可以利用这个 DE 去包装一个新的 Linux 发行版。

**Comment by User782Tec** [comment]
这是个很好的主意
但…但是这有点超出我们的能力范围了

**Comment by tjy-gitnub** [comment]
算是一个不切实际的梦想吧
