### ISSUE TITLE
工程化重构[建议]

### ISSUE THREAD

**Issue by bobabc** [win12-online/win12#328]
## 描述

有没有想过用商用规范重构，看你的项目，表面上看着很很悬，打开你源文件，感觉你就说闹着玩，代码乱成一锅粥，语法不规范，只能作为娱乐看下，想要商用太难，除了你们几个能快速看懂，其他人想要用必须重构，多看看别人开源项目！

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
这个项目代码确实臃肿，这是毋庸置疑的，但是它本身就是一个娱乐项目，甚至在开发初期都没有想过要让其他人帮助开发。。
至于商用。。这玩意能商用？（

**Comment by itakeo** [comment]
看了一下代码，属于那种前端初学者练手的项目，代码都是一点点拼凑的，不过对于一个初中生算不错的了，说不定后面技术进步了，react或者vue重构也不是没可能，至于商用？微软会答应?

**Comment by User782Tec** [comment]
感谢您的建议
我们已经开始着手于win12的重构，感谢您的支持！

**Comment by tjy-gitnub** [comment]
再次感谢您的建议
我们已经放弃着手于win12的重构，仍感谢您的支持！

**Comment by NB-Group** [comment]
再次感谢您的建议
https://github.com/User782Tec/win12-react
我们已经着手放弃更新这个项目（指react版win12）
