### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by window15** [win12-online/win12#331]
## 描述
打开billbill打开视频互转到本机浏览器
（请描述一下这个漏洞是什么样的）

## 重现
打开billbill打开视频
按以下步骤可重新复现该漏洞：

打开billbill打开视频（请用步骤的方式描述一下如何重新复现该漏洞）

## 截图

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]Chrome
浏览器版本：[请在这里填入浏览器的版本]121.0.6159.0
操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]Mac os

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
确实有这个问题，但是受平台和浏览器规则限制，目前无法修复。
感谢您的反馈～

**Comment by User782Tec** [comment]
不是你pin issue干啥

**Comment by ghost** [comment]
@User782Tec 哈哈
