### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by vozke3-weKzyc-kaqcoc** [win12-online/win12#334]
## 描述

重启或关机时会乱码

## 截图

（如果有的话，请在这里附上相关的截图或视频）

##测试环境

浏览器：safari
浏览器版本：1.0.2
操作系统：iOS 17

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by User782Tec** [comment]
额...麻烦再详细点?
具体乱码展示的是什么内容?能否提供屏幕截图
设备是什么?iPhone还是iPad?具体第几代?

**Comment by ghost** [comment]
建议使用Chrome或edge
