### ISSUE TITLE
[漏洞]设置-账户的那个登录选项写成了‘陆’

### ISSUE THREAD

**Issue by ltx-github** [win12-online/win12#335]
## 描述

（请描述一下这个漏洞是什么样的）

## 重现

按以下步骤可重新复现该漏洞：

（请用步骤的方式描述一下如何重新复现该漏洞）

## 截图

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]
浏览器版本：[请在这里填入浏览器的版本]
操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
哇，还真是，感谢您的反馈~
![image](https://github.com/tjy-gitnub/win12/assets/121747915/25c68339-5e06-434d-b852-121ce0bec92f)

**Comment by Jimmy-Effe** [comment]
文字错误
影响：容易使用户造成误解
描述：一个由同音字引出的错误
改进：通过更正文字内容解决
Fix by: Junchen Yi
