### ISSUE TITLE
[漏洞] 浏览器书签过多会遮挡内容

### ISSUE THREAD

**Issue by lingbopro** [win12-online/win12#343]
## 描述

浏览器书签过多会遮挡内容

## 重现

在 _Microsoft Edge_ 里打开一个网页，然后不停按地址栏右侧的星标图片，会**创建大量书签**，从而占用大量屏幕空间

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/148617407/b63f8b30-839c-496b-8bfd-cdd60c2401ab)

## 测试环境

浏览器：[Edge](https://www.microsoft.com/zh-cn/edge)
浏览器版本：`115.0.1901.203`
操作系统：Windows 10 `22H2`

## 其他

也许可以自动隐藏过多的内容或者做一个收藏夹上限（

**Comment by User782Tec** [comment]
感谢您的反馈！

**Comment by Jimmy-Effe** [comment]
Edge浏览器书签过多会遮挡内容
影响：用户无法正常使用Edge浏览器
描述：未限制浏览器书签显示容器的单行显示
改进：通过对该容器限制单行解决
Fix by: Junchen Yi
