### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by yiliabai** [win12-online/win12#345]
## 描述
你做的网页版图标不搭

## 其他

（如果有其他的内容，请在这里进行补充）
![屏幕截图 2023-12-17 224712](https://github.com/tjy-gitnub/win12/assets/121293136/b3f0d81c-a4f1-45bd-bd4c-6aca1e009f84)
![屏幕截图 2023-12-17 224700](https://github.com/tjy-gitnub/win12/assets/121293136/342f49c4-7d79-4860-bd62-73291c82f33a)
## 其他 语音输入法 应该是在设置>个性化>输入法（你自己添加）里启动
![屏幕截图 2023-12-17 225143](https://github.com/tjy-gitnub/win12/assets/121293136/fe61ce65-62f1-4d13-a7c8-3c1fb48afe0e)
主要是不好看

**Comment by ghost** [comment]
什么意思？

**Comment by User782Tec** [comment]
请补充下列信息：具体是哪方面不搭配？（配色？形状？设计？参数？动画？尺寸？）
