### ISSUE TITLE
WINDOWS DEFENDER 无效按钮导致蓝屏

### ISSUE THREAD

**Issue by zsr-lukezhang** [win12-online/win12#351]
## 描述

Windows Defender无效按钮导致蓝屏。

## 方案

按下无效按钮后显示蓝屏。建议的错误代码：
WINDOWS_DEFENDER_KILLED_SYSTEM

**Comment by Jimmy-Effe** [comment]
是否能提供一些复现问题的截屏或者视频以便我们更快的修复

**Comment by zsr-lukezhang** [comment]
呃，这是建议，不是问题

**Comment by User782Tec** [comment]
@NB-Group

**Comment by NB-Group** [comment]
@User782Tec

**Comment by tjy-gitnub** [comment]
一本正经地在那 @ 呢。。这是彩蛋！（（
