### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by vaggchen** [win12-online/win12#354]
## 描述

删除小组件后删除文字没有消失

## 重现

按以下步骤可重新复现该漏洞：

新增小组件，拖动，删除小组件，删除小组件后删除文字没有消失

## 截图
![202401-73ea066403021e85e6edb3652f7fcd4b](https://github.com/tjy-gitnub/win12/assets/28042774/66fd6618-8cf7-41da-9e89-2aaa9aed7e96)

## 测试环境

浏览器：[Chrome]
浏览器版本：[120.0.6099.130 64位] 
操作系统：[Windows 10]

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
win12祖传bug，实际上你可以在各种地方找到这个问题。
感谢你的反馈~
@User782Tec

**Comment by NB-Group** [comment]
@User782Tec

**Comment by User782Tec** [comment]
别@了

**Comment by ltx-github** [comment]
真祖传bug

**Comment by ltx-github** [comment]
Windows11 21H2的时候资源管理器删除后就删除字符不消失

**Comment by tjy-gitnub** [comment]
@User782Tec

**Comment by Mbilse** [comment]
> Windows11 21H2的时候资源管理器删除后就删除字符不消失

err...
