### ISSUE TITLE
[建议]增加minecraft

### ISSUE THREAD

**Issue by wodemc** [win12-online/win12#356]
## 描述

如题。

## 方案

可以加入eagler minecraft的源代码（原作者被mojang律师函了，且开源，见[https://github.com/lax1dude/eaglercraftx-1.8）](https://github.com/lax1dude/eaglercraftx-1.8%EF%BC%89)。

eagler是国外大佬利用javascript制作的minecraft仿制版，目前有许多版本，以下是主要的几个：
1.3 - 功能齐全。
1.5 - 功能齐全。
1.8 - 仅限多人游戏。【2023.1.5日更新】
1.8光影版 - 仅限多人（好像也没什么光影）。
1.8.8 -  仅限多人游戏。
每个版本仅仅不到20000kb，都是单独的html文件，不调用任何其他文件。最初的1.3版本甚至只有4458kb。每个版本都是单独的html文件，不调用任何其他文件，贴图都以data:的方式存储在js代码里。

其中，1.8.8原版的源代码：
https://github.com/vidio-boy/Eaglercraft1.8.8
此版本为全英。
其余版本的翻译版源代码，都在https://games.imc.re/。这些是国人翻译得到的，并稍加了修改，应该可以改回来。
更多版本因资料不足（其实是不挂梯子上不了github）而无法全面讲述，请自行搜索吧。

## 其他

因为原作者有被mojang律师函，所以加入时请谨慎，避免侵权。

**Comment by User782Tec** [comment]
感谢您的建议
但为了避免侵权，我们并不打算加入该功能
