### ISSUE TITLE
[建议]空文件夹文字

### ISSUE THREAD

**Issue by wodemc** [win12-online/win12#357]
## 描述

最好在打开空文件夹时显示“此文件夹为空”，不然有种电脑卡了的错觉。

## 方案

如上文。

## 其他

无。

**Comment by Jimmy-Effe** [comment]
![iShot_2024-01-13_下午11 07 46](https://github.com/tjy-gitnub/win12/assets/63986407/fdb5e1c3-f6dc-477a-911c-6c0dbead591a)

**Comment by Jimmy-Effe** [comment]
没有查找到相对应的Bug，请您继续提供更多细节

**Comment by wodemc** [comment]
噢，可能是我没看清。

**Comment by wodemc** [comment]
等等，打开C:/用户/Administrator/AppData/Local Microsoft/windows后就没有。

**Comment by wodemc** [comment]
当文件路径堆叠超过路径框范围时就不会显示了。

**Comment by NB-Group** [comment]
> ![iShot_2024-01-13_下午11 07 46](https://private-user-images.githubusercontent.com/63986407/296499125-fdb5e1c3-f6dc-477a-911c-6c0dbead591a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDY1MDAsIm5iZiI6MTcwNTIwNjIwMCwicGF0aCI6Ii82Mzk4NjQwNy8yOTY0OTkxMjUtZmRiNWUxYzMtZjZkYy00NzdhLTkxMWMtNmMwZGJlYWQ1OTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA0MjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MWRmYTllZTY4Y2RlMmMwMmVjMGFiZmU2NjBkMWFiYTllN2QwZWE5ZjYyNmI4NWQ3ODI2YjY4NTljNWZmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OuozmaPiYl9pGi47b5lu_j8CmlgyQOaqhnfRclQAyTU)

据我观察，你貌似在使用不受支持的浏览器，例如火狐，建议你使用edge、chorme。（你这个窗口的毛玻璃寄了）

**Comment by NB-Group** [comment]
> 等等，打开C：/用户/管理员/AppData/Local Microsoft/windows后就没有。

感谢你的反馈~
