### ISSUE TITLE
[建议]个性化增强和缓存

### ISSUE THREAD

**Issue by wodemc** [win12-online/win12#358]
## 描述

1.可以在个性化中新增“任务栏位置”“任务栏布局”和“恢复默认设置”几个选项或其中之一。
2.存储功能，即重启系统后不会回到初始设置。

## 方案

如上文。

## 其他

无。

**Comment by NB-Group** [comment]
1、非常感谢您宝贵的建议
2、其实部分功能已经有储存了，例如设置个性化里的选项，我们会逐渐扩充的。
感谢您的反馈

**Comment by tjy-gitnub** [comment]
任务栏能有什么布局？: )
