### ISSUE TITLE
Edge

### ISSUE THREAD

**Issue by rayqwe1234** [win12-online/win12#359]
## 描述

  浏览器打开网页后下面会空一行

##按以下步骤可重新复现该漏洞：

（请用步骤的方式描述一下如何重新复现该漏洞）

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/119114594/86eddc54-3067-45c5-8404-620dd4feec74)
![微信图片_20240115134624](https://github.com/tjy-gitnub/win12/assets/119114594/a4031e7f-586a-4097-aaec-4ce5211bee8e)

## 测试环境

浏览器：Edge
浏览器版本：120.0.2210.133 (正式版本) (64 位)
操作系统：Windows 11

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
有没有一种可能，那是dock栏（

**Comment by User782Tec** [comment]
但是dock栏现在会隐藏了

**Comment by rayqwe1234** [comment]
> 有没有一种可能，那是dock栏（
可是下面空一块很丑

**Comment by rayqwe1234** [comment]
> 有没有一种可能，那是dock栏（

可是下面空一块很丑

**Comment by NB-Group** [comment]
已经在一个PR里修掉了
