### ISSUE TITLE
桌面小组件被窗口遮挡后会有一个一闪一闪的黑影

### ISSUE THREAD

**Issue by rayqwe1234** [win12-online/win12#360]
## 描述

 桌面小组件被窗口遮挡后会有一个一闪一闪的黑影

## 重现

按以下步骤可重新复现该漏洞：

（请用步骤的方式描述一下如何重新复现该漏洞）

## 截图

https://github.com/tjy-gitnub/win12/assets/119114594/b2776ea3-b35d-477f-9cf6-355bfde71ae3
(video)
## 测试环境

浏览器：Edge
浏览器版本：120.0.2210.133 (正式版本) (64 位)
操作系统：Windows 11

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
这个貌似是浏览器的bug呢~
我们会尝试解决的，感谢您的反馈~
@User782Tec

**Comment by tjy-gitnub** [comment]
请使用较高配置的显卡。另外我们发现屏幕采集（比如录屏）也会导致此问题
