### ISSUE TITLE
[漏洞]网络断开无用

### ISSUE THREAD

**Issue by wodemc** [win12-online/win12#362]
## 描述

在任务栏里关闭WLAN，在设置里不会断开。

## 重现

1.点击任务栏里的网络图标；
2.关闭WLAN；
![image](https://github.com/tjy-gitnub/win12/assets/154050608/e8b7e704-b749-4636-b7a1-08712724c03f)
3.打开设置；
4.点击“网络和Internet”；
5.可以发现，上面的网络“瓶盖”仍然连接中。

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/154050608/7e3fa0c8-3c9b-4470-95e6-58a779233726)

## 测试环境

浏览器：Edge
浏览器版本：版本 120.0.2210.133 (正式版本) (64 位)
操作系统：Windows 11

## 其他

无。

**Comment by User782Tec** [comment]
噢，额...设置是一个摆设(
我们会在以后完善设置功能，感谢您的反馈!

**Comment by tjy-gitnub** [comment]
我们大概率不会完善此功能，但仍然感谢
