### ISSUE TITLE
[漏洞]文件在修改后缀后仍然用记事本打开

### ISSUE THREAD

**Issue by wodemc** [win12-online/win12#363]
## 描述

文件在修改后缀，去掉“.txt”.txt后，双击，仍然用记事本打开。

## 重现

按以下步骤可重新复现该漏洞：

1.新建一个文件（默认是文本文档）；
2.将文件名后的“.txt”去掉；
3.右键，菜单中显示无法打开；
4.双击，文件却以记事本的方式打开了。
![image](https://github.com/tjy-gitnub/win12/assets/154050608/cef13771-0564-44f4-8e48-0f8521d81c87)

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/154050608/94edb5d9-9bf2-4bda-b9f1-9b7d5e8e4f47)

## 测试环境

浏览器：Edge
浏览器版本：版本 120.0.2210.133 (正式版本) (64 位)
操作系统：Windows 11

## 其他
无。

**Comment by jobsofferings** [comment]
应该本身只支持记事本

![image](https://github.com/tjy-gitnub/win12/assets/53618422/52dc18ce-5181-416d-950c-2dceb7eaec93)

**Comment by User782Tec** [comment]
是的只能用记事本打开(
我们(可能应该)会在以后完善打开文件机制

**Comment by tjy-gitnub** [comment]
是的，很有道理。你会发现他其实 记事本并没有 “打开文件”，而文件 “打开了记事本”
