### ISSUE TITLE
当ChatGPT回答比较长的时候，无法完整地显示

### ISSUE THREAD

**Issue by CNLiuShuhan** [win12-online/win12#367]
## 描述

当ChatGPT回答比较长的时候，无法完整地显示

## 重现

按以下步骤可重新复现该漏洞：
问ChatGPT : 请帮我用Python写一个倒计时程序，要美丽 实用 简洁
他就会回答，但是在回答底部，会有一句被截掉的话：You can modify the `seconds` argument to change the

## 截图

![Untitled](https://github.com/tjy-gitnub/win12/assets/143274270/8863ad7a-e7d7-41a6-aa82-a1a045be4c00)

## 测试环境

Microsoft edge
浏览器版本：最新
操作系统：Windows10 22H2 

## 其他

无

**Comment by User782Tec** [comment]
感谢您的反馈！
@NB-Group

**Comment by NB-Group** [comment]
不关我事（

**Comment by NebulaTechs** [comment]
我的更加严重：根本无法使用（悲

**Comment by NB-Group** [comment]
每分钟50条限制，多试试

**Comment by NebulaTechs** [comment]
"出现错误，请检查控制台输出"你确定是因为限制的原因吗

**Comment by User782Tec** [comment]
我擦nebula！

**Comment by User782Tec** [comment]
你的翻译呢（

**Comment by NebulaTechs** [comment]
时间：6，不过现在已经开始了

**Comment by ghost** [comment]
有时还会中英文混杂
直接对他说 Thanks.

**Comment by NB-Group** [comment]
> "出现错误，请检查控制台输出"你确定是因为限制的原因吗

这东西是我开发的，我当然确定，你自己去控制台监视一下数据流就知道了啊

**Comment by NebulaTechs** [comment]
对了是每人每分钟50次还是每分钟50次，或者，一定人数为一组，每组50次

**Comment by NB-Group** [comment]
所有人加起来

**Comment by NB-Group** [comment]
以后可以加上排队系统

**Comment by wdx2ky** [comment]
所以我的win12下下来AI直接换成了GPT套壳（hhh)

**Comment by tjy-gitnub** [comment]
现在已经不用修了：）
