### ISSUE TITLE
美丽的语音球拖动到边角时卡顿

### ISSUE THREAD

**Issue by HanXiaozeng** [win12-online/win12#377]
## 描述

美丽的语音球拖动到边角时十分卡顿 **十分卡顿！！！**

## 重现

按以下步骤可重新复现该漏洞：
注意看视频哦~

## 视频(肥底优）

https://github.com/tjy-gitnub/win12/assets/110365422/302f0a41-7c06-4517-a1a0-f46e725bf48b

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]
浏览器版本：[请在这里填入浏览器的版本]
操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]
不写了，“蒜”了吧

## 其他

没啥

**Comment by NB-Group** [comment]
emm，我这里测试之后并没有发现问题。
估计是您电脑太菜了，这边建议您更换电脑呢亲~
你也可以尝试提供您设备的硬件信息，以便我们参考优化。

**Comment by HanXiaozeng** [comment]
> emm，我这里测试之后并没有发现问题。 估计是您电脑太菜了，这边建议您更换电脑呢亲~ 你也可以尝试提供您设备的硬件信息，以便我们参考优化。

不菜！
![屏幕截图 2024-01-30 073059](https://github.com/tjy-gitnub/win12/assets/110365422/e847ffc8-837b-44a3-8007-3cc3a834886a)

**Comment by User782Tec** [comment]
菜，就多练！（
能用chrome，就多用！
chrome是chrome，其他浏览器是其他浏览器！
你拿chrome和其他浏览器比哥们你咋不拿自己刚出生时和现在比呢（

**Comment by ghost** [comment]
我电脑13年买的都能重装成win11。win11很垃圾的

**Comment by HanXiaozeng** [comment]
别说了，我要close了
