### ISSUE TITLE
[漏洞]语音球关闭

### ISSUE THREAD

**Issue by wodemc** [win12-online/win12#380]
## 描述

关闭语音球之后，点击语音球原来所在的位置，仍然会启用语音球。

## 重现

1.设置-个性化-关闭语音球；
2.点击语音球原来所在的位置（可能要多点几下）；
3.仍然会提示语音球。

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/154050608/aadd06c6-57f0-4b8c-8bbf-88db152aee22)
注意：这张图片中，语音球选项是关闭的。

## 测试环境

浏览器：Edge
浏览器版本：版本 120.0.2210.133 (正式版本) (64 位)
操作系统：Windows 11

## 其他

如果无法复现，请多试几次，本人在两台设备（一台电脑，一台手机）中进行测试，均有以上漏洞。

**Comment by NB-Group** [comment]
首先这个关闭语音球功能不是我开发的哈（
貌似确实有这个问题，把开发者拉出去斩了（
感谢您的反馈~

**Comment by User782Tec** [comment]
炸裂

**Comment by ghost** [comment]
@NB-Group 别这么残忍
瞧吧,人家782都炸裂了

**Comment by NebulaTechs** [comment]
这.

**Comment by ghost** [comment]
@NebulaTechs 别这啊那啊的

**Comment by lingbopro** [comment]
我找到问题所在了，#450 

这玩意是 @jobsofferings 写的

**Comment by tjy-gitnub** [comment]
炸裂

**Comment by lingbopro** [comment]
> 炸裂

？
