### ISSUE TITLE
[漏洞]语音球

### ISSUE THREAD

**Issue by dongtz123** [win12-online/win12#381]
## 描述

语音球有时点不开

## 重现

按以下步骤可重新复现该漏洞：

1. 点语音球左下角没反应

## 截图

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：edge
浏览器版本：121.0.2277.98
操作系统：windows 12 (win10) 😉

## 其他

真的没有其他内容了！！！

**Comment by User782Tec** [comment]
如果您在点击语音球后发现没有动画或其他的样式能指示当前是否正在识别的状态，请不要慌张，因为@NB-Group 暂时没有给语音球添加反馈动画
如果要使用语音球，请先打开记事本并将焦点移到记事本的输入框内之后再点击语音球
语音球使用时，需要对页面提供对麦克风的使用权限
如果上面的方法不能解决您的问题，您可以为我们提供录屏、控制台输出等信息以让我们更好地解决问题
感谢您的反馈！
