### ISSUE TITLE
希望图标可以改色

### ISSUE THREAD

**Issue by MacroMeng** [win12-online/win12#384]
## 描述

主题不是有颜色吗？桌面图标不是也有颜色吗？
当我们更改*主题颜色*时，桌面图标并不会改色，所以导致灰常难看。（以下是Minecraft主题）
![image](https://github.com/tjy-gitnub/win12/assets/132897527/07b108a8-0e07-4b49-9f8d-83f28086f1c4)
如果桌面图标可以与主题颜色*同步*，那就好了ヾ(≧▽≦*)o

## 方案

可以用调(tiáo)色调(diào)等方式改变图标颜色……具体实现如下（感谢TurboWarp的大力支持！！！）
![image](https://github.com/tjy-gitnub/win12/assets/132897527/a3a5cf73-bf97-42a4-a77f-e6344529724d)

## 其他

我爱MC！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by NB-Group** [comment]
scratch玩多了吧你（雾

这个比较难实现，毕竟需要重新绘制图标
感谢您的建议～

**Comment by ghost** [comment]
听说图标是svg，重新填色不就行了
况且你们还有PowerPoint

**Comment by NB-Group** [comment]
部分图标不是svg，并且需要分别给每个主题的每个图标填色，工作量太大

**Comment by User782Tec** [comment]
CSS变量不就行了

**Comment by MacroMeng** [comment]
这样的话，那就俩主题颜色变量（不知道有没有）放进SVG图形颜色里？并不是很懂SVG格式……
________________________________
发件人: User782Tec ***@***.***>
发送时间: 2024年2月14日 下午 01:28
收件人: tjy-gitnub/win12 ***@***.***>
抄送: Macros ***@***.***>; Author ***@***.***>
主题: Re: [tjy-gitnub/win12] 希望图标可以改色 (Issue #384)


CSS变量不就行了

―

**Comment by MacroMeng** [comment]
看了下svg渐变，简单把玩了下scratch：
[cid:04fc472a-d98a-42da-9ecd-4f5191f11ac7]
保存后看到颜色在这里：[cid:22c2f237-e771-4051-aa2d-69aa0947715c]
应该就是两个<stop ...>标签。你们有什么办法吗？
________________________________
发件人: Meng Macros ***@***.***>
发送时间: 2024年2月15日 上午 10:59
收件人: tjy-gitnub/win12 ***@***.***>; tjy-gitnub/win12 ***@***.***>
抄送: Author ***@***.***>
主题: 回复: [tjy-gitnub/win12] 希望图标可以改色 (Issue #384)

这样的话，那就俩主题颜色变量（不知道有没有）放进SVG图形颜色里？并不是很懂SVG格式……
________________________________
发件人: User782Tec ***@***.***>
发送时间: 2024年2月14日 下午 01:28
收件人: tjy-gitnub/win12 ***@***.***>
抄送: Macros ***@***.***>; Author ***@***.***>
主题: Re: [tjy-gitnub/win12] 希望图标可以改色 (Issue #384)


CSS变量不就行了

―

**Comment by User782Tec** [comment]
定义一段渐变，从--theme-1到--theme-2（在本项目中已经定义这两个变量）
然后直接在要渐变的地方用这段渐变就行了

**Comment by tjy-gitnub** [comment]
一个可行的办法是对每个图标设置 `filter`，另一个方法是添加一层主题色的覆盖。但这样往往只会让图标变得更难以辨认，却不会对其美观程度有太大提升，故不予采纳。
