### ISSUE TITLE
有关于新闻板块的想法

### ISSUE THREAD

**Issue by lingbaijun** [win12-online/win12#385]
微软已黑入所有Android手机，将在明日自动刷入Windows Phone 12系统，内置安卓子系统，由魅族Flyme提供

**Comment by ghost** [comment]
过头了吧。。。（我平板就是Android）

**Comment by MacroMeng** [comment]
吉利把魅族收了，那是不是来个梦幻联动[bushi]

**Comment by ltx-github** [comment]
过分了吧，人家微软怎么可能“黑”呢，Windowsphone12也不是所有用户都想要的

**Comment by tjy-gitnub** [comment]
微软：好好好
