### ISSUE TITLE
[建议]新设“Windows 帮助”和cmd中的help指令

### ISSUE THREAD

**Issue by wodemc** [win12-online/win12#388]
## 描述

1.可以新增一个Windows帮助功能，以免用户不知道部分功能的全部用法。
2.在cmd中加入?或help指令，用于提供帮助。
3.在关闭记事本、白板等功能时，提示是否要保存。

## 方案

同上。

## 其他

1.如果愿意的话，还可以加入原神（
（https://ys.fancyb.top/）
2.如果真正的Windows 12出来之后，这个项目会怎么样……
3.这个标签是干什么用的？
![image](https://github.com/tjy-gitnub/win12/assets/154050608/8fd1e769-ee98-49e8-9696-29142940a192)

**Comment by wodemc** [comment]
对了，原神是假的，只是个登录界面

**Comment by surfissh** [comment]
或许可以加入`node`命令，使用`Function`运行代码

**Comment by tjy-gitnub** [comment]
1. 参阅 Windows11 帮助
2. 就是说 cmd 并没有什么正经功能，或请在本地 cmd 中运行 `help` 查看帮助
3. 目前不支持保存
4. 其他：链接 404 了
