### ISSUE TITLE
[漏洞] 某些应用（edge、关于等）用任务栏切换至文件资源管理器时不靠前的bug（机型：MatePad 11英寸 2023）

### ISSUE THREAD

**Issue by zhy-ac** [win12-online/win12#389]
## 描述

某些应用（edge、关于等）用任务栏切换至文件资源管理器时不靠前的bug

## 重现

按以下步骤可重新复现该漏洞：

（MatePad 11英寸 2023）打开网页里的edge，接着打开explorer，edge靠前为焦点，任务栏再切换至explorer，发现没有靠前。

## 测试环境

浏览器：默认浏览器（不知道什么名字）
浏览器版本：14.0.7.302
操作系统：HarmonyOS 4.0.0

**Comment by tjy-gitnub** [comment]
经测试，并无此 bug 或其已解决
