### ISSUE TITLE
[漏洞] 打开飞行模式后，可以打开Wi-Fi、蓝牙和移动热点

### ISSUE THREAD

**Issue by surfissh** [win12-online/win12#390]
## 描述

飞行模式打开后，可以打开Wi-Fi、蓝牙和移动热点

## 重现

按以下步骤可重新复现该漏洞：

- 点击页面下方「工具栏」
- 打开 *Wi-Fi*
- 打开 *飞行模式* ， *Wi-Fi* 自动关闭。此时一切正常。
- 再次尝试打开 *Wi-Fi* ，发现可以打开，并且飞行模式没有关闭。
- 蓝牙和移动热点同理。

## 截图

![image](https://github.com/tjy-gitnub/win12/assets/80567300/2254d12b-3310-4f75-82f0-d0b2635b0533)

## 测试环境

浏览器： Chrome
浏览器版本：108.0.5359.125
操作系统：Windows 7

## 其他

已经修复并提交 Pull Request 。

**Comment by Kingsmai** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/23566051/c23964e9-a75d-4428-83d2-09acb6f06814)
没想到吧，2024 年的 Windows 11 也有这个 BUG，所以是特性~ 🦊

**Comment by NaHCO3-code** [comment]
> ![image](https://private-user-images.githubusercontent.com/23566051/305883323-c23964e9-a75d-4428-83d2-09acb6f06814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzYwOTYsIm5iZiI6MTcwODMzNTc5NiwicGF0aCI6Ii8yMzU2NjA1MS8zMDU4ODMzMjMtYzIzOTY0ZTktYTc1ZC00NDI4LTgzZDItMDlhY2I2ZjA2ODE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA5NDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNWQzNDViZjU4NWI3MGIwMjcyZWQ0NTJlM2U3ZjE5OGIxMGVjOTQ2OTI1ODVkZDhkNzkyNzBmOTA0YzY2YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RkZz6227LJF0Ldm67aBumXOUtPsv6VigURk_8X28T7g) 没想到吧，2024 年的 Windows 11 也有这个 BUG，所以是特性~ 🦊
逆天

**Comment by surfissh** [comment]
> ![image](https://private-user-images.githubusercontent.com/23566051/305883323-c23964e9-a75d-4428-83d2-09acb6f06814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzYwOTYsIm5iZiI6MTcwODMzNTc5NiwicGF0aCI6Ii8yMzU2NjA1MS8zMDU4ODMzMjMtYzIzOTY0ZTktYTc1ZC00NDI4LTgzZDItMDlhY2I2ZjA2ODE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA5NDMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNWQzNDViZjU4NWI3MGIwMjcyZWQ0NTJlM2U3ZjE5OGIxMGVjOTQ2OTI1ODVkZDhkNzkyNzBmOTA0YzY2YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RkZz6227LJF0Ldm67aBumXOUtPsv6VigURk_8X28T7g) 没想到吧，2024 年的 Windows 11 也有这个 BUG，所以是特性~ 🦊

逆天

**Comment by genius-alray** [comment]
因为开启飞行模式只是会禁用移动数据，WLAN只是自动关闭，如果是在飞机上有相关规定或者得到工作人员的允许是可以开启WLAN的

**Comment by surfissh** [comment]
是我孤陋寡闻了
