### ISSUE TITLE
[建议]在微软发布的宣传片中，任务栏并不是这种形式，而是上下左右都分离一丢丢，并且圆角。还有一个类似MacOS的顶部栏，鼠标移动到最上面就会出现。建议的这些内容可以让Win12网页版更像真实发布的Win12。

### ISSUE THREAD

**Issue by ltx-github** [win12-online/win12#392]
## 描述

    在微软发布的宣传片中，任务栏并不是和这种形式相同。 
 

## 方案

任务栏在Win11基础上，透明度增加，上下左右仅分离一点点，圆角。还有一个类似MacOS的顶部栏，鼠标移动到最上面就会出现。

##致谢

    用html创作的Windows12网页版很新奇，希望和实际发布的Windows12更像。

**Comment by NebulaTechs** [comment]
感谢您宝贵的意见
但不得不说的是 Windows12不会在2024年发布，今年只有Windows11 24H2

**Comment by tjy-gitnub** [comment]
虽然但是，微软至今没有发布所谓 “宣传片”
