### ISSUE TITLE
[建议]增加全屏快捷键

### ISSUE THREAD

**Issue by wodemc** [win12-online/win12#394]
## 描述

可以做一个快速全屏的按键，这是可以实现的。

## 方案

参见geekprank.com，这个网站有类似的功能。

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by ColvinWest054554** [comment]
我记得这个得靠浏览器本身实现

**Comment by CafeKiller** [comment]
JavaScript 原生就内置有对应API，mdn文档中有相关说明。

相关链接：https://developer.mozilla.org/zh-CN/docs/Web/API/Fullscreen_API/Guide

**Comment by OUYANGSIR** [comment]
直接F11

**Comment by wodemc** [comment]
> 直接F11

要是可以我还问啊……
我们学校电脑没有硬键盘，软键盘没有Fn

**Comment by tjy-gitnub** [comment]
这个是浏览器的事，就算加也是调用浏览器的 api，估计会有平台问题。`F11` 秒了
