### ISSUE TITLE
[建议] 添加新闻：迷你世界或将停服？迷你玩：我们会争取让玩家备份数据

### ISSUE THREAD

**Issue by ColvinWest054554** [win12-online/win12#395]
随便配个迷你的图

**Comment by Minemetero** [comment]
## 投稿新闻

1. 请确保您所投稿的新闻**均不在当前时刻或过去时刻的现实生活中出现**，即为纯虚构。

2. 禁止上传任何违反法律或政治敏感的内容，否则将会采取锁定+视情况封禁的处理（温馨提示：时事新闻也不行）。

I just found this from the contributing file.......

**Comment by tjy-gitnub** [comment]
《或将》
