### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by shx20140617** [win12-online/win12#398]
## 描述

一个莫名其妙出现的透明窗口，没有软件描述，LOGO也是无法显示的，且无法打开（打开就跟没打开一样）

## 重现

按以下步骤可重新复现该漏洞：

1.打开Copilot
2.向它发送“关闭云母效果"
3.Copilot不仅出错了，任务栏上还会出现BUG窗口图标

## 截图

![反馈](https://github.com/tjy-gitnub/win12/assets/148339128/f9811c16-6691-4100-b83b-b8920098cf0b)

## 测试环境

浏览器：Edge
浏览器版本：122.0.2365.52 64位
操作系统：Windows 10 22H2

**Comment by NB-Group** [comment]
AI 是基于 4bit 量化后的 llama 的，所以智商比较低，我没有办法（
实际上只需要刷新就可以解决。

**Comment by NebulaTechs** [comment]
试试Claude 3(bs

**Comment by tjy-gitnub** [comment]
`Ctrl + R` 秒了。（现在应该没有这个 bug 了吧，毕竟 copilot 都没了

**Comment by NB-Group** [comment]
《》
其实后面还会开的（
