### ISSUE TITLE
[建议] 加一个在任务管理器关闭关键应用蓝屏的功能

### ISSUE THREAD

**Issue by ColvinWest054554** [win12-online/win12#399]
没什么用，只是更仿真一点

**Comment by User782Tec** [comment]
而事实是已经有了(
结束system进程会引发蓝屏

**Comment by zsr-lukezhang** [comment]
可惜现实世界中（Microsoft Windows）会拒绝访问

**Comment by zsr-lukezhang** [comment]
有一个问题
任务管理器全是随机的，根本点不到啊...
能不能再逼真一点，分成“应用”“后台进程”和“Windows 进程”
并按字母顺序排序。
![image](https://github.com/tjy-gitnub/win12/assets/145239958/e8bcd771-b56d-46cd-a0ec-16e5d2858dc2)
进程列表参考任务管理器本体。

**Comment by tjy-gitnub** [comment]
可以搜索
