### ISSUE TITLE
hui

### ISSUE THREAD

**Issue by huangzh20** [win12-online/win12#4]
这里是黄测评工作室
这个开源项目的想法非常好，有良好的应用前景😁
希望可以加快更新
对啦，什么时候可以适配安卓或iphone手机呢？我希望人人都想用手机来看这个，好玩的windows12模拟器吧！
我是黄测评工作室，感谢大家来评论
(≧∇≦)

**Comment by huangzh20** [comment]
这确实是一个良有良好应用前景的开源项目

**Comment by tjy-gitnub** [comment]
嗯嗯，说得有道理
