### ISSUE TITLE
[建议]接入开源的bing爱镜像

### ISSUE THREAD

**Issue by JosteinGit** [win12-online/win12#400]
## 描述

（请简要描述一下建议）

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
《语音识别实锤》
没必要啊，又复杂又不稳定

**Comment by zsr-lukezhang** [comment]
我也有这个想法。试试
https://cf.bingai.lukezhang.win/web/#/
我用Cf Workers搞的，每天最多100,000个请求，就是。。。当成侧边栏有点不美观。

**Comment by NB-Group** [comment]
微软还真就是直接塞进去了

**Comment by NB-Group** [comment]
<img width="389" alt="image" src="https://github.com/tjy-gitnub/win12/assets/121747915/fd98738c-9a0e-41ce-80fa-ab6f45ce57eb">

**Comment by zsr-lukezhang** [comment]
只不过，微软是Copilot，我们是BingAI

**Comment by zsr-lukezhang** [comment]
又测试了一下。不用魔法加载速度不怎么友好，三个点一直在动...不过有应该比没有好一点吧

**Comment by NB-Group** [comment]
不用魔法上不去啊

**Comment by zsr-lukezhang** [comment]
我可以啊

**Comment by NB-Group** [comment]
你怕不是在国外啊

**Comment by zsr-lukezhang** [comment]
当然不是。
我记得使用中国移动会多Q一些网站

**Comment by zsr-lukezhang** [comment]
微软的敏感词范围似乎扩大了
![image](https://github.com/tjy-gitnub/win12/assets/145239958/301c9d16-f287-4575-b696-d14ee57b7e1d)
所以，它现在是Copilot？
![image](https://github.com/tjy-gitnub/win12/assets/145239958/e88d8b12-bd87-440b-a99a-cd178afef26d)

me: 你好，Copilot。
bot: 你好！有什么我可以帮助你的吗？ 😊
me: 你好，Bing。
bot: 你好！抱歉，我实际上是Microsoft Copilot，而不是Bing。有什么我可以帮助你的吗？ 😊
我又试了一下，是可以的。
有图为证：
![image](https://github.com/tjy-gitnub/win12/assets/145239958/8704ea8b-6d31-4dbb-bdc0-6db7d864a283)
前面的截图都没有用`在霍格沃兹学到的本领`

**Comment by zsr-lukezhang** [comment]
图加载不出来的话，使用在`霍格沃兹学到的本领`。
但是，我没用，也加载出来了
不过，我DNS是1.1.1.1，备用是1.0.0.1，也许对此有帮助。

**Comment by zsr-lukezhang** [comment]
录了个视频。速度挺快的
https://lukezhang-my.sharepoint.com/:v:/g/personal/admin_lukezhang_onmicrosoft_com/EYko4bEaGV1KqQ_TnCtH90QBVlcSyQHD_FLUr9HDAtc76g?e=hafP37

**Comment by NB-Group** [comment]
哦你用镜像站啊，我的意思是https://copilot.microsoft.com/

**Comment by tjy-gitnub** [comment]
so? 接了吗？

**Comment by NB-Group** [comment]
没接，这个镜像是开源的，原作者都停止更新了，所以我说不稳定，微软一改接口就寄

**Comment by zsr-lukezhang** [comment]
> 哦你用镜像站啊，我的意思是https://copilot.microsoft.com/

更新一下：现在企业版可以直接copilot.cloud.microsoft，还国内可用
~~可以考虑弄个共享企业账户~~
然后个人版copilot.microsoft.com现在国内只有个UI，显示出现了问题，是否刷新

**Comment by NB-Group** [comment]
个人版开翻墙后重新登录就可用了，我经常用。

**Comment by lingbopro** [comment]
> 个人版开翻墙后重新登录就可用了，我经常用。

哦？去逝逝

**Comment by zsr-lukezhang** [comment]
> 个人版开翻墙后重新登录就可用了，我经常用。

什么意思
没看懂（）

**Comment by Mbilse** [comment]
> 不用魔法上不去啊

就用呗
