### ISSUE TITLE
我用不了copilot

### ISSUE THREAD

**Issue by huangzh1206** [win12-online/win12#401]

**Comment by NB-Group** [comment]
请你检查自己的网络环境，或使用代理服务器。另一种可能是达到了访问次数限制(所有人每分钟50次)

**Comment by huangzh1206** [comment]
> 请你检查自己的网络环境，或使用代理服务器。另一种可能是达到了访问次数限制(所有人每分钟50次)

我检查过了，而且从来没用过copilot，会不会是地区在大陆访问不了copilot啊

**Comment by NB-Group** [comment]
不，是所有人加在一起一分钟不能超过50次，而且是中国大陆可以访问的，详见：[DNS解析报告](https://github.com/tjy-gitnub/win12/blob/main/scripts/AI%20Copilot%20service/README.md)

**Comment by huangzh1206** [comment]
这样得改进一下吧要不然就像堵车一样大家都挤着

**Comment by huangzh1206** [comment]
> 不，是所有人加在一起一分钟不能超过50次，而且是中国大陆可以访问的，详见：[DNS解析报告](https://github.com/tjy-gitnub/win12/blob/main/scripts/AI%20Copilot%20service/README.md)

是不是可以几个人分组然后一分钟50次这样也好而且成本没有增加很多

**Comment by NB-Group** [comment]
其实有很多方法，例如堵塞式等待，或者多开一个分流，至是懒得搞而已（

**Comment by huangzh1206** [comment]
> 其实有很多方法，例如堵塞式等待，或者多开一个分流，至是懒得搞而已（

嗯嗯
