### ISSUE TITLE
[建议]copilot 全是英文，看不懂

### ISSUE THREAD

**Issue by zhaowenmo** [win12-online/win12#402]
## 描述

copilot 全是英文，看不懂

## 方案

copilot 改为中文

**Comment by NB-Group** [comment]
看不懂请翻译

**Comment by lingbopro** [comment]
直接跟Copilot 说`用中文`就行了吧
![Screenshot](https://github.com/tjy-gitnub/win12/assets/148617407/dae23fb8-94f9-4043-8454-6367e04e1f91)

**Comment by NB-Group** [comment]
确实

**Comment by NB-Group** [comment]
但是LLAMA的训练预料大部分是英文，建议用英文

**Comment by ruziniuuuuu** [comment]
不如新加一个特性：更改系统语言

**Comment by lingbopro** [comment]
> 不如新加一个特性：更改系统语言

但是i18n的工作量会很大
