### ISSUE TITLE
[建议] Issue界面分类

### ISSUE THREAD

**Issue by zsr-lukezhang** [win12-online/win12#407]
## 描述

Issue界面分类使用标签而非【建议】【漏洞】

## 方案

举个例子（要举就举个高大上的）微软PowerToys。
![image](https://github.com/tjy-gitnub/win12/assets/145239958/f6dd2b23-8991-4b67-a100-b2fb87a91fa4)
用的都是小标签。

## 其他

GitHub地址：https://github.com/microsoft/PowerToys/issues

**Comment by User782Tec** [comment]
有标签啊...
