### ISSUE TITLE
[建议] 更换AI源

### ISSUE THREAD

**Issue by Minemetero** [win12-online/win12#410]
可以把模型换成谷歌开源的 gemma :)

**Comment by NB-Group** [comment]
没钱思密达~

**Comment by Minemetero** [comment]
> 没钱思密达~

https://huggingface.co/google/gemma-7b

这不是有吗?

**Comment by NB-Group** [comment]
部署它不需要钱吗（）
而且从4/1开始，cloudflare的AI托管开始计费了

**Comment by huangzh1206** [comment]
> 可以把模型换成谷歌开源的 gemma :)

不是Windows和copilot都是微软的所以要搭配啊

**Comment by NB-Group** [comment]
> 不是Windows和copilot都是微软的所以要搭配啊

啊？我是这Copliot的开发者，你这发言我都没看懂（

**Comment by Minemetero** [comment]
> > 不是Windows和copilot都是微软的所以要搭配啊
> 
> 啊？我是这Copliot的开发者，你这发言我都没看懂（

它是指Microsoft Copilot 的图标,所以他的理解是图标一样,核心就一样....

**Comment by NB-Group** [comment]
斯，好吧
