### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by zjbjjnj** [win12-online/win12#411]
## 描述

[小组件]【新闻】bilibili即将推出子项目atotatot（A站）?
## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by Minemetero** [comment]
## 投稿新闻

1. 请确保您所投稿的新闻**均不在当前时刻或过去时刻的现实生活中出现**，即为纯虚构。

2. 禁止上传任何违反法律或政治敏感的内容，否则将会采取锁定+视情况封禁的处理（温馨提示：时事新闻也不行）。

I just found this from the contributing file.......
