### ISSUE TITLE
[建议]添加JSON配置功能

### ISSUE THREAD

**Issue by LemonDrug** [win12-online/win12#412]
## 描述

其实每个人在将这个项目部署到本地时，都是希望可以有一些自定义信息修改的，可是每次更新都要手动修改一大堆东西真的会很苦恼。

## 方案

希望可以将所有文本整合为一个Json，每个键对应的内容就是自定义的内容，这样方面日后可以修改，多谢啦。

## 其他

呜呜，电脑好好看，手机上有点差，不过，辛苦各位了。

**Comment by LemonDrug** [comment]
话说，要不要考虑真的做个WebOS呢？
请看这里https://webdesk.cc/

**Comment by wodemc** [comment]
但好像调用json在本地会出现跨域问题。

**Comment by lingbopro** [comment]
> 但好像调用json在本地会出现跨域问题。

可以写进JS，用`<script>`引入

**Comment by tjy-gitnub** [comment]
这个确实需要一定的代码能力，毕竟这个项目也不是为了做一个高度自定义的系统，也没有这个必要吧
