### ISSUE TITLE
[建议]终端版python不易修改和再次运行输入过的命令

### ISSUE THREAD

**Issue by yaoying2012** [win12-online/win12#413]
## 描述

调试时，对于只需要改动一个值的命令，需要复制粘贴。

## 方案

终端版python建议捕获向上的键盘按键，按下后跳回到上一条命令。

**Comment by NB-Group** [comment]
懒哦（
@User782Tec 你来吧（）

**Comment by tjy-gitnub** [comment]
你本地没有python终端吗？为什么不去用？ >u-)o
