### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ghost** [win12-online/win12#42]
我在**github**里逛了一圈，发现了你的作品，感觉很有前景。我希望与你展开合作，但由于我对HTML不太了解（其实是小白）。
但是开始时我可以从优化文字，图片资源及回复消息开始。
我也在学习HTML。
bye
@tjy-gitnub

**Comment by tjy-gitnub** [comment]
你好😏

**Comment by tjy-gitnub** [comment]
你是怎么"逛"到这么一个小项目的🤔😂😅

**Comment by Samtjs** [comment]
网上康到的

**Comment by Samtjs** [comment]
D确不是《逛》到的。

**Comment by ghost** [comment]
网上《康》到的
