### ISSUE TITLE
[漏洞]Windows 12 Copilot

### ISSUE THREAD

**Issue by fanghuangxu** [win12-online/win12#420]
## 描述

Windows 12 Copilot无法使用

## 重现

按以下步骤可重新复现该漏洞：

打开Windows 12 Copilot

## 测试环境

浏览器：Safari,
浏览器版本：17.3.1 
操作系统：macOS Monterey 12.7.2

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/71709a9a-19d0-4047-8d6a-556a13270de0)

**Comment by ghost** [comment]
不是正常吗？
