### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by mymac123** [win12-online/win12#421]
## 描述

（请简要描述一下建议）
copilot全是英文·，对于新手不太友好
![屏幕截图 2024-05-16 204333](https://github.com/tjy-gitnub/win12/assets/169814922/73215e1b-f0cf-4541-9a5b-95ce33f90b9f)

## 方案

（请在这里提出施行建议的方案或希望有的功能）
希望coplot支持中文

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by NB-Group** [comment]
目前我我们使用的时llama模型，该模型使用语料大多数都是外国的，并且我们暂时不会更换模型。
所以考验英语的时候到啦（

**Comment by tjy-gitnub** [comment]
让他说中文就行了
