### ISSUE TITLE
[漏洞]winver和cmd中显示的构建版本号不一致

### ISSUE THREAD

**Issue by ZZY3312** [win12-online/win12#422]
## 描述

winver和cmd中显示的构建版本号不一致

## 重现

按以下步骤可重新复现该漏洞：

1. 打开这个网页版windows
2. 点击开始菜单 > 运行，输入cmd.exe
3. 在cmd中输入winver.exe
4. 可看到cmd显示构建39035.7324，winver显示构建24612.1896

## 截图

![IMG_0025](https://github.com/tjy-gitnub/win12/assets/149882253/76df7753-c9aa-41d0-b474-982f84df264b)

## 测试环境

浏览器：Safari
操作系统：iPadOS 17.4.1 (21E237)

**Comment by ghost** [comment]
这是故意的

**Comment by zsr-lukezhang** [comment]
> 这是故意的

为什么🤔

**Comment by tjy-gitnub** [comment]
啊，这，，，重要吗。。

**Comment by lingbopro** [comment]
十分甚至九分的重要啊（恼
