### ISSUE TITLE
[建议]关于开始菜单

### ISSUE THREAD

**Issue by hitech2233** [win12-online/win12#423]
## 描述
![image](https://github.com/tjy-gitnub/win12/assets/164608562/0f27af3a-1f0a-4237-8773-a279e29f9342)
点击桌面，程序之类的要把开始菜单之类的自动关上吧

**Comment by tjy-gitnub** [comment]
确实，很合理（肯定
但是不想做了。。

**Comment by kjmjh** [comment]
> 确实，很合理（肯定
> 但是不想做了。。

我也想有这个功能(主要是……)
