### ISSUE TITLE
大模型部分错误比较严重

### ISSUE THREAD

**Issue by yukiwhite** [win12-online/win12#426]
问了一个问题出现乱码后，图标贴图莫名丢失，之后再也打不开了，是调用的API吗？好像微软的AI停用了要，这块也要注意下

**Comment by tjy-gitnub** [comment]
@NB-Group

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/731373b2-d92c-42cc-acf6-d1527e244fb5)

另外模型输出解析是谭景元(@tjy-gitnub )写的（）

**Comment by tjy-gitnub** [comment]
额，你说的对，但是错误这种东西并不一定需要改嘛

**Comment by NB-Group** [comment]
@tjy-gitnub 你中考考完了吗

**Comment by NB-Group** [comment]
咋不回嘛（
