### ISSUE TITLE
[建议]关于Microsoft Form和帮助功能

### ISSUE THREAD

**Issue by wodemc** [win12-online/win12#427]
## 描述

1.Microsoft的反馈方式不能用了，得重置一下。
![image](https://github.com/tjy-gitnub/win12/assets/154050608/a8f82ed4-392f-43a4-afeb-5d2839db2ed6)
2.增加一个帮助功能（就像我，我一直不知道还有winver.exe一样）。

**Comment by tjy-gitnub** [comment]
1. 你可以在github上交issues
2. 沒事，就是個彩蛋

**Comment by NB-Group** [comment]
@tjy-gitnub 你中考成绩出了吗（

**Comment by tjy-gitnub** [comment]
6
