### ISSUE TITLE
[建议]添加新闻：金鹰卡通与佳佳卡通融合发布中国新声代第111111123454系

### ISSUE THREAD

**Issue by Xuwanxia** [win12-online/win12#428]
## 描述

（请简要描述一下建议）

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by lingbopro** [comment]
虽然但是，好像没图是不行的吧（

**Comment by Xuwanxia** [comment]
发自我的iPhone照片


------------------ 原始邮件 ------------------
发件人: Lingbo ***@***.***&gt;
发送时间: 2024年6月23日 11:48
收件人: tjy-gitnub/win12 ***@***.***&gt;
抄送: Xuwanxia ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [tjy-gitnub/win12] [建议]添加新闻：金鹰卡通与佳佳卡通融合发布中国新声代第111111123454系 (Issue #428)





 
虽然但是，好像没图是不行的吧（

**Comment by lingbopro** [comment]
> 发自我的iPhone照片
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Lingbo ***@***.***&gt; 发送时间: 2024年6月23日 11:48 收件人: tjy-gitnub/win12 ***@***.***&gt; 抄送: Xuwanxia ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [tjy-gitnub/win12] [建议]添加新闻：金鹰卡通与佳佳卡通融合发布中国新声代第111111123454系 (Issue #428) 虽然但是，好像没图是不行的吧（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

啊？
照片？

这是发附件里了吗...

**Comment by Xuwanxia** [comment]
没错，发附件里面了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lingbo ***@***.***&gt;
发送时间: 2024年6月23日 12:10
收件人: tjy-gitnub/win12 ***@***.***&gt;
抄送: Xuwanxia ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [tjy-gitnub/win12] [建议]添加新闻：金鹰卡通与佳佳卡通融合发布中国新声代第111111123454系 (Issue #428)





  
发自我的iPhone照片
 …
 ------------------ 原始邮件 ------------------ 发件人: Lingbo @.&gt; 发送时间: 2024年6月23日 11:48 收件人: tjy-gitnub/win12 @.&gt; 抄送: Xuwanxia @.&gt;, Author @.&gt; 主题: Re: [tjy-gitnub/win12] [建议]添加新闻：金鹰卡通与佳佳卡通融合发布中国新声代第111111123454系 (Issue #428) 虽然但是，好像没图是不行的吧（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
啊？
 照片？
 
这是发附件里了吗...

**Comment by lingbopro** [comment]
> 没错，发附件里面了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Lingbo ***@***.***&gt; 发送时间: 2024年6月23日 12:10 收件人: tjy-gitnub/win12 ***@***.***&gt; 抄送: Xuwanxia ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [tjy-gitnub/win12] [建议]添加新闻：金鹰卡通与佳佳卡通融合发布中国新声代第111111123454系 (Issue #428) 发自我的iPhone照片 … ------------------ 原始邮件 ------------------ 发件人: Lingbo @.&gt; 发送时间: 2024年6月23日 11:48 收件人: tjy-gitnub/win12 @.&gt; 抄送: Xuwanxia @.&gt;, Author @.&gt; 主题: Re: [tjy-gitnub/win12] [建议]添加新闻：金鹰卡通与佳佳卡通融合发布中国新声代第111111123454系 (Issue #428) 虽然但是，好像没图是不行的吧（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 啊？ 照片？ 这是发附件里了吗... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

emmm
发邮件附件里在GitHub是看不到的啊
你得在 GitHub 网页版或者 [GitHub Mobile](https://github.com/mobile) 上传才行

**Comment by tjy-gitnub** [comment]
离大谱（
