### ISSUE TITLE
copilot挂了

### ISSUE THREAD

**Issue by Oliver13211** [win12-online/win12#430]
## 描述

copilot无法使用

## 重现

1、打开Windows 12 Copilot
2、点击开始使用
3、显示“发生错误，请查看控制台输出或重试”
4、也没有在控制台中找到关于此错误的输出

## 截图
![屏幕截图 2024-07-10 123155](https://github.com/tjy-gitnub/win12/assets/140150018/2a4e9dfc-79d6-4eaa-99fb-e4be198f6e49)

## 测试环境

浏览器：Edge
浏览器版本：126.0.2592.87 64位 正式版本
操作系统：Windows 11 23H2 build 22631.3880

## 其他

无

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/22a2a564-5b4e-41cc-b6c8-90dd83c40a57)
难怪呢，这个模型已经被弃用了，我正在着手更新代码

**Comment by Oliver13211** [comment]
https://github.com/meta-llama/llama3
llama3可以吗？

**Comment by NB-Group** [comment]
现在我更新了Qwen1.5-14B，但是相关适配还没做好

**Comment by Oliver13211** [comment]
通义千问？

**Comment by NB-Group** [comment]
是的，他们开源的模型。Cloudflare最近增加了对它的支持，[这里](https://developers.cloudflare.com/workers-ai/models/qwen1.5-14b-chat-awq/)

**Comment by Oliver13211** [comment]
免费的吗？

**Comment by NB-Group** [comment]
有免费的额度，不过已经非常够用了

**Comment by Oliver13211** [comment]
那上面模型还行全的，谢谢！

**Comment by Mbilse** [comment]
> ![image](https://github.com/tjy-gitnub/win12/assets/121747915/22a2a564-5b4e-41cc-b6c8-90dd83c40a57)
> 难怪呢，这个模型已经被弃用了，我正在着手更新代码

不如用国内模型，或可以切换的
