### ISSUE TITLE
[漏洞] AI 又没了

### ISSUE THREAD

**Issue by ghost** [win12-online/win12#431]
## 描述
AI用不了了，控制台显示 500 INTERNAL SERVER ERROR

## 重现

按以下步骤可重新复现该漏洞：
点击ai助手，点击开始对话，然后就错误了

## 截图
![image](https://s21.ax1x.com/2024/07/10/pkheTyR.png)
![image](https://s21.ax1x.com/2024/07/10/pkhmSld.png)

## 测试环境

浏览器：msedge
浏览器版本：![image](https://github.com/tjy-gitnub/win12/assets/175222166/d9e446b7-39f7-47ad-bdbd-59754757c543)
操作系统：![image](https://github.com/tjy-gitnub/win12/assets/175222166/71fa6218-0c82-4752-9bc2-ca0366a26466)

## 其他
无

**Comment by NB-Group** [comment]
#430
