### ISSUE TITLE
[建议]新闻加一条

### ISSUE THREAD

**Issue by yuyuan08** [win12-online/win12#435]
## 描述

建议加一条新闻

## 方案

新闻内容：近日，微软发布会提出：Microsoft 365 将向广大用户提供免费服务

## 其他

莫有了

**Comment by github0801230xyz** [comment]
再加一个加载效果（就是新闻可以多加一点）和开机功能

**Comment by tjy-gitnub** [comment]
微软：6

***

（仔细阅读提交新闻的说明，内容不合规定
