### ISSUE TITLE
[问题]关于VSCode

### ISSUE THREAD

**Issue by mcr130102OIer** [win12-online/win12#437]
我有一个VSCode的网页版，我想在我的改编中替换掉以前的VSCode网页版，我阅读了源代码，我了解到了打开APP的函数，但是我不知道这些应用是在哪里定义的？并且我也想增加一些应用，请问我应该在哪里添加？

**Comment by lingbopro** [comment]
emm...
现在这个项目的HTML和JS文件都特难读，JS和HTML互相混杂，而且一个文件几千行，也没啥抽象函数，总之就是很难弄...

**Comment by tjy-gitnub** [comment]
如果是vscode.dev，那么就麻烦把issue关了罢，我们已经尝试过了

如果能成功
你可以在desktop.html中找到.window.vscode，可以进行修改
