### ISSUE TITLE
[漏洞] Copilot 无法使用

### ISSUE THREAD

**Issue by aaron888hacker** [win12-online/win12#439]
#我太懒了，不加了
QwQ

**Comment by tjy-gitnub** [comment]
copilot.microsoft.com 免费的>u-)o

**Comment by YHX2010-Dev** [comment]
> copilot.microsoft.com 免费的>u-)o

额……[Go Proxy BingAI](https://github.com/harry-zklcdc/go-proxy-bingai)，Copilot 聊天+BingAPI+自动人机验证+强制 GPT-4 Turbo+超多功能，了解一下？

**Comment by aaron888hacker** [comment]
> copilot.microsoft.com 免费的>u-)o

thank u(谢谢)

**Comment by aaron888hacker** [comment]
> 额……[Go Proxy BingAI](https://github.com/harry-zklcdc/go-proxy-bingai)，Copilot 聊天+BingAPI+自动人机验证+强制 GPT-4 Turbo+超多功能，了解一下？

# __谢谢__
