### ISSUE TITLE
想增添win12新闻

### ISSUE THREAD

**Issue by iamkezo1** [win12-online/win12#44]
[新闻：今日凌晨，Minecraft居然把代理权交给中国退役航天员谭景元，网易败下阵来了？

**Comment by iamkezo1** [comment]
![](https://i.17173cdn.com/2fhnvk/YWxqaGBf/cms3/urOXnYbptpylnCD.png%21a-3-540x.jpg)

**Comment by ghost** [comment]
好的我会提醒作者的

**Comment by ghost** [comment]
就是图片要剪

**Comment by tjy-gitnub** [comment]
高级
安排

**Comment by ghost** [comment]
J
