### ISSUE TITLE
建议增加在桌面上右键可以实现新建文件的功能，并且可以增加WPS，打开D：中的。。。文件

### ISSUE THREAD

**Issue by GitHubbianchengxiaobai** [win12-online/win12#440]
## 描述

（请简要描述一下建议）

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by lingbopro** [comment]
WPS…首先Windiws12绝对不会内置这种东西，而且要在Web端处理Office文档…不知道咋说了…

**Comment by tjy-gitnub** [comment]
windows12 全新的设计理念，桌面只放应用（快捷方式）。因为原来的桌面有些时候确实忒乱了
wps的话一则制作麻烦。
二则就算做出来了也不会叫wps，而是office。
这种专业的事情还是交给专业的人做吧（refer to jinshan

**Comment by YHX2010-Dev** [comment]
（WPS？出门右转[Microsoft 365](https://microsoft365.com)）

**Comment by tjy-gitnub** [comment]
桌面本来就不是放文件的地方，如果你有这个习惯，尽快改掉，不然重要文件在系统出现问题需要重装时容易丢失数据，很危险的。:)

**Comment by lingbopro** [comment]
> 桌面本来就不是放文件的地方，如果你有这个习惯，尽快改掉，不然重要文件在系统出现问题需要重装时容易丢失数据，很危险的。:)

正确

**Comment by Mbilse** [comment]
> windows12 全新的设计理念，桌面只放应用（快捷方式）。因为原来的桌面有些时候确实忒乱了
> wps的话一则制作麻烦。
> 二则就算做出来了也不会叫wps，而是office。
> 这种专业的事情还是交给专业的人做吧（refer to jinshan

还是叫tjy office
