### ISSUE TITLE
[漏洞]终端问题

### ISSUE THREAD

**Issue by JulyGlow** [win12-online/win12#443]
## 描述

终端输入一行字符,回车到下一行还是填充上一行的字符

## 重现

按以下步骤可重新复现该漏洞：

1.打开终端,输入一行字符
2.回车

## 截图

![issue](https://github.com/user-attachments/assets/527b73f9-d091-49b1-be3c-4d431240e8bf)

## 测试环境

浏览器：Edge
浏览器版本：Microsoft Edge 版本 127.0.2651.86 (正式版本) (64 位)
操作系统： Windows 10(版本2004 OS内部版本 19041.264)

**Comment by lingbopro** [comment]
有没有一种可能，这是方便你输入了错误或者不存在的命令后可以方便的修改（
毕竟这个终端也就支持几个命令，`echo`都没有

**Comment by JulyGlow** [comment]
> 有没有一种可能，这是方便你输入了错误或者不存在的命令后可以方便的修改（ 毕竟这个终端也就支持几个命令，`echo`都没有

我认为格式化输出更好,更像cmd,毕竟这是Windows 12,总得像一点.
方便修改,我觉得,既然终端支持命令极少,那么剩下的命令都是不存在的吧,不存在就没必要改了,直接`delete`.

**Comment by lingbopro** [comment]
emm

**Comment by tjy-gitnub** [comment]
![image](https://github.com/user-attachments/assets/91c49283-5bf5-40e7-9cd7-03a996226e68)
哈？你那是 pwsh 吧？

**Comment by lingbopro** [comment]
> ![image](https://private-user-images.githubusercontent.com/71509955/354802894-91c49283-5bf5-40e7-9cd7-03a996226e68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NzE4MTEsIm5iZiI6MTcyMjY3MTUxMSwicGF0aCI6Ii83MTUwOTk1NS8zNTQ4MDI4OTQtOTFjNDkyODMtNWJmNS00MGU3LTljZDctMDNhOTk2MjI2ZTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA3NTE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZTNmMGE1YTdjMDc0ZTY2M2IxOTdhZGVmZWUwMTk5NTAyMTA0OTdjNWVjM2RiNWQzMzQxMjFmNTQ1ZDFmNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oGV8cu4qjvqqZ51qXx53nkQZ22AleF5USa04a_BvHiw) 哈？你那是 pwsh 吧？

？

**Comment by lingbopro** [comment]
![type 2024 in powershell](https://github.com/user-attachments/assets/53f5b475-f5c3-4791-adf8-cd7e67f9259e)

这跟pwsh啥关系

**Comment by JulyGlow** [comment]
咳咳,从web跌入了本地(找了半天也没看到win12有cmd这东西)
问题指向win12的终端,你们却是一张一张的本地运行......

**Comment by lingbopro** [comment]
> 咳咳,从web跌入了本地(找了半天也没看到win12有cmd这东西) 问题指向win12的终端,你们却是一张一张的本地运行......

前面tjy说了一句是pwsh，我就本地运行了一下

**Comment by tjy-gitnub** [comment]
额，看图吧，格式化输出是 pwsh 的功能，cmd 没有这个功能，只会输入不是内部啥外部啥的报错。所以这不是 bug，这是 Windows 特性

**Comment by JulyGlow** [comment]
我是说,在终端输入命令回车后,清除新的一行.我可没见过cmd和pwsh会回车后填充上一行命令.
理解了没 ? : )

**Comment by tjy-gitnub** [comment]
> 我是说,在终端输入命令回车后,清除新的一行.我可没见过cmd和pwsh会回车后填充上一行命令. 理解了没 ? : )

> 有没有一种可能，这是方便你输入了错误或者不存在的命令后可以方便的修改（

**Comment by JulyGlow** [comment]
不改嘛,就不改喽.终端有自己的风格,就让它这样吧.
没事,毕竟这不是microsoft家造的.
