### ISSUE TITLE
[建议]构建一个插件系统，让更多的用户可以参与到win12页面内软件的开发，丰富网页内容

### ISSUE THREAD

**Issue by yushu200403** [win12-online/win12#445]
## 描述

增加一个插件系统，丰富网页生态
## 方案

可以简单的基于js、css、html，在网页内开发一些接口，从而让用户可以自由开发属于自己的软件（插件），或上传和其他用户分享

**Comment by lingbopro** [comment]
以这个项目目前的代码，想要实现这个很难啊，很多东西都得重构或者重写

**Comment by NB-Group** [comment]
关键是根本就没多少用户啊（

**Comment by lingbopro** [comment]
e

**Comment by tjy-gitnub** [comment]
接口有是有的，只是文档写的不多，还要自己阅读代码。目前的方案就是提交 pr。若只是要 iframe 嵌套网页作应用，也是不难的。

**Comment by tjy-gitnub** [comment]
@User782Tec 那边搞了个 msstore，不清楚他会不会搞这个

**Comment by NB-Group** [comment]
782《有轻微意向》继续完善msstore，但是考虑到我们的活跃用户并不多的问题，问题还是比较大的

**Comment by lingbopro** [comment]
（#484）

**Comment by Mbilse** [comment]
> 接口有是有的，只是文档写的不多，还要自己阅读代码。目前的方案就是提交 pr。若只是要 iframe 嵌套网页作应用，也是不难的。

不如直接用link rel,网上库特别多

**Comment by Mbilse** [comment]
> > 接口有是有的，只是文档写的不多，还要自己阅读代码。目前的方案就是提交 pr。若只是要 iframe 嵌套网页作应用，也是不难的。
> 
> 不如直接用link rel,网上库特别多
>.
>>.
>>>.
>>>>.
>>>>>.
>>>>>>.
>>>>>>>.
>>>>>>>>.
>>>>>>>>>.
随便搭几个库

**Comment by Mbilse** [comment]
> 接口有是有的，只是文档写的不多，还要自己阅读代码。目前的方案就是提交 pr。若只是要 iframe 嵌套网页作应用，也是不难的。

比如neal.fun
