### ISSUE TITLE
[建议]移动端问题(比如用移动端Chrome打开edge必应图标显示不全(能用))另外设置移动端下滑是个问题(下滑会点进去)还有不知道什么问题，移动端win12 copilot不能用(不知道是不是我的问题)pc端体验很好👍

### ISSUE THREAD

**Issue by kjmjh** [win12-online/win12#447]
## 描述

（请简要描述一下建议）

## 方案

（请在这里提出施行建议的方案或希望有的功能）

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by lingbopro** [comment]
所以为什么要把这么一长串文字放标题

**Comment by kjmjh** [comment]
> 所以为什么要把这么一长串文字放标题

e…………………………………………我想

**Comment by kjmjh** [comment]
下次丕定改

**Comment by NB-Group** [comment]
。copilot确实寄了，Cloudflare更新之后要收费了，免费限额比较少，不大够用，我决定先关一会（

**Comment by kjmjh** [comment]
> 。copilot确实寄了，Cloudflare更新之后要收费了，免费限额比较少，不大够用，我决定先关一会（

@NB-Group 可以参考一下这位的AI[](https://uutool.cn/ai/)

**Comment by kjmjh** [comment]
@NB-Group 可以参考一下这位的AI[]()https://uutool.cn/ai/

**Comment by kjmjh** [comment]
额……，说句题外话，@tjy-gitnub 也不知道你看没看，在你主页仓库的#1议题…………(弱弱的问一句:那是你本人吗？)
![IMG_20240822_084133_105.jpg](https://github.com/user-attachments/assets/884c5277-da2b-4d54-9ede-d5af2816c91e)

(图片被我打码了)(不关我任何事［菩萨保佑］)

**Comment by lingbopro** [comment]
> 额……，说句题外话，@tjy-gitnub 也不知道你看没看，在你主页仓库的#1议题…………(弱弱的问一句:那是你本人吗？)

tjy-gitnub/tjy-gitnub.github.io#1？

**Comment by kjmjh** [comment]
> > 额……，说句题外话，@tjy-gitnub 也不知道你看没看，在你主页仓库的#1议题…………(弱弱的问一句:那是你本人吗？)
> 
> tjy-gitnub/tjy-gitnub.github.io#1？

yes

**Comment by tjy-gitnub** [comment]
抽象，大家来评评理，谁更
![image](https://github.com/user-attachments/assets/0dbd4cc1-44e3-463e-80c9-f52ebe6e3233)

**Comment by kjmjh** [comment]
> 抽象，大家来评评理，谁更
> ![image](https://github.com/user-attachments/assets/0dbd4cc1-44e3-463e-80c9-f52ebe6e3233)
> 

评好了@User782Tec  来更（

**Comment by tjy-gitnub** [comment]
开桌面模式，实在不行用电脑。在移动端用电脑本来就不现实（，让我适配更不现实 >u-)ooo

**Comment by tjy-gitnub** [comment]
开桌面模式，实在不行用电脑。在移动端用电脑本来就不现实（，让我适配更不现实 >u-)ooo
