### ISSUE TITLE
[建议]关于动画以及一点细节

### ISSUE THREAD

**Issue by kjmjh** [win12-online/win12#448]
## 描述
1.希望窗口动画（打开或关闭窗口）可以参考一下这位的windows93网页版
[]()http://www.windows93.net/ (当然只是一个小希望，不做也行)
2.希望开始菜单展开时点击其它地方会自动收回
3.希望增加一个GitHub应用，打不开也行
## 方案

以上只是一些希望，也可以不做

## 其他

( *ˊᵕˋ)✩︎‧₊嗨害，又是我

**Comment by tjy-gitnub** [comment]
你指的是让 win12 这样 `摇摆` 起来？很天才的想法。。

**Comment by kjmjh** [comment]
> 你指的是让 win12 这样 `摇摆` 起来？很天才的想法。。

不是，只是想借鉴一部分

**Comment by kjmjh** [comment]
小脑萎缩了:[]()https://github.com/Misaka-0x447f/Dress
```
终极萎缩:
```
[]()https://drsrel.github.io/photos

**Comment by lingbopro** [comment]
Dress这个项目我之前看过，~~可惜~~只不过我不需要练习git🤓👆
（repo没了挺可惜的

**Comment by kjmjh** [comment]
> Dress这个项目我之前看过，~~可惜~~只不过我不需要练习git🤓👆
> （repo没了挺可惜的

雀食，原项目找不到了

**Comment by kjmjh** [comment]
准备换个头像，你们觉得这个好吗？
![kj.png](https://github.com/user-attachments/assets/fc9b51a5-064b-45e2-9b85-5d498f7207cb)

这个？![southeast.jpeg](https://github.com/user-attachments/assets/0e6b0787-7359-4096-9cce-f2ffaaa7ee55)

这个？![u=3752627732,3870014400&fm=253&fmt=auto&app=138&f=JPEG.jpeg](https://github.com/user-attachments/assets/7e06253a-ed2c-4fe7-9134-287799eb6aaa)

这个？
![u=3024950091,442688843&fm=253&fmt=auto&app=138&f=JPEG.jpeg](https://github.com/user-attachments/assets/8e34e236-b42a-4792-adae-a544f8176f99)

还是这个？
![oIJVjegAcFgNsAffykEeQHD6YCfPfyAsAAf6JAe~tplv-dy-shrink:480:720.jpg](https://github.com/user-attachments/assets/df6243a0-615a-42a6-a98f-92f43edb58d5)

**Comment by kjmjh** [comment]
或者？不换？

**Comment by lingbopro** [comment]
我不到啊…不过图是我的了（

**Comment by kjmjh** [comment]
> 我不到啊…不过图是我的了（

。。。。。。。。。。6

**Comment by kjmjh** [comment]
> 我不到啊…不过图是我的了（

那么，~~再给你几张如何?~~

**Comment by lingbopro** [comment]
> > 我不到啊…不过图是我的了（
> 
> 那么，~~再给你几张如何?~~

~~也不是不行~~

**Comment by kjmjh** [comment]
> > > 我不到啊…不过图是我的了（
> > 
> > 那么，~~再给你几张如何?~~
> 
> ~~也不是不行~~

如你所愿
![oAfDnQwAy6feJfgsCAVPgf2FJAjfAcAAf6NyYek~tplv-dy-shrink:480:720.jpg](https://github.com/user-attachments/assets/541ae8c8-6e32-4a73-afd4-1e480fe25188)

![o0SkfLfxDAqPA8WHWAaIAABfEQA5E6nvBQ9b7K~tplv-dy-shrink:480:723.jpg](https://github.com/user-attachments/assets/2b676d48-c9af-4230-9a18-b5be3daf5762)

**Comment by kjmjh** [comment]
此情此景，不禁想rap几句:（非我原创）

那就任由思念随风归去，北方雁阵已列。
我的生活能否如意，等来年得当面问喜鹊。
一场秋雨收了夏，既往忧喜都作罢
若这就收笔丟墨那我诗的尾章便剩几页。
手里总是握着笔或只烟，不知不觉和"秋"已错失"千"里。
明白了我这一生也不过就是在这来回"起落之间"。
一个人抽烟望着山，背影在秋千上落单。
今晚月亮和我一样都先荡个弯。
指与君勾许诺盼同甘，何必心忧体弱叹穷酸。
我离开这几年，故乡也不过新修几座"烂红砖"
从此不再独明月啊，"星都挤破半穹天"。
月下船里坐着摇奖，听鸥起落岸丛边。
独自轻忧喜乐，日子熬成"清粥米色"
就算重新勾起这段曾经也均都已各散成烟。
一叶孤舟载一舟孤叶也应收起这"扇蓬帆"     待
金秋雨落旱逢甘，
轻舟已过万重山…………
    
                            ————《一叶知秋》

**Comment by lingbopro** [comment]
也是成功上传到了我的有5层防护的网盘（（（

**Comment by kjmjh** [comment]
> 也是成功上传到了我的有5层防护的网盘（（（

![u=2366798081,3461850780&fm=253&fmt=auto&app=138&f=GIF.gif](https://github.com/user-attachments/assets/1b6d0d1b-94c1-4672-939a-77ef7eae2576)

!

**Comment by kjmjh** [comment]
请你们听歌:[](歌)https://kjmjh.github.io/MJH/musichtml.html
（懒得居中
