### ISSUE TITLE
[漏洞]老Bug了

### ISSUE THREAD

**Issue by kjmjh** [win12-online/win12#450]
## 描述

在设置里关闭语音输入球，再点击语音输入球原来的位置，任然会显示提示窗口

## 重现

按以下步骤可重新复现该漏洞：

在设置里关闭语音输入球，再点击语音输入球原来的位置，任然会显示提示窗口

## 截图

![IMG_20240827_143117_564.jpg](https://github.com/user-attachments/assets/8aea6d5d-677f-4f4e-96e3-8b183922a42a)
这里用的是手机，电脑也有这问题

## 测试环境

浏览器：Chrome
浏览器版本：107.0.5304.105

## 其他

之前就有人反馈，好像是没修…… :trollface:
在#380 议题……

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/f625f768-7b77-4045-84fe-5e011cabe62a)

问题出在这里

目前隐藏语音球的代码是将 `div.rainbow-container-main` 的样式设为 `display:none`，然而父元素（`div#draggableBtn`）仍然有 100x30 的大小，导致点击的时候触发了鼠标点击事件

**Comment by lingbopro** [comment]
解决方案就是设置父元素的样式而非子元素，或者给父元素设置 `pointer-events: none`

**Comment by lingbopro** [comment]
对应的代码位于：

https://github.com/tjy-gitnub/win12/blob/96df3e46e360acfd0b7ba47abb6df623803eabb7/desktop.js#L4196

@jobsofferings 拉出来斩了（

**Comment by kjmjh** [comment]
> 对应的代码位于：
> 
> https://github.com/tjy-gitnub/win12/blob/96df3e46e360acfd0b7ba47abb6df623803eabb7/desktop.js#L4196
> 
> @jobsofferings 拉出来斩了（

👍😃@lingbopro  交个朋友吧

**Comment by lingbopro** [comment]
彳亍

**Comment by kjmjh** [comment]
请你们听歌:[]()https://kjmjh.github.io/MJH/musichtml.html
（懒得居中

然后呢还弄了一个这个 :[]()https://github.com/kjmjh/TOT

![u=340662732,3500067480&fm=253&app=138&size=b931,650&q=75&n=0&f=JPEG&fmt=auto&maxorilen2heic=2000000.jpg](https://github.com/user-attachments/assets/d376bbe3-d44f-477d-98df-620212925650)

**Comment by lingbopro** [comment]
看来我收藏的40多张图有用处了 :trollface:

**Comment by kjmjh** [comment]
> 看来我收藏的40多张图有用处了 :trollface:

woc!!!

**Comment by jobsofferings** [comment]
好家伙，我的😭

**Comment by kjmjh** [comment]
> 好家伙，我的😭

~~😂👉🤠~~ e……

**Comment by lingbopro** [comment]
我的PR！！！没人看吗
