### ISSUE TITLE
[漏洞]copilot又寄了

### ISSUE THREAD

**Issue by Oliver13211** [win12-online/win12#452]
## 描述

copilot文本输入框和发送按钮在已经点击开始对话后依旧无法使用。。。

## 重现

按以下步骤可重新复现该漏洞：

1、打开copilot
2、点击开始对话
3、文本输入框是灰的，发送按钮也无法点击，也没有任何提示信息

## 截图

https://github.com/user-attachments/assets/e41be45e-a644-4e27-8a38-e4055090eb8d

## 测试环境

浏览器：Edge
浏览器版本：128.0.2739.42
操作系统：Windows11

## 其他

copilot已经出过很多问题了，如果实在不行，不做也没关系

**Comment by lingbopro** [comment]
https://github.com/tjy-gitnub/win12/issues/447#issuecomment-2301455219

@NB-Group 在这个Issue下面说过，Copilot关了

**Comment by Oliver13211** [comment]
如果关了应该写个提示什么的，避免再有这样的issue出现

**Comment by lingbopro** [comment]
@NB-Group 来改

**Comment by NB-Group** [comment]
。

**Comment by kjmjh** [comment]
吃瓜.jpg

**Comment by kjmjh** [comment]
斯……
![IMG_20240829_075605_314.jpg](https://github.com/user-attachments/assets/acf4a0db-0d1f-4018-b7ba-7c7c556d88b2)

**Comment by kjmjh** [comment]
嘻嘻

**Comment by github0801230xyz** [comment]
建议作者写个提示

**Comment by kjmjh** [comment]
> 建议作者写个提示
> 

？(不是哥们，写了呀？应该你没刷新(今天刚写的

**Comment by lingbopro** [comment]
![github-staff
删除了评论，来自 syedmaaz9905](https://github.com/user-attachments/assets/e89491b7-fcd9-4004-91c2-d63e82bccaac)

这是什么

**Comment by kj23qaq** [comment]
> ![github-staff
> 删除了评论，来自 syedmaaz9905](https://github.com/user-attachments/assets/e89491b7-fcd9-4004-91c2-d63e82bccaac)
> 
> 这是什么

我也不到？
