### ISSUE TITLE
[漏洞]还是语音输入球

### ISSUE THREAD

**Issue by kjmjh** [win12-online/win12#453]
## 描述

好吧，这次语音输入球直接没了😂

## 重现

按以下步骤可重新复现该漏洞：

1.关闭语音输入球
2.重启
3.打开语音输入球
4.发现它没了(不知道是不是我的问题)
BUT!:打开后再次重启或刷新就有了

## 截图
![IMG_20240829_080214_449.jpg](https://github.com/user-attachments/assets/a9c42fac-b97d-48d0-9400-552196a91b95)

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]
浏览器版本：[请在这里填入浏览器的版本]
操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by kjmjh** [comment]
@lingbopro  ( 这种情况应该是JavaScript的问题吧

**Comment by kjmjh** [comment]
html应该是在1587行（你应该找到了吧

**Comment by lingbopro** [comment]
这代码看不动，真的看不动…丝毫没有模块化，一堆毫不相干的代码堆在一起，不想看了

**Comment by lingbopro** [comment]
不过这个语音球的代码好像是在开机的函数里的？（我记得好像是

**Comment by kjmjh** [comment]
孽障@jobsofferings  拉出来斩了!

**Comment by lingbopro** [comment]
跟他倒也没啥关系，整个项目都这样，一个又臭又长的`desktop.js`谁看谁迷糊

**Comment by kjmjh** [comment]
> 跟他倒也没啥关系，整个项目都这样，一个又臭又长的`desktop.js`谁看谁迷糊

e…在提交里你找到Global settings now allow hidden voice balls那个
你就知道万恶之源的起点了
![hh.jpeg](https://github.com/user-attachments/assets/1202aa36-232d-466c-885c-931f48fcaf0e)

**Comment by lingbopro** [comment]
那个提交我看过

**Comment by kjmjh** [comment]
> 那个提交我看过

哦……

**Comment by lingbopro** [comment]
这个语音球的代码确实在开机的函数里

@jobsofferings 再罚！

**Comment by tjy-gitnub** [comment]
不是，这么折腾过来过去的，不能一次改好吗？交之前能不能自己测试一下啊
什么改了一行的也来交 pr ，（（

***

> 咱就是说，这个语音球有什么用吗。。

**Comment by lingbopro** [comment]
虽然但是，我改的是关闭后仍可点击，可否关闭不关我事（（（

**Comment by lingbopro** [comment]
至于真正的意义…@NB-Group 回答一下（

**Comment by NB-Group** [comment]
语音输入法啊（

**Comment by lingbopro** [comment]
但是想必各位的系统/输入法都有对应的功能吧

**Comment by NB-Group** [comment]
win12 为什么需要输入

**Comment by tjy-gitnub** [comment]
我中考考完了

**Comment by NB-Group** [comment]
好吧

**Comment by lingbopro** [comment]
但是这个语音球的外观真的一般

我觉得不如搞个微软拼音然后把语音输入放输入法工具栏上

或者屏幕键盘上，就像Windows10一样

**Comment by NB-Group** [comment]
![image](https://github.com/user-attachments/assets/e0958208-901c-4146-896c-fe577af70897)

**Comment by NB-Group** [comment]
他大概没有太多时间吧

**Comment by kjmjh** [comment]
我改了一点(还没测试

**Comment by kjmjh** [comment]
@tjy-gitnub  失踪人口回归了）

**Comment by lingbopro** [comment]
今天早上我的收件箱都被tjy在win12的issue操作堆爆了

**Comment by kjmjh** [comment]
> 今天早上我的收件箱都被tjy在win12的issue操作堆爆了

他看样子好生气，(一下子关了200多个议题😱

**Comment by NB-Group** [comment]
> 我中考考完了

# 所以多少分？你准备去哪所高中？上了高中还有时间开发吗？
# 请你务必！务必！_正面回答_ 一下！ @tjy-gitnub

**Comment by kjmjh** [comment]
e…该出英文系统了吧，(我正在改

**Comment by lingbopro** [comment]
> e…该出英文系统了吧，(我正在改

#457？

**Comment by tjy-gitnub** [comment]
<h1 style="font-size: 100px !important;">我考了 750 分。行了吧。谢谢关心。</h1>
<h1 style="font-size: 100px !important;">我准备上清北附中，没有时间，劳烦您继续开发。</h1>

**Comment by kjmjh** [comment]
> <h1 style="font-size: 100px !important;">我考了 750 分。行了吧。谢谢关心。</h1>
> <h1 style="font-size: 100px !important;">我准备上清北附中，没有时间，劳烦您继续开发。</h1>

沃趣!

**Comment by kjmjh** [comment]
太有实力了，750分!!!（（（

**Comment by NB-Group** [comment]
沃趣！
太有实力了！（）

**Comment by NB-Group** [comment]
所以清北附中是什么学校？
@tjy-gitnub 
（）

**Comment by lingbopro** [comment]
> 所以清北附中是什么学校？ @tjy-gitnub （）

emmm...好问题（（（

**Comment by tjy-gitnub** [comment]
清华北京大学附属中学

**Comment by kjmjh** [comment]
> 清华北京大学附属中学

6
![无敌.jpeg](https://github.com/user-attachments/assets/c6a7736f-86d2-4f8d-9da4-85e17f8ca72a)

**Comment by lingbopro** [comment]
可以关了吧

**Comment by kjmjh** [comment]
好的
