### ISSUE TITLE
[建议]

### ISSUE THREAD

**Issue by github0801230xyz** [win12-online/win12#456]
## 描述
b站 检测到您的页面展示可能受到浏览器插件影响，建议您将当前页面加入插件白名单，以保障您的浏览体验～

close
## 方案

反插件检测

## 其他

![image](https://github.com/user-attachments/assets/055e55cf-1972-42d0-8244-ab54f06169ea)

**Comment by kjmjh** [comment]
斯……
应该是用了内嵌页面的问题(我猜的
但我没有找到`<iframe>`元素(也许是我眼瞎了)

**Comment by lingbopro** [comment]
你确定不是你浏览器装了扩展？

**Comment by kjmjh** [comment]
> 你确定不是你浏览器装了扩展？

这哥们也有这个可能

**Comment by kjmjh** [comment]
我这边没有这种情况

**Comment by kjmjh** [comment]
要开学了😭

**Comment by lingbopro** [comment]
我今天下午到校报道，然后还有两天

**Comment by kjmjh** [comment]
> 我今天下午到校报道，然后还有两天

我今天不用
![无敌.jpeg](https://github.com/user-attachments/assets/dde97fab-0b4e-4bbe-a9ab-a1fa700d6eb0)

![u=340662732,3500067480&fm=253&app=138&size=b931,650&q=75&n=0&f=JPEG&fmt=auto&maxorilen2heic=2000000.jpg](https://github.com/user-attachments/assets/4b80de55-a267-47f5-a2b3-d466f45b68d2)

**Comment by lingbopro** [comment]
:(

**Comment by kjmjh** [comment]
> :(

哈哈😄

**Comment by lingbopro** [comment]
我回来了
