### ISSUE TITLE
细节

### ISSUE THREAD

**Issue by kjmjh** [win12-online/win12#465]
就想说……为啥开始界面和设置里的用户不一样？
![IMG_20240914_200816_565.jpg](https://github.com/user-attachments/assets/1c6f2bff-2ed3-402c-859b-654793fb627d)

![IMG_20240914_200905_192.jpg](https://github.com/user-attachments/assets/a68c15e8-5ab2-45de-9922-4ef93d70a0b6)

**Comment by lingbopro** [comment]
绝对是故意的（）

**Comment by kjmjh** [comment]
@lingbopro  有没有兴趣参加我这个项目:[]()https://github.com/kjmjh/tysystem

**Comment by lingbopro** [comment]
> @lingbopro 有没有兴趣参加我这个项目:https://github.com/kjmjh/tysystem

sus

**Comment by lingbopro** [comment]
不过我也有想过做Web OS

但是我现在正在做Electron，回头我可以去康康

**Comment by kjmjh** [comment]
👌随时欢迎你

**Comment by lingbopro** [comment]
@kjmjh 

https://github.com/kjmjh/tysystem/blob/f1e6385c6245fe06f3ab31c9389ee7ae9bc2f342/other/error.html#L28

typo，“`无发解决`”

**Comment by kjmjh** [comment]
> @kjmjh 
> 
> https://github.com/kjmjh/tysystem/blob/f1e6385c6245fe06f3ab31c9389ee7ae9bc2f342/other/error.html#L28
> 
> typo，“`无发解决`”

awa?

**Comment by kjmjh** [comment]
感谢指出错误

**Comment by kjmjh** [comment]
@lingbopro 你住宿吗？

**Comment by lingbopro** [comment]
> @lingbopro 你住宿吗？

不

**Comment by kjmjh** [comment]
请问这个最小化窗口，放大或缩小窗口，关闭窗口是怎么实现的？
![IMG_20240915_182355_489.jpg](https://github.com/user-attachments/assets/561b595e-ab82-498a-b5c1-e33e9148c256)

**Comment by tjy-gitnub** [comment]
有没有可能，设置里面显示的那个是 microsoft 账户和邮件，登陆界面是本地用户名。。

**Comment by kjmjh** [comment]
斯。。。关了

**Comment by Mbilse** [comment]
> 不过我也有想过做Web OS
> 
> 但是我现在正在做Electron，回头我可以去康康

我也在做一个MbilseOS
可以用到吧？

**Comment by Mbilse** [comment]
> 👌随时欢迎你

不考虑vercel?
我的Mbilse OS纳入了...一些奇怪的东西...
