### ISSUE TITLE
[漏洞]很奇怪的一个小小的问题

### ISSUE THREAD

**Issue by zhaotang5** [win12-online/win12#466]
## 描述

安全中心的一个图标在转动

## 重现

按以下步骤可重新复现该漏洞：

打开网页并打开安全中心

## 截图

![IMG_0184](https://github.com/user-attachments/assets/4af3e9cd-c55e-4710-880b-dec3061fb043)

## 测试环境

浏览器：Edge
浏览器版本：[最新iPad版]
操作系统：[iPad OS 17.5.1]

## 其他

无

**Comment by zhaotang5** [comment]
图片我不知道是不是上传成功的，但是至少是能显示的吧

**Comment by lingbopro** [comment]
这个东西好像就这样，我也不知道谁做的（）

**Comment by kjmjh** [comment]
@NB-Group 好像是他做的

**Comment by zhaotang5** [comment]
> 这个东西好像就这样，我也不知道谁做的（）

@lingbopro 6:（

**Comment by NB-Group** [comment]
不知道，可能被别的类修改了样式

**Comment by lingbopro** [comment]
> 不知道，可能被别的类修改了样式

应该是语音球和这个东西的类名重了

**Comment by zhaotang5** [comment]
> > 不知道，可能被别的类修改了样式
> 
> 应该是语音球和这个东西的类名重了

o

**Comment by lingbopro** [comment]
## 我找到问题所在了

和语音球的类名（`pink`）重了

![image](https://github.com/user-attachments/assets/9f39b644-2f1c-443b-8c40-29220b28752b)

![image](https://github.com/user-attachments/assets/8d0c8727-6245-4067-bb9b-579fd3258224)

话说，这种简单名称的类名，选择器真的不限制一下父元素嘛... @NB-Group @tjy-gitnub

**Comment by zhaotang5** [comment]
那么，你们修好了吗？

**Comment by lingbopro** [comment]
没有，不过不难

**Comment by zhaotang5** [comment]
6

**Comment by lingbopro** [comment]
我现在修

**Comment by lingbopro** [comment]
修了：#474

**Comment by NB-Group** [comment]
Merged

**Comment by lingbopro** [comment]
那应该可以关了吧

**Comment by Mbilse** [comment]
> ## 我找到问题所在了
> 
> 和语音球的类名（`pink`）重了
> 
> ![image](https://github.com/user-attachments/assets/9f39b644-2f1c-443b-8c40-29220b28752b)
> 
> ![image](https://github.com/user-attachments/assets/8d0c8727-6245-4067-bb9b-579fd3258224)
>

改一个类名
pink2
