### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by zhaotang5** [win12-online/win12#467]
## 描述

语音球错误，关闭过渡动画即可重现

## 重现

按以下步骤可重新复现该漏洞：

-

## 截图

文件太大无法上传？

## 测试环境

浏览器：[Edge]
浏览器版本：[iPad最新]
操作系统：[iPad OS17.5.1]

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by lingbopro** [comment]
um?

**Comment by Wwhisperi** [comment]
um没听懂

**Comment by lingbopro** [comment]
确实，缺少截图的话根本不知道你在指什么，文件太大的话可以压缩一下质量然后上传

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/a53b1579-bbdb-4bb2-9513-b662aaf8e360)

@zhaotang5 如果你说的是这个的话，这是因为关闭动画后语音球的动画也停了，这个是动画的第一帧

**Comment by kjmjh** [comment]
让我看看👀

**Comment by zhaotang5** [comment]
> ![image](https://private-user-images.githubusercontent.com/148617407/367571316-a53b1579-bbdb-4bb2-9513-b662aaf8e360.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTcyOTAsIm5iZiI6MTcyNjM5Njk5MCwicGF0aCI6Ii8xNDg2MTc0MDcvMzY3NTcxMzE2LWE1M2IxNTc5LWJiZGItNGJiMi05NTEzLWI2NjJhYWY4ZTM2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxMDQzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWUzZmVjY2RjOTQzZGNkNjgxOWI2ZTM5MjhhMzczMmU1ZDk5MDg0OGE2M2YxNjgwMThiZDFlN2NlZjU1YTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K2evXuX0Zm8JND7hvcvn55Nu39HzB3a59svuVo_SsJA)
> 
> @zhaotang5 如果你说的是这个的话，这是因为关闭动画后语音球的动画也停了，这个是动画的第一帧
@lingbopro 就是这个谢谢

**Comment by zhaotang5** [comment]
按错了
