### ISSUE TITLE
[建议]感觉取消圆角语音框怪怪的

### ISSUE THREAD

**Issue by zhaotang5** [win12-online/win12#469]
## 描述

打开设置，关闭圆角看语音框

## 方案

更改方框形的语音框图片

## 其他

-

**Comment by lingbopro** [comment]
emmm

**Comment by NB-Group** [comment]
这是历史遗留问题，语音球是把一个框框圆角调到最大实现的，关了圆角就变成框框了

**Comment by kjmjh** [comment]
awa?

**Comment by zhaotang5** [comment]
> 这是历史遗留问题，语音球是把一个框框圆角调到最大实现的，关了圆角就变成框框了

好吧

**Comment by kjmjh** [comment]
请问这个最小化窗口，放大或缩小窗口，关闭窗口是怎么实现的？
![IMG_20240915_182355_489.jpg](https://github.com/user-attachments/assets/c22bbd8d-2d30-4483-85bf-f6953daad8ba)

**Comment by zhaotang5** [comment]
6

**Comment by zhaotang5** [comment]
> 请问这个最小化窗口，放大或缩小窗口，关闭窗口是怎么实现的？ ![IMG_20240915_182355_489.jpg](https://private-user-images.githubusercontent.com/168880230/367575673-c22bbd8d-2d30-4483-85bf-f6953daad8ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTcxNTMsIm5iZiI6MTcyNjM5Njg1MywicGF0aCI6Ii8xNjg4ODAyMzAvMzY3NTc1NjczLWMyMmJiZDhkLTJkMzAtNDQ4My04NWJmLWY2OTUzZGFhZDhiYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxMDQwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2M0NjBmMDA2YTA5ODk4OTE1MzBhNWNmNDIxYWM0OTRhMzk2NzVjN2Q0MGE0OGQwYzMxY2Q1MjI1ZjhjMjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qOOoVPN0qo_g_Br5wIxpRtFAayUf4a9tMMWSg5re10A)

按X关闭窗口

**Comment by zhaotang5** [comment]
> 这是历史遗留问题，语音球是把一个框框圆角调到最大实现的，关了圆角就变成框框了

那我要不要结束这个话题了啊

**Comment by kjmjh** [comment]
> > 请问这个最小化窗口，放大或缩小窗口，关闭窗口是怎么实现的？ ![IMG_20240915_182355_489.jpg](https://private-user-images.githubusercontent.com/168880230/367575673-c22bbd8d-2d30-4483-85bf-f6953daad8ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTcxNTMsIm5iZiI6MTcyNjM5Njg1MywicGF0aCI6Ii8xNjg4ODAyMzAvMzY3NTc1NjczLWMyMmJiZDhkLTJkMzAtNDQ4My04NWJmLWY2OTUzZGFhZDhiYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxMDQwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2M0NjBmMDA2YTA5ODk4OTE1MzBhNWNmNDIxYWM0OTRhMzk2NzVjN2Q0MGE0OGQwYzMxY2Q1MjI1ZjhjMjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qOOoVPN0qo_g_Br5wIxpRtFAayUf4a9tMMWSg5re10A)
> 
> 按X关闭窗口

e…我问是怎么实现的

**Comment by NB-Group** [comment]
> 请问这个最小化窗口，放大或缩小窗口，关闭窗口是怎么实现的？

6，人家问的是怎么实现的，你回答怎么操作。
其实你只需要一个devtool就行了

**Comment by NB-Group** [comment]
看看 .window.max 和 .window.notrans

**Comment by kjmjh** [comment]
知道啦

**Comment by kjmjh** [comment]
所以到底怎么实现的？awa

**Comment by NB-Group** [comment]
在点击最大化和关闭(最小化)按钮的时候分别添加.window.max 和 .window.notrans  class

**Comment by kjmjh** [comment]
刚关电脑的我:
![ylwh.jpeg](https://github.com/user-attachments/assets/410ead99-ef00-4189-b44b-54ec4df6b488)

**Comment by kjmjh** [comment]
具体代码能发一下吗？(主要是我看不懂js)

**Comment by lingbopro** [comment]
> 具体代码能发一下吗？(主要是我看不懂js)

4298行的 `desktop.js`...

**Comment by kjmjh** [comment]
感谢

**Comment by kjmjh** [comment]
@lingbopro 
![yi.jpeg](https://github.com/user-attachments/assets/8d434da7-b328-4d06-9f86-57552c89cb29)
4298……行的……desktop.js?

**Comment by lingbopro** [comment]
是的，整个4189行，我也不知道在哪行，得自己翻 :trollface:

**Comment by kjmjh** [comment]
算了，看来我(非常)有必要学习一下js了
(对了，我这个关机界面侵权吗？[]()https://kjmjh.github.io/tysystem/Shutdown.html

**Comment by lingbopro** [comment]
>  (对了，我这个关机界面侵权吗？https://kjmjh.github.io/tysystem/Shutdown.html

没啥侵权之说吧，都是开源的

**Comment by kjmjh** [comment]
担心怀疑我抄袭win11的关机界面

**Comment by lingbopro** [comment]
see https://github.com/tjy-gitnub/win12/issues/118#issuecomment-2322751035

**Comment by kjmjh** [comment]
e…

**Comment by kjmjh** [comment]
我这个系统草图画好了，就是不会做😥(草图落学校了)

**Comment by lingbopro** [comment]
> 我这个系统草图画好了，就是不会做😥(草图落学校了)

emmm，我也在学校画过114514张草图，但是大多数都没了（）

**Comment by kjmjh** [comment]
~~哈哈~~ 那么你有兴趣做个web版的系统吗？

**Comment by lingbopro** [comment]
> ~哈哈~ 那么你有兴趣做个web版的系统吗？

当然，不过目前正在经历React114514难（）

**Comment by kjmjh** [comment]
哦，那么这个`React114514难`具体指什么？

**Comment by lingbopro** [comment]
> 哦，那么这个`React114514难`具体指什么？

目前我遇到的几难：

- ~~不会用~~
- 依赖装不上
- 和Electron的配合出了问题
- 一个组件里塞的节点太多了导致不易复用
- 不爱用函数组件，改用类组件
- props传不进去
- 写i18n文件太麻烦
- state用着不如DOM顺手
- 自定义名称的事件不触发
- `useRef` 只能在函数组件里用
- 各种~~无关紧要的致命~~CSS问题
- ~~10行代码lint出11个警告~~
- 又臭又长的属性列表
- Electron暴露的渲染器函数EsLint不认
- 样式太丑
- 样式库功能太少
- 一个组件114个回调
- 懒得写

:trollface:

**Comment by kjmjh** [comment]
哇!
![n.jpeg](https://github.com/user-attachments/assets/82e0c25b-7878-4b2b-91ed-ef7f70dc7985)

**Comment by kjmjh** [comment]
e…一个简单的问题:js下拉菜单如何改变方向，使他成为"上拉菜单"

**Comment by lingbopro** [comment]
> e…一个简单的问题:js下拉菜单如何改变方向，使他成为"上拉菜单"

下拉菜单？

**Comment by kjmjh** [comment]
不，是上拉菜单

**Comment by lingbopro** [comment]
<img width="991" alt="image" src="https://github.com/user-attachments/assets/53ecb086-bb4c-4ca0-aedd-cb47e6e68f7d">

`node_modules`...

![8bf1ab7557cfc83463ff34e8c335b06](https://github.com/user-attachments/assets/6b59bf1f-43f0-4b86-8bec-53497b29eb26)

**Comment by kjmjh** [comment]
e…

**Comment by kjmjh** [comment]
所以怎么实现

**Comment by lingbopro** [comment]
所以说下拉菜单是什么东西

**Comment by kjmjh** [comment]
e……我在学习的:[]()https://www.jyshare.com/codedemo/3180/
那么，换一种方式:开始菜单怎么实现()

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/c9d13af5-a647-4871-98f3-aa537b6a4600)

....

**Comment by NB-Group** [comment]
你就不能直接读代码吗（

**Comment by zhaotang5** [comment]
6

**Comment by kjmjh** [comment]
> 你就不能直接读代码吗（

读不懂js😶

**Comment by kjmjh** [comment]
@lingbopro 你怎么知道这是我头像的!
![u=3587253402,3640939835&fm=217&app=126&size=r3,2&q=75&n=0&g=4n&f=JPEG&fmt=auto&maxorilen2heic=2000000.jpg](https://github.com/user-attachments/assets/495d86a7-1910-42d7-b2ff-c7cd7d4e52ae)

**Comment by lingbopro** [comment]
> @lingbopro 你怎么知道这是我头像的!
> ![u=3587253402,3640939835&fm=217&app=126&size=r3,2&q=75&n=0&g=4n&f=JPEG&fmt=auto&maxorilen2heic=2000000.jpg](https://github.com/user-attachments/assets/495d86a7-1910-42d7-b2ff-c7cd7d4e52ae)
> 
> 

？

**Comment by kjmjh** [comment]
不要笑我:[]()https://kjmjh.github.io/tysystem

**Comment by Wwhisperi** [comment]
> ![image](https://private-user-images.githubusercontent.com/148617407/367583517-c9d13af5-a647-4871-98f3-aa537b6a4600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzI5NDgsIm5iZiI6MTcyNjQ3MjY0OCwicGF0aCI6Ii8xNDg2MTc0MDcvMzY3NTgzNTE3LWM5ZDEzYWY1LWE2NDctNDg3MS05OGYzLWFhNTM3YjZhNDYwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQwNzQ0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTk3OGYyYzRhMTgxYzJjOTc4ZWE1YWY0YWVjNmU2MmQyZjcxMjAwMjdiNWIxMGM3ZWE2YzQzMDk4NTdjNzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u42f3t48dsWJmeHvN-RGrtTEFFzHJ69WOSOR-63AwCI)
> 
> ....

这vpn是不是玉豆，看着好熟悉

**Comment by NB-Group** [comment]
？
就叫v2ray啊

**Comment by lingbopro** [comment]
> ？ 就叫v2ray啊

对啊

**Comment by kjmjh** [comment]
我:？

**Comment by Wwhisperi** [comment]
> ？ 就叫v2ray啊

它应用上写的v2ray但我记得叫玉豆

**Comment by NB-Group** [comment]
啊？
https://github.com/v2ray/v2ray-core/
这玩意要是叫玉豆我吃了它（

**Comment by kjmjh** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊!!!

**Comment by lingbopro** [comment]
https://github.com/2dust/v2rayN/

我开V2rayN摊的能卖你生玉豆蛋子啊（）

**Comment by zhaotang5** [comment]
what

**Comment by lingbopro** [comment]
@NB-Group 把前面这堆东西隐藏了吧

**Comment by zhaotang5** [comment]
？

**Comment by zhaotang5** [comment]
居然还有在线的人啊

**Comment by zhaotang5** [comment]
![IMG_0206](https://github.com/user-attachments/assets/38c3d27a-7a92-48b8-887f-8b825ad09818)
正在捣乱中。。。

**Comment by kjmjh** [comment]
e…请问拖拽窗口怎么实现的？awa

**Comment by lingbopro** [comment]
> e…请问拖拽窗口怎么实现的？awa

bing

**Comment by kjmjh** [comment]
bing可以搜到？

**Comment by lingbopro** [comment]
> bing可以搜到？

不要怀疑搜索引擎搜技术内容的能力…

另外，w3school上也有例子

**Comment by kjmjh** [comment]
是我低估了必应……

**Comment by lingbopro** [comment]
我现在就是用Bing+AdGuard插件，特好用还没广告

**Comment by NB-Group** [comment]
读读代码行不行啊（
至少打开devtools看一眼吧

读不懂代码至少会用chatgpt吧

**Comment by kjmjh** [comment]
> 读读代码行不行啊（
> 至少打开devtools看一眼吧
> 
> 读不懂代码至少会用chatpgt吧

1.读不懂js
2.还是读不懂js
3.问到我也看不懂()
😭

**Comment by kjmjh** [comment]
~~我感觉我可以重开了~~

**Comment by NB-Group** [comment]
读不懂就学啊（
又不是天生就会js，而且chatgpt说的都是大白话。

**Comment by kjmjh** [comment]
某ai的回答:
```
要在HTML页面中实现元素的拖拽功能，你可以使用HTML5中的拖放（Drag and Drop, DnD）API。这项技术允许用户直接在网页上拖动元素并放置到其他位置。下面是一个简单的示例，展示如何让一个元素可拖拽：

1. 首先，在HTML文件中定义一个可拖拽的元素。为该元素添加`draggable="true"`属性。

```html
<div id="dragItem" draggable="true" ondragstart="dragStart(event)" ondrop="drop(event)" ondragover="allowDrop(event)">
    拖拽我
</div>
```

2. 接下来，编写JavaScript函数来处理拖拽事件：

```javascript
function allowDrop(ev) {
    ev.preventDefault();
}

function dragStart(ev) {
    ev.dataTransfer.setData("text", ev.target.id);
}

function drop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");
    ev.target.appendChild(document.getElementById(data));
}
```

3. 你需要确保目标元素（即可以放置拖拽项的地方）也支持拖放操作。为此，可以在目标元素上添加`ondrop`和`ondragover`事件处理器，并调用相应的函数。

```html
<div id="dropZone" ondrop="drop(event)" ondragover="allowDrop(event)">
    放置区
</div>
```

这个示例展示了如何创建一个可以被拖动的元素（`#dragItem`），以及一个接受拖放操作的目标区域（`#dropZone`）。当用户将可拖动元素拖入目标区域时，`drop`函数会被触发，将拖动的元素附加到目标区域中。

请注意，这只是一个基础示例，实际应用中你可能需要根据具体需求调整代码逻辑。例如，你可能需要对不同类型的元素实现不同的拖放行为，或者在拖放过程中显示视觉反馈等。此外，确保你的实现对所有主流浏览器都是兼容的。
```

**Comment by NB-Group** [comment]
。
不是让你这么问的啊。
你至少得把win12里的代码贴进去吧

**Comment by kjmjh** [comment]
所以把哪里的代码贴进去？

**Comment by lingbopro** [comment]
搜一下不行么…


https://www.w3ccoo.com/howto/howto_js_draggable.asp

算了，给个链接吧，我当时也看的这个

**Comment by NB-Group** [comment]
不，我们直接用绝对q定位，有拖拽事件的时候改一下

**Comment by NB-Group** [comment]
多打了一个q

**Comment by kjmjh** [comment]
算了，我还是~~重开吧~~认真学习js吧

**Comment by tjy-gitnub** [comment]
首先你需要学习 js ，其次你需要学习 bing，再次你不能在 issue 里讨论

**Comment by kjmjh** [comment]
对不起……

**Comment by lingbopro** [comment]
这个东西是不是可以关了
