### ISSUE TITLE
[漏洞]诡异的四条线

### ISSUE THREAD

**Issue by Wwhisperi** [win12-online/win12#470]
打开别的网页，如油管再回来会出现黑线

![IMG_0235](https://github.com/user-attachments/assets/760a8e7b-c6dd-4a34-95d9-17c608c6308c)
语音球边上的线会随着球旋转一周然后渐变消失
然后程序坞上的3条线会一直在除非重新加载

**Comment by lingbopro** [comment]
应该是浏览器问题，我移动端Chrome经常这样

**Comment by Wwhisperi** [comment]
> 应该是浏览器问题，我移动端Chrome经常这样

哦哦谢谢

**Comment by kjmjh** [comment]
我到没有这种bug

**Comment by zhaotang5** [comment]
我也没有遇到这个问题

**Comment by lingbopro** [comment]
浏览器问题，应该可以关了
