### ISSUE TITLE
[漏洞]又tnnd是语音输入球

### ISSUE THREAD

**Issue by kjmjh** [win12-online/win12#472]
## 描述

不用我多说了吧……

## 重现

按以下步骤可重新复现该漏洞：
1.确保语音输入球一开始就开启着
2.打开设置
3.找到"个性化"关闭语音输入球
4.点击语音输入球原来的位置
5.不说你也知道。。。

## 截图

![IMG_20240917_145603_419.jpg](https://github.com/user-attachments/assets/f963a705-43f3-4d9c-aae1-e54c702bdda5)

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]
浏览器版本：[请在这里填入浏览器的版本]
操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by kjmjh** [comment]
补充一句:关闭语音输入球后再重启，再到设置打开，你就会发现它打不开了

**Comment by lingbopro** [comment]
仅首次使用才会复现的话…不想修:(

**Comment by kjmjh** [comment]
你是指第一次打开win网页版？

**Comment by kjmjh** [comment]
:rage4:

**Comment by Wwhisperi** [comment]
确实开不开了，刷新也开不开

**Comment by zhaotang5** [comment]
那个关闭之后开不了了+1

**Comment by lingbopro** [comment]
尝试修了一下：#474

**Comment by Mbilse** [comment]
> 那个关闭之后开不了了+1

真的+1

**Comment by kjmjh** [comment]
> > 那个关闭之后开不了了+1
> 
> 真的+1

在看你网站 :trollface:
