### ISSUE TITLE
[建议]论如何让谭式毛玻璃看起来更加高端

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#476]
谭景元曾经提出了一个问题，“为什么我的毛玻璃看起来非常低端”（

经过我 ~夜以继日~ 的观察，我总结了一下三点：

1. 超级拟物风格：
重点在于增加玻璃的反光以模拟真实的光照。
![image](https://github.com/user-attachments/assets/0a55d22a-8ee3-48e2-b1c9-d3445f5da17d)

2.巨硬风格
一条1px宽的线包裹一下，简洁？
主要的精髓在于其中参入了大量黑色/白色(取决于主题)
![image](https://github.com/user-attachments/assets/b236fb5a-7cb1-4abf-beb3-c388aec877f1)
会比win12的黑很多

3.苹果高端风格
没有边框，没有反光，没有参色，但是毛玻璃足够的糊。
![img_v3_02e2_1ac17ba0-aa53-47ac-a386-f77a041a2c5g](https://github.com/user-attachments/assets/fd6f30b6-9a8b-4515-8a6f-d5e540c8719c)

**Comment by User782Tec** [comment]
也可以加一点噪点，更加模拟毛玻璃的粗糙材质

**Comment by NB-Group** [comment]
![image](https://github.com/user-attachments/assets/d0879576-4b73-4965-a89c-931c9bbccb35)
点名批评win11的单色“毛玻璃”任务栏

**Comment by lingbopro** [comment]
_毛玻璃 ✖️_  
**X11的痛 ✔️**

**Comment by tjy-gitnub** [comment]
![image](https://github.com/user-attachments/assets/193f9e35-d9d7-4321-8c71-d492df47721e).。
好看吗（

**Comment by NB-Group** [comment]
合理（

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/a7b77dd2-e668-4686-b916-e958801aac9b)

我觉得Windows终端这种亚克力挺好的

**Comment by NB-Group** [comment]
![image](https://github.com/user-attachments/assets/a295d7de-32b5-4045-b5d9-5a10447173e7)
你指的是标题栏？
实际上微软是给cmd加毛玻璃了的，但是需要手动开启

**Comment by lingbopro** [comment]
> ![image](https://github.com/user-attachments/assets/a295d7de-32b5-4045-b5d9-5a10447173e7)
> 你指的是标题栏？
> 实际上微软是给cmd加毛玻璃了的，但是需要手动开启

准确来说是Windows终端而非cmd

另外Win10上的Windows终端没有窗体亚克力:(

**Comment by NB-Group** [comment]
。
聊天默认把win补成win11（）

**Comment by tjy-gitnub** [comment]
<https://starry-source.github.io/content-zh-hans.html>
看看？ 把你说的全加上了

**Comment by NB-Group** [comment]
高级（

**Comment by lingbopro** [comment]
<details>
<summary>展开图片</summary>

![Screenshot_20241001_164630_com.microsoft.emmx.canary.jpg](https://github.com/user-attachments/assets/fbf3a844-3dc4-4c06-a888-5046e8900702) ![Screenshot_20241001_164614_com.microsoft.emmx.canary.jpg](https://github.com/user-attachments/assets/31e11f7a-6032-4a86-a4cb-c87a92170af0) ![Screenshot_20241001_164604_com.microsoft.emmx.canary.jpg](https://github.com/user-attachments/assets/7893f4ff-e49e-4641-a41c-5e34a29b46f3)

</details>

移动端体验极其炸裂

**Comment by NB-Group** [comment]
请横屏体验

**Comment by NB-Group** [comment]
![image](https://github.com/user-attachments/assets/1e87587e-49ca-4794-980f-b271341f6a7c)

**Comment by lingbopro** [comment]
虽然但是，移动端优化很重要捏

**Comment by NB-Group** [comment]
![image](https://github.com/user-attachments/assets/55d5ca56-e655-4234-838d-e8f9411a1dd9)
《完全还原》

**Comment by NB-Group** [comment]
@tjy-gitnub 你看一下，没问题我push了（

**Comment by NB-Group** [comment]
![image](https://github.com/user-attachments/assets/cf106217-f3df-4ac6-8ad0-461b36a30a3a)
@tjy-gitnub ！

**Comment by NB-Group** [comment]
谭景元！这个毛玻璃好不好看？！
你不回的话我直接push了啊

**Comment by NB-Group** [comment]
提交了，结案了！
[Commit-7c0b612](https://github.com/tjy-gitnub/win12/commit/7c0b612ec398f21a78ad225067f947ad21b584f9)

**Comment by tjy-gitnub** [comment]
祖传不适配移动端（

你这个啊，，感觉有点过于鲜艳了。。blur越大越好，直接抛弃低端设备（

**Comment by NB-Group** [comment]
@tjy-gitnub 
复活了！？

我提交的最终效果不在这个issue里，见 #486 。
分明是低调、高端、大气、上档次、非常美观、对移动端适配非常好、融合了径向渐变和高斯模糊的超级mica（

**Comment by NB-Group** [comment]
![image](https://github.com/user-attachments/assets/6b19d372-1959-431b-9f9e-e629acf439a4)

你看！分明就是超越微软的存在（）（）

**Comment by NB-Group** [comment]
而且有了半透明的径向渐变，即使用火狐也能有不错的效果（

**Comment by NB-Group** [comment]
为了tjy我决定重新打开（

**Comment by NB-Group** [comment]
tjy亖了呜呜呜（

**Comment by kjmjh** [comment]
> @tjy-gitnub 
> 复活了！？
> 
> 我提交的最终效果不在这个issue里，见 #486 。
> 分明是低调、高端、大气、上档次、非常美观、对移动端适配非常好、融合了径向渐变和高斯模糊的超级mica（

《低调》《高端》《大气》《上档次》(()

**Comment by Mbilse** [comment]
> ![Screenshot_20241001_164630_com.microsoft.emmx.canary.jpg](https://github.com/user-attachments/assets/fbf3a844-3dc4-4c06-a888-5046e8900702) ![Screenshot_20241001_164614_com.microsoft.emmx.canary.jpg](https://github.com/user-attachments/assets/31e11f7a-6032-4a86-a4cb-c87a92170af0) ![Screenshot_20241001_164604_com.microsoft.emmx.canary.jpg](https://github.com/user-attachments/assets/7893f4ff-e49e-4641-a41c-5e34a29b46f3)
> 
> 移动端体验极其炸裂

"炸裂:)"
确"十"
