### ISSUE TITLE
[漏洞]夜间模式切换问题

### ISSUE THREAD

**Issue by KBWriting** [win12-online/win12#481]
## 描述
点开悬浮窗后 通过底部按钮切换日夜间模式, 悬浮窗中夜间模式状态未根据当前状态改变选中

## 重现
先点开WLAN 蓝牙悬浮窗, 然后通过底部按钮切换日夜间模式, 悬浮窗中的夜间模式会一直保持在之前状态
## 截图

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：Chrome
浏览器版本：118.0.0.0
操作系统：Windows 11

## 其他

![微信图片_20240927092610](https://github.com/user-attachments/assets/18d4bc93-408e-42c6-ba85-aba7ccd1c9ad)
![微信图片_20240927092617](https://github.com/user-attachments/assets/9047a542-1e94-4bc2-a84a-26e7f4f86e03)

**Comment by lingbopro** [comment]
见 #462

**Comment by tjy-gitnub** [comment]
区分 夜间模式 与 深色模式。: )
