### ISSUE TITLE
[漏洞]设置中点击后没有反应

### ISSUE THREAD

**Issue by LEEYOU-China** [win12-online/win12#483]
![Screenshot 2024-09-28 at 11 02 07 PM](https://github.com/user-attachments/assets/28e11064-bb19-4d34-b002-127f00703758)

<img width="1065" alt="Screenshot 2024-09-28 at 10 59 04 PM" src="https://github.com/user-attachments/assets/fd47b127-71ce-4c44-b090-2813b9ec677d">
## 描述

设置中点击后没有反应

## 重现

按以下步骤可重新复现该漏洞：

（请用步骤的方式描述一下如何重新复现该漏洞）

## 截图

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]
浏览器版本：[请在这里填入浏览器的版本]
<img width="1470" alt="Screenshot 2024-09-28 at 11 01 23 PM" src="https://github.com/user-attachments/assets/7ca03564-d467-4a6c-b8b1-b891df749a8e">

操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]

## 其他

（如果有其他的内容，请在这里进行补充）
<img width="1065" alt="Screenshot 2024-09-28 at 10 59 04 PM" src="https://github.com/user-attachments/assets/ffc8772d-d6a3-422e-9ba3-77b59a00d58c">

**Comment by LEEYOU-China** [comment]
怎么回事

**Comment by wcgwz** [comment]
感觉这个应该是没做完里面的功能所以没开放🤔

**Comment by LEEYOU-China** [comment]
原来如此，应该是

**Comment by lingbopro** [comment]
确实是没做

**Comment by kjmjh** [comment]
盯

**Comment by NB-Group** [comment]
就是没做啊（

**Comment by kjmjh** [comment]
谁做:(

**Comment by NB-Group** [comment]
这个项目都要凉凉了，没人做（）

**Comment by kjmjh** [comment]
> 这个项目都要凉凉了，没人做（）

why?不是挺火的吗？

**Comment by NB-Group** [comment]
凉了啊，1个月凑不出一个新功能的PR（

**Comment by kjmjh** [comment]
没逝，热热还能吃
