### ISSUE TITLE
[漏洞]关于深色模式

### ISSUE THREAD

**Issue by kjmjh** [win12-online/win12#487]
## 描述

（请描述一下这个漏洞是什么样的）

## 重现

按以下步骤可重新复现该漏洞：
1.关闭深色模式
2.刷新(指刷新网页)
3.深色模式又回来了

## 截图

（如果有的话，请在这里附上相关的截图或视频）

## 测试环境

浏览器：[请在这里填入使用的浏览器，如Edge, Chrome, Firefox, Safari, Opera等]
浏览器版本：[请在这里填入浏览器的版本]
操作系统：[请在这里填入使用的操作系统，如iOS 15, Windows 11, Android 13, Ubuntu 22.04.2 LTS等]

## 其他

还有，
1.打开设置
2.关闭深色模式
3.窗口背景没变但文字变了
![IMG_20241004_090808_615.jpg](https://github.com/user-attachments/assets/c88d44d8-6019-4dcc-b8ef-1700c0a447c7)

**Comment by NB-Group** [comment]
咳咳，这是我的问题，我只写了深色的mica（）

**Comment by kjmjh** [comment]
啊？但是以前没有这两个bug啊？

**Comment by NB-Group** [comment]
是啊，这是v9.0.0的bug啊

**Comment by kjmjh** [comment]
![m.gif](https://github.com/user-attachments/assets/47fdeb37-dbca-40b0-8448-036f2f059704)

哇！刚更新就有bug

**Comment by lingbopro** [comment]
> ![m.gif](https://github.com/user-attachments/assets/47fdeb37-dbca-40b0-8448-036f2f059704)
> 
> 哇！刚更新就有bug

这可太正常了

**Comment by kjmjh** [comment]
![m.gif](https://github.com/user-attachments/assets/47fdeb37-dbca-40b0-8448-036f2f059704)

《这可太正常了》

**Comment by lingbopro** [comment]
> ![m.gif](https://github.com/user-attachments/assets/47fdeb37-dbca-40b0-8448-036f2f059704)
> 
> 《这可太正常了》

确实正常，如果没进行非常深度的测试就会这样

**Comment by kjmjh** [comment]
可是我看见更新了，就只是想体验一下新的"毛玻璃"突然就发现了这个bug

**Comment by NB-Group** [comment]
确实没测试，写完了之后就直接交了（）

**Comment by kjmjh** [comment]
![ylwh.jpeg](https://github.com/user-attachments/assets/6b5f1853-7bed-41df-ab8d-ba0c2027b762)

**Comment by NB-Group** [comment]
Bug 在新提交的更新里解决了
