### ISSUE TITLE
neal的iframe嵌套

### ISSUE THREAD

**Issue by Wwhisperi** [win12-online/win12#488]
![image](https://github.com/user-attachments/assets/e92b0045-af19-4b96-a2d3-d85877a8fcf4)
一个有小游戏的网站，测试了，可以嵌套

**Comment by lingbopro** [comment]
neal.fun 是吧，但是你起码给个链接啊

**Comment by Wwhisperi** [comment]
> neal.fun 是吧，但是你起码给个链接啊

就叫Neal.fun

**Comment by Mbilse** [comment]
> > neal.fun 是吧，但是你起码给个链接啊
> 
> 就叫Neal.fun

...
