### ISSUE TITLE
关于字体

### ISSUE THREAD

**Issue by YYJ-YUAN-YI** [win12-online/win12#49]
字体有些大 希望作者改进一下 （要是有个更好看的字体更好）

**Comment by tjy-gitnub** [comment]
字体...大？
好吧我调一下，也可能是平台不同
建议是用电脑体验更佳
字体是浏览器默认字体，可以自己调的
雅黑不好看吗🙃

**Comment by ghost** [comment]
仿宋好

**Comment by ghost** [comment]
也可以手写体

**Comment by tjy-gitnub** [comment]
emm 
雅黑应该是系统默认字体
这样更真实一些
当然如果不喜欢也是可以再浏览器设置里面调的😁

**Comment by yiliabai** [comment]
6
