### ISSUE TITLE
[漏洞]

### ISSUE THREAD

**Issue by Mbilse** [win12-online/win12#493]
## 描述

在微信打开会报毒，报色情

## 重现

按以下步骤可重新复现该漏洞：

tjy可以考虑一下买个域名，映射到微信

## 测试环境

浏览器：微信，qq浏览器，
微信版本：8.0.41
操作系统： Android 10

## 其他

（如果有其他的内容，请在这里进行补充）

**Comment by Mbilse** [comment]
域名比如tjy.com(88元)
tjy.cn(33元)
tjy.fun(8元)
[真实物价，我已经查过]

**Comment by lingbopro** [comment]
。。。

微信关我们啥事

这种墙中墙，正常，很多项目都在 `github.io` 下面，有一个子域被屏蔽了整个 `github.io` 都可能报毒

建议 close

**Comment by lingbopro** [comment]
斯…不应该是 not planned 吗，为啥是 done
