### ISSUE TITLE
[建议]edge插件功能

### ISSUE THREAD

**Issue by Mbilse** [win12-online/win12#500]
## 描述

edge加一个设置和插件
直接用div加

## 方案

参考(
style
span
div
)
结合一下吧

## 其他

无

**Comment by Mbilse** [comment]
还有内容，见#484

**Comment by tjy-gitnub** [comment]
如有用

**Comment by Mbilse** [comment]
k

**Comment by Mbilse** [comment]
up

**Comment by tjy-gitnub** [comment]
想关。有意见吗（quq

**Comment by Mbilse** [comment]
No

Mbilse

________________________________
发件人: Starry Source ***@***.***>
发送时间: 星期六, 十二月 7, 2024 5:17:06 下午
收件人: tjy-gitnub/win12 ***@***.***>
抄送: Mbilse ***@***.***>; Author ***@***.***>
主题: Re: [tjy-gitnub/win12] [建议]edge插件功能 (Issue #500)


想关。有意见吗（quq

―
