### ISSUE TITLE
[建议]有没有c编辑器

### ISSUE THREAD

**Issue by Mbilse** [win12-online/win12#501]
## 描述

有没有c编辑器可用，开发py编辑器时带一下呗

## 其他

启动时更新动画改成进入登录前加个重启
和
bios加一个boot theme进去

**Comment by Mbilse** [comment]
#500和#484带一下

**Comment by lingbopro** [comment]
有 Code 用啊

另外Web端编辑这种编译型语言没啥意义

**Comment by Mbilse** [comment]
> 有 Code 用啊
> 
> 另外Web端编辑这种编译型语言没啥意义

sudio code用手机操作不方便

**Comment by Mbilse** [comment]
> > 有 Code 用啊
> > 
> > 另外Web端编辑这种编译型语言没啥意义
> 
> sudio code用手机操作不方便

我现在用的mobile

**Comment by tjy-gitnub** [comment]
科普一下，C 属于编译型语言，前端是基本不可能实现的，除非仿照其语法重新写一个 cscript 之类的新语言。。

**Comment by ProgramCX** [comment]
> 科普一下，C 属于编译型语言，前端是基本不可能实现的，除非仿照其语法重新写一个 cscript 之类的新语言。。

可以搞一个后端啊。我正好有一个服务器没怎么用

**Comment by tjy-gitnub** [comment]
> 可以搞一个后端啊。我正好有一个服务器没怎么用

可以跑大模型吗？copilot 已经瘫痪有一段时间了

**Comment by ProgramCX** [comment]
> > 可以搞一个后端啊。我正好有一个服务器没怎么用
> 
> 可以跑大模型吗？copilot 已经瘫痪有一段时间了

![image](https://github.com/user-attachments/assets/17a7df83-4601-44f8-99e2-80d9a8982fd1)
你看看配置可否，我不太清楚

**Comment by Mbilse** [comment]
还行，我正好

Mbilse

________________________________
发件人: Program ***@***.***>
发送时间: 星期六, 十二月 7, 2024 12:16:14 上午
收件人: tjy-gitnub/win12 ***@***.***>
抄送: Mbilse ***@***.***>; Author ***@***.***>
主题: Re: [tjy-gitnub/win12] [建议]有没有c编辑器 (Issue #501)


可以搞一个后端啊。我正好有一个服务器没怎么用

可以跑大模型吗？copilot 已经瘫痪有一段时间了

image.png (view on web)<https://github.com/user-attachments/assets/17a7df83-4601-44f8-99e2-80d9a8982fd1>
你看看配置可否，我不太清楚

―

**Comment by tjy-gitnub** [comment]
过于《还行》了还是。 2G 跑大模型委屈你能想的出来 -_-)o

**Comment by lingbopro** [comment]
> 过于《还行》了还是。 2G 跑大模型委屈你能想的出来 -_-)o

还真行，我手机都能跑个简单的模型

![Qwen2.5 on Termux](https://github.com/user-attachments/assets/cf7149dc-a61f-4020-a5f9-d8b09f07e52e)

**Comment by Mbilse** [comment]
> > 过于《还行》了还是。 2G 跑大模型委屈你能想的出来 -_-)o
> 
> 还真行，我手机都能跑个简单的模型
> 
> ![Qwen2.5 on Termux](https://github.com/user-attachments/assets/cf7149dc-a61f-4020-a5f9-d8b09f07e52e)
> 
> 

zero termux
怎么弄的
node？

**Comment by lingbopro** [comment]
> zero termux
> 怎么弄的
> node？

proot+ollama

**Comment by kjmjh** [comment]
ollama.com

**Comment by Mbilse** [comment]
> > zero termux
> > 怎么弄的
> > node？
> 
> proot+ollama

thanks
