### ISSUE TITLE
[意见征集]论"横屏以获得最佳体验" 动画的设计

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#509]
https://github.com/user-attachments/assets/e6065bce-89d4-48d4-aae6-73f353e7d27e

这个功能将实现我长久以来的梦想（）
动画效果预览请看上方的视频。

**Comment by Wwhisperi** [comment]
bush(

**Comment by Mbilse** [comment]
要不检测浏览器标识，识别出android后识别横竖屏，动画己设计,正在本地试验，成功了挂仓库里

**Comment by Mbilse** [comment]
> 要不检测浏览器标识，识别出android后识别横竖屏，动画己设计,正在本地试验，成功了挂仓库里

见#503

**Comment by tjy-gitnub** [comment]
网上抄的吧（

**Comment by NB-Group** [comment]
自己写的，全网无重。图标都是用ppt画的（）

**Comment by NB-Group** [comment]
我已经提交了，在手机端竖屏打开就能看到

**Comment by Mbilse** [comment]
k

**Comment by tjy-gitnub** [comment]
well

**Comment by Mbilse** [comment]
a...

________________________________
发件人: Starry Source ***@***.***>
发送时间: 星期六, 十二月 7, 2024 5:16:30 下午
收件人: tjy-gitnub/win12 ***@***.***>
抄送: Mbilse ***@***.***>; Comment ***@***.***>
主题: Re: [tjy-gitnub/win12] [意见征集]论"横屏以获得最佳体验" 动画的设计 (Issue #509)


well

―
