### ISSUE TITLE
[建议]点击登录就蓝屏，要不然改成直接跳转到https://logon.live.com

### ISSUE THREAD

**Issue by Mbilse** [win12-online/win12#510]
## 描述
在设置里点击登录就蓝屏，要不然改成直接跳转到https://logon.live.com

## 方案

改成直接跳转到https://logon.live.com/
或在win12的edge里iframe

## 其他

把ai换成国内通道的api

**Comment by Mbilse** [comment]
https://login.live.com/login.srf?wa=wsignin1.0

**Comment by Mbilse** [comment]
> https://login.live.com/login.srf?wa=wsignin1.0

这

**Comment by Mbilse** [comment]
> https://login.live.com/login.srf?wa=wsignin1.0

https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=166&ct=1733489740&rver=7.5.2211.0&wp=MBI_SSL&wreply=https%3a%2f%2foutlook.live.com%2fowa%2f%3fnlp%3d1%26cobrandid%3dab0455a0-8d03-46b9-b18b-df2f57b9e44c%26deeplink%3dowa%252f%26RpsCsrfState%3d34c21b1d-1102-8069-dc9c-3b1a0e09eead&id=292841&aadredir=1&CBCXT=out&lw=1&fl=dob%2cflname%2cwld&cobrandid=ab0455a0-8d03-46b9-b18b-df2f57b9e44c

**Comment by kjmjh** [comment]
.....

**Comment by tjy-gitnub** [comment]
该会蓝屏的吧？。。早就有了
