### ISSUE TITLE
[建议]启动时如果有更新了，动画改成进入登录前加个重启
和
bios加一个boot theme进去

### ISSUE THREAD

**Issue by Mbilse** [win12-online/win12#513]
## 描述

直接a href

## 方案

href到reload.html再启动

## 其他

加上新版本浏览

**Comment by tjy-gitnub** [comment]
有必要吗？。。。

**Comment by Mbilse** [comment]
......boot theme可以把开机动画改一下
调整个性化......

Mbilse

________________________________
发件人: Starry Source ***@***.***>
发送时间: 星期六, 十二月 21, 2024 9:05:48 下午
收件人: tjy-gitnub/win12 ***@***.***>
抄送: Mbilse ***@***.***>; Author ***@***.***>
主题: Re: [tjy-gitnub/win12] [建议]启动时如果有更新了，动画改成进入登录前加个重启 和 bios加一个boot theme进去 (Issue #513)


有必要吗？。。。

―
