### ISSUE TITLE
新闻内容

### ISSUE THREAD

**Issue by ghost** [win12-online/win12#52]
Windows14计划即将起动，官方透露:将与苹果联合打造
![wallpaper-windows-14-500x375](https://user-images.githubusercontent.com/122671846/213092439-690b4012-5734-4033-835a-b794f96c49d4.jpg)

**Comment by tjy-gitnub** [comment]
这不office吗？
哈哈
好，安排
不过要过几天去了，这几天有事

**Comment by iamkezo1** [comment]
厉害👍

**Comment by iamkezo1** [comment]
> 这不办公室吗？ 哈哈 好， 安排不过要过几天去了，这几天有事

两周前。。。😅

**Comment by notepadTom** [comment]
Windows12更新已《发布》
下崽脸解：https://microsoft.com/windows12/download/hhhhhh

**Comment by User782Tec** [comment]
> Windows12更新已《发布》 下崽脸解：https://microsoft.com/windows12/download/hhhhhh

你这链接保熟吗 (

**Comment by tjy-gitnub** [comment]
[https://www.microsoft.com/zh-cn/software-download/windows12](https://www.microsoft.com/zh-cn/software-download/windows11)
最新iso下载地址，保熟 ||>v-)

**Comment by User782Tec** [comment]
> [https://www.microsoft.com/zh-cn/software-download/windows12](https://www.microsoft.com/zh-cn/software-download/windows11) 最新iso下载地址，保熟 ||>v-)

指11为12是吧 (

**Comment by ghost** [comment]
Windows11已下架，[点此查看](https://www.microsoft.com/zh-cn/software-download/windows11)

**Comment by notepadTom** [comment]
hhh
后面可能会有链接
________________________________
发件人: User782Tec ***@***.***>
发送时间: Saturday, February 11, 2023 3:08:25 PM
收件人: tjy-gitnub/win12 ***@***.***>
抄送: notepadTom ***@***.***>; Comment ***@***.***>
主题: Re: [tjy-gitnub/win12] 新闻内容 (Issue #52)


Windows12更新已《发布》 下崽脸解：https://microsoft.com/windows12/download/hhhhhh

你这链接保熟吗 (

―

**Comment by ghost** [comment]
Windows12(非宫方版)，[点此下载](https://pan.baidu.com/s/1Wvtht6BTZq3SDmAarN4wjA) 
，保证无坑！
提取码:vgex

**Comment by tjy-gitnub** [comment]
虽然但是，win13 还没出呢
