### ISSUE TITLE
者作

### ISSUE THREAD

**Issue by ghost** [win12-online/win12#58]
建议将Office界面做成
（一个大镐子）《因为没找到图片》
作者正在努力搭建中，即将推出......
可以用Minecraft的大钻石镐

**Comment by ghost** [comment]
@tjy-gitnub

**Comment by tjy-gitnub** [comment]
in fact 作者并没有"正在努力搭建"，也没有"打算努力搭建"
>_>

**Comment by ghost** [comment]
@æ¯”è¾ƒè¾“å…¥çš„éduªŒè¯ç å’Œå®žé™…

çŸæˆçš„éªŒè¯çæ˜¯å¦ç›¸åç¦å»ºå®½å®¢æŠ•èµ„æ–å»ºå…

ƒé›†å›¢¸Šæµ·duå»ºå·¥æŠ•èµ„æµ·å»ºåˆæŠ•èµ„ç®¡ç†å»ºä¿¡åŸºé‡‘ç®¡ç†æœ‰é™è´£ä»»å…¬åMèµ„æœ¬æœ›æ­£èµ„äº§ç›¸èšèµ„æœ¬å† é¡¶èµ„æœ

斅baiH兝I谲9萿祧C 劝?M峅H夬殡?E1繦够夐??氍duA兯f吷EH?葾隼t两zhif?

H冴E绘dao9鷘志婾H兠L峫$pH夑环??婥峆吚塖鎱??

**Comment by ghost** [comment]
你好

**Comment by ghost** [comment]
可以加一句
将在2Π.e.i

**Comment by User782Tec** [comment]
> 可以加一句
> 将在2Π.e.i

> @æ¯”è¾ƒè¾“å…¥çš„éduªŒè¯�ç �å’Œå®žé™…
> 
> çŸæˆ�çš„éªŒè¯�ç�æ˜¯å�¦ç›¸åç¦�å»ºå®½å®¢æŠ•èµ„æ–å»ºå…
> 
> ƒé›†å›¢¸Šæµ·duå»ºå·¥æŠ•èµ„æµ·å»ºå�ˆæŠ•èµ„ç®¡ç�†å»ºä¿¡åŸºé‡‘ç®¡ç�†æœ‰é™�è´£ä»»å…¬å�Mèµ„æœ¬æœ›æ­£èµ„äº§ç›¸è�šèµ„æœ¬å† é¡¶èµ„æœ
> 
> �斅baiH兝�I�谲9萿祧C� �劝?M峅�H夬殡?E1繦够夐??氍�duA兯�f吷E�H?葾隼�t�两�zhif?
> 
> H冴�E�绘dao9鷘志婾H兠�L峫$pH夑环??婥峆吚塖�鎱??

?

**Comment by tjy-gitnub** [comment]
> @æ¯”è¾ƒè¾“å…¥çš„éduªŒè¯�ç �å’Œå®žé™…
> 
> çŸæˆ�çš„éªŒè¯�ç�æ˜¯å�¦ç›¸åç¦�å»ºå®½å®¢æŠ•èµ„æ–å»ºå…
> 
> ƒé›†å›¢¸Šæµ·duå»ºå·¥æŠ•èµ„æµ·å»ºå�ˆæŠ•èµ„ç®¡ç�†å»ºä¿¡åŸºé‡‘ç®¡ç�†æœ‰é™�è´£ä»»å…¬å�Mèµ„æœ¬æœ›æ­£èµ„äº§ç›¸è�šèµ„æœ¬å† é¡¶èµ„æœ
> 
> �斅baiH兝�I�谲9萿祧C� �劝?M峅�H夬殡?E1繦够夐??氍�duA兯�f吷E�H?葾隼�t�两�zhif?
> 
> H冴�E�绘dao9鷘志婾H兠�L峫$pH夑环??婥峆吚塖�鎱??

还麻烦解释一下>_>

**Comment by ghost** [comment]
@tjy-gitnub

**Comment by lingbopro** [comment]
> @æ¯”è¾ƒè¾“å…¥çš„éduªŒè¯ç å’Œå®žé™…
> 
> çŸæˆçš„éªŒè¯çæ˜¯å¦ç›¸åç¦å»ºå®½å®¢æŠ•èµ„æ–å»ºå…
> 
> ƒé›†å›¢¸Šæµ·duå»ºå·¥æŠ•èµ„æµ·å»ºåˆæŠ•èµ„ç®¡ç†å»ºä¿¡åŸºé‡‘ç®¡ç†æœ‰é™è´£ä»»å…¬åMèµ„æœ¬æœ›æ­£èµ„äº§ç›¸èšèµ„æœ¬å† é¡¶èµ„æœ
> 
> 斅baiH兝I谲9萿祧C 劝?M峅H夬殡?E1繦够夐??氍duA兯f吷EH?葾隼t两zhif?
> 
> H冴E绘dao9鷘志婾H兠L峫$pH夑环??婥峆吚塖鎱??

看起来是UTF-8转ISO8859-1的时候乱码了？
