### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiaoyu827** [win12-online/win12#6]
体验了2分钟，给我的感觉，不是很好， 我发现了一个bug ， 打开设置鼠标点击左上角的设置图标时，拖动一会后，松开鼠标，那个设置就一直跟着动，js的点击有bug,没生效，然后就是希望多个功能，进去里面什么都没

**Comment by tjy-gitnub** [comment]
非常遗憾
这个bug我一定会在下一个版本改进
另外因为只是我一个人做的，我还是学生，只能在周末之余做一做，所有功能较少
不过我会一点一点加一些新的功能，使之趋于完善
感谢理解
