### ISSUE TITLE
关于我去开发者的主页转了一圈发现他不会JAVA(*^▽^*)

### ISSUE THREAD

**Issue by iamkezo1** [win12-online/win12#61]
如题，没有恶意（顺便问一句开发者多大）

**Comment by User782Tec** [comment]
哦（这还用发issue吗（bushi
（我不知道作者多大，不过我还是个六年级的小学生（

**Comment by tjy-gitnub** [comment]
但是我会写javascript >_>)o
如果你真的去开发者的主页转了一圈就会知道我多大 >v-)o

**Comment by iamkezo1** [comment]
> 但是我会写javascript >_>)o 如果你真的去开发者的主页转了一圈就会知道我多大>v-)o

哦，是1...我*才比我大两岁，初1？
