### ISSUE TITLE
投稿一个新闻

### ISSUE THREAD

**Issue by HHCL233** [win12-online/win12#64]
微软发布Windows中的Macos软件，以后想使用Macos软件再也不是梦！
![image](https://user-images.githubusercontent.com/108406074/221352766-fa3e0387-7eaf-4b39-858d-a6b17d135d3f.png)

**Comment by tjy-gitnub** [comment]
O-o)!?o
真的假的？
这样怎么样
![image](https://user-images.githubusercontent.com/71509955/221391744-ecb4ef4e-d4ce-47c3-a796-393545e3c688.png)
Microsoft 发布 Windows Subsystem for Mac

**Comment by HHCL233** [comment]
OK
