### ISSUE TITLE
制作应用程序版

### ISSUE THREAD

**Issue by dzc120223** [win12-online/win12#7]
希望可以发行Windows12在各操作系统平台的应用程序版并增加
![image](https://user-images.githubusercontent.com/117005381/198870300-b4b0f7cb-89f4-439d-bc9f-ae7598d9ce1a.png)
的更新功能

**Comment by tjy-gitnub** [comment]
好建议，这个可以考虑做一个应用内嵌一个浏览器
或者和win11 网页版一样搞一个pwa
不过在html里实现更新似乎有亿点困难。。。
感谢支持

**Comment by dzc120223** [comment]
我的意思是只对应用程序版添加Windows Update

**Comment by tjy-gitnub** [comment]
是啊，但是应用程序这个项目本质上还是网页，应用程序只是个套壳 
计划v3就会出pwa应用了

**Comment by hzh-droid** [comment]
越来越苹果化了

**Comment by skyions** [comment]
或许你可以自己再创造一个软件，可以仿照Windows Update，但是一个网址，远程更新很困难

**Comment by User782Tec** [comment]
Windows 更新终于实现辣(

**Comment by Mbilse** [comment]
> 越来越苹果化了

是哦

**Comment by Mbilse** [comment]
> 是啊，但是应用程序这个项目本质上还是网页，应用程序只是个套壳 
> 计划v3就会出pwa应用了

直接挂webapp可以吗

**Comment by hzh-droid** [comment]
唔，你觉得微软会采用你的方案吗哈哈哈我是挺喜欢这种的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月13日(周四) 下午4:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tjy-gitnub/win12] 制作应用程序版 (Issue #7)




  
是啊，但是应用程序这个项目本质上还是网页，应用程序只是个套壳
 计划v3就会出pwa应用了
  
直接挂webapp可以吗

**Comment by Mbilse** [comment]
> 唔，你觉得微软会采用你的方案吗哈哈哈我是挺喜欢这种的
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2025年2月13日(周四) 下午4:32
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [tjy-gitnub/win12] 制作应用程序版 (Issue #7)
> 
> 
> 
> 
>   
> 是啊，但是应用程序这个项目本质上还是网页，应用程序只是个套壳
>  计划v3就会出pwa应用了
>   
> 直接挂webapp可以吗
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

我做成了！
也是用autojs打包的
自动横屏并桌面模式
