### ISSUE TITLE
基于Python的Edge扩展程序

### ISSUE THREAD

**Issue by User782Tec** [win12-online/win12#70]
新特性前瞻: 
使用在Replit上的服务器、Python语言和Flask框架，完成获取标题等网页版Edge的扩展功能
程序已基本完成，准备发布在[User782Tec/win12-addons](https://github.com/User782Tec/win12-addons)仓库中o(^ ^)o
现正在解决跨域问题...

---
@tjy-gitnub 你的愿望(PR [#68](https://github.com/tjy-gitnub/win12/pull/68#issuecomment-1501773152))要实现力(喜(bushi

**Comment by tjy-gitnub** [comment]
wow OoO)o
这个6了
（这个要收费吗，有没有什么使用限制啊？）
你是指的是在js中通过这个项目获取网页内容吗？还是把整个项目通过flask框架变成动态的？

**Comment by User782Tec** [comment]
> wow OoO)o 这个6了 （这个要收费吗，有没有什么使用限制啊？） 你是指的是在js中通过这个项目获取网页内容吗？还是把整个项目通过flask框架变成动态的？

是把一些需要后端的功能放在一个服务器上
前端通过向服务器发送请求以获取数据

(网页内容比较难实现 不太能做出来 先试着获取下标题)

**Comment by User782Tec** [comment]
据我所知貌似没有时长限制
不过服务器内存、存储空间和cpu都有限制

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/232259481-cde2d50d-3d16-4c60-aa57-3823c03f14f4.png)
诺

**Comment by User782Tec** [comment]
草
要钱
溜了溜了

**Comment by User782Tec** [comment]
草
要钱
溜了溜了

**Comment by tjy-gitnub** [comment]
啊这... >_>)o

**Comment by tjy-gitnub** [comment]
(我觉得可以用flask做一个本地的应用，来代替pwa应用 >_o)o
我计划在里面加上emmm 获取标题 还有更新的模块 tjy-gitnub/win12-offline

**Comment by User782Tec** [comment]
> (我觉得可以用flask做一个本地的应用，来代替pwa应用 >_o)o 我计划在里面加上emmm 获取标题 还有更新的模块 tjy-gitnub/win12-offline

可是flask是做服务器的
应用的话...electron可否

**Comment by NB-Group** [comment]
> > （我觉得可以用flask做一个本地的应用，来代替pwa应用 >_o）o 我计划在里面加上emmm 获取标题 还有更新的模块 tjy-gitnub/win12-offline
> 
> 可是flask是做服务器的 应用的话...electron可否

你们这个可以啊，anaconda有个免费的代码托管服务，可以在云端部署你们这个代码欸

**Comment by tjy-gitnub** [comment]
> > > （我觉得可以用flask做一个本地的应用，来代替pwa应用 >_o）o 我计划在里面加上emmm 获取标题 还有更新的模块 tjy-gitnub/win12-offline
> > 
> > 
> > 可是flask是做服务器的 应用的话...electron可否
> 
> 你们这个可以啊，anaconda有个免费的代码托管服务，可以在云端部署你们这个代码欸

免费的？？！！Oo0)!o
确定？有什么限制吗，你试过吗？

**Comment by User782Tec** [comment]
> > > （我觉得可以用flask做一个本地的应用，来代替pwa应用 >_o）o 我计划在里面加上emmm 获取标题 还有更新的模块 tjy-gitnub/win12-offline
> > 
> > 
> > 可是flask是做服务器的 应用的话...electron可否
> 
> 你们这个可以啊，anaconda有个免费的代码托管服务，可以在云端部署你们这个代码欸

有吗?诶嘿嘿...(
透露一下呗

**Comment by NB-Group** [comment]
> > > > （我觉得可以用flask做一个本地的应用，来代替pwa应用 >_o）o 我计划在里面加上emmm 获取标题 还有更新的模块 tjy-gitnub/win12-offline
> > > 
> > > 
> > > 可是flask是做服务器的 应用的话...electron可否
> > 
> > 
> > 你们这个可以啊，anaconda有个免费的代码托管服务，可以在云端部署你们这个代码欸
> 
> 免费的？？！！Oo0)!o 确定？有什么限制吗，你试过吗？

https://www.anaconda.com/code-in-the-cloud
这个是网址，我用过，不用魔法的话有点慢，但是能访问，免费，云端，无限制，linux的

**Comment by NB-Group** [comment]
> > > > （我觉得可以用flask做一个本地的应用，来代替pwa应用 >_o）o 我计划在里面加上emmm 获取标题 还有更新的模块 tjy-gitnub/win12-offline
> > > 
> > > 
> > > 可是flask是做服务器的 应用的话...electron可否
> > 
> > 
> > 你们这个可以啊，anaconda有个免费的代码托管服务，可以在云端部署你们这个代码欸
> 
> 免费的？？！！Oo0)!o 确定？有什么限制吗，你试过吗？

提醒一下，如果要在github仓库的搭建的网站里向本地的服务器发请求会有跨域问题哦

**Comment by User782Tec** [comment]
> > > > > （我觉得可以用flask做一个本地的应用，来代替pwa应用 >_o）o 我计划在里面加上emmm 获取标题 还有更新的模块 tjy-gitnub/win12-offline
> > > > 
> > > > 
> > > > 可是flask是做服务器的 应用的话...electron可否
> > > 
> > > 
> > > 你们这个可以啊，anaconda有个免费的代码托管服务，可以在云端部署你们这个代码欸
> > 
> > 
> > 免费的？？！！Oo0)!o 确定？有什么限制吗，你试过吗？
> 
> https://www.anaconda.com/code-in-the-cloud 这个是网址，我用过，不用魔法的话有点慢，但是能访问，免费，云端，无限制，linux的

笑死
没有魔法
根本访问不了

![318D4C58-24A5-4DDB-9908-E842EC8C893F](https://user-images.githubusercontent.com/115236204/235551600-5dd602cd-12de-41d8-b390-0922ea3ab307.jpeg)

**Comment by NB-Group** [comment]
根本笑不死，无魔法edge照常访问
![image](https://user-images.githubusercontent.com/121747915/235564659-8d59fd40-c8ac-4b9f-be80-64196e400755.png)

**Comment by User782Tec** [comment]
> 根本笑不死，无魔法edge照常访问
> ![image](https://user-images.githubusercontent.com/121747915/235564659-8d59fd40-c8ac-4b9f-be80-64196e400755.png)

笑死
Jupyter Notebook

**Comment by NB-Group** [comment]
> > 根本笑不死，无魔法edge照常访问
> > ![image](https://user-images.githubusercontent.com/121747915/235564659-8d59fd40-c8ac-4b9f-be80-64196e400755.png)
> 
> 笑死 Jupyter Notebook

笑死，打开网站就要1分钟，尼玛比github还慢

**Comment by User782Tec** [comment]
> > > 根本笑不死，无魔法edge照常访问
> > > ![image](https://user-images.githubusercontent.com/121747915/235564659-8d59fd40-c8ac-4b9f-be80-64196e400755.png)
> > 
> > 
> > 笑死 Jupyter Notebook
> 
> 笑死，打开网站就要1分钟，尼玛比github还慢

笑死
不会用(

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/235567783-054cb7e8-93bb-4e31-a9f5-fbf92d100f90.png)

笑死
没有管理员权限

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/235567783-054cb7e8-93bb-4e31-a9f5-fbf92d100f90.png)
> 
> 笑死 没有管理员权限

笑死，只能端口映射了

**Comment by User782Tec** [comment]
> > ![image](https://user-images.githubusercontent.com/115236204/235567783-054cb7e8-93bb-4e31-a9f5-fbf92d100f90.png)
> > 笑死 没有管理员权限
> 
> 笑死，只能端口映射了

笑死
可以在子进程运行

**Comment by User782Tec** [comment]
累了
不会了
草

**Comment by User782Tec** [comment]
甚至连个管理员用户都没有

**Comment by NB-Group** [comment]
> 甚至连个管理员用户都没有

要不我帮你搞一搞？

**Comment by User782Tec** [comment]
> > 甚至连个管理员用户都没有
> 
> 要不我帮你搞一搞？

行
感谢

**Comment by tjy-gitnub** [comment]
笑死

**Comment by User782Tec** [comment]
> 笑死

笑死
根本笑不死

用了一个月的Ubuntu
服务器上的Ubuntu
就不会用了（？

**Comment by User782Tec** [comment]
咳咳
这个Issue貌似还没死

**Comment by tjy-gitnub** [comment]
看来你们都很闲啊
我现在还在机房刷题(偷偷来瞟一眼

**Comment by User782Tec** [comment]
> 看来你们都很闲啊
> 我现在还在机房刷题(偷偷来瞟一眼

机房？你在学校？

**Comment by tjy-gitnub** [comment]
> > 看来你们都很闲啊
> > 我现在还在机房刷题(偷偷来瞟一眼
> 
> 机房？你在学校？

是啊，好惨 TuT)o

**Comment by User782Tec** [comment]
> > > 看来你们都很闲啊
> > > 我现在还在机房刷题(偷偷来瞟一眼
> > 
> > 
> > 机房？你在学校？
> 
> 是啊，好惨 TuT)o

所以你如何在学校登上GitHub并逃过老师的监视和我们聊天？（
像我们学校，老师都不给开网络
就算是开也仅限访问几个站点（被编程猫迫害的日子啊啊啊啊啊啊

**Comment by User782Tec** [comment]
> > > ![image](https://user-images.githubusercontent.com/115236204/235567783-054cb7e8-93bb-4e31-a9f5-fbf92d100f90.png)
> > > 笑死 没有管理员权限
> > 
> > 
> > 笑死，只能端口映射了
> 
> 笑死 可以在子进程运行

笑死
没有管理员权限，装不了端口映射软件

**Comment by tjy-gitnub** [comment]
> 所以你如何在学校登上GitHub并逃过老师的监视和我们聊天？（ 像我们学校，老师都不给开网络 就算是开也仅限访问几个站点（被编程猫迫害的日子啊啊啊啊啊啊

你以为老师不会像我一样摸鱼？

**Comment by User782Tec** [comment]
> > 所以你如何在学校登上GitHub并逃过老师的监视和我们聊天？（ 像我们学校，老师都不给开网络 就算是开也仅限访问几个站点（被编程猫迫害的日子啊啊啊啊啊啊
> 
> 你以为老师不会像我一样摸鱼？

6

**Comment by NB-Group** [comment]
> > > > ![image](https://user-images.githubusercontent.com/115236204/235567783-054cb7e8-93bb-4e31-a9f5-fbf92d100f90.png)
> > > > 笑死 没有管理员权限
> > > 
> > > 
> > > 笑死，只能端口映射了
> > 
> > 
> > 笑死 可以在子进程运行
> 
> 笑死 没有管理员权限，装不了端口映射软件

其实还有一种解决方式，你家路由器端口映射到电脑

**Comment by NB-Group** [comment]
不得不说，chatGPT是一个很牛x的工具
![image](https://user-images.githubusercontent.com/121747915/235650675-51157cd3-95b0-439a-8ae3-22bd76762ca5.png)

**Comment by NB-Group** [comment]
不过6也是真的6，返回的居然是个字符串格式的utf-8码。。。
![image](https://user-images.githubusercontent.com/121747915/235651579-75884cae-3d18-4d73-b8e2-b23ced9f6ed2.png)

**Comment by User782Tec** [comment]
> 不过6也是真的6，返回的居然是个字符串格式的utf-8码。。。 ![image](https://user-images.githubusercontent.com/121747915/235651579-75884cae-3d18-4d73-b8e2-b23ced9f6ed2.png)

不得不说
其实我都写好了

**Comment by User782Tec** [comment]
> > 不过6也是真的6，返回的居然是个字符串格式的utf-8码。。。 ![image](https://user-images.githubusercontent.com/121747915/235651579-75884cae-3d18-4d73-b8e2-b23ced9f6ed2.png)
> 
> 不得不说 其实我都写好了

几个星期前写好的（就是本Issue的提出之日

**Comment by NB-Group** [comment]
> > 不过6也是真的6，返回的居然是个字符串格式的utf-8码。。。![图像](https://user-images.githubusercontent.com/121747915/235651579-75884cae-3d18-4d73-b8e2-b23ced9f6ed2.png)
> 
> 不得不说 其实我都写好了

啊哈哈，直接给我吧

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/235652760-f73e230e-d7e3-406c-8cdd-9a4cbb979f8d.png)
[main.py.txt](https://github.com/tjy-gitnub/win12/files/11372501/main.py.txt)

（没法上传Python文件，我在后面加了个.txt）

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/235653646-c4327a34-fa0a-498c-844b-966b738ef0e4.png)

使用例

![image](https://user-images.githubusercontent.com/115236204/235653713-0fe8d7f3-0628-4313-874f-131b03b800b5.png)

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/235652760-f73e230e-d7e3-406c-8cdd-9a4cbb979f8d.png) [主.py.txt](https://github.com/tjy-gitnub/win12/files/11372501/main.py.txt)
> 
> （没法上传Python文件，我在后面加了个.txt）

云端和本地都遇到这错
![image](https://user-images.githubusercontent.com/121747915/235653615-56b17ded-3fa6-45e5-ab8c-2af6c421dceb.png)

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/235653646-c4327a34-fa0a-498c-844b-966b738ef0e4.png)
> 
> 使用例
> 
> ![image](https://user-images.githubusercontent.com/115236204/235653713-0fe8d7f3-0628-4313-874f-131b03b800b5.png)

结果用万物皆可遇报错删代码调试方法把那两行删了就可以了。。。

**Comment by NB-Group** [comment]
> > 所以你如何在学校登上GitHub并逃过老师的监视和我们聊天？（ 像我们学校，老师都不给开网络 就算是开也仅限访问几个站点（被编程猫迫害的日子啊啊啊啊啊啊
> 
> 你以为老师不会像我一样摸鱼？

逝世效果？https://win12server.freehk.svipss.top/?url=https://www.baidu.com/
@User782Tec

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/235653646-c4327a34-fa0a-498c-844b-966b738ef0e4.png)
> 
> 使用例
> 
> ![image](https://user-images.githubusercontent.com/115236204/235653713-0fe8d7f3-0628-4313-874f-131b03b800b5.png)

康下行不行吧，https://win12server.freehk.svipss.top/?url=https://www.baidu.com/
注意url一定是完整域名

**Comment by User782Tec** [comment]
> > ![image](https://user-images.githubusercontent.com/115236204/235652760-f73e230e-d7e3-406c-8cdd-9a4cbb979f8d.png) [主.py.txt](https://github.com/tjy-gitnub/win12/files/11372501/main.py.txt)
> > （没法上传Python文件，我在后面加了个.txt）
> 
> 云端和本地都遇到这错 ![image](https://user-images.githubusercontent.com/121747915/235653615-56b17ded-3fa6-45e5-ab8c-2af6c421dceb.png)

鹅鹅鹅
其实pip install flask-cors就行了

**Comment by User782Tec** [comment]
> > ![image](https://user-images.githubusercontent.com/115236204/235653646-c4327a34-fa0a-498c-844b-966b738ef0e4.png)
> > 使用例
> > ![image](https://user-images.githubusercontent.com/115236204/235653713-0fe8d7f3-0628-4313-874f-131b03b800b5.png)
> 
> 康下行不行吧，https://win12server.freehk.svipss.top/?url=https://www.baidu.com/ 注意url一定是完整域名

可以
但有跨域问题
（qwq服务器和域名哪儿来的
透露一下呗

**Comment by User782Tec** [comment]
> 结果用万物皆可遇报错删代码调试方法把那两行删了就可以了。。。

其实那两行就是允许跨域请求的脚本（

**Comment by NB-Group** [comment]
> > > ![image](https://user-images.githubusercontent.com/115236204/235653646-c4327a34-fa0a-498c-844b-966b738ef0e4.png)
> > > 使用例
> > > ![image](https://user-images.githubusercontent.com/115236204/235653713-0fe8d7f3-0628-4313-874f-131b03b800b5.png)
> > 
> > 
> > 康下行不行吧，https://win12server.freehk.svipss.top/?url=https://www.baidu.com/ 注意url一定是完整域名
> 
> 可以 但有跨域问题 （qwq服务器和域名哪儿来的 透露一下呗

自己的电脑做服务器，用内网穿透连接外网，域名是赠送的https://www.fgnwct.com/

**Comment by NB-Group** [comment]
> > 结果用万物皆可遇报错删代码调试方法把那两行删了就可以了。。。
> 
> 其实那两行就是允许跨域请求的脚本（

啊，我把它加回来

**Comment by NB-Group** [comment]
> > 结果用万物皆可遇报错删代码调试方法把那两行删了就可以了。。。
> 
> 其实那两行就是允许跨域请求的脚本（

![image](https://user-images.githubusercontent.com/121747915/235672462-1d3a6a4c-49d2-491b-8c21-9a5b617d89a3.png)
是不是应为它的版本不对啊，库重装了也没用啊

**Comment by NB-Group** [comment]
> > > ![image](https://user-images.githubusercontent.com/115236204/235652760-f73e230e-d7e3-406c-8cdd-9a4cbb979f8d.png) [主.py.txt](https://github.com/tjy-gitnub/win12/files/11372501/main.py.txt)
> > > （没法上传Python文件，我在后面加了个.txt）
> > 
> > 
> > 云端和本地都遇到这错 ![image](https://user-images.githubusercontent.com/121747915/235653615-56b17ded-3fa6-45e5-ab8c-2af6c421dceb.png)
> 
> 鹅鹅鹅 其实pip install flask-cors就行了
不是，我看错报错了，我不是不会pip install，是
![image](https://user-images.githubusercontent.com/121747915/235673206-ed7384ea-2ce7-46d2-a33b-cd682151041e.png)

**Comment by NB-Group** [comment]
> > 结果用万物皆可遇报错删代码调试方法把那两行删了就可以了。。。
> 
> 其实那两行就是允许跨域请求的脚本（

哦↘喉↗
![image](https://user-images.githubusercontent.com/121747915/235674166-fda4ad61-1158-4a44-a6da-4b3c862b1f1b.png)

**Comment by User782Tec** [comment]
好家伙
自己的电脑
我寄了（没电脑了5555）

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/235675357-20de1ddc-bacb-4b99-8fcb-adead1962a45.png)

？

**Comment by User782Tec** [comment]
话说你那个电脑是闲置的吗
能一直运行咩

**Comment by NB-Group** [comment]
> 话说你那个电脑是闲置的吗 能一直运行咩

当然不是闲置的，但是我们家有7-9台闲置电脑，只不过电费。。。

**Comment by User782Tec** [comment]
草
大富人家

其实可以装服务器系统（比如Ubuntu Server等），功耗（可能，但一定比桌面系统）低一点

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/235675357-20de1ddc-bacb-4b99-8fcb-adead1962a45.png)
> 
> ？

很简单啊，在这个标签里用的所有print都会打印在背景上，如果要实现print的效果，可以通过
`Element('text-cmd').write("")`的形式，这也是我把print replace掉的原因

**Comment by NB-Group** [comment]
跨域的你再逝世，我这里改完代码了

**Comment by User782Tec** [comment]
可是
万一是在函数里调用的print函数呢？防不胜防
现在解决方案有两个：
1. 重写PyScript脚本，适配该项目
2. 置之不理，把自带的终端隐藏起来

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/235683126-6aa9bd8f-1646-4fbf-b1aa-8566b1a1778d.png)

好了！

**Comment by NB-Group** [comment]
> 

是哦，我比较懒就选方案2吧，主要是没几个函数会在里面print()执行结果的，正常都是return的。

**Comment by User782Tec** [comment]
还有个问题
就是所有带关键字的语句基本上都没法运行

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/235683126-6aa9bd8f-1646-4fbf-b1aa-8566b1a1778d.png)
> 
> 好了！

我这台电脑是我经常不关机的，可以先这么撑一会，等有除了自动域名以外的功能加进来了我就把项目搬到我的闲置电脑上去。

**Comment by User782Tec** [comment]
好的
感谢好心人！

**Comment by NB-Group** [comment]
> 还有个问题 就是所有带关键字的语句基本上都没法运行

雀食，就凭这个可以重写了，写成除了print其他全部直接执行，print单独拿出来Element('text-cmd').write("")。

**Comment by User782Tec** [comment]
我是这样写的2333333
![image](https://user-images.githubusercontent.com/115236204/235689354-4d1eb98a-651c-4445-82ac-812370ac2cfe.png)

检测是否出现了关键字

**Comment by tjy-gitnub** [comment]
<s>Amazing!</s> Scary!
我不在一天...
估计明天还要去集训 T_T)o

**Comment by User782Tec** [comment]
qwq

**Comment by NB-Group** [comment]
> 我是这样写的2333333 ![image](https://user-images.githubusercontent.com/115236204/235689354-4d1eb98a-651c-4445-82ac-812370ac2cfe.png)
> 
> 检测是否出现了关键字

可以的，但是还有小bug，就是它执行的时候好像不会把以前执行的执行了，这个也蛮简单的，不过要replace(/&gt;&gt;&gt;/g, ""); &gt;&gt;&gt;是>>>我也不知道为啥会被转换（竟然延用了我的离谱变量名nb,nbyyds23333）

**Comment by NB-Group** [comment]
> 我是这样写的2333333 ![image](https://user-images.githubusercontent.com/115236204/235689354-4d1eb98a-651c-4445-82ac-812370ac2cfe.png)
> 
> 检测是否出现了关键字

> 我是这样写的2333333 ![image](https://user-images.githubusercontent.com/115236204/235689354-4d1eb98a-651c-4445-82ac-812370ac2cfe.png)
> 
> 检测是否出现了关键字

可以的，但是还有小bug，就是它执行的时候好像不会把以前执行的执行了，这个也蛮简单的，不过要replace(/& gt;& gt;& gt;/g, ""); & gt;& gt;&g t;是>>>我也不知道为啥会被转换（竟然延用了我的离谱变量名nb,nbyyds23333）

**Comment by NB-Group** [comment]
> 我是这样写的2333333 ![image](https://user-images.githubusercontent.com/115236204/235689354-4d1eb98a-651c-4445-82ac-812370ac2cfe.png)
> 
> 检测是否出现了关键字

可以的，但是还有小bug，就是它执行的时候不会把以前执行的执行了，这个也蛮简单的，不过要replace(/&gt;&gt;&gt;/g, ""); &gt;&gt;&gt;是>>>我也不知道为啥会被转换（竟然延用了我的离谱变量名nb,nbyyds23333）

**Comment by User782Tec** [comment]
用pyodide吧
貌似更好一点

**Comment by User782Tec** [comment]
pyscript太麻烦了

**Comment by User782Tec** [comment]
> 可是 万一是在函数里调用的print函数呢？防不胜防 现在解决方案有两个：
> 
> 1. 重写PyScript脚本，适配该项目
> 2. 置之不理，把自带的终端隐藏起来

现在有第三个方案了
3. 抛弃Pyscript，拥抱Pyodide

**Comment by NB-Group** [comment]
>

> 用pyodide吧 貌似更好一点

我去看了下，这个可以的。

**Comment by tjy-gitnub** [comment]
可以用iframe嵌套，输出在背景上就ok了
 |u-)o

**Comment by User782Tec** [comment]
我们已经不用Pyscript了
也就没有这个问题了
|u-)o

**Comment by tjy-gitnub** [comment]
|w-)o
