### ISSUE TITLE
能不能加个开机(started)和登录(logon)啊？

### ISSUE THREAD

**Issue by chineseLiuhaoyan** [win12-online/win12#72]
还有各种音效

**Comment by tjy-gitnub** [comment]
开机有啊(加载的时候会显示，但是pwa有缓存，加载时间就几乎没有了...总不能故意拖慢加载速度吧)
额哈...
登录的话可以考虑的
音效就算了吧，也没有太多的音效，就个开机提示音
开机提示音也不能抄win11的啊，我又只会抄 `TvT)o`

**Comment by User782Tec** [comment]
此 Isssue 中所提出的建议已在 Commit <https://github.com/tjy-gitnub/win12/commit/532b33b006e18d64fa79d286f57c18c212a73312> ( Pull Request https://github.com/tjy-gitnub/win12/pull/81 ) 中使用。
