### ISSUE TITLE
建议添加窗口分屏

### ISSUE THREAD

**Issue by lh11117** [win12-online/win12#77]
win11都有的功能，win12为什么没有（看下面的图片）
![NVIDIA_Share_Ni2xOJ9aeg](https://user-images.githubusercontent.com/99455215/235273449-ad96857e-7bd9-49f6-b2e3-902627962516.gif)

**Comment by tjy-gitnub** [comment]
好吧 你为什么有那么多
![image](https://user-images.githubusercontent.com/71509955/235283724-fa17db87-d07f-4d98-a083-413599bae411.png)
嗯 这个有那么一定的难度啊 - t-)o
我可以 呃 尝试一下
(你的深色模式背景为什么是浅色的啊？
