### ISSUE TITLE
投稿一个新闻

### ISSUE THREAD

**Issue by Luoboa2** [win12-online/win12#79]
新苏联
近日，由俄罗斯总统发起的“苏维埃改革”进行的如火如荼。有美国专家分析，俄罗斯将会和多个国家进行联盟，形成像苏联一样的强大联盟。

**Comment by tjy-gitnub** [comment]
真的啊？ Oo0)o

**Comment by User782Tec** [comment]
> 真的啊？ Oo0)o

应该是假的
