### ISSUE TITLE
多一些细节与其他

### ISSUE THREAD

**Issue by sadfsgr** [win12-online/win12#8]
时间右边加桌面按钮
加一些游戏与程序，如扫雷等
记事本的内容应可保存至desktop
explorer中的快速访问应可点击
尽快完善系统程序，如cmd, defender 等
开始按键应可右键
开始界面中的‘所有应用’，‘更多’应可点击
搜索界面应可有效搜索程序，如‘设置’
  如果意见被采纳，在此表示感谢并请发至：YEason2022@outlook.com

**Comment by tjy-gitnub** [comment]
谢谢你的建议，这些功能之后都应该会有的

**Comment by ghost** [comment]
@tjy-gitnub 现在已经v7.3.6系列了，咋还没看着

**Comment by tjy-gitnub** [comment]
不到。

**Comment by tjy-gitnub** [comment]
（开始按钮早就加了右键菜单啊

**Comment by tjy-gitnub** [comment]
实现了一部分，其他的嘛。。。

***

感谢你的建议
