### ISSUE TITLE
直接贡献以完成的代码：python应用

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#80]
众所周知，一个好的操作系统，要兼容除了编写操作系统的语言的其他语言。
所以，我为win12编写了python应用（改的原来的终端）。
先看下效果，本评论包含原理和代码。
![image](https://user-images.githubusercontent.com/121747915/235349233-6fc8340b-7de5-4969-a0f4-07398a6dcde0.png)
那么如何实现这个效果的呢
pyscript是一个开源的网页端python解释器项目，官网[pyscript](https://pyscript.net )。
在html文件里添加以下代码：
```
<link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
<script defer src="https://pyscript.net/latest/pyscript.js"></script>
```
即可引入此库（第一次加载时间会有亿点点长，可以放在开机的页面里加载，但是之后就快了）
接下来，可以创建一个py-script标签（一对标签<py-script></py-script>），在标签内部写入需要运行的python代码即可。
当然，他内置了api来修改网页元素的属性。
例如：
Element('便签id').write("")
注意，此代码是覆盖式的。
那么，只要使用js向网页添加一个py-script标签并在其中添加控制台输入的代码代码执行完毕的结果使用Element('便签id').write("")输出就可以了。
完整代码部署：

首先，在desktop.html代码中找到第980行，应该有一个<p>终端</p>标签，在1035行，应该有个<p>新建标签页</p>标签，接下来，用以下代码替换980-1035行的内容(包括980-1035行):
```
			<p>终端</p>
			<div>
				<a class="a wbtg red" onclick="hidewin('terminal')"><i class="bi bi-x-lg"></i></a>
				<a class="a wbtg max" onclick="maxwin('terminal')"><i class="bi bi-app"></i></a>
				<a class="a wbtg" onclick="minwin('terminal')"><i class="bi bi-dash-lg"></i></a>
			</div>
		</div>
		<div class="loadback">
			<img src="icon/terminal.png" class="icon">
		</div>

		<div class="content" id="win-terminal">
            		<script>
function keyup_submit(e){
   var evt = window.event || e;
   if (evt.keyCode == 13){
      //回车事件
      var value = document.getElementById("nb").value;
      document.getElementById("nb").value = "";
      var nbyyds = document.getElementById("text-cmd").innerHTML;  //推荐使用
      value = value.replace(/"/g, "'");
      if(value.includes("print("))
      {
      	value = value.replace(")", "");
      }
      value = value.replace("print(", "");
      nbyyds = nbyyds.replace(/\n/g, "\\n");
      nbyyds = nbyyds.replace(/"/g, "'");
      nbyyds = nbyyds.replace(/&gt;&gt;&gt;/g, ">>>");
      var nb = `Element('text-cmd').write(\"${nbyyds}>>>${value}\\n\"+str(${value})+\"\\n\")`;
      // 创建新的p元素
var newP = document.createElement('py-script');

// 设置元素内容
newP.textContent = nb;

// 将元素添加到现有的DOM树中
var myDiv = document.getElementById('win-terminal');
myDiv.appendChild(newP);

    }
  }
</script>
            <pre>Python 3.7.0  [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
</pre>
			<pre id="text-cmd"></pre>
            <pre >>>><input id = "nb" type="text" onkeydown="keyup_submit(event);"></pre>
		</div>
	</div>
	<div class="window edge" onmousedown="focwin('edge')" ontouchstart="focwin('edge')">
		<div class="titbar" oncontextmenu="return showcm(event,'titbar','edge')" ondblclick="maxwin('edge')">
			<img src="icon/edge.png" class="icon"><p style="display: none;">Microsoft Edge</p>
			<div class="tabs">
				<div class="tab">
					<p>新建标签页</p>
```
接下来，在desktop.js中找到第517到524行代码，将以下代码
```
    terminal: {
        init: () => {
        $('#win-terminal>pre').html(`Python 3.7.0  [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>><input id = "nb" type="text">`)


           }
    },
```
改为
```
    terminal: {
        init: () => {
//        $('#win-terminal>pre').html(`Python 3.7.0  [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
//Type "help", "copyright", "credits" or "license" for more information.
//>>><input id = "nb" type="text">`)

           }
    },
```
最后记得在desktop.html的<head>加上：
```
<link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
<script defer src="https://pyscript.net/latest/pyscript.js"></script>
```
在重新启动终端应用后，即可使用python应用。

最后的最后，我说一些废话：
谭景元giegie，我蛮想认识下你的，我先来做个自我介绍吧。
我是一个五年级小~屁孩~学生，别看我年龄小，我技术可不拉只因。
先来看看我的代表作吧——[流浪地球MOSS复刻](https://www.bilibili.com/video/BV1Dh411g7aR/)
当然，我能够通过这张截图证明这是我制作的
![image](https://user-images.githubusercontent.com/121747915/235352471-a819452d-a4e6-4def-9940-ce80c641ddf5.png)

还有20多个"NB"系列GUI软件（名字起的很离谱）
![image](https://user-images.githubusercontent.com/121747915/235352246-78507598-6da8-40ee-8cb1-747cedaa99de.png)

我用c语言加汇编编过NBOS，并真正的安装到了我的笔记本上，它除了文件系统，其他的应有尽有，不过截图没了。

还有一些自制鬼畜的视频，我的b站主页里有，但是别看，很拉只因。

你问我还有其他项目吗，当然有，我用java制作过多个安卓app，只不过制作起来比较复杂，我也就没做太多。

我喜欢编程，也受到家长的支持，我看了你的项目，真的很棒，我想认识下你，留个联系方式？谢谢

**Comment by tjy-gitnub** [comment]
wowowowowowoowowowowwoowowowow
我对你那个moss很感兴趣啊
那个脑袋是个摆设还是真的里面有麦克风什么的啊
同学，看你的技术，我对你家长的支持表示羡慕 ^u^)o
可是你有没有想过这些技术有什么用啊？你的家长为什么支持你学这个？我不理解 >_-)o

另：你可以发一个pr，算是你对项目的贡献 : )

**Comment by NB-Group** [comment]
脑袋里就一个麦克风和扬声器，还有控制俩电机和一个灯的ESP32。
至于这个技术，现在是人工智能时代嘛，以后想学就晚了，我家长觉得搞这些也挺有用的，主要是也在各种比赛中获奖了

**Comment by User782Tec** [comment]
挖槽
牛逼
拜见大师！

---

我们欢迎你成为windows12网页版项目的贡献者之一！

---

qwq
不像我
我的父母极力反对我编程

---

建议加个python命令，输入命令时才进入python解释器
这样更好一点
毕竟终端是终端

---

@tjy-gitnub 
我登录界面和开机音效做好啦

**Comment by tjy-gitnub** [comment]
好吧，6
嗯你可以发一个pr

另：开源许可是有法律效应的，记得在你的项目里注明原作者哦😊

**Comment by NB-Group** [comment]
> 好吧，6 嗯你可以发一个PR
> 
> 另：开源许可是有法律效应的，记得在你的项目里注明原作者哦😊

发了合并请求了，看下吧

**Comment by User782Tec** [comment]
我有个想法
咱就不改终端了
我们做个低配版(指没有代码高亮、自动补全这样的高只因功能)的半个IDE(指没有调试功能，只有运行功能)
这样就不用考虑怎么把表达式返回值放在终端里了
py-script官方提供了元素，可作为终端使用，且可以自定义
@NB-Group

**Comment by NB-Group** [comment]
> 我有个想法 咱就不改终端了 我们做个低配版(指没有代码高亮、自动补全这样的高只因功能)的半个IDE(指没有调试功能，只有运行功能) 这样就不用考虑怎么把表达式返回值放在终端里了 py-script官方提供了元素，可作为终端使用，且可以自定义 @NB-Group

可以的，改个记事本

**Comment by User782Tec** [comment]
> > 我有个想法 咱就不改终端了 我们做个低配版(指没有代码高亮、自动补全这样的高只因功能)的半个IDE(指没有调试功能，只有运行功能) 这样就不用考虑怎么把表达式返回值放在终端里了 py-script官方提供了元素，可作为终端使用，且可以自定义 @NB-Group
> 
> 可以的，改个记事本

咳咳
记事本可不兴改啊
为何不直接再造个软件呢

**Comment by NB-Group** [comment]
> > > 我有个想法 咱就不改终端了 我们做个低配版(指没有代码高亮、自动补全这样的高只因功能)的半个IDE(指没有调试功能，只有运行功能) 这样就不用考虑怎么把表达式返回值放在终端里了 py-script官方提供了元素，可作为终端使用，且可以自定义 @NB-Group
> > 
> > 
> > 可以的，改个记事本
> 
> 咳咳 记事本可不兴改啊 为何不直接再造个软件呢

我改的意思是新造个类似记事本的

**Comment by User782Tec** [comment]
行
但你可以看看现在的记事本
俨然是个Word了

**Comment by kjmjh** [comment]
至尊时刻!收藏!!!

**Comment by lingbopro** [comment]
啊？两年前的东西？

**Comment by kjmjh** [comment]
> 啊？两年前的东西？

啊？！你怎么知道我在这？

**Comment by lingbopro** [comment]
> > 啊？两年前的东西？
> 
> 啊？！你怎么知道我在这？

我关注了win12的所有活动 :)

**Comment by kjmjh** [comment]
> > > 啊？两年前的东西？
> > 
> > 啊？！你怎么知道我在这？
> 
> 我关注了win12的所有活动 :)

6

**Comment by tjy-gitnub** [comment]
。。。《夕拾朝花》

**Comment by kjmjh** [comment]
啊？？！！

**Comment by NB-Group** [comment]
这是真《朝花夕拾》了

**Comment by tjy-gitnub** [comment]
挖去，折磨热闹？

**Comment by kjmjh** [comment]
不是？!
