### ISSUE TITLE
希望可以增加窗口大小调整的按钮和动画

### ISSUE THREAD

**Issue by wchenyi** [win12-online/win12#83]

**Comment by User782Tec** [comment]
emm
详细一点？

**Comment by NebulaTechs** [comment]
希望可以增加窗口大小拖动功能

**Comment by User782Tec** [comment]
好的
安排
(预计发布版本：v5.4.0

**Comment by NB-Group** [comment]
> 好的 安排 (预计发布版本：v5.4.0

马上就要到了，是时候考虑下了吧

**Comment by User782Tec** [comment]
> > 好的 安排 (预计发布版本：v5.4.0
> 
> 马上就要到了，是时候考虑下了吧

目前思路是这样的:
在每个窗口上加上八个拖动条
然后检测拖动进行调整

**Comment by NB-Group** [comment]
> > > 好的 安排 (预计发布版本：v5.4.0
> > 
> > 
> > 马上就要到了，是时候考虑下了吧
> 
> 目前思路是这样的: 在每个窗口上加上八个拖动条 然后检测拖动进行调整

应该可以吧，还有那个问题看下啊

**Comment by User782Tec** [comment]
制作完成`(^ v ^)`
预计发布版本：v5.4.3

拖更了一会，抱歉qwq

**Comment by User782Tec** [comment]
已发布
搭建完成
