### ISSUE TITLE
更高端的后端服务

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#84]
我基于昨天开发的网页标题获取开发了聊天机器人服务（不是chatGPT其实chatGPT也可以）

调用方法，向https://win12server.freehk.svipss.top/Chat?msg=发送请求，在msg后增加发送的内容。

例如：
![image](https://user-images.githubusercontent.com/121747915/235829822-9a429549-35d5-4a4e-b94e-df8803831f8a.png)
当然，也有关键词检测增加更多功能。
以下是api关键词

中英翻译：msg=翻译i love you
笑话：msg=笑话
歌词⑴：msg=歌词后来
歌词⑵：msg=歌词后来-刘若英
手机⑴：msg=归属13430108888
手机⑵：msg=13430108888
成语查询：msg=成语一生一世
五笔/拼音：msg=好字的五笔/拼音

关键词事例：
![image](https://user-images.githubusercontent.com/121747915/235830255-4586601c-4e72-4dd9-860b-33eb01d83a72.png)

好了，这些乱七八糟的功能就交给你们前端开发了，记得给我康下啊
@User782Tec @tjy-gitnub

**Comment by tjy-gitnub** [comment]
Cortana?

**Comment by NB-Group** [comment]
> Cortana?

哈？

**Comment by NB-Group** [comment]
这个支持跨域请求

**Comment by tjy-gitnub** [comment]
？是什么东西啊？你自己做的

**Comment by tjy-gitnub** [comment]
{face:31}是什么鬼???

**Comment by NB-Group** [comment]
> ？是什么东西啊？你自己做的

昨天我不是和 @User782Tec 用后端做了获取网站标题的功能吗，这是新的聊天机器人拓展，可以内置到win12里面

**Comment by User782Tec** [comment]
卧槽
牛逼

**Comment by User782Tec** [comment]
终于把python做好了

支持：
- 普通的函数调用
- 捕获所有的输出内容
- 关键字使用
- 内置库导入
- 函数定义
- 循环、判断等语句
- 错误与异常捕获

**Comment by tjy-gitnub** [comment]
啊... `TwT)ooooooooooooooo`
这样吧，我做一个这个Cortana
换一下图标
你们把python和Edge做好了
一起直接发6.0吧(7.0也行 -_-)o

**Comment by User782Tec** [comment]
> 啊... `TwT)ooooooooooooooo` 这样吧，我做一个这个Cortana 换一下图标 你们把python和Edge做好了 一起直接发6.0吧(7.0也行 -_-)o

咳咳
不太行
个性化没弄
仓库没弄
解析器没弄
窗口大小调整没弄
5555555

**Comment by tjy-gitnub** [comment]
啊... TwT)oooooooooooooo

**Comment by User782Tec** [comment]
要不咱加一个团队？

**Comment by tjy-gitnub** [comment]
? >o>)o?

**Comment by User782Tec** [comment]
就GitHub里的

**Comment by tjy-gitnub** [comment]
??? ?o?)?o ??

**Comment by User782Tec** [comment]
![加号下面的New Organization]()

诺
就这个

**Comment by tjy-gitnub** [comment]
![image](https://user-images.githubusercontent.com/71509955/235847137-8b852e0d-ebd0-45ab-9867-eee8ab5a0fbb.png)
这个?

**Comment by User782Tec** [comment]
嗯...
我这网不好
看不见图片

**Comment by User782Tec** [comment]
额
可能不是的
这个是合作

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/235847617-90d7f0e8-8598-43c8-993c-d0a7f5f8d417.png)

**Comment by User782Tec** [comment]
不过合作也挺好滴

**Comment by tjy-gitnub** [comment]
![image](https://user-images.githubusercontent.com/71509955/235848075-681e6fdd-1ed3-4574-89ae-339a045b02b6.png)
这是新建一个账户

**Comment by tjy-gitnub** [comment]
你通过一下试试 @User782Tec

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/235848461-44cb11ea-e166-4b06-8f90-cfa0d0ab66f8.png)

耶
`(^－^)V`

**Comment by User782Tec** [comment]
> ![image](https://user-images.githubusercontent.com/71509955/235848075-681e6fdd-1ed3-4574-89ae-339a045b02b6.png) 这是新建一个账户

这就是新建一个组织

**Comment by tjy-gitnub** [comment]
我试一下组织呢

**Comment by tjy-gitnub** [comment]
看到了吗 @User782Tec 
@windows12-online

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/235849757-dc9a1c93-0c4f-423b-a4e9-1a260ae9af80.png)

额
@NB-Group

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/235849952-03794bf9-08d0-4755-971f-4d9b19828200.png)

进来了！

**Comment by User782Tec** [comment]
建议加个图标
![logo](https://user-images.githubusercontent.com/115236204/235850177-f52ebe9d-f48a-4150-a318-8c43277da5e7.png)

**Comment by tjy-gitnub** [comment]
你觉得组织和合作那个好?

**Comment by User782Tec** [comment]
如果项目小的话，合作好
- 人员固定
- 属于个人

如果项目的规模越来越大，贡献者越来越多，组织好
- 他人可参加
- 属于组织

（个人理论，不喜勿喷）

**Comment by tjy-gitnub** [comment]
所以你有什么 建议 吗？
我觉得就保持目前的状态不错吧
如果合作和组织要选一个的话我选组织，
因为只是合作的话pr其实就可以啊
而且合作可以随意push，感觉有些混乱
So what about your thought?

**Comment by User782Tec** [comment]
臣附议(bushi

**Comment by User782Tec** [comment]
还有
既然在组织上有新的仓库了
我觉得要把这个仓库存档一下
再在新的仓库上继续努力

**Comment by User782Tec** [comment]
嘶
不对啊
你是怎么把仓库迁移到组织上的
怎么数据都没了

**Comment by tjy-gitnub** [comment]
好像是的欸
（你附议附的是哪个啊

**Comment by User782Tec** [comment]
> 所以你有什么 建议 吗？
> 我觉得就保持目前的状态不错吧
> 如果合作和组织要选一个的话我选组织，
> 因为只是合作的话pr其实就可以啊
> 而且合作可以随意push，感觉有些混乱
> So what about your thought?

这个

**Comment by User782Tec** [comment]
你是怎么迁移的

**Comment by tjy-gitnub** [comment]
这个是
> 我觉得就保持目前的状态不错吧

还是

> 如果合作和组织要选一个的话我选组织，

<hr>

直接克隆啊 >_-)o

**Comment by User782Tec** [comment]
咳咳
都是

---

不能直接克隆啊喂

在仓库页面里，点击"Settings"，向下拉，找到"Danger Zone"，有一个叫做"Transfer ownership"的选项，点右边的"Transfer"，然后从下面的下拉菜单里选"windows12-online"，在下面的输入框里确定仓库名称，并完成下面的验证，之后点击"I understand, transfer this repository"就行了 : )

**Comment by User782Tec** [comment]
哦对了，我还建了个Project

**Comment by tjy-gitnub** [comment]
> 哦对了，我还建了个Project

where?

<hr>

就用组织吧，准备迁移，请全体人员进入深海模式

**Comment by User782Tec** [comment]
> 就用组织吧，准备迁移，请全体人员进入深海模式

浅浅地打出一个“？”

**Comment by User782Tec** [comment]
在这儿
https://github.com/users/User782Tec/projects/2/views/2

**Comment by tjy-gitnub** [comment]
我想了一下还是算了吧
毕竟这还是一个个人项目，还没有到组织
而且url都放出去了，不熟悉的甚至熟悉的估计都找不到项目了
就先这样吧，以后时机成熟（搞出名了 >->
再思考这些问题吧
>_-)o

**Comment by User782Tec** [comment]
行
（我怎么记得可以重定向呢？）

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/235849757-dc9a1c93-0c4f-423b-a4e9-1a260ae9af80.png)
> 
> 额 @NB-Group

啊，我刚才在高铁上没wifi，现在用流量的，可以再逝世

**Comment by NB-Group** [comment]
> 终于把python做好了
> 
> 支持：
> 
> * 普通的函数调用
> * 捕获所有的输出内容
> * 关键字使用
> * 内置库导入
> * 函数定义
> * 循环、判断等语句
> * 错误与异常捕获

import os
os.system("dir")
会怎么样，如果
os.system("del *.*")
呢(doge)

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/235849757-dc9a1c93-0c4f-423b-a4e9-1a260ae9af80.png)
> 
> 额 @NB-Group

c，我爸不让我用流量了

**Comment by tjy-gitnub** [comment]
啊...

**Comment by User782Tec** [comment]
> > 终于把python做好了
> > 支持：
> > 
> > * 普通的函数调用
> > * 捕获所有的输出内容
> > * 关键字使用
> > * 内置库导入
> > * 函数定义
> > * 循环、判断等语句
> > * 错误与异常捕获
> 
> import os os.system("dir") 会怎么样，如果 os.system("del _._") 呢(doge)

笑死
我是Linux系统

**Comment by User782Tec** [comment]
好了我试过了
无事发生
![image](https://user-images.githubusercontent.com/115236204/235927372-b559f992-f6bd-4831-a289-74973aa69d1d.png)

**Comment by NB-Group** [comment]
> 好了我试过了 无事发生 ![image](https://user-images.githubusercontent.com/115236204/235927372-b559f992-f6bd-4831-a289-74973aa69d1d.png)

好，后端服务现在能用了

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/236213227-39f0e57d-52fb-4fe2-9c6f-efb1272ac9f2.png)

说吧
怎么解释（bushi
@NB-Group

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/236213227-39f0e57d-52fb-4fe2-9c6f-efb1272ac9f2.png)
> 
> 说吧 怎么解释（bushi @NB-Group

它是闲聊机器人，不是chatGPT让你提问题的。。。不过我可以换成chatGPT

另:
![image](https://user-images.githubusercontent.com/121747915/236220824-ecb98e59-f5ec-4130-adfb-f0dc6fc94f8a.png)
可以用了，明天我把css写好看点

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/236213227-39f0e57d-52fb-4fe2-9c6f-efb1272ac9f2.png)
> 
> 说吧 怎么解释（bushi @NB-Group

![image](https://user-images.githubusercontent.com/121747915/236481112-22b7fc04-2429-447d-951b-345f1703d9e3.png)
有点zz
@User782Tec @tjy-gitnub

**Comment by tjy-gitnub** [comment]
发的消息一般不应该是在右边吗？
还有，你没有很好地学习到巨硬ui的精髓哦 >u-)o

**Comment by NB-Group** [comment]
> 发的消息一般不应该是在右边吗？ 还有，你没有很好地学习到巨硬ui的精髓哦 >u-)o

![image](https://user-images.githubusercontent.com/121747915/236613308-dd8f1123-37a7-4f6f-a8cd-9f2c735350ac.png)
搞了半天还是不知道精髓。。。哈哈辅导辅导下我呗(

**Comment by NB-Group** [comment]
![image](https://user-images.githubusercontent.com/121747915/236619799-89dedbba-b0d2-4e9a-91f3-6679144168a5.png)
现在智商高一点了，换成了本地的PP-ASR模型，以前那个青云客的api什么智障玩意

**Comment by tjy-gitnub** [comment]
巨硬ui一句话：
德芙动画雅黑体，圆角阴影亚克力。

**Comment by tjy-gitnub** [comment]
还有主题色#2983cc (win12有自己的主题色

`>u-)o`

**Comment by NB-Group** [comment]
> #2983cc



> 巨硬ui一句话： 德芙动画雅黑体，圆角阴影亚克力。

懂了懂了

**Comment by NB-Group** [comment]
> #2983cc

[chat.zip](https://github.com/tjy-gitnub/win12/files/11412375/chat.zip)
康一些

**Comment by NB-Group** [comment]
康一下
[chat.zip](https://github.com/tjy-gitnub/win12/files/11412377/chat.zip)
@tjy-gitnub @User782Tec

**Comment by User782Tec** [comment]
> 康一下 [chat.zip](https://github.com/tjy-gitnub/win12/files/11412377/chat.zip) @tjy-gitnub @User782Tec

让我康康()

**Comment by tjy-gitnub** [comment]
![image](https://user-images.githubusercontent.com/71509955/236627304-723499e7-8a4b-4d84-a9ac-496dc03bbd66.png)
6

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/236627637-eea3cfdf-2498-459e-a961-8c6ebb8d9b89.png)

6

**Comment by User782Tec** [comment]
![image](https://user-images.githubusercontent.com/115236204/236627743-8a5f5570-7c62-4a26-aa94-5827879553c9.png)

废话大赏（bushi

**Comment by tjy-gitnub** [comment]
变性机器人: )
还有
![image](https://user-images.githubusercontent.com/71509955/236627976-6aa1d1b7-6e00-49be-9197-6a81406c812d.png)

**Comment by NB-Group** [comment]
> 变性机器人: ) 还有 ![image](https://user-images.githubusercontent.com/71509955/236627976-6aa1d1b7-6e00-49be-9197-6a81406c812d.png)

好家伙，你们玩的有点离谱了啊，我要不换chatGPT吧

**Comment by User782Tec** [comment]
chatGPT不要钱么

**Comment by NB-Group** [comment]
> chatGPT不要钱么

坑，啊不，白嫖镜像站的，或者我直接selenium控制浏览器向官网发请求

**Comment by NB-Group** [comment]
> chatGPT不要钱么

呐，就像这样的镜像。
![image](https://user-images.githubusercontent.com/121747915/236628799-851bcfbf-527a-41f4-a6f6-ce395c1f0353.png)
https://ai.usesless.com/chat/
记得登录

**Comment by tjy-gitnub** [comment]
chatgpt也赛不过我 >uu-)o
![image](https://user-images.githubusercontent.com/71509955/236630585-3b85cef4-ad5a-4236-8b14-34539eb3e406.png)

**Comment by NB-Group** [comment]
![image](https://user-images.githubusercontent.com/121747915/236656987-407ab0e5-f5fc-4a68-8c8b-025c1cbd4cbf.png)
逐渐狂躁的谭景元[doge]

**Comment by NB-Group** [comment]
![image](https://user-images.githubusercontent.com/121747915/236657008-ee64922f-d74d-4af8-a300-2baf0aeb88dd.png)
逐渐狂躁

**Comment by NebulaTechs** [comment]
<img width="1280" alt="image" src="https://github.com/tjy-gitnub/win12/assets/126944988/19e396e0-1f1d-4d2b-920d-35b226ca3c5b">

**Comment by NB-Group** [comment]
> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/126944988/238106269-19e396e0-1f1d-4d2b-920d-35b226ca3c5b.png">

目前调试状态我就给他关了，等chatGPT写好之后就会开启
