### ISSUE TITLE
请教下，你平时用什么svg编辑器

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#85]
如题，无详细内容。

@tjy-gitnub

**Comment by User782Tec** [comment]
咳咳 来凑个热闹
我平时会用Inkscape
在iPad上会用Vectornator
(当然，我平时不做图标2333)

**Comment by NB-Group** [comment]
> 咳咳 来凑个热闹 我平时会用Inkscape 在iPad上会用Vectornator (当然，我平时不做图标2333)

我搜下啊，还有你看下新的聊天机器人，换模型了，详情见那个lssus

**Comment by NB-Group** [comment]
> 咳咳 来凑个热闹 我平时会用Inkscape 在iPad上会用Vectornator (当然，我平时不做图标2333)

![image](https://user-images.githubusercontent.com/121747915/236623105-45c57b2c-ae6c-4e72-9129-9a506bdbd5a7.png)
wdf!

**Comment by User782Tec** [comment]
> > 咳咳 来凑个热闹 我平时会用Inkscape 在iPad上会用Vectornator (当然，我平时不做图标2333)
> 
> ![image](https://user-images.githubusercontent.com/121747915/236623105-45c57b2c-ae6c-4e72-9129-9a506bdbd5a7.png) wdf!

emmm
6(我是用snap下的，所以很快

**Comment by NB-Group** [comment]
> > > 咳咳 来凑个热闹 我平时会用Inkscape 在iPad上会用Vectornator (当然，我平时不做图标2333)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/121747915/236623105-45c57b2c-ae6c-4e72-9129-9a506bdbd5a7.png) wdf!
> 
> emmm 6(我是用snap下的，所以很快

可我不是ubuntu啊。。

**Comment by tjy-gitnub** [comment]
说出来你可能不信 ...
![image](https://user-images.githubusercontent.com/71509955/236623630-5dcc0b21-0209-4654-9a70-a320bc47da95.png)

-u-)o

**Comment by tjy-gitnub** [comment]
Inkscape 怎么样，好用吗？
@User782Tec

**Comment by User782Tec** [comment]
> Inkscape 怎么样，好用吗？ @User782Tec

咳咳
不会用(?

要不是我没有PowerPoint(bushi

**Comment by User782Tec** [comment]
> > > > 咳咳 来凑个热闹 我平时会用Inkscape 在iPad上会用Vectornator (当然，我平时不做图标2333)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/121747915/236623105-45c57b2c-ae6c-4e72-9129-9a506bdbd5a7.png) wdf!
> > 
> > 
> > emmm 6(我是用snap下的，所以很快
> 
> 可我不是ubuntu啊。。

论ubuntu系统的好处(?
我爱ubuntu

**Comment by tjy-gitnub** [comment]
听网上说挺不错，下下来只会用铅笔画一团，导出都找不到，果断放弃 `^u^)o`

**Comment by tjy-gitnub** [comment]
> > > > > 咳咳 来凑个热闹 我平时会用Inkscape 在iPad上会用Vectornator (当然，我平时不做图标2333)
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/121747915/236623105-45c57b2c-ae6c-4e72-9129-9a506bdbd5a7.png) wdf!
> > > 
> > > 
> > > emmm 6(我是用snap下的，所以很快
> > 
> > 
> > 可我不是ubuntu啊。。
> 
> 论ubuntu系统的好处(? 我爱ubuntu

你不是用k什么吗
(最近打算试一下
![image](https://user-images.githubusercontent.com/71509955/236623950-83b1cd69-9d68-4ea6-94f9-392f7f2a5355.png)

**Comment by NB-Group** [comment]
> 说出来你可能不信 ... ![image](https://user-images.githubusercontent.com/71509955/236623630-5dcc0b21-0209-4654-9a70-a320bc47da95.png)
> 
> -u-)o

啊啊啊？好家伙，这能导出成svg？

**Comment by User782Tec** [comment]
> > 说出来你可能不信 ... ![image](https://user-images.githubusercontent.com/71509955/236623630-5dcc0b21-0209-4654-9a70-a320bc47da95.png)
> > -u-)o
> 
> 啊啊啊？好家伙，这能导出成svg？

貌似不能

**Comment by User782Tec** [comment]
> > > > > > 咳咳 来凑个热闹 我平时会用Inkscape 在iPad上会用Vectornator (当然，我平时不做图标2333)
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/121747915/236623105-45c57b2c-ae6c-4e72-9129-9a506bdbd5a7.png) wdf!
> > > > 
> > > > 
> > > > emmm 6(我是用snap下的，所以很快
> > > 
> > > 
> > > 可我不是ubuntu啊。。
> > 
> > 
> > 论ubuntu系统的好处(? 我爱ubuntu
> 
> 你不是用k什么吗 (最近打算试一下 ![image](https://user-images.githubusercontent.com/71509955/236623950-83b1cd69-9d68-4ea6-94f9-392f7f2a5355.png)

对的
其实都是ubuntu系统
只是kubuntu使用的是kde桌面 好看一点

**Comment by tjy-gitnub** [comment]
你低估了office的力量
（不然你觉得为什么卖那么贵？-u-)o
ppt还可以画画，可以抠图(去除背景)，可以剪视频(导出为视频)，可以做游戏(嵌入vb)

**Comment by tjy-gitnub** [comment]
> > > 说出来你可能不信 ... ![image](https://user-images.githubusercontent.com/71509955/236623630-5dcc0b21-0209-4654-9a70-a320bc47da95.png)
> > > -u-)o
> > 
> > 
> > 啊啊啊？好家伙，这能导出成svg？
> 
> 貌似不能

![image](https://user-images.githubusercontent.com/71509955/236627082-f98d0d2c-5820-4c4d-b39c-4a6f53a2eae9.png)

**Comment by User782Tec** [comment]
> > > > 说出来你可能不信 ... ![image](https://user-images.githubusercontent.com/71509955/236623630-5dcc0b21-0209-4654-9a70-a320bc47da95.png)
> > > > -u-)o
> > > 
> > > 
> > > 啊啊啊？好家伙，这能导出成svg？
> > 
> > 
> > 貌似不能
> 
> ![image](https://user-images.githubusercontent.com/71509955/236627082-f98d0d2c-5820-4c4d-b39c-4a6f53a2eae9.png)

草
