### ISSUE TITLE
这好像半成品的有点严重啊

### ISSUE THREAD

**Issue by NebulaTechs** [win12-online/win12#87]
1，不能直接在终端中输入内容
2，（如下图）

**Comment by User782Tec** [comment]
首先：图呢
其次：我已经完善了终端，记得清除缓存再试试

**Comment by NebulaTechs** [comment]
<img width="866" alt="屏幕截图 2023-05-07 185539" src="https://user-images.githubusercontent.com/126944988/236675878-f31f89e1-db7d-4eee-8848-154edca3d21b.png">

**Comment by NebulaTechs** [comment]
<img width="935" alt="屏幕截图 2023-05-07 185520" src="https://user-images.githubusercontent.com/126944988/236675896-7d1c7909-913c-4781-ada3-027abe722326.png">
bi

**Comment by User782Tec** [comment]
咳咳
这个终端被你玩坏了

---

好的
马上修复

**Comment by User782Tec** [comment]
预计将在v5.3.0修复该问题

**Comment by User782Tec** [comment]
修好了:)
还没发布
