### ISSUE TITLE
加一个查看windows版本的软件。

### ISSUE THREAD

**Issue by Flystra** [win12-online/win12#88]
像windows11:
![屏幕截图 2023-05-09 214558](https://github.com/tjy-gitnub/win12/assets/126071197/98dc088f-971f-4629-9bd4-552aceadfcc5)
(winver)

**Comment by tjy-gitnub** [comment]
哦哦哦
可以可以
v6加入(我本来都计划加进去的，忘了
>u-)o

**Comment by Flystra** [comment]
> 哦哦哦 可以可以 v6加入（我本来都计划加进去的，忘了
> 
> > u-）o

ok。

**Comment by tjy-gitnub** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/71509955/19e26ddd-8ae2-4430-9a7e-0ee6e6f3d982)
Is that ok?

**Comment by Flystra** [comment]
> 

可以。

**Comment by Flystra** [comment]
什么版本加进去？

**Comment by tjy-gitnub** [comment]
6.0 >u-)o

**Comment by User782Tec** [comment]
> 6.0 >u-)o

what's up

**Comment by tjy-gitnub** [comment]
> > 6.0 >u-)o
> 
> what's up

？
