### ISSUE TITLE
这tnnd才叫后端！！！

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#89]
我在一个星期之前说过要写chatGPT，一直没时间，现在，它来了！！
通过https://win12server.freehk.svipss.top/Chat?msg=你好  直接发送get请求即可。
当然，我也有写好的，可以直接复制的
[chat.zip](https://github.com/tjy-gitnub/win12/files/11471571/chat.zip)
不过啊，这个接口呢不是特别稳定，因为用的是我们家台式机，一天tnnd就要36度电，所以准备换成我空闲的阿里云服务器。

这个是真·chatGPT智商很高，但是不要拿他写代码，有概率报错
@tjy-gitnub @User782Tec

**Comment by User782Tec** [comment]
我草
牛逼！！！

---

（唯一的缺点就是速度可能有些慢，不过无伤大雅）

---

阿哲原来你有服务器qwq

**Comment by NB-Group** [comment]
> 我草 牛逼！！！
> 
> （唯一的缺点就是速度可能有些慢，不过无伤大雅）
> 
> 阿哲原来你有服务器qwq

赶紧去整合到win12里吧(

**Comment by User782Tec** [comment]
<del>qwq
跨域还是有点问题</del>

没有，没有
就是403
希望作者能早日搬到服务器上（ ^ V ^ ）

**Comment by NB-Group** [comment]
> ~qwq 跨域还是有点问题~
> 
> 没有，没有 就是403 希望作者能早日搬到服务器上（ ^ V ^ ）

昨天休眠了，今天早上忘开了。

等正式上线了就搬，因为服务器没python环境（以前都是pyinstaller打包好上传运行的，这次这个方法用不了）需要装下就比较麻烦。

**Comment by User782Tec** [comment]
> > ~qwq 跨域还是有点问题~
> > 没有，没有 就是403 希望作者能早日搬到服务器上（ ^ V ^ ）
> 
> 昨天休眠了，今天早上忘开了。
> 
> 等正式上线了就搬，因为服务器没python环境（以前都是pyinstaller打包好上传运行的，这次这个方法用不了）需要装下就比较麻烦。

服务器提供在控制面板使用终端的服务（或SSH远程控制）的功能吗
如果可以的话，我也许能帮一帮
（我比较熟悉Linux
当然 如果是Windows Server 就当我没说）

**Comment by NB-Group** [comment]
> > > ~qwq 跨域还是有点问题~
> > > 没有，没有 就是403 希望作者能早日搬到服务器上（ ^ V ^ ）
> > 
> > 
> > 昨天休眠了，今天早上忘开了。
> > 等正式上线了就搬，因为服务器没python环境（以前都是pyinstaller打包好上传运行的，这次这个方法用不了）需要装下就比较麻烦。
> 
> 服务器提供在控制面板使用终端的服务（或SSH远程控制）的功能吗 如果可以的话，我也许能帮一帮 （我比较熟悉Linux 当然 如果是Windows Server 就当我没说）

服务器是正版windows(嘿嘿嘿有亿点小贵

**Comment by User782Tec** [comment]
> > > > ~qwq 跨域还是有点问题~
> > > > 没有，没有 就是403 希望作者能早日搬到服务器上（ ^ V ^ ）
> > > 
> > > 
> > > 昨天休眠了，今天早上忘开了。
> > > 等正式上线了就搬，因为服务器没python环境（以前都是pyinstaller打包好上传运行的，这次这个方法用不了）需要装下就比较麻烦。
> > 
> > 
> > 服务器提供在控制面板使用终端的服务（或SSH远程控制）的功能吗 如果可以的话，我也许能帮一帮 （我比较熟悉Linux 当然 如果是Windows Server 就当我没说）
> 
> 服务器是正版windows(嘿嘿嘿有亿点小贵

哦
有桌面环境就问题不大

**Comment by tjy-gitnub** [comment]
Cortana 来啦！
NBNBNBNB!!!
在开始菜单旁边加一个类似于win10的cortana的按钮 >u-)o
> 接口贵吗？还是白嫖的？（有没有使用限制？）
[激动]

**Comment by User782Tec** [comment]
哇
合并地狱（？

**Comment by NB-Group** [comment]
> Cortana 来啦！ NBNBNBNB!!! 在开始菜单旁边加一个类似于win10的cortana的按钮 >u-)o
> 
> > 接口贵吗？还是白嫖的？（有没有使用限制？）
> > [激动]

用啥搞的？但其实没chatGPT聪明。
![image](https://github.com/tjy-gitnub/win12/assets/121747915/510c0019-3347-4d96-8fdf-f7ec21c6f934)

**Comment by tjy-gitnub** [comment]
> 哇 合并地狱（？

哈哈，来，我们各自汇报一下自己做了啥
我先来：
新图标，自定义主题，winver

**Comment by NB-Group** [comment]
开发chatGPT接口，写了前端

**Comment by User782Tec** [comment]
“运行”应用、触控设备排序标签页、重构代码、修复若干bug

版本号5.3.0

**Comment by NB-Group** [comment]
所以什么时候合并发新版本(

**Comment by NB-Group** [comment]
> 接口贵吗？还是白嫖的？（有没有使用限制？）
 > [激动]

炒，刚刚看到，白嫖镜像站的，人家反爬是真的6，不过被我攻破了(doge，没使用限制

**Comment by tjy-gitnub** [comment]
6
真:合并地狱

**Comment by NB-Group** [comment]
chatGPT已经部署至服务器，使用无限制，24h随时访问，同时网页标题获取也部署完成，但是还是不要用它写代码。
如果过多人同时使用chatGPT，响应会使用先后机制，如果有多人同时调用接口，会在前一人完成后响应。
