### ISSUE TITLE
能不能搞成这样,带内容的 ^_^

### ISSUE THREAD

**Issue by vivafriend** [win12-online/win12#93]
gitee仓库:https://gitee.com/fs185085781/webos
github仓库: https://github.com/fs185085781/webos

**Comment by User782Tec** [comment]
不行吧...?

**Comment by vivafriend** [comment]
> 

他俩合作会有可能  0.O

**Comment by User782Tec** [comment]
> > 
> 
> 他俩合作会有可能 0.O

?

**Comment by vivafriend** [comment]
> > > 
> > 
> > 
> > 他俩合作会有可能 0.O
> 
> ?

我的意思 如果他们合作，无非就是个主题

**Comment by User782Tec** [comment]
> > > > 
> > > 
> > > 
> > > 他俩合作会有可能 0.O
> > 
> > 
> > ?
> 
> 我的意思 如果他们合作，无非就是个主题

额
你去找tjy吧
我理解不了

**Comment by vivafriend** [comment]
哈哈 我就说说。。。。

**Comment by vivafriend** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 他俩合作会有可能 0.O
> > > 
> > > 
> > > ?
> > 
> > 
> > 我的意思 如果他们合作，无非就是个主题
> 
> 额 你去找tjy吧 我理解不了

呃 我就是说说，

**Comment by User782Tec** [comment]
你是说
借鉴一下它的样式?

**Comment by vivafriend** [comment]
> 你是说 借鉴一下它的样式?

是这个意思

**Comment by vivafriend** [comment]
> > 你是说 借鉴一下它的样式?
> 
> 是这个意思

就是他们那个系统借鉴12这个样式 会不会更酷

**Comment by User782Tec** [comment]
这个会考虑一下:)

**Comment by tjy-gitnub** [comment]
额。。。
这个win12网页版不是做出来用于办公的（估计也没几个人用他那个网页版win11办公
我(们)的目标是win11.blueedge.me这样的
当然丰富内容也是必不可少的，不过现在基础的架构还没有建立起来..-u-)o
我们人可不多...

**Comment by User782Tec** [comment]
确实
人不是很多 qwq

**Comment by tjy-gitnub** [comment]
等等... 这是什么意思？
![image](https://github.com/tjy-gitnub/win12/assets/71509955/af6af03b-549f-4bf6-8444-c92a5f067f1d)
![image](https://github.com/tjy-gitnub/win12/assets/71509955/02f35a10-f0e0-4024-baf3-747b9acd8a7e)
