### ISSUE TITLE
代码高亮，自动补全，超级牛波一的网页python编辑器应用来了！

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#94]
没啥，其实就是个进展汇报的。
![image](https://github.com/tjy-gitnub/win12/assets/121747915/2a863174-c65b-4244-85c6-6376b7318e45)
这是目前的效果
@tjy-gitnub @User782Tec

**Comment by User782Tec** [comment]
可以
我觉得把字体换成consolas会更好看

**Comment by User782Tec** [comment]
你用的啥框架(?
我感觉codemirror挺好的

**Comment by NB-Group** [comment]
> codemirror

用的就是codemirror。这个效果不错吧（喜

**Comment by tjy-gitnub** [comment]
> 可以 我觉得把字体换成consolas会更好看

附议

**Comment by NB-Group** [comment]
字体改了
![image](https://github.com/tjy-gitnub/win12/assets/121747915/23397137-4f65-4c04-89ea-4bf04b45d406)

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/043f93d1-4ca1-4fe8-8c3e-789401ec1e82)

**Comment by User782Tec** [comment]
> ![image](https://user-images.githubusercontent.com/121747915/239689608-043f93d1-4ca1-4fe8-8c3e-789401ec1e82.png)

我先把亮度调整做了
马上来做这个
(可以逝逝改成Pycharm?)

**Comment by NB-Group** [comment]
> > ![image](https://user-images.githubusercontent.com/121747915/239689608-043f93d1-4ca1-4fe8-8c3e-789401ec1e82.png)
> 
> 我先把亮度调整做了 马上来做这个 (可以逝逝改成Pycharm?)

你，真，勇。
![image](https://github.com/tjy-gitnub/win12/assets/121747915/ab20f15b-bf7a-4edf-a5f1-6b0a1bf4a86d)

**Comment by NB-Group** [comment]
> 我先把亮度调整做了 马上来做这个 (可以逝逝改成Pycharm?)

亮度调整不是很简单吗，你把图标一换css重写一下不就行了，可你搞了两天了。。。

**Comment by User782Tec** [comment]
> > 我先把亮度调整做了 马上来做这个 (可以逝逝改成Pycharm?)
> 
> 亮度调整不是很简单吗，你把图标一换css重写一下不就行了，可你搞了两天了。。。

没多少时间
况且我今天阳了(悲

**Comment by NB-Group** [comment]
> > > 我先把亮度调整做了 马上来做这个 (可以逝逝改成Pycharm?)
> > 
> > 
> > 亮度调整不是很简单吗，你把图标一换css重写一下不就行了，可你搞了两天了。。。
> 
> 没多少时间 况且我今天阳了(悲

好惨，其实我也没多少时间，毕业了尼玛还要搞个文创产品，烦（炒！）

**Comment by tjy-gitnub** [comment]
所有不能运行？？？

**Comment by NB-Group** [comment]
> 所有不能运行？？？

待会把运行加上去，上次 @User782Tec 写python应用的时候写了个
![image](https://github.com/tjy-gitnub/win12/assets/121747915/fb734938-8d90-4cde-9374-da7bec8a4767)
我用它把运行写下。

**Comment by User782Tec** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/115236204/a759ee9f-7f94-4b69-91a2-a760cd1a4823)

这样行吗

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/239731782-a759ee9f-7f94-4b69-91a2-a760cd1a4823.png)
> 
> 这样行吗

可以的

**Comment by NB-Group** [comment]
fuck.
![image](https://github.com/tjy-gitnub/win12/assets/121747915/5698605c-7e14-4c26-8644-5cbff78e5e2b)
查了一圈结果是框架的bug，炒！！！
（可以看到，行号和代码重叠了）

**Comment by NB-Group** [comment]
mmp的，整个重写了，但是更帅气了（确信）
![image](https://github.com/tjy-gitnub/win12/assets/121747915/aaefbbec-3d12-491a-a024-e1d6eb09c0f3)
@User782Tec @tjy-gitnub

**Comment by User782Tec** [comment]
> mmp的，整个重写了，但是更帅气了（确信） ![image](https://user-images.githubusercontent.com/121747915/239932981-aaefbbec-3d12-491a-a024-e1d6eb09c0f3.png) @User782Tec @tjy-gitnub

哇
牛逼

---

我觉得这个滚动条...有点一言难尽
把滚动条的背景删了
上下箭头也不要了
滚动条颜色设置为#FFFFFF22(?
滚动条不要圆角，直接铺满

**Comment by User782Tec** [comment]
> > > ![image](https://user-images.githubusercontent.com/121747915/239689608-043f93d1-4ca1-4fe8-8c3e-789401ec1e82.png)
> > 
> > 
> > 我先把亮度调整做了 马上来做这个 (可以逝逝改成Pycharm?)
> 
> 你，真，勇。 ![image](https://user-images.githubusercontent.com/121747915/239690520-ab20f15b-bf7a-4edf-a5f1-6b0a1bf4a86d.png)

你这个是...PyCharm专业版？

**Comment by User782Tec** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/115236204/91d3c3d4-5d8c-4fd2-9456-4e75519249ff)

我草
这个6(来自Visual Studio Code厨的推荐

- - -

额 这个Monaco editor貌似除了外观之外没有优势

**Comment by NB-Group** [comment]
> > > > ![image](https://user-images.githubusercontent.com/121747915/239689608-043f93d1-4ca1-4fe8-8c3e-789401ec1e82.png)
> > > 
> > > 
> > > 我先把亮度调整做了 马上来做这个 (可以逝逝改成Pycharm?)
> > 
> > 
> > 你，真，勇。 ![image](https://user-images.githubusercontent.com/121747915/239690520-ab20f15b-bf7a-4edf-a5f1-6b0a1bf4a86d.png)
> 
> 你这个是...PyCharm专业版？

pycharm设置里有个新ui，把它打开就行

**Comment by NB-Group** [comment]
我！的！标！题！栏！呢？
![image](https://github.com/tjy-gitnub/win12/assets/121747915/01139930-e0ab-4d98-afc0-72be1a945b53)

**Comment by NB-Group** [comment]
额，貌似显得格格不入。
现在的选择：
1，就这样吧
2，nnd一定要搞好
![image](https://github.com/tjy-gitnub/win12/assets/121747915/7c0b21a8-f4ab-4908-882d-0a5b6adce902)

**Comment by NB-Group** [comment]
> > mmp的，整个重写了，但是更帅气了（确信） ![image](https://user-images.githubusercontent.com/121747915/239932981-aaefbbec-3d12-491a-a024-e1d6eb09c0f3.png) @User782Tec @tjy-gitnub
> 
> 哇 牛逼
> 
> 我觉得这个滚动条...有点一言难尽 把滚动条的背景删了 上下箭头也不要了 滚动条颜色设置为#FFFFFF22(? 滚动条不要圆角，直接铺满

![image](https://github.com/tjy-gitnub/win12/assets/121747915/c7b65f18-9605-4d79-acaf-b86d0d66d7d4)
这样？

**Comment by NB-Group** [comment]
> > > mmp的，整个重写了，但是更帅气了（确信） ![image](https://user-images.githubusercontent.com/121747915/239932981-aaefbbec-3d12-491a-a024-e1d6eb09c0f3.png) @User782Tec @tjy-gitnub
> > 
> > 
> > 哇 牛逼
> > 我觉得这个滚动条...有点一言难尽 把滚动条的背景删了 上下箭头也不要了 滚动条颜色设置为#FFFFFF22(? 滚动条不要圆角，直接铺满
> 
> ![image](https://user-images.githubusercontent.com/121747915/240280590-c7b65f18-9605-4d79-acaf-b86d0d66d7d4.png) 这样？

算了我就写个框架css你们来写吧

**Comment by NB-Group** [comment]
又是一言难尽的ui
![image](https://github.com/tjy-gitnub/win12/assets/121747915/81ff71bc-b574-4192-8f41-3167526102a7)

**Comment by User782Tec** [comment]
> > > mmp的，整个重写了，但是更帅气了（确信） ![image](https://user-images.githubusercontent.com/121747915/239932981-aaefbbec-3d12-491a-a024-e1d6eb09c0f3.png) @User782Tec @tjy-gitnub
> > 
> > 
> > 哇 牛逼
> > 我觉得这个滚动条...有点一言难尽 把滚动条的背景删了 上下箭头也不要了 滚动条颜色设置为#FFFFFF22(? 滚动条不要圆角，直接铺满
> 
> ![image](https://user-images.githubusercontent.com/121747915/240280590-c7b65f18-9605-4d79-acaf-b86d0d66d7d4.png) 这样？

哇
就是这样！
真的是心有灵犀一点通

**Comment by User782Tec** [comment]
> 又是一言难尽的ui ![image](https://user-images.githubusercontent.com/121747915/240289218-81ff71bc-b574-4192-8f41-3167526102a7.png)

永远记住:终端里一定要用Consolas，如果没有，至少也要等宽字体

**Comment by User782Tec** [comment]
不如把窗口劈两半
上面编辑
下面运行

**Comment by User782Tec** [comment]
运行可以放在标题栏下面的下拉菜单里(仿照记事本窗口的来写)
还有
CSS类名不要用驼峰命名法，尤其是不要用大驼峰
把PythonEditor改成python-editor
(感觉倒不如改成python-ide)

你用的框架是codemirror5还是codemirror6

---

尽管功能不多
但把图标换成pycharm可能会好一点
因为这个图标
看起来格格不入

**Comment by NB-Group** [comment]
> 运行可以放在标题栏下面的下拉菜单里(仿照记事本窗口的来写) 还有 CSS类名不要用驼峰命名法，尤其是不要用大驼峰 把PythonEditor改成python-editor (感觉倒不如改成python-ide)
> 
> 你用的框架是codemirror5还是codemirror6

我感觉仿照pycharm就行。
框架换了，codemirror有bug换成了ace。
图标我觉得的确格格不入，等会给换了

**Comment by tjy-gitnub** [comment]
我。。。
抱歉啊，这几天...一言难尽啊
我安kubuntu tm不小心把windows引导抹了，然后想修，又把kubuntu给抹了😖
现在用的是手机...打算周末去找人修

**Comment by NB-Group** [comment]
> 我。。。 抱歉啊，这几天...一言难尽啊 我安kubuntu tm不小心把windows引导抹了，然后想修，又把kubuntu给抹了😖 现在用的是手机...打算周末去找人修

好家伙，我用windows最大的灾难事故也就是把user文件夹删了

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/f0e9709a-e17a-4979-b8ed-f30eb87b27db)
怪怪的，反正你们帮我改ui，我负责功能实现就好

**Comment by tjy-gitnub** [comment]
看到这个ui就很手痒...
<hr>
其实我这个还好，数据完好无损，只是启动不了

**Comment by NB-Group** [comment]
> 看到这个ui就很手痒...
> 
> 其实我这个还好，数据完好无损，只是启动不了

我也觉得，哈哈，过会改下css

我那个也还好，因为有备份

**Comment by User782Tec** [comment]
> 我。。。 抱歉啊，这几天...一言难尽啊 我安kubuntu tm不小心把windows引导抹了，然后想修，又把kubuntu给抹了confounded 现在用的是手机...打算周末去找人修

6
你不是在虚拟机里装的吗

**Comment by User782Tec** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/115236204/c3a0b62a-fa82-4110-8dc5-de1c32225cb4)

根据vscode自定义的ace代码编辑器主题

**Comment by NB-Group** [comment]
> ![image](https://user-images.githubusercontent.com/115236204/240513365-c3a0b62a-fa82-4110-8dc5-de1c32225cb4.png)
> 
> 根据vscode自定义的ace代码编辑器主题

可以的

**Comment by User782Tec** [comment]
> > ![image](https://user-images.githubusercontent.com/115236204/240513365-c3a0b62a-fa82-4110-8dc5-de1c32225cb4.png)
> > 根据vscode自定义的ace代码编辑器主题
> 
> 可以的

所以这个是你来做？我来做？还是各做一个？

**Comment by User782Tec** [comment]
你那个服务器
语言设置有问题（毕竟是香港的）
可以试一下在windows里修改默认语言
也可以在请求时加上accept-language指定请求语言

**Comment by NB-Group** [comment]
> 你那个服务器 语言设置有问题（毕竟是香港的） 可以试一下在windows里修改默认语言 也可以在请求时加上accept-language指定请求语言

啊，怎么语言设置有问题了？

**Comment by NB-Group** [comment]
> > > ![image](https://user-images.githubusercontent.com/115236204/240513365-c3a0b62a-fa82-4110-8dc5-de1c32225cb4.png)
> > > 根据vscode自定义的ace代码编辑器主题
> > 
> > 
> > 可以的
> 
> 所以这个是你来做？我来做？还是各做一个？

我来做吧，你搞搞其他的，我们要向替代win10的方向发展

**Comment by User782Tec** [comment]
> > 你那个服务器 语言设置有问题（毕竟是香港的） 可以试一下在windows里修改默认语言 也可以在请求时加上accept-language指定请求语言
> 
> 啊，怎么语言设置有问题了？

服务器在香港
所以返回的内容是繁体中文

**Comment by NB-Group** [comment]
> > > 你那个服务器 语言设置有问题（毕竟是香港的） 可以试一下在windows里修改默认语言 也可以在请求时加上accept-language指定请求语言
> > 
> > 
> > 啊，怎么语言设置有问题了？
> 
> 服务器在香港 所以返回的内容是繁体中文

这个怕不是网站服务器检测ip之后自动的？（指定语言的我也加下

解决方法：我这里写过一个繁体转简体的代码，过会加上去

**Comment by tjy-gitnub** [comment]
wow vscode nb
(我周末要用考试（编程），今天才告诉我妈...问了好像只有能重装系统，我也会啊，可是数据哪！crying...
那个音量（亮度）其实可以**参考**blueedge的，做的还是挺好的
另外：githubapi有限制？为什么我没有遇到安？

**Comment by User782Tec** [comment]
> > > > 你那个服务器 语言设置有问题（毕竟是香港的） 可以试一下在windows里修改默认语言 也可以在请求时加上accept-language指定请求语言
> > > 
> > > 
> > > 啊，怎么语言设置有问题了？
> > 
> > 
> > 服务器在香港 所以返回的内容是繁体中文
> 
> 这个怕不是网站服务器检测ip之后自动的？（指定语言的我也加下
> 
> 解决方法：我这里写过一个繁体转简体的代码，过会加上去


这个可能是请求的时候自动加上的接受语言(因为我在浏览器里，请求头里都有个accept-language: zh-cn，也就是简体中文)，而非服务器检测ip

**Comment by User782Tec** [comment]
> wow vscode nb (我周末要用考试（编程），今天才告诉我妈...问了好像只有能重装系统，我也会啊，可是数据哪！crying... 那个音量（亮度）其实可以**参考**blueedge的，做的还是挺好的 另外：githubapi有限制？为什么我没有遇到安？

I'm sorry to hear that...
不过我觉得你可以用Windows PE(比如微PE)修复引导 (尽管我也不会

**Comment by User782Tec** [comment]
布鲁艾纸复活啦

**Comment by NB-Group** [comment]
好了，我把中文加上去了，顺手修了几个服务器bug。
电脑的话额的确是有很多pe自带修复的，网上随便找找多的是

**Comment by tjy-gitnub** [comment]
特殊癖好吧，不太喜欢用第三方的东西。。。pe都是官方的，只有命令行diskpart。
是啊，blueedge复活啦（可以抄啦

**Comment by NB-Group** [comment]
《可以抄啦》

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/fa30c6b0-b947-42d8-8e32-4ce4e04aabd2)
额，还可以吧？起码能接受吧（还是那句话，我不适合写前端

**Comment by User782Tec** [comment]
> ![image](https://user-images.githubusercontent.com/121747915/240856999-fa30c6b0-b947-42d8-8e32-4ce4e04aabd2.png) 额，还可以吧？起码能接受吧（还是那句话，我不适合写前端

可以接受

运行按钮有点突兀
可以放在下拉菜单里
或者是整一个在标题栏下面的标签页栏，把运行放在最右边

字体可以再大一点

话说你这个标题栏咋变胖了

还有 图标没改呢

对了，不要用apps.python.pyodide.runPython运行
要先创建一个字符串io流
并将标准输出流设置为该io流
然后运行
最后把该io流中的内容放在终端里
可以参考apps.python.run方法
就像这样
```javascript
apps.python.pyodide.runPython('sys.stdout = io.StringIO()');
apps.python.pyodide.runPython(/*要运行的代码*/);
const result = apps.python.pyodide.runPython('sys.stdout.getvalue()');
```
我已经提前导入过sys库和io库了，无需重复导入

---

我试着做一个白板

**Comment by NB-Group** [comment]
运行按钮暂时放在这里吧，毕竟就这一个按钮，放在下拉框里怪怪的。

字体我调下。

标题栏我不到啊，我fork的代码啊。

图标马上改。

吆西，我现在去写运行。


好，

**Comment by User782Tec** [comment]
[vscode-theme.zip](https://github.com/tjy-gitnub/win12/files/11563442/vscode-theme.zip)

我写了一个vscode样式
解压缩后
vscode.css是样式表
test.html是使用例

**Comment by NB-Group** [comment]
你就不觉得字体太大了吗
![image](https://github.com/tjy-gitnub/win12/assets/121747915/74f75680-5e36-43c0-ba44-bd95bd5228a4)

**Comment by NB-Group** [comment]
文本获取搞定（还好我机智，用了超级简单的方法搞定了
![image](https://github.com/tjy-gitnub/win12/assets/121747915/2ceedc42-b876-4ae7-b63c-ea47ba55c188)

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/b159f3bb-05e1-4b1b-9a6e-bb3099b35bf7)
最终效果
@tjy-gitnub @User782Tec

**Comment by User782Tec** [comment]
> 你就不觉得字体太大了吗 ![image](https://user-images.githubusercontent.com/121747915/240876465-74f75680-5e36-43c0-ba44-bd95bd5228a4.png)

额
没事

我把文本框调成html模式了...
你再改回来吧

**Comment by tjy-gitnub** [comment]
嗯...这个可以实时输出吗？
还有就是input的问题...

**Comment by tjy-gitnub** [comment]
嗯...这个可以实时输出吗？
还有就是input的问题...

**Comment by NB-Group** [comment]
> 嗯...这个可以实时输出吗？ 还有就是input的问题...

当然是按下运行键输出结果了。
input好像也是啊，但是网页版运行python就不大可能input

**Comment by tjy-gitnub** [comment]
我指的是实时输出内容而不是运行完了之后一起输出（能实现吗？

**Comment by tjy-gitnub** [comment]
我的思路是重新定义print函数，但是如果有库引用就没办法了

**Comment by User782Tec** [comment]
不太行
但可以用多线程+循环试一下

**Comment by NB-Group** [comment]
> 我指的是实时输出内容而不是运行完了之后一起输出（能实现吗？

可以的，不过我pr已经发了。。其实很简单，一行一行执行就行你们合并之后帮我改下吧。
desktop.js
636行左右

**Comment by NB-Group** [comment]
> 不太行
> 但可以用多线程+循环试一下

其实很简单的啊！一行一行执行就行啊！

**Comment by User782Tec** [comment]
这不太好吧
万一有什么循环结构啥的

**Comment by NB-Group** [comment]
> 这不太好吧 万一有什么循环结构啥的

阿巴阿巴

**Comment by User782Tec** [comment]
> 文本获取搞定（还好我机智，用了超级简单的方法搞定了 ![image](https://user-images.githubusercontent.com/121747915/240882521-2ceedc42-b876-4ae7-b63c-ea47ba55c188.png)

?为啥要自己写获取文本的脚本

**Comment by NB-Group** [comment]
> > 文本获取搞定（还好我机智，用了超级简单的方法搞定了![图像](https://user-images.githubusercontent.com/121747915/240882521-2ceedc42-b876-4ae7-b63c-ea47ba55c188.png)
> 
> ?为啥要自己写获取文本的脚本

人家没给吧

**Comment by User782Tec** [comment]
《 P E 》
好家伙，PyCharm教育版
不过确实和Python Editor挺搭的(

**Comment by User782Tec** [comment]
> > > 文本获取搞定（还好我机智，用了超级简单的方法搞定了![图像](https://user-images.githubusercontent.com/121747915/240882521-2ceedc42-b876-4ae7-b63c-ea47ba55c188.png)
> > 
> > 
> > ?为啥要自己写获取文本的脚本
> 
> 人家没给吧

editor.getValue()

**Comment by NB-Group** [comment]
> > > > 文本获取搞定（还好我机智，用了超级简单的方法搞定了![图像](https://user-images.githubusercontent.com/121747915/240882521-2ceedc42-b876-4ae7-b63c-ea47ba55c188.png)
> > > 
> > > 
> > > ?为啥要自己写获取文本的脚本
> > 
> > 
> > 人家没给吧
> 
> editor.getValue（）

wdf!
不过没关系啊，我这个也能用

**Comment by User782Tec** [comment]
> > > > > 文本获取搞定（还好我机智，用了超级简单的方法搞定了![图像](https://user-images.githubusercontent.com/121747915/240882521-2ceedc42-b876-4ae7-b63c-ea47ba55c188.png)
> > > > 
> > > > 
> > > > ?为啥要自己写获取文本的脚本
> > > 
> > > 
> > > 人家没给吧
> > 
> > 
> > editor.getValue（）
> 
> wdf! 不过没关系啊，我这个也能用

啊对对对
能跑就行

**Comment by NB-Group** [comment]
> 啊对对对 能跑就行

编程要遵循能跑就行的原则嘛
