### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#96]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/2cc04830-b8c8-47c0-a9bd-fda2c7b12a9c)
十年了，十年了！你们知道我每次看到这个开始菜单时觉得多别扭吗？你们考虑过用户的感受吗？
tnnd，赶紧去修！

**Comment by User782Tec** [comment]
> ![image](https://user-images.githubusercontent.com/121747915/241211845-2cc04830-b8c8-47c0-a9bd-fda2c7b12a9c.png) 十年了，十年了！你们知道我每次看到这个开始菜单时觉得多别扭吗？你们考虑过用户的感受吗？ tnnd，赶紧去修！

tnnd你用的啥浏览器
是不是Firefox

**Comment by NB-Group** [comment]
> > ![image](https://user-images.githubusercontent.com/121747915/241211845-2cc04830-b8c8-47c0-a9bd-fda2c7b12a9c.png) 十年了，十年了！你们知道我每次看到这个开始菜单时觉得多别扭吗？你们考虑过用户的感受吗？ tnnd，赶紧去修！
> 
> tnnd你用的啥浏览器 是不是Firefox

tnnd edge

**Comment by User782Tec** [comment]
> > > ![image](https://user-images.githubusercontent.com/121747915/241211845-2cc04830-b8c8-47c0-a9bd-fda2c7b12a9c.png) 十年了，十年了！你们知道我每次看到这个开始菜单时觉得多别扭吗？你们考虑过用户的感受吗？ tnnd，赶紧去修！
> > 
> > 
> > tnnd你用的啥浏览器 是不是Firefox
> 
> tnnd edge

tnnd不对啊
我只在Firefox中发现了该问题
看一下 #29

**Comment by NB-Group** [comment]
等下我录个屏

**Comment by NB-Group** [comment]
tnnd google chrome居然也有这个问题

https://github.com/tjy-gitnub/win12/assets/121747915/18ea8325-895d-43d4-89f7-13e7045cc8f6

**Comment by User782Tec** [comment]
> tnnd google chrome居然也有这个问题
> 
>  20230526_201627.mp4

你这个视频根本看不了啊啊啊啊啊啊

**Comment by User782Tec** [comment]
你这不是没有问题吗

---

homo特有的无处不在(悲

**Comment by NB-Group** [comment]
![image](https://github.com/tjy-gitnub/win12/assets/121747915/3404f607-0900-4317-8572-c2efcd0a2b83)
这个问题啊啊啊啊
我的意思是下面有一部分文字没了啊啊啊

不过神奇的是用win10自带的截图，好的坏的毛玻璃都给你抛光喽

**Comment by User782Tec** [comment]
哦 截屏软件的问题啊
行 我去加一个滚动条应该就行了

**Comment by NebulaTechs** [comment]
emm..我记得tjy说过开始菜单加滚动条很离谱吖

**Comment by NebulaTechs** [comment]
还有麻烦把嘴巴放干净点

**Comment by NB-Group** [comment]
> emm..我记得tjy说过开始菜单加滚动条很离谱吖

不知道啊

**Comment by User782Tec** [comment]
https://github.com/tjy-gitnub/win12/issues/16#issuecomment-1367925793
