### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by NB-Group** [win12-online/win12#98]
前言：有个神奇的东西叫做cookie，通过js可以修改它，它能够在用户退出网站后留下记录。

![image](https://github.com/tjy-gitnub/win12/assets/121747915/1ed6acdf-a25f-4cb6-8164-f0db5fcea356)
看到这张充满灰黑色的图，是不是非常难受，这就是多窗口透明关闭后全屏窗口后再次打开窗口的画面，是不是很难受，当然我不是来让你们默认多窗口透明的，而是来建议另一个功能：通过cookie保存用户设置。

以下是cookie操作说明：
1.设置cookie：
```
document.cookie = "name=value; expires=date; path=path; domain=domain; secure";
```
其中：

name是cookie的名字（键）。
value是你要设置的值。
expires是选填的参数，表示cookie的过期时间，格式为GMT格式的日期字符串。
path是选填的参数，表示要设置cookie的路径。如果不指定该参数，则默认为当前文档路径。
domain是选填的参数，表示要设置cookie的域名。如果不指定该参数，则默认为当前文档的域名。
secure是选填的参数，表示是否需要通过 HTTPS 连接来传输 cookie。
2.获取cookie：

```
var cookies = document.cookie;
```
以上代码将返回一个包含当前页面所有 cookie 的字符串。最好对其进行解析以获得特定 cookie 的值。

3.删除cookie：

```
document.cookie = "name=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/;";
```
在这种情况下，仅需要设置 cookie 的名称和过期时间即可。日期应设置为过去的日期，以便浏览器将其视为已经过期并删除它。请注意，当你设置 expires 或 max-age 为 0（或不写）时，就会删掉这个 cookie，因此并不需要真正地设置 cookie 的值为空字符串。

只需要将用户的设置存入cookie，然后每次启动win12时读取并做相应更改即可

**Comment by NB-Group** [comment]
@tjy-gitnub @User782Tec

**Comment by User782Tec** [comment]
cookie不好用
我在相机应用的用户条款里用的是localStorage

**Comment by User782Tec** [comment]
哦对了
你那个windows安全中心不要用什么absolute定位、relative定位、fixed定位什么的
你要学着去用flex和grid布局
那个Python editor就是你用了一堆绝对定位
才导致标题栏消失的
帮你改成grid和flex布局后就没问题了

**Comment by NB-Group** [comment]
哦哦哦，我windows安全中心的侧边栏也没有过，我改了之后就好了

**Comment by NB-Group** [comment]
> localStorage

不管怎么着，只要保存设置数据就行。

所以等你文件系统搞好就搞这个哈

**Comment by tjy-gitnub** [comment]
可以直接用 setData(key,value)
然后在 getdata 里设置
然后至于那个黑色...
![image](https://github.com/tjy-gitnub/win12/assets/71509955/13c29fec-d477-431f-baa5-72d9238beb5e)
亚克力...

**Comment by tjy-gitnub** [comment]
你可以用云母（如果你的cpu撑得住

**Comment by NB-Group** [comment]
> 可以直接用 setData（key，value） 然后在 getdata 里设置 然后至于那个黑色... ![image](https://user-images.githubusercontent.com/71509955/241976031-13c29fec-d477-431f-baa5-72d9238beb5e.png) 亚克力...

![image](https://github.com/tjy-gitnub/win12/assets/121747915/a3daecba-c2a4-4f24-ae92-ba9d8e6da8e1)
好像也是啊。。

**Comment by NB-Group** [comment]
> 你可以用云母（如果你的cpu撑得住

还有这个云母啊（看下下面的图
![image](https://github.com/tjy-gitnub/win12/assets/121747915/8b29d51d-0798-432c-a1f8-e221bea27b3d)
![image](https://github.com/tjy-gitnub/win12/assets/121747915/d368bb44-fa2e-483a-97aa-0d478587e7be)
你们测试的时候没发现吗

**Comment by tjy-gitnub** [comment]
> > 你可以用云母（如果你的cpu撑得住
> 
> 还有这个云母啊（看下下面的图  你们测试的时候没发现吗

呃...可以看一下用法，里面写了的（不然怎么叫实验呢（v6计划取了，太烧cpu了

**Comment by User782Tec** [comment]
> > 你可以用云母（如果你的cpu撑得住
> 
> 还有这个云母啊（看下下面的图 ![image](https://user-images.githubusercontent.com/121747915/241981293-8b29d51d-0798-432c-a1f8-e221bea27b3d.png) ![image](https://user-images.githubusercontent.com/121747915/241981349-d368bb44-fa2e-483a-97aa-0d478587e7be.png) 你们测试的时候没发现吗

你只需要调整一下浏览器窗口就好了
别问我为什么
这是特性(tjy说过了，在window的onresize事件触发时渲染)

**Comment by NB-Group** [comment]
哦

**Comment by ProgramCX** [comment]
建议搞一个更新功能

**Comment by NB-Group** [comment]
啥说详细点

**Comment by ProgramCX** [comment]
像Windows一样的更新页面，后台在更新html css js 文件。

**Comment by tjy-gitnub** [comment]
这个因为平台限制暂时是不能完成的奥
pwa似乎并没有提供这样一个api
不过之后（不确定）做应用（甚至独立系统）的时候肯定会有的
现在也可以更新啊，不过确实比较被动

**Comment by NB-Group** [comment]
啥说详细点

**Comment by User782Tec** [comment]
> 这个因为平台限制暂时是不能完成的奥 pwa似乎并没有提供这样一个api 不过之后（不确定）做应用（甚至独立系统）的时候肯定会有的 现在也可以更新啊，不过确实比较被动

我有一个可能有点大胆的想法
就是在点击更新按钮之后
通过发送信息的方式
触发sw更新

或者是点击更新按钮后
再在localStorage或者是sessionStorage里存储一个表示确认更新的键值对
接着重启
sw检测到是否更新的键值对后
接着更新

(瞎说的 有误勿喷)

**Comment by NB-Group** [comment]
我有个更更更大胆的想法，我在我家电脑实体机上装一个chrome os，并设置win12开机自启动，直接tnnd实体机装win12!!!

**Comment by kjmjh** [comment]
> 我有个更更更大胆的想法，我在我家电脑实体机上装一个chrome os，并设置win12开机自启动，直接tnnd实体机装win12!!!

6
